### ISSUE TITLE
希望能在面板直接控制服务器

### ISSUE THREAD

**Issue by pppwaw** [Suwings/MCSManager#101]
目前面板是要进入服务器的管理或控制台才有开启选项，希望能在服务器列表直接有开启。

**Comment by Suwings** [comment]
那服务器比较多的话，在控制台面板进行操作，显得有点多余了

**Comment by pppwaw** [comment]
我的意思是在服务器列表界面选中某些服务器然后开启，因为团队需要可能只需要开启几个进行测试，而目前物理机性能又没办法全开。

**Comment by pppwaw** [comment]
或者说服务器列表面板增加开启关闭重启这些按钮，方便操作
