### ISSUE TITLE
建议增加一个在线编辑器

### ISSUE THREAD

**Issue by TheresaQWQ** [Suwings/MCSManager#102]
如题，目前只能编辑properties，希望可以增加编辑器功能，编辑插件的配置文件

**Comment by Suwings** [comment]
感谢提供建议，短期内此项目不会进行功能性更新（只修BUG），感谢你的支持。

**Comment by huangsijun17** [comment]
同求。。。

**Comment by Ghost-chu** [comment]
+1

**Comment by huangsijun17** [comment]
可否再附带两个功能？
1. 编辑器的行号。
2. 自动换行的单选框。

**Comment by Suwings** [comment]
> 可否再附带两个功能？
> 
> 1. 编辑器的行号。
> 2. 自动换行的单选框。

优先级较低。下面要做，压缩打包功能和其他功能，毕竟这个暂时还不影响使用。
