### ISSUE TITLE
能否提供直接打开终端的功能

### ISSUE THREAD

**Issue by haojie06** [Suwings/MCSManager#103]
您好，请问在面板中启动的服务器是否可以不经过面板直接访问后台？因为我有一些需求需要在tmux或者screen中查看服务器后台。

**Comment by Suwings** [comment]
暂时性没有相关的功能提供，只能通过访问面板来进行服务器开关。无法在终端直接访问 Minecraft 服务端。

**Comment by huangsijun17** [comment]
MC加个SSH插件再SSH上去？

**Comment by haojie06** [comment]
感谢回复了，我的是基岩版的服务器所以插件暂时没办法了，因为我需要使用QQ机器人操控服务器，不能直接打开后台有些影响。谢谢了，这个还是很好用的
