### ISSUE TITLE
服务端运行时改名 BUG 问题

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#104]
服务器运行时修改服务器名会导致模板识别出服务器关闭，但实际上却在运行。

我们的服主评价：MDZZ

我无言以对。

建议：
1. 禁止在服务器运行时修改配置。
2. 取消现有服务器名称，更改为通过内部ID索引。
3. 添加服务器昵称功能，允许中文等的昵称。

**Comment by Suwings** [comment]
感谢提供反馈！

**Comment by Suwings** [comment]
已解决。
