### ISSUE TITLE
给段没啥用的代码

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#105]
#!/bin/bash

screen -dAr MC && exit 3

screen -dmS MC || exit 2

screen -x -S MC -p 0 -X stuff $'cd /mnt/minecraft/MCManager/\n' || exit 2

screen -x -S MC -p 0 -X stuff $'node app.js\n' || exit 2

screen -dAr MC || exit 2

我拿来一句话开程序的...

然后服(sha)主(X)输入了1 .sh说我写的脚本不能用了。……

**Comment by Suwings** [comment]
你好像经历过一些悲惨的故事。
