### ISSUE TITLE
希望能通过API和后台交互

### ISSUE THREAD

**Issue by doubihui** [Suwings/MCSManager#106]
比如可以用API创建或删除一个用户或服务器

**Comment by Suwings** [comment]
暂时没有这方面的API提供。抱歉。

**Comment by luckydog6132** [comment]
@doubihui 如果是需要远程使用命令的话，可以考虑使用RCON模块，就是通过接口执行命令的
然后组合QQ聊天机器人或者微信机器人，就可以实现群消息重启服务器，或者查看在线人数啥的
