### ISSUE TITLE
服务器日志文字获取错误

### ISSUE THREAD

**Issue by Anders233** [Suwings/MCSManager#108]
# 控制面板某些文字显示不正常
### 首先这是正常的显示，CMD也是如此显示
![IDEA](https://raw.githubusercontent.com/Anders233/MCSManager/master/IDEA.png)
---

### 这是面板显示，多出了符号:"","[1;31m","[36m","[34m","[m]"等...
![MCSM](https://raw.githubusercontent.com/Anders233/MCSManager/master/MCSM.png)
---

### 服务器的,log文件
![NukkitLog](https://raw.githubusercontent.com/Anders233/MCSManager/master/server.log.png)
---

### MCSM的.log文件
![MCSMLOG](https://raw.githubusercontent.com/Anders233/MCSManager/master/MCSM-log.png)
---

### 即使这样设置也会显示
![TOOLS_JS](https://raw.githubusercontent.com/Anders233/MCSManager/master/tools.js.png)

#### 代替所有强迫症患者在此表示感谢
> - 使用[NukkitX](https://github.com/NukkitX/Nukkit)服务端，是一个使用Java编写的高性能MCBE服务端
> - 服务器启动参数直接设置为核心启动亦是如此
> - 服务器启动参数设置为CMD脚本启动亦是如此
> - 确认使用CMD运行不会出现此状况

**Comment by Anders233** [comment]
# 经过这两天测试，原来是我正则表达式写错了
###### 补习了一下JS正则表达式之后
###### 使用tools.js替换后效果图：![fix](https://raw.githubusercontent.com/Anders233/MCSManager/master/fix.png)
>如果你也在使用Nukkit服务端
>只需将以下代码复制在`public\common\js\tools.js` **118行**上下即可

```JavaScript
text = text.replace(/\[34mINFO/igm, "<span style='color:#0000AA;'> 信息</span>");
text = text.replace(/\[31mWARN/igm, "<span style='color:#FFFF55;'> 警告</span>");
text = text.replace(/\[5;1;31mFATAL/igm, "<span style='color:#FF5555;'> 危急 </span>");
text = text.replace(/\[1;31mERROR/igm, "<span style='color:#AA0000;'> 错误 </span>");
text = text.replace(/\[36m(\d{2,}:\d{2,}:\d{2,})\[m/igm, "<span style='color:#017EBC;'>$1</span>");
text = text.replace(/\[m/igm, "<span></span>");
text = text.replace(/\[/igm, "<span style='color:#FFFFFF;'>[</span>");
text = text.replace(/\]/igm, "<span style='color:#FFFFFF;'>]</span>");
```
# 是不是瞬间感觉舒服多了 XD

**Comment by huangsijun17** [comment]
还行...

**Comment by Anders233** [comment]
> 还行...

哈哈，看来不止我一人有这种困惑啊

**Comment by Suwings** [comment]
感谢此议题的作者的问题与自己写出的解决方案。

由于这个软件的控制台页面是通过前端渲染的颜色，并非终端下的原生颜色，所以有些颜色参数就被输出了，从而导致有些使用不适，十分抱歉。

再次表示感谢。
@Anders233

**Comment by Anders233** [comment]
> 感谢此议题的作者的问题与自己写出的解决方案。
> 
> 由于这个软件的控制台页面是通过前端渲染的颜色，并非终端下的原生颜色，所以有些颜色参数就被输出了，从而导致有些使用不适，十分抱歉。
> 
> 再次表示感谢。
> @Anders233

23333，只是看着乱糟糟的，并无其他影响，能修复自然是最好不过 XD

**Comment by Anders233** [comment]
`完全自定义启动命令` 真是个很棒的功能呢！XD

**Comment by Suwings** [comment]
> > 感谢此议题的作者的问题与自己写出的解决方案。
> > 由于这个软件的控制台页面是通过前端渲染的颜色，并非终端下的原生颜色，所以有些颜色参数就被输出了，从而导致有些使用不适，十分抱歉。
> > 再次表示感谢。
> > @Anders233
> 
> 23333，只是看着乱糟糟的，并无其他影响，能修复自然是最好不过 XD

你这个方法是在前端使用正则表达式通过替换的方式来解决混乱的象限，这个方法虽好，但是不是一个根本的解决方案。未来版本我们会争取实现完全模拟终端，也已经有很多现有的框架可以供我们使用。

不过，短期内，由于这是一个开源项目，无经济收入，考虑到时间与人力等问题，在没有出现安全性BUG的情况下，我们不打算进行更新此软件，十分抱歉。

感谢你的使用！

**Comment by Suwings** [comment]
现已完全修复这个问题，采用全新的终端界面，可以展示原生颜色。

**Comment by lwee02020909** [comment]
![WWWWWWWW](https://user-images.githubusercontent.com/61728893/75755661-0204b180-5d6a-11ea-9817-4aa6439f86b7.jpg)
請問這要怎麼解決 編碼都是UTF-8

**Comment by Suwings** [comment]
服务端管理界面->参数设置->右边有输入输出编码，设置为utf8，gbk，big5进行尝试。

**Comment by huangsijun17** [comment]
> 现已完全修复这个问题，采用全新的终端界面，可以展示原生颜色。

如果是模拟shell的话，是不是也支持shell里的删除屏幕等等了吗？
之前如果运行mohist服务端的自动下载，进度条会刷满一屏幕。

**Comment by lwee02020909** [comment]
以解決 感謝

**Comment by Suwings** [comment]
> > 现已完全修复这个问题，采用全新的终端界面，可以展示原生颜色。
> 
> 如果是模拟shell的话，是不是也支持shell里的删除屏幕等等了吗？
> 之前如果运行mohist服务端的自动下载，进度条会刷满一屏幕。

没有支持完全的tty运行方式，后端代码还是原本的暂未修改，只是前端改成了模拟的终端。这个终端能够支持Linux的原生颜色，与部分操作，所以你说的那种刷新整个屏幕的情况，可能还是会刷满一屏幕。
