### ISSUE TITLE
是否有考虑上传至 NPM

### ISSUE THREAD

**Issue by langyo** [Suwings/MCSManager#109]
#106 

如果能公开为 NPM 包那就太好了……请问下有考虑过吗？

（或者，如果仓库主同意，我可以自行在我自己的 Fork 分支对其设计 API 并公开到 NPM）

**Comment by Suwings** [comment]
当然同意，没有问题。感谢帮助。

**Comment by Suwings** [comment]
抱歉，删除了原本的发言。
我们还是不建议你对此设计API并且发布，因为我们随时可能有大规模更新，从而导致你的工作浪费，所以短期内不建议做这些事情。谢谢！

**Comment by langyo** [comment]
@Suwings 本人仅仅会设计最小化的 API 套在最外层，除非你们那把项目改的和原来的架构完全是两个样子、根本不通用，我仍然能为此保持兼容...

短期之内我暂时不会做这事情，我还有些别的事情要忙...不过后续我仍然希望把这个项目包裹好传到 NPM ...

感谢你的回复
