### ISSUE TITLE
希望可以一键获取现在的开服指令

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#110]
由于一个BUG，需要添加一段Java的启动参数来优化服务器。但是，居然要我自己完完整整得去写整段启动参数。就不能单击自定义按钮，获取现有服务器的开服指令吗？

**Comment by Suwings** [comment]
获取现有的开服指令？我感觉还没有必要做到这个吧。
不过你想添加启动参数来优化服务器，有个附加参数的选项供你使用，另外自定义启动命令也不差，只是可能有点麻烦。
感谢反馈这个问题。

**Comment by huangsijun17** [comment]
仔细看了查了一下，希望可以给一个自定义Java参数和Minecraft参数即可。这样，那些使用统一通行证等等的也能方便一些。当然，如果可以添加一个统一参数（即对所有服务器生效）那就最好了。
