### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by pppwaw** [Suwings/MCSManager#112]
现在有不少服务器选择authlib-injector
我觉得我们可以添加一个一键加载的功能

**Comment by Potterli20** [comment]
你知道mc1.14.2如何弄？？

**Comment by pppwaw** [comment]
如何弄什么鬼玩意- -直接jar一放面板一添加就好了啊
authlib是全班本通用的，直接修改字节码

**Comment by Potterli20** [comment]
@pppwaw 好像我配了，但是用不了，端口也没有写错，而我在本地建都不行，我也不知道那里有错

**Comment by pppwaw** [comment]
有提示错误么？把你写的参数发下

**Comment by Suwings** [comment]
这个`authlib-injector`不考虑加入,面板不打算参与插件下载或一键添加这方面的功能，抱歉哈~
