### ISSUE TITLE
使用caddy进行反向代理时出现https错误

### ISSUE THREAD

**Issue by FishMagic** [Suwings/MCSManager#115]
在登陆界面正确载入了https，但是在点击登陆按钮获取key的时候，降级回了http，导致获取key的链接被浏览器拦截而无法正常登陆

**Comment by Suwings** [comment]
打开前端 URL 定位文件 public/common/URL.js, 将 http 与 ws 改成 https 与 wss；

试试看。

**Comment by FishMagic** [comment]
问题已解决
