### ISSUE TITLE
请问怎么进行自动定时备份

### ISSUE THREAD

**Issue by ljttty** [Suwings/MCSManager#116]
服务器的存档，希望能够定时备份或者用指令备份，但是没研究出来，特殊指令也不知道在哪里看，希望懂的人只条明路，谢谢

**Comment by Suwings** [comment]
自动备份功能，控制面板不自带，因为最好的自动备份功能的实现，应该交付给 Minecraft 服务端插件来做，因为备份最好不是简单的文件复制，用插件备份会更好！

你可以配合插件命令（一般插件都自带定时备份）与计划任务，来实现你的自动定时备份。

**Comment by ljttty** [comment]
我只用过原版的核心。从来没有接触过插件，我还是用FPT手动备份吧，不过还是要谢谢你的答复

**Comment by huangsijun17** [comment]
可以考虑使用Docker并让其自动备份。

**Comment by aliyuchang33** [comment]
可以用docker加rdiff-backup实现，但是他们并没有实现的意思，虽然这是唯一一个让我留在MineOS的理由
