### ISSUE TITLE
关于双S颜色代码

### ISSUE THREAD

**Issue by 2696703792** [Suwings/MCSManager#117]
![image](https://user-images.githubusercontent.com/42534870/61183936-35c78580-a67a-11e9-825d-c9f18d1d6f63.png)
看着很鸡肋，望改进。

**Comment by Anders233** [comment]
https://github.com/pmmp/PocketMine-MP/blob/3fae57508bf85f35bd3e05639cbfd4ffe21922eb/src/pocketmine/utils/TextFormat.php#L304

**Comment by 2696703792** [comment]
> https://github.com/pmmp/PocketMine-MP/blob/3fae57508bf85f35bd3e05639cbfd4ffe21922eb/src/pocketmine/utils/TextFormat.php#L304

？

**Comment by Anders233** [comment]
> > https://github.com/pmmp/PocketMine-MP/blob/3fae57508bf85f35bd3e05639cbfd4ffe21922eb/src/pocketmine/utils/TextFormat.php#L304
> 
> ？

相关颜色准换代码参考

**Comment by 2696703792** [comment]
> > > https://github.com/pmmp/PocketMine-MP/blob/3fae57508bf85f35bd3e05639cbfd4ffe21922eb/src/pocketmine/utils/TextFormat.php#L304
> > 
> > 
> > ？
> 
> 相关颜色准换代码参考

![image](https://user-images.githubusercontent.com/42534870/61184309-d1f38b80-a67e-11e9-9b25-61939a63fd3e.png)
这是RGB代码估计不适用（小白勿喷）

**Comment by Anders233** [comment]
> > > > https://github.com/pmmp/PocketMine-MP/blob/3fae57508bf85f35bd3e05639cbfd4ffe21922eb/src/pocketmine/utils/TextFormat.php#L304
> > > 
> > > 
> > > ？
> > 
> > 
> > 相关颜色准换代码参考
> 
> ![image](https://user-images.githubusercontent.com/42534870/61184309-d1f38b80-a67e-11e9-9b25-61939a63fd3e.png)
> 这是RGB代码估计不适用（小白勿喷）

亲测可用，转换效果不错

**Comment by 2696703792** [comment]
> > > > > https://github.com/pmmp/PocketMine-MP/blob/3fae57508bf85f35bd3e05639cbfd4ffe21922eb/src/pocketmine/utils/TextFormat.php#L304
> > > > 
> > > > 
> > > > ？
> > > 
> > > 
> > > 相关颜色准换代码参考
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/42534870/61184309-d1f38b80-a67e-11e9-9b25-61939a63fd3e.png)
> > 这是RGB代码估计不适用（小白勿喷）
> 
> 亲测可用，转换效果不错

请问能发一下代码吗？

**Comment by Anders233** [comment]
面板我没找到去除§符号的地方，我是有其他用途

**Comment by 2696703792** [comment]
> 面板我没找到去除§符号的地方，我是有其他用途

![image](https://user-images.githubusercontent.com/42534870/61184423-306d3980-a680-11e9-97b7-7ff67e2db727.png)
我只知道mcsm用的是特点字符匹配的方法

**Comment by Anders233** [comment]
> 如果你不想看到颜色代码
> 只需将以下代码复制在`public\common\js\tools.js` **119行**上下即可

```JavaScript
text = text.replace(/§[0-9a-zA-Z]/igm, "");
```

**Comment by 2696703792** [comment]
> > 如果你不想看到颜色代码
> > 只需将以下代码复制在`public\common\js\tools.js` **119行**上下即可
> 
> ```js
> text = text.replace(/§[0-9a-zA-Z]/igm, "");
> ```

然而我想让他颜色也变，但就是不知道怎么弄，很烦

**Comment by Anders233** [comment]
> > > 如果你不想看到颜色代码
> > > 只需将以下代码复制在`public\common\js\tools.js` **119行**上下即可
> > 
> > 
> > ```js
> > text = text.replace(/§[0-9a-zA-Z]/igm, "");
> > ```
> 
> 然而我想让他颜色也变，但就是不知道怎么弄，很烦

直接CMD运行即可，目前市面上大多数面板都是这个样子

**Comment by 2696703792** [comment]
> > > > 如果你不想看到颜色代码
> > > > 只需将以下代码复制在`public\common\js\tools.js` **119行**上下即可
> > > 
> > > 
> > > ```js
> > > text = text.replace(/§[0-9a-zA-Z]/igm, "");
> > > ```
> > 
> > 
> > 然而我想让他颜色也变，但就是不知道怎么弄，很烦
> 
> 直接CMD运行即可，目前市面上大多数面板都是这个样子

你的意思是说不直接用面板启动，而是中间加一层bat？
但这样会不会导致面板的参数无法使用？

**Comment by Anders233** [comment]
> > > > > 如果你不想看到颜色代码
> > > > > 只需将以下代码复制在`public\common\js\tools.js` **119行**上下即可
> > > > 
> > > > 
> > > > ```js
> > > > text = text.replace(/§[0-9a-zA-Z]/igm, "");
> > > > ```
> > > 
> > > 
> > > 然而我想让他颜色也变，但就是不知道怎么弄，很烦
> > 
> > 
> > 直接CMD运行即可，目前市面上大多数面板都是这个样子
> 
> 你的意思是说不直接用面板启动，而是中间加一层bat？
> 但这样会不会导致面板的参数无法使用？

是的，启动参数直接写进cmd脚本即可
但是用面板都是为了方便管理吧，
直接脚本岂不又麻烦了

**Comment by 2696703792** [comment]
等作者系列

**Comment by huangsijun17** [comment]
双S的代码我不是之前加了个正表来删了吗？还有？不是最新版本？

**Comment by Anders233** [comment]
> 双S的代码我不是之前加了个正表来删了吗？还有？不是最新版本？

请问§符号是在哪里删除的？

**Comment by huangsijun17** [comment]
> > 双S的代码我不是之前加了个正表来删了吗？还有？不是最新版本？
> 
> 请问§符号是在哪里删除的？

https://github.com/Suwings/MCSManager/pull/94

**Comment by Anders233** [comment]
> > > 双S的代码我不是之前加了个正表来删了吗？还有？不是最新版本？
> > 
> > 
> > 请问§符号是在哪里删除的？
> 
> #94

不删除面板上就会显示§[0-9a-z]对吗，为什么不试着转换呢

**Comment by huangsijun17** [comment]
> > > > 双S的代码我不是之前加了个正表来删了吗？还有？不是最新版本？
> > > 
> > > 
> > > 请问§符号是在哪里删除的？
> > 
> > 
> > #94
> 
> 不删除面板上就会显示§[0-9a-z]对吗，为什么不试着转换呢

是某些端会显示，某些没有。目测是原作者都没想到会有段往日志里写这个，所以他没考虑转义，而是只是去将日期等改了彩色。
我是因为我们服务器的符号多到影响阅读，才去吧这个符号删了。

**Comment by huangsijun17** [comment]
没有考虑转义为颜色是因为原来的已经有日期等的改色，再转义成改色导致色彩怪怪的，还容易冲突。
