### ISSUE TITLE
很重要的功能！备份！

### ISSUE THREAD

**Issue by MrSeven590** [Suwings/MCSManager#12]
希望增加一个能自动备份地图的功能，最好能够设置云备份。。。

昨天因为不可抗拒因素，损失了整个服务端

**Comment by Suwings** [comment]
关于备份，事实上已经有很多Minecraft插件已经做到了这一点，我想你可以考虑使用某些插件来完成这个任务。
云备份的话，难以实现，以为这意味着这个免费的项目要为此付出资金，但是我们并没有这一项。

你可以去参考一些插件来实现你的需求。
这个项目如果要加上这个功能，那可能需要很长一段时间，因为这不是一个主要必须的功能。

**Comment by HonokaClub** [comment]
我觉的是不是可以开发一个选项，自动把设置的地图文件夹打包，以email形式发给用户呢？

**Comment by Suwings** [comment]
不太现实，某些服务器经过一段时间地图可能会上GB大小。这个大小纵使压缩，也不适合作为邮件附件发送。

**Comment by HonokaClub** [comment]
hmm 如果是压缩起来放到某个目录，邮件或站内信方式提醒用户呢？
如果上GB的话，小水管服务器一时半会也传不上云端

**Comment by MrSeven590** [comment]
我觉得崩服自动重启，定时自动重启这类的功能是不是可以有

**Comment by Suwings** [comment]
蹦服自动重启功能已经实现，计划在未来版本开发计划任务这类功能。 @MrSeven590

**Comment by Suwings** [comment]
压缩起来放在某个目录，这类功能备份插件已经完整实现并且实现更好（身为外置程序，并不能很好的干预Minecraft 服务端）。
  如果地图上GB，云备份难上加上，我们没有这服务器为此提供。

最重要的是，为此大费周章的实现，代价太大，意义不大。
@HonokaClub

**Comment by HonokaClub** [comment]
了解

**Comment by aliyuchang33** [comment]
我觉得可以直接把Mineos的rdiff-backup restore point移植过来，虽然只有Linux能用

**Comment by HonokaClub** [comment]
@aliyuchang33 短期内还没有这个打算，感谢提供建议辣
