### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by zsn741656478** [Suwings/MCSManager#121]
能否增加一个查看磁盘剩余空间的功能？
以及当前带宽使用量

**Comment by Suwings** [comment]
感谢提供意见，我们会考虑的。

**Comment by zsn741656478** [comment]
> 感谢提供意见，我们会考虑的。

顺便问一下，有自动更新的功能吗？并不知道以后更新后自己需要怎么样操作才能更新0,0。全部重新设置的话太麻烦了

**Comment by Suwings** [comment]
自动更新，目前只支持使用 git 工具获取的软件代码，然后通过 git pull 命令拉取最新的代码，在主分支，最新的代码通常都是可以直接运行的，所以直接拉取即可。

如果没有使用 git，那就只能重新下载发行版本代码，然后解压并且覆盖原文件，即可。

两种更新方式，均不会覆盖你的配置文件，服务器信息和用户信息。

**Comment by zsn741656478** [comment]
> 自动更新，目前只支持使用git工具获取的软件代码，然后通过git pull命令拉取最新的代码，在主分支，最新的代码通常都是可以直接运行的，所以直接拉取即可。
> 
> 如果没有使用git，那就只能重新下载发行版本代码，然后解压并且覆盖原文件，即可。
> 
> 两种更新方式，均不会覆盖你的配置文件，服务器信息和用户信息。

如果覆盖的话，已经修改过的一些图片似乎就跟着被覆盖掉了吧？

**Comment by Suwings** [comment]
> > 自动更新，目前只支持使用git工具获取的软件代码，然后通过git pull命令拉取最新的代码，在主分支，最新的代码通常都是可以直接运行的，所以直接拉取即可。
> > 如果没有使用git，那就只能重新下载发行版本代码，然后解压并且覆盖原文件，即可。
> > 两种更新方式，均不会覆盖你的配置文件，服务器信息和用户信息。
> 
> 如果覆盖的话，已经修改过的一些图片似乎就跟着被覆盖掉了吧？

是的，你对网页或后端代码进行的任何修改，采用直接覆盖方法，会覆盖掉。
配置文件，服务端信息与用户信息目录是分开独立的，启动后才会自动生成，所以不会覆盖。
