### ISSUE TITLE
docker怎么开放多个端口

### ISSUE THREAD

**Issue by YooKing** [Suwings/MCSManager#124]
?

**Comment by Suwings** [comment]
在控制面板 -> 服务端管理 -> 参数 -> Docker 配置 -> 开放端口那里。

以这样的形式进行输入：

如，我想开放 25565 8080 80 这三个端口则：
```
25565:25565 -p 8080:8080 -p 80:80
```

**Comment by IwasawaMasami** [comment]
> 在控制面板 -> 服务端管理 -> 参数 -> Docker 配置 -> 开放端口那里。
> 
> 以这样的形式进行输入：
> 
> 如，我想开放 25565 8080 80 这三个端口则：
> 
> ```
> 25565:25565 -p 8080:8080 -p 80:80
> ```

emm 作者貌似没有容器化dashboard

**Comment by masnn** [comment]
这样设计似乎有注入风险？

**Comment by Suwings** [comment]
> 这样设计似乎有注入风险？

这个参数配置只有管理员才可进行操作，除非是管理员想通过面板进行恶意操作，普通用户是干预不到这个参数的设定。

请保护好管理员的密码，设置极其复杂的密码即可。
