### ISSUE TITLE
将动态界面修改为静态页面地址， 修改 URL.js。

### ISSUE THREAD

**Issue by KarStudio** [Suwings/MCSManager#126]
当前的MCSManager的所有页面均通过一个地址访问，且界面加载须等待WebSocket链接。

希望调整为静态地址 (如https://mcsmanager.org/servers/LOGIN)，且将除必须使用websocket实时传输的数据外的内容无需加载直接显示，可以大幅度提升用户体验。

另 URL.js 过于闹心，希望能自动获取，免除用户手动设置的过程。

**Comment by KarStudio** [comment]
久久无消息了

**Comment by Suwings** [comment]
此反馈早已熟知，但是短期内没有这样的调整计划，十分抱歉！依然感谢你的反馈。
