### ISSUE TITLE
令牌失效后依然可以接受控制台信息或发送指令

### ISSUE THREAD

**Issue by AFlyignPig** [Suwings/MCSManager#127]
令牌失效后仍能接受控制台消息
同样能发送指令
刷新后才不能

**Comment by Suwings** [comment]
我未能测试出你说的情况，能否提供更详细的操作方式与说明。我好重现你所说的情况。

**Comment by AFlyignPig** [comment]
登陆后打开控制台，很久之后令牌过期，
但是扔能接受控制台的消息并发送指令。

**Comment by Suwings** [comment]
你说的令牌，是指第一次登陆之后输入密码，然后接下来一段时间不需要输入密码用于直接登陆的令牌吗？

即：我现在登陆之后，过了大约240分钟（可自定义）之后，令牌失效，如果此时重新刷新网页，那么会要求跳转到登录页面重新登录。但是在此令牌失效期间，依然是可以对面板进行操作的。是这样的情况吗？

如果是这样的情况，那么这是没有问题的。

原因如下：第一次登陆之后，进行身份验证，并且建立了ws网络连接。这个链接不能断开，一旦断开就需要重新验证身份，验证身份也可以靠令牌来验证。于是很久之后，令牌过期，但是ws网络连接还是依然链接着的，这个链接不会过期，所以你依然可以进行收发指令，外者难以干预。

由于令牌过期了，所以你再次刷新网页（重新ws网络链接），就会跳转到登录界面。

**Comment by AFlyignPig** [comment]
好的，谢谢解答
