### ISSUE TITLE
可否修改“ 服务与支持”中“最新动态与信息通知”的获取逻辑？

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#128]
现在是面板重启时自动更新，但我运行在Ubuntu-Server上，可能几周甚至几个月都不会去重启面板。
希望可以修改为由浏览器在每次开启面板时由浏览器获取通知信息，并弹窗提示版本更新。

**Comment by Suwings** [comment]
确实如此，值得修改。

**Comment by Suwings** [comment]
已经实现，等功能再实现几个便一同打包到 8.5.7 版本。

**Comment by huangsijun17** [comment]
谢谢。
