### ISSUE TITLE
node v10+ fs.writeFile问题导致创建目录失败

### ISSUE THREAD

**Issue by kiseopt** [Suwings/MCSManager#134]
在node v10 开始 fs.writeFile中的回调是必要的，因此如果通过面板里的"确认并创建目录" 会导致 eula.txt 写入失败直接提示 目录创建 失败 (实际是目录创建成功，但是...因此到eula写入阶段会直接报错(就不pr了，刚才手滑了

**Comment by Alice-space** [comment]
同一个问题
node 11.0.0

**Comment by Alice-space** [comment]
> > 同一个问题
> > node 11.0.0
> 
> 不会改代码暂时用可以先用我的
> https://github.com/kiseopt/MCSManager-mod
> 修正了 fs.writeFile 和默认情况下 的dockerfile 写错导致的创建docker镜像问题....后面发现新bug也会直接修，但是会加一些我会用到的功能所以酌情使用......
> fs.writeFile 是在V10以上就强制要求回调了，所以只要是V10版本以上就会有这个问题，会直接报TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. 不过解决办法也简单，直接在写入Eula的那里加个回调就行(刚才手滑了....

谢谢啦，现在用node 8.1.0就可以啦

**Comment by Suwings** [comment]
感谢你的反馈，已经修复。
https://github.com/Suwings/MCSManager/commit/de78ad2de1536733d1805b5a6633a8ffeb722c45
