### ISSUE TITLE
希望允许独立的用户开启MC服务端

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#137]
MCSM，我现在是通过systemctl来以独立低权限用户运行，但所有MC服务端也会以该用户运行。
我希望可以指定用户来开启服务端，从而解决由于某些服务端可能存在高权限的文件管理、shell，甚至后门、漏洞等，可能危害管理面板。

**Comment by Suwings** [comment]
短期内没有这个考虑，十分抱歉。
尽可能还是配合docker来使用。
