### ISSUE TITLE
端类型如何修改？

### ISSUE THREAD

**Issue by cnluminous** [Suwings/MCSManager#138]
服务端端类型如何修改？bc服显示为默认端，配置文件无法打开bc的

**Comment by huangsijun17** [comment]
？？？什么意思？什么叫默认端？配置文件无法打开bc的，可以通过FTP里的文件编辑打开。

**Comment by Suwings** [comment]
你说的就是服务端列表里面显示的服务端类型，那只有三个类型，默认是 默认端 自定义 和 未配置。配置文件可以通过文件在线管理在线编辑。
