### ISSUE TITLE
可以拿来开泰拉瑞亚吧。

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#139]
我们那个服主一时兴起，想玩泰拉瑞亚。我试了一下，把泰拉瑞亚开开了，应该没啥问题吧。

**Comment by Suwings** [comment]
除了默认的配置文件不支持读取，其他都没问题，另外配置文件其实可以通过在线文件管理修改。

**Comment by huangsijun17** [comment]
> 除了默认的配置文件不支持读取，其他都没问题，另外配置文件其实可以通过在线文件管理修改。

最后发现几个问题：
1.  无法敲出空白的回车。
2. 泰拉瑞亚的MOD需要放置到$HOME下，我最后是把文件丢服务端目录，再link到了$HOME下的文件夹里面。从而FTP修改。省的那个傻X服主拿SFTP搞，权限搞不清楚。

**Comment by huangsijun17** [comment]
`mv ~/.local/share/Terraria/ModLoader /mnt/minecraft/Terraria/ModLoader
link /mnt/minecraft/Terraria/ModLoader ~/.local/share/Terraria/ModLoader`
PS，服务端们都存放在/mnt/minecraft/。

**Comment by huangsijun17** [comment]
> 除了默认的配置文件不支持读取，其他都没问题，另外配置文件其实可以通过在线文件管理修改。

无法敲出空白的回车这个问题可以解决吗？

**Comment by Suwings** [comment]
我没开过泰拉瑞亚服务器，你说的情况我也不了解。

**Comment by huangsijun17** [comment]
我也是第一次玩泰拉瑞亚，才知道泰拉瑞亚的TModLoader会把MOD等等丢在用户目录下面，而非服务器目录下。才出了这么一个注意，移动过来链接过去。

**Comment by huangsijun17** [comment]
还是这个问题，泰拉瑞亚经常会出现需要在后台敲回车的情况。即不输入内容，直接一个回车。

**Comment by huangsijun17** [comment]
新版前端可以不输入文本，只输入回车符。
