### ISSUE TITLE
无法使用nginx做为web服务

### ISSUE THREAD

**Issue by kot4ri** [Suwings/MCSManager#14]
无法使用nginx做为web服务，希望给面板签个证书，长期使用http明文传输服务器所有数据不太好

**Comment by Suwings** [comment]
我们认为可以通过反向代理来实现你需要的功能，虽然没有采用 https，但是我们登录时提供的账号与密码并不会明文传输，而是只传递MD5混合salt的值，其安全性可以保证，请放心在公共场所登录账号。

**Comment by kot4ri** [comment]
ok
