### ISSUE TITLE
请问关于服务器的开设帮助页面

### ISSUE THREAD

**Issue by Systemyescool** [Suwings/MCSManager#140]
因为最近刚开始玩服务器, 不太懂控制面板应该如何操作.

引导创建服务器那个页面里该填些什么? 希望wiki里有个页面教一下怎么填写这些

我们这个控制面板是不是只支持创建java版的我的世界, 支持创建PE版的我的世界吗??

还是萌新, 感谢大触控制面板~

**Comment by Suwings** [comment]
用自定义命令启动 MC 服务器的话，可以启动任何应用程序，所以你 PE 版本的 Minecraft 也是可以支持的，只是配置文件读取的兼容性，与控制台能否很好的显示，这个问题不能保证。

一般来说，创建一个服务器只需要填写好服务端核心名字，然后创建即可。随后在文件在线管理功能中，上传你的服务端核心文件，名字确保和你规定的名字一致，然后点击开启服务器即可。

**Comment by Systemyescool** [comment]
什么是服务端核心文件啊？我在服务器上拷贝了bedrock-Server的zip包，解压到了那个路径下，但是还是不行。所以pe版的服务端核心文件是啥？

**Comment by Nuyoahhjh** [comment]
服务器核心文件在哪里？

**Comment by huangsijun17** [comment]
> 服务器核心文件在哪里？

您可以从mojang官网或其他第三方核心发布平台下载。
