### ISSUE TITLE
能配置多台服务器吗？

### ISSUE THREAD

**Issue by ldxw** [Suwings/MCSManager#141]
希望可以配置多台服务器，一个面板控制多台服务器搭建，
这样就可以一台直接配置多台了。。

**Comment by Suwings** [comment]
暂时不支持。一个控制面板软件只能控制一台服务器。

**Comment by huangsijun17** [comment]
或许还真可以，把其他电脑的文件映射到本地，再自定义开服命令，通过ssh或者telnet去开服。

**Comment by ldxw** [comment]
> 暂时不支持。一个控制面板软件只能控制一台服务器。

开发个api？这样可以搞第三方开服插件。2333

**Comment by huangsijun17** [comment]
> > 暂时不支持。一个控制面板软件只能控制一台服务器。
> 
> 开发个api？这样可以搞第三方开服插件。2333

这不是一个api就可以解决的事情。而是需要在被控服务器和主控服务器分别安装新的程序。进乎于面板重写。

**Comment by Kiritow** [comment]
可以基于自定义命令来做，主控机+ssh
