### ISSUE TITLE
PocketMine-MP

### ISSUE THREAD

**Issue by ldxw** [Suwings/MCSManager#142]
![mc1](https://user-images.githubusercontent.com/25827746/69140894-70489f80-0afe-11ea-800a-5370e14a4a05.PNG)
![mc2](https://user-images.githubusercontent.com/25827746/69140913-7b9bcb00-0afe-11ea-8331-66e058210fa2.PNG)
这样设置吗？不成功。。

**Comment by Suwings** [comment]
假设你用的是 Windows 的话，你应该是有个启动的命令的（如 java -jar xxx.jar）,如果只有一行，则直接写入到自定义命令中，启动即可。如果有多行，新建一个bat（sh）脚本，然后粘贴到里面，在自定义命令中写入 cmd.exe start.bat 就行。

**Comment by ldxw** [comment]
> 假设您用的是Windows的话，你应该是有个启动的命令的（如java -jar xxx.jar），如果只有一行，则直接写入到自定义命令中，启动即可。如果有多行，新建一个bat（sh）脚本，然后粘贴到里面，在自定义命令中写入cmd.exe start.bat就行。

linux也是同理吧，谢了
