### ISSUE TITLE
内存显示错误问题

### ISSUE THREAD

**Issue by Sprite233** [Suwings/MCSManager#143]
linux应该取available，而不是free
![图片](https://user-images.githubusercontent.com/42002296/69909677-d6f08600-1439-11ea-9e69-d6324761832e.png)
![图片](https://user-images.githubusercontent.com/42002296/69909688-f7b8db80-1439-11ea-9578-f4743d3b7dca.png)

**Comment by huangsijun17** [comment]
这问题，我们（我和服主）年初就注意到了，一直忘了提交。

**Comment by huangsijun17** [comment]
> available

闲着无聊，翻了一下，MCSM是使用了Node.js自带的[os.freemem()](http://nodejs.cn/api/os.html#os_os_freemem)，这很可能是Node.js的锅。

**Comment by huangsijun17** [comment]
> > available
> 
> 闲着无聊，翻了一下，MCSM是使用了Node.js自带的[os.freemem()](http://nodejs.cn/api/os.html#os_os_freemem)，这很可能是Node.js的锅。

[https://github.com/nodejs/node/issues/23892](https://github.com/nodejs/node/issues/23892)
一年多前，别人提交的问题，至今未解决~~~
