### ISSUE TITLE
错误代码128

### ISSUE THREAD

**Issue by dndnt** [Suwings/MCSManager#144]
Ubuntu-Server 19.10

`1191 verbose stack Error: exited with error code: 128
1191 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
1191 verbose stack     at ChildProcess.emit (events.js:182:13)
1191 verbose stack     at maybeClose (internal/child_process.js:962:16)
1191 verbose stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
1191 verbose stack     at Socket.emit (events.js:182:13)
1191 verbose stack     at Pipe._handle.close (net.js:611:12)
1192 verbose cwd /root/mcsmanager
1193 verbose Linux 5.3.0-19-generic
1194 verbose argv "/root/.nvm/versions/node/v11.0.0/bin/node" "/root/.nvm/versions/node/v11.0.0/bin/npm" "install"
1195 verbose node v11.0.0
1196 verbose npm  v6.4.1
1197 error Error while executing:
1197 error /usr/bin/git ls-remote -h -t https://github.com/sstur/nodeftpd.git
1197 error
1197 error fatal: failed to stat '/root/mcsmanager': Permission denied
1197 error
1197 error exited with error code: 128
1198 verbose exit [ 1, true ]
`
[2019-12-04T13_01_28_470Z-debug.log](https://github.com/Suwings/MCSManager/files/3925341/2019-12-04T13_01_28_470Z-debug.log)

**Comment by huangsijun17** [comment]
failed to stat '/root/mcsmanager': Permission denied
权限问题？

**Comment by dndnt** [comment]
> 用的root账户操作，试过了重设目录权限；

> Kali下成功安装了；

> 脚本无法将nvm内容写入.zshrc 。

**Comment by Suwings** [comment]
https://github.com/Suwings/MCSManager/wiki/Linux-%E4%B8%8B%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8%E8%AF%A6%E8%A7%A3

尝试这里面的方法二吧。
