### ISSUE TITLE
linux系统上，希望在启动命令最后加上nogui参数。

### ISSUE THREAD

**Issue by FDuiv** [Suwings/MCSManager#147]
没有做隧道导致启动失败。

**Comment by huangsijun17** [comment]
???
nogui会导致启动失败？什么核心？

**Comment by FDuiv** [comment]
> ???
> nogui会导致启动失败？什么核心？

当你用xshell的时候会申请隧道，如果拒绝MSCManger下的服务就会被结束

**Comment by FDuiv** [comment]
> ???
> nogui会导致启动失败？什么核心？

![image](https://user-images.githubusercontent.com/45262140/70845745-34022800-1e8d-11ea-81c2-934ff2b6abf1.png)

**Comment by FDuiv** [comment]
> ???
> nogui会导致启动失败？什么核心？

![image](https://user-images.githubusercontent.com/45262140/70845758-56944100-1e8d-11ea-9300-09e80bb211d1.png)
我用命令才成功的

**Comment by huangsijun17** [comment]
我用Putty，之前拿Screen来复用，现在是用的systemd。都没有出现过因为nogui导致不开服的问题。xshell的问题？

**Comment by FDuiv** [comment]
> 我用Putty，之前拿Screen来复用，现在是用的systemd。都没有出现过因为nogui导致不开服的问题。xshell的问题？

mcserver是我用笔记本在家里搭的，用阿里云的服务器和nps做tcp隧道连接家里的mcserver，反复启动不行，每次启动都弹出隧道申请，就是windows下那个gui，我本来以为是java的问题，手动启动一边没有加nogui参数，报错，报告和MCSManager一样；当我加上nogui，两边都解决了。所以在某种情况下，不会用命令的人就很难找出报错的原因，所以建议加上nogui也无妨。

**Comment by huangsijun17** [comment]
之前我就提过nogui的问题。因为我这是跑在Ubuntu-Server上面的，没有GUI界面。某次我开了GUI调试一些东西，却发现弹出来GUI。我就此还丢过issues。、
大家都以为只是小bug就没在意。

**Comment by FDuiv** [comment]
> 之前我就提过nogui的问题。因为我这是跑在Ubuntu-Server上面的，没有GUI界面。某次我开了GUI调试一些东西，却发现弹出来GUI。我就此还丢过issues。、
> 大家都以为只是小bug就没在意。

原来如此

**Comment by huangsijun17** [comment]
> > 之前我就提过nogui的问题。因为我这是跑在Ubuntu-Server上面的，没有GUI界面。某次我开了GUI调试一些东西，却发现弹出来GUI。我就此还丢过issues。、
> > 大家都以为只是小bug就没在意。
> 
> 原来如此

我修了，等通过后更新即可。

**Comment by Suwings** [comment]
已更新，感谢 @huangsijun17
