### ISSUE TITLE
关于服务端类型支持更新建议！

### ISSUE THREAD

**Issue by laomie233** [Suwings/MCSManager#15]
建议下一步支持mcpe服务端。
比如：
Nukkit
Genisys
PocketMine
这样pe玩家就有福了！

**Comment by Suwings** [comment]
十分感谢你的建议。
目前，暂时不考虑向Minecraft PE 服务端方面完美支持。
不过我认为，如果你想用于PE端的服务端的话，你也许可以通过"自定义参数"这个功能实现。
谢谢反馈。
