### ISSUE TITLE
分配服务器给用户了，用户不能自己手动更换服务器版本吗？

### ISSUE THREAD

**Issue by duanycmark** [Suwings/MCSManager#151]
比如我创建了一个user：test1，并且分配给他了一个服务器 server1

用户test1怎么才能随时自己切换server1的服务核心版本呢？

**Comment by huangsijun17** [comment]
用户可以去FTP替换jar文件为自己想要的版本。

**Comment by duanycmark** [comment]
> 用户可以去FTP替换jar文件为自己想要的版本。

意思是 还需要再上传一个同名但是核心版本不同的文件吗

**Comment by Suwings** [comment]
> > 用户可以去FTP替换jar文件为自己想要的版本。
> 
> 意思是 还需要再上传一个同名但是核心版本不同的文件吗

对的，用户通过文件管理，上传一个名字与你取的名字一致的核心文件，然后就行了。

**Comment by Suwings** [comment]
另外强调一下，直接出租给用户是不安全的，用户可以通过安装恶意的Java程序，伪装成MC插件或核心文件，来达到入侵宿主机的危险。

如果你是出租给朋友或者信任的人那没关系。但是出租给陌生人请务必使用 Docker 配合使用。如何使用的话，软件页面内部有"这是什么?"的相关链接，你点击它会进入教程，可以按照教程操作。

**Comment by duanycmark** [comment]
> > > 用户可以去FTP替换jar文件为自己想要的版本。
> > 
> > 
> > 意思是 还需要再上传一个同名但是核心版本不同的文件吗
> 
> 对的，用户通过文件管理，上传一个名字与你取的名字一致的核心文件，然后就行了。

服务器启动后会解压核心jar包，如果上传同名其他版本的核心，再次启动的时候解压出来的文件不会覆盖冲突吗

**Comment by Suwings** [comment]
服务器启动后不会解压jar包，只是会生成或下载一些库文件和配置文件，核心文件你可以理解成是一个应用程序，看做一个整体，不会解压。不会有任何冲突覆盖。

核心文件第二次启动时，会判断文件是否存在，存在则读取，不存在则生成。

**Comment by huangsijun17** [comment]
> 另外强调一下，直接出租给用户是不安全的，用户可以通过安装恶意的Java程序，伪装成MC插件或核心文件，来达到入侵宿主机的危险。
> 
> 如果你是出租给朋友或者信任的人那没关系。但是出租给陌生人请务必使用 Docker 配合使用。如何使用的话，软件页面内部有"这是什么?"的相关链接，你点击它会进入教程，可以按照教程操作。

另外。Docker时请不要使用root用户，亦请注意限制端口开放。

**Comment by duanycmark** [comment]
多谢，顺便想问一下 forge ftp上传后怎么运行呢？
