### ISSUE TITLE
forge ftp上传后怎么运行？

### ISSUE THREAD

**Issue by duanycmark** [Suwings/MCSManager#152]
上传核心后 想要支持插件和mod 就需要安装forge ，请问ftp上传后该怎么运行呢？

**Comment by Suwings** [comment]
服务器参数配置，核心文件名字填写你上传的核心名字。

运行第一次，可能会出现要你修改elua协议，修改完毕之后再启动一次，应该会下载生成相应的文件，如果提示缺少文件，那你只能自己去下载所需文件并上传。

**Comment by duanycmark** [comment]
> 服务器参数配置，核心文件名字填写你上传的核心名字。
> 
> 运行第一次，可能会出现要你修改elua协议，修改完毕之后再启动一次，应该会下载生成相应的文件，如果提示缺少文件，那你只能自己去下载所需文件并上传。

forge 怎么启动啊

**Comment by FDuiv** [comment]
> > 服务器参数配置，核心文件名字填写你上传的核心名字。
> > 运行第一次，可能会出现要你修改elua协议，修改完毕之后再启动一次，应该会下载生成相应的文件，如果提示缺少文件，那你只能自己去下载所需文件并上传。
> 
> forge 怎么启动啊

![image](https://user-images.githubusercontent.com/45262140/72130875-ae9f6400-33b5-11ea-884a-847e66b4e8ed.png)
![image](https://user-images.githubusercontent.com/45262140/72130875-ae9f6400-33b5-11ea-884a-847e66b4e8ed.png)
