### ISSUE TITLE
备份问题

### ISSUE THREAD

**Issue by Pai2Chen** [Suwings/MCSManager#154]
这个面板管理是不带有服务器端备份的吗
如果没有，望加上，崩溃回档挺需要的

**Comment by BecodReyes** [comment]
Linux下可配合crontab+tar实现
具体实现方法请自行谷歌

**Comment by Pai2Chen** [comment]
还有请问有没有方法服务器开机时自动把mc服务器打开

**Comment by BecodReyes** [comment]
请使用rc.local或systemctl
具体实现方法请自行谷歌

**Comment by Suwings** [comment]
面板的计划任务拥有开启服务器的功能，但是只能间接性的实现你想要的功能。
列如你设置一个每隔1分钟就开启一次服务器的计划任务，当面板启动时，计划任务也会执行，在随后的继续执行中，因为服务器已经启动，所有不会在启动第二次。

**Comment by Pai2Chen** [comment]
可不可以在面板本身添加这个功能（还有自动备份，这样对新人腐竹比较友好

**Comment by Suwings** [comment]
抱歉，暂无新增自动备份功能的安排。
