### ISSUE TITLE
用MCSM启动的服务器重启后的问题

### ISSUE THREAD

**Issue by Soldier233** [Suwings/MCSManager#155]
有时候服务器重启 面板会正常新开进程 但是这个进程不被面板的控制台控制
如果ctrl z结束面板的node进程 那个不受控制的端也会被关闭
![image](https://user-images.githubusercontent.com/22394506/71776074-1f194000-2fc6-11ea-9b09-4df611b06901.png)
如上图
查这个端口 确实是有端在运行 但是不受这个面板的控制 并且是由面板开启的进程

**Comment by huangsijun17** [comment]
我也遇到过，一般在出错时会有。
