### ISSUE TITLE
MCSM的localhost:23333服务+tcp隧道+Nginx反向代理，可以进行登录，但一直显示正在传输资源

### ISSUE THREAD

**Issue by FDuiv** [Suwings/MCSManager#156]
是这样的：
1.本地服务器上运行着MCSM的localhost:23333
2.利用nps做tcp隧道映射到阿里云公网ip的23333
3.用nginx二级域名反向代理：http://www.mcsmanager.fduiv.com
问题：
可以打开登录页面：
![image](https://user-images.githubusercontent.com/45262140/71908992-fbaeea80-31a9-11ea-9dd5-23659d0844d4.png)
但登录后：
![image](https://user-images.githubusercontent.com/45262140/71909016-09647000-31aa-11ea-8c4f-c199295746b0.png)

**Comment by Suwings** [comment]
这个`正在传输资源`的页面。是需要Websocket来进行传输的，你Nginx是否忘记了此步骤呢？

参考：https://github.com/Suwings/MCSManager/wiki/%E4%BD%BF%E7%94%A8-Apache2.4-%E8%BF%9B%E8%A1%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86

**Comment by FDuiv** [comment]
> 这个`正在传输资源`的页面。是需要Websocket来进行传输的，你Nginx是否忘记了此步骤呢？
> 
> 参考：https://github.com/Suwings/MCSManager/wiki/%E4%BD%BF%E7%94%A8-Apache2.4-%E8%BF%9B%E8%A1%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86

![image](https://user-images.githubusercontent.com/45262140/72045184-771ab400-32f0-11ea-891a-4814149b30e1.png)

**Comment by Suwings** [comment]
就此没看出什么问题，具体原因不清楚，你可以搜一搜其他人提交的 issue。
同时我也看了一下你那个地址，http 的反代已经没问题了，关键就是 ws 链接没有链接上去，只要将ws 成功连接上去即可。

这些也行能帮助你：
https://github.com/Suwings/MCSManager/issues/146
https://github.com/Suwings/MCSManager/issues/89

**Comment by FDuiv** [comment]
> ws 链

是这样的：
1. 我做了两个域名：mscmanager.fduiv.com以及www.mscmanager.fduiv.com。
2. mscmanager.fduiv.com如下设置：
    
![image](https://user-images.githubusercontent.com/45262140/72124211-dcc57980-339e-11ea-8c98-fac002c071e4.png)
3. www.mscmanager.fduiv.com如下设置：

![image](https://user-images.githubusercontent.com/45262140/72124357-6f661880-339f-11ea-9cbd-20b3566e23e3.png)
4. 显然我设置www.mscmanager.fduiv.com映射到mscmanager.fduiv.com：
5. 当“在www.mscmanager.fduiv.com中添加proxy_set_header Host $host;” 或者 “两个域名同时加上proxy_set_header Host $host;”的时候就会出现上面无法传输的情况。然而只在mscmanager.fduiv.com中加上proxy_set_header Host $host;是没有问题的。
效果：
![image](https://user-images.githubusercontent.com/45262140/72124737-c4eef500-33a0-11ea-9584-7be46e14275d.png)

**Comment by Suwings** [comment]
非常不错，感谢提供解决方案以及原因说明，谢谢你对本项目的贡献。
