### ISSUE TITLE
面板后台报错

### ISSUE THREAD

**Issue by Pai2Chen** [Suwings/MCSManager#157]
今天登网页登不上
一看后台报错了
![批注 2020-01-11 133340](https://user-images.githubusercontent.com/46253320/72199437-ffc35c80-3476-11ea-831d-13ea2ffc0b86.jpg)
![批注 2020-01-11 133325](https://user-images.githubusercontent.com/46253320/72199438-005bf300-3477-11ea-9f71-04cf33d5e916.jpg)

**Comment by Suwings** [comment]
最近是否有直接强制关机或者断电式的关机情况？

可以删除 /core/info.json 文件来尝试恢复，重启面板即可。
