### ISSUE TITLE
docker问题

### ISSUE THREAD

**Issue by Pai2Chen** [Suwings/MCSManager#158]
我在创建虚拟镜像的时候
一按下创建镜像，点任务列表，就提示失败，
望求解

**Comment by Suwings** [comment]
创建失败意味着docker环境有问题，如果是创建后瞬间就失败，检查你的docker安装是否正确，输入 docker version 命令试试是否有输出，检查docker相关服务是否已经启动。

如果是创建后等待了一段时间，再显示创建失败，则可能是网络问题。

**Comment by lovekurtwang** [comment]
我也是这一个问题，docker version输出正常，docker run hello-world输出正常，国内镜像源配置正常。ROOT用户服务模式运行mcsm。但创建虚拟镜像，点击后，马上显示构建失败。

**Comment by lovekurtwang** [comment]
以服务模式运行，瞬间失败，使用命令运行就可以了。
