### ISSUE TITLE
二次开发websocket

### ISSUE THREAD

**Issue by CHminggao** [Suwings/MCSManager#159]
我想将终端控制台的websocket广播出去，无需登录就可以操作终端
奈何实在搞不明白，可以出个例子或者文档吗？

**Comment by Suwings** [comment]
较为复杂，ws广播那部分的代码都是必须经过登录授权才可能有权限发送mc服务端日志。

若你真的想做，建议你从 https://github.com/Suwings/MCSManager/blob/master/core/Process/BaseMcserver.js#L220 文件下手，其中220行到221行是mc服务端的日志输出，你可以从这里截断输出，然后以你想要的方式发送出去。

若想无授权执行命令，则可以模仿https://github.com/Suwings/MCSManager/blob/master/route/websocket/console/command.js#L44 来进行尝试。

这并不是很简单，但也不是很困难，如果你有这样的想法，祝你成功！
