### ISSUE TITLE
IPv6支持问题

### ISSUE THREAD

**Issue by Pai2Chen** [Suwings/MCSManager#161]
IPv6已经可以在mc服务器中使用
并且在单独启动服务器核心时可用（不通过mcsm启动
但通过mcsm启动服务器时
ipv6无法连接
望解决

**Comment by Suwings** [comment]
面板启动只是将命令启动方式加入了网页访问功能而已，理论上面板开启 Minecraft 服务端与直接在终端使用命令启动方式是一致的。

控制面板的服务端配置界面，里面有`附加参数`，`自定义启动命令`等 功能。

关于你的 `并且在单独启动服务器核心时可用（不通过mcsm启动` 这句话，你可以参考你自己的服务端的启动命令，复制粘贴到`自定义启动命令`，效果应该会一致，若依然通过面板启动就无法ipv6访问，而使用终端却可以ipv6访问，那么请检查面板控制的那个服务端配置文件，若依然无法找出问题，请在此写下你的服务端类型，版本，系统和网络信息。

控制面板从不干预服务器网络与防火墙，除非你使用了 Docker 配合，那么可能才会有网络访问问题。
若有最新情况，可以在此写下你的情况。

**Comment by huangsijun17** [comment]
在服务器上面直接访问
::1:23333
试试看

**Comment by Pai2Chen** [comment]
> 面板启动只是将命令启动方式加入了网页访问功能而已，理论上面板开启 Minecraft 服务端与直接在终端使用命令启动方式是一致的。
> 
> 控制面板的服务端配置界面，里面有`附加参数`，`自定义启动命令`等 功能。
> 
> 关于你的 `并且在单独启动服务器核心时可用（不通过mcsm启动` 这句话，你可以参考你自己的服务端的启动命令，复制粘贴到`自定义启动命令`，效果应该会一致，若依然通过面板启动就无法ipv6访问，而使用终端却可以ipv6访问，那么请检查面板控制的那个服务端配置文件，若依然无法找出问题，请在此写下你的服务端类型，版本，系统和网络信息。
> 
> 控制面板从不干预服务器网络与防火墙，除非你使用了 Docker 配合，那么可能才会有网络访问问题。
> 若有最新情况，可以在此写下你的情况。

试过用自定义命令了
面板里说要加入jline参数
我在命令行中加入该参数，可以用ipv6
但在面板中却不行

**Comment by Pai2Chen** [comment]
> 在服务器上面直接访问
> ::1:23333
> 试试看

用ipv6可以访问面板但无法访问mc服务器

**Comment by Suwings** [comment]
那你可以试试将启动命令写入到一个sh（bat）文件中，然后在面板自定义命令中写入 sh ./xxxx.sh 来启动这个sh文件，你的服务端就会像你用普通命令一样启动，sh文件里面参数一定要完整。

可以试试，面板是不会阻止你服务端 ipv6 访问的，所以我认为应该是启动参数的问题。
