### ISSUE TITLE
sudo: npm: command not found解决

### ISSUE THREAD

**Issue by cailun123** [Suwings/MCSManager#162]
按照教程一步一步走，遇到sudo: npm: command not found
如何解决

**Comment by huangsijun17** [comment]
你是哪个Linux系统？

**Comment by cailun123** [comment]
> 你是哪个Linux系统？

CentOS7

**Comment by huangsijun17** [comment]
`sudo yum install npm`

**Comment by cailun123** [comment]
> `sudo yum install npm`

还是不行
[root@localhost ~]# sudo yum install npm
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.163.com
 * extras: mirrors.163.com
 * updates: mirror.bit.edu.cn
base                                                         | 3.6 kB  00:00:00     
extras                                                       | 2.9 kB  00:00:00     
updates                                                      | 2.9 kB  00:00:00     
No package npm available.
Error: Nothing to do

**Comment by EKwongChum** [comment]
因为找不到源吧。可以先试试

```shell
sudo yum install epel-release
```

然后再
```shell
sudo yum install npm
```

**Comment by ValiantShishu** [comment]
You try this when the system is completely empty (please follow this exactly)
May solve your problem
http://blog.vlssu.com/views/tutorials/2019/121202.html

**Comment by cailun123** [comment]
Thanks♪(･ω･)ﾉ
已经解决了
