### ISSUE TITLE
Ubuntu18.04无法安装

### ISSUE THREAD

**Issue by junxiesky** [Suwings/MCSManager#163]
使用阿里云华北轻量服务器
运行
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
没有反应

**Comment by mnixry** [comment]
如果无法安装NVM可以尝试直接安装nodejs
[这个安装方式](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions)应该可以给Ubuntu用

安装完成以后输入`node --version`看看有没有报错
如果没有就可以直接跳到`npm install`和`npm start`那一步了

**Comment by junxiesky** [comment]
> 如果无法安装NVM可以尝试直接安装nodejs
> [这个安装方式](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions)应该可以给Ubuntu用
> 
> 安装完成以后输入`node --version`看看有没有报错
> 如果没有就可以直接跳到`npm install`和`npm start`那一步了

搭建成功了，请问如何用此面板搭建pm服务器

**Comment by Suwings** [comment]
使用自定义命令功能启动你的pm服务器，自定义命令中的命令与你使用终端启动方式一致。

**Comment by junxiesky** [comment]
> 使用自定义命令功能启动你的pm服务器，自定义命令中的命令与你使用终端启动方式一致。

显示我没有写入核心名称，无法开服

**Comment by junxiesky** [comment]
> 使用自定义命令功能启动你的pm服务器，自定义命令中的命令与你使用终端启动方式一致。

我用的是./start来启动服务器
