### ISSUE TITLE
请问是否有计划加入多端支持

### ISSUE THREAD

**Issue by emoust** [Suwings/MCSManager#164]
如题，我想让面板前端与后端彻底分离，以便于同时操作多个物理服务器。请问是否有计划支持。
谢谢作者的贡献分享。

**Comment by Suwings** [comment]
暂无此计划。因为面板是开箱即用的轻量级面板系统，每个物理机需要单独部署一个面板。

**Comment by emoust** [comment]
好的，非常感谢。
