### ISSUE TITLE
普通用户权限运行

### ISSUE THREAD

**Issue by IzzelAliz** [Suwings/MCSManager#166]
环境  CentOS 7

面板目前只能运行在超级用户下，有两个问题：

* 运行的服务器实例也是运行在超级用户下的，后门插件和YUM插件可以进行各种高权限操作
* 在线文件编辑功能将会改变文件或（和）目录的 owner

其中第二个问题，我们日常维护都是使用普通用户进行维护，只要面板进行过编辑，那个文件对于普通用户就不能写了，只能每次 chown 或者 sudo 或者一把梭 chmod 777，这三个显然都不好

希望能进行改进

**Comment by Suwings** [comment]
关于权限以及安全问题：
如果你想出租给你的用户的话，请不要直接出租，而是配合docker虚拟化功能来进行，这样的话用户就算上传后门插件或者恶意程序也不会损坏主机。你说的这种情况，如果不使用虚拟化功能的话是无法根治的。

关于编辑文件的问题：
可能确实有这样的现象，我们过段时间会测试这个情况，感谢你的反馈。

谢谢你！

**Comment by IzzelAliz** [comment]
我这里是自用，第一个问题其实用root运行的服务器生成的文件的owner也是root

**Comment by himekifee** [comment]
不是很清楚为啥只能在超级用户，我改了一下systemd的user，普通权限用得挺好，docker加入组就好，就是如过不是docker的实例，插件可以某种程度上获取主机权限，这个也没办法

**Comment by Sciroccogti** [comment]
我认为是安装的时候的脚本就有问题，没有使用sudo，因此安装必须在root用户下。这本身就不合理
