### ISSUE TITLE
容器的端口就进不去

### ISSUE THREAD

**Issue by ldxw** [Suwings/MCSManager#167]
用容器启动端口就进不去，不用容器就可以，懵逼了。。

**Comment by Suwings** [comment]
你这些信息不足以我猜测你的问题所在，请上报更多的信息。

列如：
操作系统版本
面板版本
面板的 Docker 配置截图
面板服务端配置截图

目前根据猜测，你查看一下你的面板中的 Docker 配置中有没有修改命令模板。

若没有修改模板，请查看其配置中是否添加了你的端口，在 `面板主界面->服务端管理菜单项->参数->Docker 配置` 中，有个开放端口，确认它已经填写了你要的端口，并且填写正确，注意格式（如25565:25565）。

如有最新情况，可以继续在此发布。

**Comment by ldxw** [comment]
> 你这些信息不足以我猜测你的问题所在，请上报更多的信息。
> 
> 列如：
> 操作系统版本
> 面板版本
> 面板的 Docker 配置截图
> 面板服务端配置截图
> 
> 目前根据猜测，你查看一下你的面板中的 Docker 配置中有没有修改命令模板。
> 
> 若没有修改模板，请查看其配置中是否添加了你的端口，在 `面板主界面->服务端管理菜单项->参数->Docker 配置` 中，有个开放端口，确认它已经填写了你要的端口，并且填写正确，注意格式（如25565:25565）。
> 
> 如有最新情况，可以继续在此发布。

系统:CentOS 7.7.1908
搭建的宝塔
Mcserver 面板 8.6.0
![容器 镜像](https://user-images.githubusercontent.com/25827746/73446015-f4d55b00-4396-11ea-8ee7-76ef3b2dd41d.png)
![容器配置](https://user-images.githubusercontent.com/25827746/73446017-f56df180-4396-11ea-933f-cf814780629a.png)

在宝塔容器管理器上面看是运行的，手动创建别的容器也是可以

**Comment by Suwings** [comment]
感谢你辛苦的截图，我知道原因所在了，是因为你同时开放了多个端口，端口配置项目那里不支持你那样的写法（-p），如果你要开放多个端口的话，你改上面的那个模板，将${ports}改成你要的样子。

你也可以先开放一个端口试试。

**Comment by ldxw** [comment]
> 感谢你辛苦的截图，我知道原因所在了，是因为你同时开放了多个端口，端口配置项目那里不支持你那样的写法（-p），如果你要开放多个端口的话，你改上面的那个模板，将${ports}改成你要的样子。
> 
> 你也可以先开放一个端口试试。

单端口也不行。。。

**Comment by Suwings** [comment]
很抱歉，过了这么久才回复你，我在面板上看了一个mc服务器，并且测试了一下，端口开放好像没有什么问题，功能依然是正常的。

你可以使用命令 docker ps，来查看docker已经运行的容器，然后里面有一个ports列，如果要是显示端口代理，那就应该没有什么问题。

检查一下网络的配置，如果依然没有什么问题的话，那我也不清楚为什么。

你可以直接改命令模板，改成你需要的样子，多次尝试吧。

**Comment by ldxw** [comment]
> docker ps

![查看容器运行_2020-02-01_01-45-23.png](https://i.loli.net/2020/02/01/wPtfA5J2OSuLdbQ.png)
已经不报希望了，直接java搞起吧。。
