### ISSUE TITLE
Suggestion: Allow managing remote processes via ssh

### ISSUE THREAD

**Issue by masnn** [Suwings/MCSManager#169]
Hope to allow users manage servers on multiple machines.

**Comment by Suwings** [comment]
感谢提供建议，在很早之前已有这样的计划考虑，甚至已经做出了此功能的独立成品（https://github.com/Suwings/Linkresshd），但是出于一些原因未能坚持完成这个功能，未来暂无这样的计划考虑，还请理解。

**Comment by masnn** [comment]
Suggest to type a space before&after the link.
Do you accept pull requests for this?

**Comment by Suwings** [comment]
建议在链接前与后加入一个空格，你指的是什么？

控制面板的终端显示输出的时候，链接前后增加空格？还是指刚刚我发的回复。

**Comment by masnn** [comment]
I mean the reply.
Or you can use [Markdown Link](https://github.com/Suwings/Linkresshd) .
