### ISSUE TITLE
Linux版本上可以考虑用Docker来实现整体的虚拟化

### ISSUE THREAD

**Issue by XiLingHost** [Suwings/MCSManager#17]
Docker是个很方便的工具，不仅可以用于虚拟化，还可以便于在不同环境下的快速部署。
就当前这个安装方式来看，Dockerfile还是很好写的。
Dockerfile:
`FROM node:latest`
`RUN echo "deb http://http.debian.net/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list`
`RUN apt-get update && apt-get install -t jessie-backports openjdk-8-jdk -y`
`WORKDIR /opt`
`RUN git clone https://github.com/Suwings/MCSManager.git`
`WORKDIR /opt/MCSManager`
`RUN npm install --production`
`EXPOSE 23333`
`EXPOSE 10021`
`CMD npm start`

运行的时候用-p来添加端口映射即可。

**Comment by Suwings** [comment]
感谢提供建议，Docker 在近期有计划打算投入使用，只是工作忙碌，暂时没有行动，不过我们会尽快为我们的项目加入 Docker。
并且想一下用一种更好的姿势来使用 Docker。

**Comment by XiLingHost** [comment]
Docker的一个问题在于，Minecraft的端口是可自定义的，但是Container被创建之后，它的端口映射就不可被修改了。
不过我倒是有个想法，可以尝试集成[frpc](https://github.com/fatedier/frp)到docker的image内，然后host运行frps，这样可以不需要使用docker提供的端口映射方案。
如果是这种方案的话，在启动服务器的时候需要一个脚本来检查server.properties的server-port参数，并且运行一个frpc实例来进行反向代理。
还有一个问题就是我在使用的时候发现如果把./server映射为volume之后，在新建服务端的时候会无法正常创建目录。

**Comment by Suwings** [comment]
实际上问题可能更多，这需要进一步的研究。

**Comment by HonokaClub** [comment]
顺便 欢迎PR
