### ISSUE TITLE
Suggestion:Allow users to customize server parameters

### ISSUE THREAD

**Issue by ValiantShishu** [Suwings/MCSManager#170]
- Allow users to customize server parameters
- If you can, can you add a one-click Minecraft service pack to let users quickly add a Minecraft service pack
- In a single server page, given a certain amount of memory, can you only show him the amount of memory, not the amount of the entire server

**Comment by Suwings** [comment]
关于用户可自定义启动参数。准许用户自定义服务器参数我们认为是十分危险的，这部分应该由服务商为其分配。

关于一键快捷添加服务端包。这一点十分感谢你的建议，我们已在未来功能的计划中，有这方面的考虑。

关于只显示特定分配的内存给予用户显示，暂无这方面的考虑。不过从一开始就有这方面适当的改进，普通用户是看不见剩余内存与整体内存的具体数值的，普通用户只能获取到内存使用百分比，不过这个百分比是相当于你的整个主机。

**Comment by ValiantShishu** [comment]
- 如果能添加参数让用户选择也是不错的注意，现在有很多人都使用外置登录（authlib-injector），能否让用户有权利选择含有外置登录的参数时自定义填写认证服务器地址？
- 如果可以，很希望只显示给予用户的内存来显示
  - 比如用户在看到还没用服务器就已经占到如此之高的内存占比

**Comment by Suwings** [comment]
谢谢你的建议，我们会做考虑并有相关的调整。
