### ISSUE TITLE
无法创建文件夹

### ISSUE THREAD

**Issue by mincoft** [Suwings/MCSManager#172]
在正确安装并打开端口后,引导中文件夹创建失败,后台无报错.
使用用户:root    
系统:Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-117-generic i686)
服务提供商:aliyun
硬件配置:1vCPU1GiB
Node版本:10.0.0

![TIM截图20200210203847](https://user-images.githubusercontent.com/32572293/74150812-aa30ca00-4c45-11ea-99f9-9957e6c429dc.png)

**Comment by mincoft** [comment]
https://sm.ms/image/vxjdXu8KWBQpwqL 图片,请手动复制打开查看截图

**Comment by huangsijun17** [comment]
目测是权限问题。

**Comment by huangsijun17** [comment]
@Suwings 我看了一下，`fs.mkdirSync`和`fs.mkdir` 需要添加参数`{ recursive: true }`来实现递归创建目录。否则新建目录时父目录不存在则会创建失败。

[fs | Node.js API 文档](http://nodejs.cn/api/fs.html#fs_fs_mkdir_path_options_callback)

**Comment by Suwings** [comment]
> @Suwings 我看了一下，`fs.mkdirSync`和`fs.mkdir` 需要添加参数`{ recursive: true }`来实现递归创建目录。否则新建目录时父目录不存在则会创建失败。
> 
> [fs | Node.js API 文档](http://nodejs.cn/api/fs.html#fs_fs_mkdir_path_options_callback)


> v10.12.0 | The second argument can now be an options object with recursive and mode properties.

这个选项是 10.12.0 版本才有的功能，目前要求兼容 8.0 版本。
不过加上也无妨，感谢你的提醒，我会解决这个问题，使用原本就已经依赖 `fs-extra` 库的功能就行。

**Comment by Suwings** [comment]
> @Suwings 我看了一下，`fs.mkdirSync`和`fs.mkdir` 需要添加参数`{ recursive: true }`来实现递归创建目录。否则新建目录时父目录不存在则会创建失败。
> 
> [fs | Node.js API 文档](http://nodejs.cn/api/fs.html#fs_fs_mkdir_path_options_callback)

已修复https://github.com/Suwings/MCSManager/commit/db4973a003046eb7846d26ad988781aed0e23f65
