### ISSUE TITLE
自定义命令开Terraria服务器报错 MCPingProtocol.js:42:45

### ISSUE THREAD

**Issue by ACGMC** [Suwings/MCSManager#173]
[ 2020-2-13 3:55:31 ] [ ERROR ] UncaughtException 机制错误报告:
TypeError: Cannot read property 'replace' of undefined
    at Socket.<anonymous> (/root/MCSM/mcsmanager/helper/MCPingProtocol.js:42:45)
    at Socket.emit (events.js:219:5)
    at addChunk (_stream_readable.js:332:12)
    at readableAddChunk (_stream_readable.js:307:11)
    at Socket.Readable.push (_stream_readable.js:241:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:185:23)
--------Error-------

系统Centos8x64
能开其他服务器不报错
今天哦儿看了下控制台一直在刷这个,,terraria控制台在刷下面这个
192.168.31.1:53676 is connecting...
192.168.31.1:53700 is connecting...
192.168.31.1:53722 is connecting...
192.168.31.1:53746 is connecting...
[ SYSTEM ] MCSM Console... 
192.168.31.1:53770 is connecting...
192.168.31.1:53794 is connecting...

**Comment by huangsijun17** [comment]
我开过，可以开启。建议检查命令是否正确。

**Comment by ACGMC** [comment]
是开起来了但是 linux MCSM控制台刷报错~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "huangsijun17"<notifications@github.com&gt;; 
发送时间: 2020年2月13日(星期四) 下午4:58
收件人: "Suwings/MCSManager"<MCSManager@noreply.github.com&gt;; 
抄送: "炳松"<ACGMC@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Suwings/MCSManager] 自定义命令开Terraria服务器报错 MCPingProtocol.js:42:45 (#173)




我开过，可以开启。建议检查命令是否正确。

**Comment by huangsijun17** [comment]
> 是开起来了但是 linux MCSM控制台刷报错~~
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "huangsijun17"<notifications@github.com&gt;; 发送时间: 2020年2月13日(星期四) 下午4:58 收件人: "Suwings/MCSManager"<MCSManager@noreply.github.com&gt;; 抄送: "炳松"<ACGMC@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [Suwings/MCSManager] 自定义命令开Terraria服务器报错 MCPingProtocol.js:42:45 (#173) 我开过，可以开启。建议检查命令是否正确。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你要给完整的信息啊。这行报错是什么时候出现的？拿终端直接开是否有？

**Comment by ACGMC** [comment]
给了 整个目录 777权限  好像没事了

**Comment by huangsijun17** [comment]
> 给了 整个目录 777权限 好像没事了

没问题的话，就自己把issue关了吧。
