### ISSUE TITLE
如何导入存档

### ISSUE THREAD

**Issue by IseeIthought** [Suwings/MCSManager#174]
请问如何用现有存档开服

**Comment by Suwings** [comment]
先启动一次服务器，将改配置的配置好，接下来关闭服务器删除world目录，然后上传你的存档文件夹，改名为world即可，再开启服务器。

**Comment by IseeIthought** [comment]
非常感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Suwings"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 中午1:19
收件人:&nbsp;"Suwings/MCSManager"<MCSManager@noreply.github.com&gt;;
抄送:&nbsp;"枫云"<761053568@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Suwings/MCSManager] 如何导入存档 (#174)




先启动一次服务器，将改配置的配置好，接下来关闭服务器删除world目录，然后上传你的存档文件夹，改名为world即可，再开启服务器。
