### ISSUE TITLE
希望能够优化计划任务,实现随面板启动而启动服务器实例

### ISSUE THREAD

**Issue by Shanwer** [Suwings/MCSManager#175]
RT，我是新人...
首先很感谢有这个面板的存在，确实好用
然后，我是windows操作系统，我在任务计划程序里设置了随开机自启而启动管理面板，可是如何在自行启动完面板后再自行启动服务器实例...我遇到了难题，而面板自带的任务计划我也不会用，所以就希望MCSM能够更加自动化一点...我是环保主义者，准时开关机节约电能

**Comment by Suwings** [comment]
暂时还没有这样的功能，但是目前有个间接的实现方式。

你在 面板的计划任务项目 中创建一个新项目，接下来设置时间为每隔1分钟，命令是__start__即服务器开启命令，这样的话面板一旦启动，一分钟后服务器也会被启动，又因为面板有重复启动保护，所以多次执行启动计划任务是无效的，只有关闭之后再启动才会有效。

当然这个会对你临时的正常关服有困难，因为计划任务还是会启动你的服务器。

**Comment by Shanwer** [comment]
> 暂时还没有这样的功能，但是目前有个间接的实现方式。
> 
> 你在 面板的计划任务项目 中创建一个新项目，接下来设置时间为每隔1分钟，命令是__start__即服务器开启命令，这样的话面板一旦启动，一分钟后服务器也会被启动，又因为面板有重复启动保护，所以多次执行启动计划任务是无效的，只有关闭之后再启动才会有效。
> 
> 当然这个会对你临时的正常关服有困难，因为计划任务还是会启动你的服务器。

谢谢，另外，在面板内输入中文会变成乱码，怎么解决？

**Comment by Suwings** [comment]
创建服务器之后，进入面板的服务端管理界面，点那个服务端的参数选项，右边有个控制台输入输出编码配置，改成GBK或者UTF8试试。

**Comment by Shanwer** [comment]
解决了，谢谢
