### ISSUE TITLE
已经安装node 但是启动面板时会提示sudo: node: command not found

### ISSUE THREAD

**Issue by tanix12qly** [Suwings/MCSManager#176]
`root@vultr:~# cd mcsmanager/
root@vultr:~/mcsmanager# sudo node app.js
sudo: node: command not found
root@vultr:~/mcsmanager# nvm install 11.0.0
v11.0.0 is already installed.
Now using node v11.0.0 (npm v6.4.1)
root@vultr:~/mcsmanager# nvm use 11.0.0
Now using node v11.0.0 (npm v6.4.1)
`

**Comment by Suwings** [comment]
不加 sudo 试试。
