### ISSUE TITLE
计划任务项目如何设定执行时间？

### ISSUE THREAD

**Issue by FDuiv** [Suwings/MCSManager#177]
现在只能设定周期，比如凌晨3点重启，开始时间如何设置？

**Comment by Suwings** [comment]
列如设置在每日凌晨3点执行一次：
`* * 3 * * *` 

如果是想每隔3个小时执行一次：
`* * */3 * * *` 

如果设置3月20号凌晨1点10分执行，并将执行次数设置为1。
`* 10 1 20 3 *`

具体使用方法如下：
```
* * * * * *
┬ ┬ ┬ ┬ ┬ ┬
│ │ │ │ │ │
│ │ │ │ │ └ day of week (0 - 7) (0 or 7 is Sun)
│ │ │ │ └───── month (1 - 12)
│ │ │ └────────── day of month (1 - 31)
│ │ └─────────────── hour (0 - 23)
│ └──────────────────── minute (0 - 59)
└───────────────────────── second (0 - 59, OPTIONAL)
```

**Comment by FDuiv** [comment]
> 列如设置在每日凌晨3点执行一次：
> `* * 3 * * *`
> 
> 如果是想每隔3个小时执行一次：
> `* * */3 * * *`
> 
> 如果设置3月20号凌晨1点10分执行，并将执行次数设置为1。
> `* 10 1 20 3 *`
> 
> 具体使用方法如下：
> 
> ```
> * * * * * *
> ┬ ┬ ┬ ┬ ┬ ┬
> │ │ │ │ │ │
> │ │ │ │ │ └ day of week (0 - 7) (0 or 7 is Sun)
> │ │ │ │ └───── month (1 - 12)
> │ │ │ └────────── day of month (1 - 31)
> │ │ └─────────────── hour (0 - 23)
> │ └──────────────────── minute (0 - 59)
> └───────────────────────── second (0 - 59, OPTIONAL)
> ```

谢谢

**Comment by FDuiv** [comment]
> 列如设置在每日凌晨3点执行一次：
> `* * 3 * * *`
> 
> 如果是想每隔3个小时执行一次：
> `* * */3 * * *`
> 
> 如果设置3月20号凌晨1点10分执行，并将执行次数设置为1。
> `* 10 1 20 3 *`
> 
> 具体使用方法如下：
> 
> ```
> * * * * * *
> ┬ ┬ ┬ ┬ ┬ ┬
> │ │ │ │ │ │
> │ │ │ │ │ └ day of week (0 - 7) (0 or 7 is Sun)
> │ │ │ │ └───── month (1 - 12)
> │ │ │ └────────── day of month (1 - 31)
> │ │ └─────────────── hour (0 - 23)
> │ └──────────────────── minute (0 - 59)
> └───────────────────────── second (0 - 59, OPTIONAL)
> ```

如果可以，希望增加一个计划组，一条条计划管理起来过于凌乱 : )

**Comment by huangsijun17** [comment]
> 列如设置在每日凌晨3点执行一次：
> `* * 3 * * *`
> 
> 如果是想每隔3个小时执行一次：
> `* * */3 * * *`
> 
> 如果设置3月20号凌晨1点10分执行，并将执行次数设置为1。
> `* 10 1 20 3 *`
> 
> 具体使用方法如下：
> 
> ```
> * * * * * *
> ┬ ┬ ┬ ┬ ┬ ┬
> │ │ │ │ │ │
> │ │ │ │ │ └ day of week (0 - 7) (0 or 7 is Sun)
> │ │ │ │ └───── month (1 - 12)
> │ │ │ └────────── day of month (1 - 31)
> │ │ └─────────────── hour (0 - 23)
> │ └──────────────────── minute (0 - 59)
> └───────────────────────── second (0 - 59, OPTIONAL)
> ```

把这个注释丢wiki里吧。

**Comment by Suwings** [comment]
> > 列如设置在每日凌晨3点执行一次：
> > `* * 3 * * *`
> > 如果是想每隔3个小时执行一次：
> > `* * */3 * * *`
> > 如果设置3月20号凌晨1点10分执行，并将执行次数设置为1。
> > `* 10 1 20 3 *`
> > 具体使用方法如下：
> > ```
> > * * * * * *
> > ┬ ┬ ┬ ┬ ┬ ┬
> > │ │ │ │ │ │
> > │ │ │ │ │ └ day of week (0 - 7) (0 or 7 is Sun)
> > │ │ │ │ └───── month (1 - 12)
> > │ │ │ └────────── day of month (1 - 31)
> > │ │ └─────────────── hour (0 - 23)
> > │ └──────────────────── minute (0 - 59)
> > └───────────────────────── second (0 - 59, OPTIONAL)
> > ```
> 
> 把这个注释丢wiki里吧。

已添加：
https://github.com/Suwings/MCSManager/issues/177#issuecomment-590020035
