### ISSUE TITLE
调用普通外置接口出现跨域问题

### ISSUE THREAD

**Issue by greenhaha** [Suwings/MCSManager#179]
用jq 调用普通外置接口 提示跨域问题
控制台输出：
Access to XMLHttpRequest at 'http://xx.xx.xx.xx:xxxxx/api/status/l4d2_server_1' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

面板所在系统环境
os：centos 7
node：v13.3.0
npm: v6.13.1

**Comment by Suwings** [comment]
第一次运行时会生成一个名叫`property.js`的配置文件，打开此文件，编辑此行（大约68行）：

https://github.com/Suwings/MCSManager/blob/master/model/init_config/property.js#L68

`MCSERVER.localProperty.is_allow_csrf = false` 改为 `true`
