### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 1013403878** [Suwings/MCSManager#18]
建议添加的创建服务器时可以分配给谁，创建完成后也可以更改
然后#开头的用户可以直接拥有权限，
在服务端管理页面增加 开启，关闭，重启，按钮

**Comment by HonokaClub** [comment]
1与3已经实现 个人认为 

> #开头的用户可以直接拥有权限 

不是一个值得采纳的决定。因为有的用户可能希望其创建的用户的用户名都以#开头

**Comment by Suwings** [comment]
你所说的功能，是已经全部完全实现的功能。
不只是1与3点，你所说的功能是已经全部实现并且在最新版本里面。
可能你没有注意到或者你是使用的旧版本。 

如果依然有疑惑，可以继续联系我。
@1013403878

**Comment by Suwings** [comment]
这个控制面板是以 # 符号开头来决定这个账号是否是一个 高级账号。
这个功能也是已经在使用的。 @HonokaClub
