### ISSUE TITLE
安装到树莓派提示bash: nvm :未找到命令

### ISSUE THREAD

**Issue by wang3311835119** [Suwings/MCSManager#180]
输入的命令是nvm install 11.0.0
且wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash命令已执行，终端已重新打开
![QQ图片20200222094649](https://user-images.githubusercontent.com/43809955/75084029-44531500-5558-11ea-82e4-63e7fe560f9c.png)

**Comment by Suwings** [comment]
那就只能尝试手动安装 node 环境在你的系统上，具体方案请搜索树莓派安装node环境，安装好node环境之后，就可以跳过安装 nvm，再直接clone仓库代码，使用 npm install 安装依赖，npm start 即可运行。

**Comment by huangsijun17** [comment]
我们并不知晓你的树莓派安装的是哪一个Linux系统（甚至是自己编译的某个）。

MCSManager只基于 Node.js 环境。所以任意安装 Node.js 环境的方法即可。README.md的方法不适合多用户（Linux用户）安装，我就用别的方法装的。

你这个问题的具体方法建议还是谷歌一下你的机型、系统安装（编译）Node.js 的方法比较好。
