### ISSUE TITLE
使用frp进行内网穿透时无法正常使用面板

### ISSUE THREAD

**Issue by Cnzw** [Suwings/MCSManager#182]
- 平台:winserver 2008

- 使用[Sakura Frp](https://www.natfrp.com/) **frpc** 进行内网穿透

### 具体表现:

1. 访问地址时可以正常显示登录界面,也可以正常输入密码登录

1. 登录在显示"请稍等,正在传输资源 ..."的同时提示"服务器链接中断，数据发送失败，请刷新或登陆重试"

1. 面板后台显示用户在建立链接后的瞬间就断开链接了

### 题外话:

- 已关闭property.js中的gzip

- 是不是和ws有关

- 可以提供账户协助排查问题

**Comment by Suwings** [comment]
很有可能跟ws无法连接有关，如果可以正常显示登陆界面并且可以正常登陆，那么就代表HTTP访问没有问题，再加上显示"请稍等,正在传输资源 ..."的提示，非常有可能是Websocket无法连接上。

我没有使用过 Sakura Frp 软件，你看看此软件是否能够支持这方面的穿透。

如果无法支持支持ws，则可能难以实现，建议还是搭建在有外网ip的服务器上。

**Comment by Cnzw** [comment]
> 很有可能跟ws无法连接有关，如果可以正常显示登陆界面并且可以正常登陆，那么就代表HTTP访问没有问题，再加上显示"请稍等,正在传输资源 ..."的提示，非常有可能是Websocket无法连接上。
> 
> 我没有使用过 Sakura Frp 软件，你看看此软件是否能够支持这方面的穿透。
> 
> 如果无法支持支持ws，则可能难以实现，建议还是搭建在有外网ip的服务器上。

Sakura Frp 是使用 [frpc](https://github.com/fatedier/frp) 进行内网穿透的,frpc支持ws转发
能问一下ws的端口是多少吗(呃,也许这个问题比较蠢 [百度到的解决方法](https://www.right.com.cn/forum/thread-264594-1-1.html))

**Comment by Cnzw** [comment]
**已找到解决方法**
1. 新建一个tcp映射,将23333端口映射到到服务器任意端口
2. 修改 /public/common/js/websocket.js 的第 19 行
`//原代码
window.WS = new WebSocket(MCSERVER.URL(wsURL, MCSERVER.WS_PROTOCOL));
//现代码
window.WS = new WebSocket('ws://example.com:port/websocket/ws? + RES.TOKEN_NAME + '=' + RES.TOKEN');
`
因为直接修改 wsURL 会被 MCSERVER.URL() 转换从而失效,只能出此下策
经过短暂测试,所有功能未受影响.希望给后来的朋友一个解决方法
