### ISSUE TITLE
[Critical] 普通用户可以用配置docker提权

### ISSUE THREAD

**Issue by himekifee** [Suwings/MCSManager#183]
最新版，普通用户可以通过配置docker命令进行docker提权获取宿主机的权限，望尽快修复

**Comment by huangsijun17** [comment]
你拿Root执行的MCSM吧。

**Comment by himekifee** [comment]
不，普通用户在docker组

**Comment by himekifee** [comment]
我的意思是，面板的普通用户可以配置docker，我希望只有#master可以

**Comment by huangsijun17** [comment]
面板的普通用户可以？你确定不是#开头的管理员用户？

**Comment by himekifee** [comment]
不是，你等下，我再测试下

**Comment by himekifee** [comment]
没事了，我sb了，我用户可能不太明白docker配置是啥
