### ISSUE TITLE
Docker实例在强制停止服务器时不会stop

### ISSUE THREAD

**Issue by himekifee** [Suwings/MCSManager#184]
rt，从docker内ps可以看到已经没有在运行服务端，但是容器并没有被释放，导致端口被持续占用。我加了两个参数，分别是--rm 和 --user 1000:1000

**Comment by Suwings** [comment]
在使用 Docker 启动 Minecraft 服务端时，如果强制停止服务端时，可能的确存在这个问题。
目前建议还是尽可能通过正常命令退出的方式来关闭，这个问题我们也会排查并修复，谢谢反馈。

**Comment by himekifee** [comment]
好的，那就先开着吧

**Comment by Suwings** [comment]
已更新并修复：
https://github.com/Suwings/MCSManager/releases/tag/v8.6.6

@himekifee
