### ISSUE TITLE
一键关服依然会变成批量重启

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#185]
只有第一台被关的服务器不会自动重启。

**Comment by Suwings** [comment]
是不是其他服务器`崩溃重启`功能一直是开启的？所以在关闭所有服务端的时候就导致有些服务端会重启。

等会我改进一下这方面的代码。

**Comment by Suwings** [comment]
已修复这段代码，若不想更新的话，可以复制更改处的代码。

经过测试，所有开启了崩溃自动重启功能的服务端也会依然批量关闭。

Commit：https://github.com/Suwings/MCSManager/commit/a032de1d8df44045e38a2660ec21168748cdeaa9
