### ISSUE TITLE
centos安装后启动出错

### ISSUE THREAD

**Issue by TANGhz17** [Suwings/MCSManager#186]
[ 2020-3-2 18:51:42 ] [ Online_Fs ] 初始化 Online_Fs 路由与中间件 
[ 2020-3-2 18:51:42 ] [ Module ] 正在初始化用户管理模块

#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0x7ffed9d8cae0非法指令(吐核)

**Comment by Suwings** [comment]
你是使用的什么安装方式安装的，建议重装nodejs环境，再尝试一下。

**Comment by TANGhz17** [comment]
似乎只能8.0node，12.0不行哎

**Comment by huangsijun17** [comment]
CentOS8一切正常。

**Comment by Suwings** [comment]
这是Nodejs的问题，详情：https://github.com/nodejs/node/issues/27379

请不要使用 12.0.0 版本，教程已经修改版本。

https://github.com/Suwings/MCSManager/wiki/Linux-%E4%B8%8B%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8%E8%AF%A6%E8%A7%A3
