### ISSUE TITLE
新版终端没有历史记录功能

### ISSUE THREAD

**Issue by 10935336** [Suwings/MCSManager#187]
希望能添加历史记录功能，或者是切换回老版终端的方法。没有历史记录功能的话对管理服务器非常不利。

**Comment by Suwings** [comment]
这个功能刚出，原来老版的历史记录不适用现在新的终端界面，

我们会想办法把历史记录功能重新加回来的。

**Comment by Suwings** [comment]
已更新：

https://github.com/Suwings/MCSManager/releases/tag/v8.6.5

**Comment by himekifee** [comment]
有一个问题，现在看起来是从文件读取的日志，像paper它用的是自定义的log4j配置，如果是终端就能呢个正确显示颜色，但是从文件的话，就只能手动覆盖log4j.xml了

**Comment by Suwings** [comment]
终端功能没有从文件读取日志，所有日志来源都来自子进程的标准输入输出。

历史记录功能也没有读取任何文件，是将标准输出内容以每行为基本单位储存在内存中，由一个数组来维护。

为避免内存占用过大或数组臃肿，每个服务端最多存储1000行日志短历史左右，主要是为了方便回顾最近的情况。

如果想真正查看长期的历史记录，还是通过文件在线管理编辑日志文件来显示为好。



> 有一个问题，现在看起来是从文件读取的日志，像paper它用的是自定义的log4j配置，如果是终端就能呢个正确显示颜色，但是从文件的话，就只能手动覆盖log4j.xml了

**Comment by himekifee** [comment]
那为什么颜色会消失呢

**Comment by Suwings** [comment]
因为更新了新版本终端，原来的颜色是前端渲染的，跟服务端输出没有任何关系，也就是哪怕你输出没有任何颜色，控制台都会有颜色，因为网页的代码将日志的每一行都解析并加上了颜色。

新版本的终端不再是原先的老式文本输出，已经可以支持 Linux 终端颜色，关于 Minecraft 服务端为什么没有颜色，一方面是某些服务端输出原本就是没有任何颜色的，还有就是 Minecraft 的颜色代码符号还未解析，未来版本会在后端对颜色进行解析，以后会有颜色的。

**Comment by himekifee** [comment]
paper确实是stdout没什么颜色，它自己改过log4j，只有它的终端有颜色，还是等后续版本吧
