### ISSUE TITLE
如何控制已有服务端

### ISSUE THREAD

**Issue by GayFirends** [Suwings/MCSManager#188]
突然发现了这个项目，但我已经跑了一个服务，请问如何将已有的服务器在MCSM上面使用？？？

**Comment by Suwings** [comment]
**方法一：直接设置本地目录（适合面板所有者是自己）**

首先在服务端管理界面点击`创建服务器`按钮，使用`快速创建`模式，在服务端文件目录那一栏填写你的旧服务端目录绝对地址。然后点击创建成功即可。

这样的话，所设置的那个目录就可以被面板控制。

**方法二：将已有服务器导入到面板**

首先在服务端管理界面点击`创建服务器`按钮，使用引导创建流程，取号名字，并将你的服务端核心文件上传，设置好参数后即可创建完成。

接下来先不急着开服，将你已有的服务器存档，插件和配置文件压缩打包，从`文件在线管理`功能上传文件，解压文件之后即可像原本的样子开服。

**Comment by GayFirends** [comment]
> **方法一：直接设置本地目录（适合面板所有者是自己）**
> 
> 首先在服务端管理界面点击`创建服务器`按钮，使用`快速创建`模式，在服务端文件目录那一栏填写你的旧服务端目录绝对地址。然后点击创建成功即可。
> 
> 这样的话，所设置的那个目录就可以被面板控制。
> 
> **方法二：将已有服务器导入到面板**
> 
> 首先在服务端管理界面点击`创建服务器`按钮，使用引导创建流程，取号名字，并将你的服务端核心文件上传，设置好参数后即可创建完成。
> 
> 接下来先不急着开服，将你已有的服务器存档，插件和配置文件压缩打包，从`文件在线管理`功能上传文件，解压文件之后即可像原本的样子开服。

thx :-P
