### ISSUE TITLE
windows下无法自动重启

### ISSUE THREAD

**Issue by KYLN24** [Suwings/MCSManager#189]
已打开崩溃重启

服务器端崩溃后，控制台提示找不到start.sh，然而windows下并不用这个启动脚本

**Comment by huangsijun17** [comment]
？？？？
start.sh？
你的开服指令是什么？

**Comment by KYLN24** [comment]
### 开服指令
开服指令是在 服务端管理-参数 里直接填写的
Java 路径 C:\Program Files\Java\jre1.8.0_202\bin\java.exe
服务端文件名 Spigot.jar
启动附加参数 -javaagent:authlib-injector.jar=http://***/api/yggdrasil -XX:+AggressiveOpts
服务器根目录 D:\server
未使用完全自定义启动命令

### 版本
前端发行版: 8.6.1 发行版本
后端发行版: 8.6.1 发行版本
操作系统
系统与平台: Windows_NT ia32 WIN-1PJ2B2S1IMM 10.0.14393
进程根目录: D:\MCSManager

### 报错信息
Startup script './start.sh' does not exist! Stopping server.
Stopping server

**Comment by Suwings** [comment]
根据这条错误信息：
```
Startup script './start.sh' does not exist! Stopping server.
Stopping server
```

这并不是来自控制面板的报错信息，而是来自你的 Spigot 服务端输出的报错信息。

你先复制一份新的 Spigot 服务端，没有任何插件与任何附加参数，使用控制面板进行启动。如果启动成功并正常自动重启，则是某个插件导致的重启失效。


你目前的情况是在你说描述的配置下能够正常开启服务器？仅仅只是自动重启功能无效？

我会对这方面的代码进行检查，如果有其他情况可以继续反馈。

**Comment by 10935336** [comment]
这个应该是spigot.yml的问题
```
restart-on-crash: false
restart-script: ./start.sh
```
如果你设置为true，服务器崩溃的时候spigot会尝试调用start.sh，用MCS的话并不需要这个功能。

**Comment by KYLN24** [comment]
确实是打开的！谢谢，麻烦您了。
