### ISSUE TITLE
命令行输入指令无效

### ISSUE THREAD

**Issue by BadGGL** [Suwings/MCSManager#193]
编码格式已经设置成utf-8了，浏览器页面编码也是utf-8。但是我从页面输入指令就是没有效果的，相同的指令 别人用linux版本的QQ发给我，然后我复制进去输入就是有效的，这个有办法解决吗

**Comment by Suwings** [comment]
你启动的程序是什么程序，Spigot 服务端还是什么？执行的指令是什么？系统环境与面板版本，如果能有服务端参数设置的截图更好。
