### ISSUE TITLE
MCSManager进程突然结束

### ISSUE THREAD

**Issue by Coloryr** [Suwings/MCSManager#194]
MCSManager进程原本正常运行，服务器也没问题，
但是好像后台日志刷多了（日志600MB多了）MCSManager进程就没了
这是bug？？？

**Comment by Suwings** [comment]
能不能给予复现这个情况的具体说明方式？
就是说后台日志疯狂然后日志600MB，面板进程就崩溃了吗？

**Comment by Coloryr** [comment]
大概就是这样吧，我是群组服，然后网页监控着一台服务器，跑了一段时间，我就发现进程没了，所以的JAVA.exe也没了，后面去文件夹看，那个子服日志刷了600MB

**Comment by huangsijun17** [comment]
> 大概就是这样吧，我是群组服，然后网页监控着一台服务器，跑了一段时间，我就发现进程没了，所以的JAVA.exe也没了，后面去文件夹看，那个子服日志刷了600MB

子服日志600MB，那你应该排查你的mc服务器啊。这和开服软件有什么关系？

**Comment by Coloryr** [comment]
按你这么说，MCSManager崩溃不是它的问题？是我子服的问题？

**Comment by Coloryr** [comment]
反正我子服都炸了这是事实

**Comment by Suwings** [comment]
面板有一定的责任，猜测应该是日志记录储存功能的问题，这方面我们会继续改进的，感谢你的使用。

@Coloryr

**Comment by huangsijun17** [comment]
> 面板有一定的责任，猜测应该是日志记录储存功能的问题，这方面我们会继续改进的，感谢你的使用。
> 
> @Coloryr

估计是日志刷太多，溢出了。

**Comment by Coloryr** [comment]
等你修复！

**Comment by Suwings** [comment]
已修复。
https://github.com/Suwings/MCSManager/releases/tag/v8.6.8

顺便一提，经过我的测试，在终端巨大流量内容输出的情况下，MCSM从来没有停止过进程，但是在连续测试10分钟的时，Centos 系统强制性杀掉了 MCSM 进程。

初步认定是MCSM日志储存功能内存占用跌宕起伏让再加上服务器配置非常低（1核1G），系统不得不杀掉 MCSM 进程来释放内存。

修复这个潜在的问题后，直到现在还在进行测试，尚未出现你所说的MCSM进程结束情况。如果有问题我们会继续修复这个问题。


在此对你反馈问题的精神表达崇高的谢意。

@Coloryr
