### ISSUE TITLE
求宝塔配置反代教程

### ISSUE THREAD

**Issue by Sprite233** [Suwings/MCSManager#195]
emm宝塔不好改怕改坏了
能不能出个宝塔反代的教程qaq
apache的

顺便忠心感谢作者加了颜色支持
本人开群组服务器
用了您的管理工具效率提升很大

![ZC@K XML_NVFYYN@DFGU%%C](https://user-images.githubusercontent.com/42002296/76062146-0e824780-5fc0-11ea-9da8-d29966c3ecb3.png)

**Comment by Sprite233** [comment]
顺便忠心感谢作者加了颜色支持
本人开群组服务器
用了您的管理工具效率提升很大

**Comment by Suwings** [comment]
**感谢你对本项目进行爱发电赞助，十分感谢！**

关于宝塔的反代配置，这个应该和 Nginx 或 Apache 配置同理，具体配置方案参考一下这里：

https://github.com/Suwings/MCSManager/wiki/%E4%BD%BF%E7%94%A8-Apache2.4-%E8%BF%9B%E8%A1%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86

这是正常 Apache 的反代，我觉得宝塔虽然是控制面板，但是 Apache 的配置方式应该差别不大，有其他问题可以再讨论。

**Comment by Sprite233** [comment]
好的，谢谢

**Comment by Suwings** [comment]
另外你赞助的 "小钱钱" 已经 "记录在案"，感谢你的赞助！

[单击这里查看](https://docs.qq.com/sheet/DYWJNVXhib0dtamh2?tab=BB08J2&c=A27A0F0)

**Comment by Sprite233** [comment]
没事，你维护这么大一个项目应该还是挺辛苦的[doge]
