### ISSUE TITLE
“关闭所有实例”与“崩溃重启冲突”

### ISSUE THREAD

**Issue by Sprite233** [Suwings/MCSManager#196]
使用关闭所有实例后，如果该实例启用了崩溃重启，会自动启动。
因此必须一个一个手动关闭（如果开启了崩溃重启

**Comment by Suwings** [comment]
感谢反馈，我们会检查这个情况，并进行适当改进，谢谢！

**Comment by huangsijun17** [comment]
实测更新到最新版本后全部关闭了。

**Comment by Sprite233** [comment]
> 实测更新到最新版本后全部关闭了。

可能我煋了
