### ISSUE TITLE
终端显示问题

### ISSUE THREAD

**Issue by Sprite233** [Suwings/MCSManager#197]
![image](https://user-images.githubusercontent.com/42002296/76101858-0cdd7180-600a-11ea-8b07-ec9c81da7f0b.png)
这效果稍微有点惨
还有如果能改下配色就好了，这个配色有点刺眼..

**Comment by lone-wolf-akela** [comment]
其实也有字体的问题，控制台用粗一些的字体会好看一些

**Comment by huangsijun17** [comment]
有没有可能将配色和字体（列表）作为独立的配置文件放在外面，可以通过文本编辑器修改？

**Comment by Sprite233** [comment]
i++
