### ISSUE TITLE
使用此面板开启Unturned服务器无法输入指令

### ISSUE THREAD

**Issue by MyDandan233** [Suwings/MCSManager#198]
_我知道这个问题有点刁难，但还是想问一下。_
![QQ截图20200307095342](https://user-images.githubusercontent.com/42466144/76134485-aa13c680-6059-11ea-9437-2385a0fe0cee.png)
使用此面板开启Unturned服务器基本一切正常，但是不能在终端输入指令（远程桌面弹出一个空白的命令行，也不能输入指令）
但是直接用命令行开启又会中文乱码
有点纠结

**Comment by Suwings** [comment]
我不了解 Unturned ，这个我可能也无法帮到你，你可以尝试建一个bat文件，然后把启动命令写到bat中，再运行这个bat试试。

中文乱码的话又可以改右边的输入输出编码就能解决。

**Comment by Shuazijun** [comment]
unturned控制台本身中文就会乱码,这个问题官方一直没解决(毕竟没官中).他的服务端其实就是没有UI的客户端.并不是类似CMD窗口的命令提示符.所以存在无法通过面板来输入指令的问题.
