### ISSUE TITLE
windows如何更新

### ISSUE THREAD

**Issue by stevensane** [Suwings/MCSManager#199]

**Comment by huangsijun17** [comment]
下载覆盖……

**Comment by stevensane** [comment]
文件不同怎麼辦？

**Comment by stevensane** [comment]
> git

怎麼裝git

**Comment by huangsijun17** [comment]
> 文件不同怎麼辦？

文件不同是什么情况？？？正常情况下可以直接覆盖。当然，推荐Windows也安装个git，通过git clone下载，git pull更新。

**Comment by huangsijun17** [comment]
> > git
> 
> 怎麼裝git

在github问怎么装git……
兄弟你是来搞笑的吗？

**Comment by stevensane** [comment]
> 下載覆蓋……
> 當然，你要是有裝git的話
> 
> ```
> cd X:\...\MCSManager\
> git pull
> ```



> > > 吉特
> > 
> > 
> > 怎麼裝git
> 
> 在github問怎麼裝git……
> 兄弟你是來搞笑的嗎？

新手我啥都不會

**Comment by stevensane** [comment]
> git clone

檔案名稱相同

**Comment by stevensane** [comment]
> > 文件不同怎麼辦？
> 
> 文件不同是什麼情況？？？正常情況下可以直接覆蓋。當然，推薦Windows也可以安裝個git，通過git clone下載，git pull更新。

舊的拖到新的還是新的拖到舊的

**Comment by huangsijun17** [comment]
你之前不是git clone安装的，就不能靠git pull来更新了。

**Comment by huangsijun17** [comment]
要修复

**Comment by stevensane** [comment]
> 要修復

怎麼修復

**Comment by huangsijun17** [comment]
`git pull https://github.com/Suwings/MCSManager.git`

**Comment by stevensane** [comment]
> git pull https://github.com/Suwings/MCSManager.git

兄弟這怎麼裝阿沒用啊git也裝了

**Comment by huangsijun17** [comment]
> > git pull https://github.com/Suwings/MCSManager.git
> 
> 兄弟這怎麼裝阿沒用啊git也裝了

报错给我看一下

**Comment by stevensane** [comment]
> > > git pull https://github.com/Suwings/MCSManager.git
> > 
> > 
> > 兄弟這怎麼裝阿沒用啊git也裝了
> 
> 报错给我看一下

fatal: Not a git repository (or any of the parent directories): .git

**Comment by Suwings** [comment]
Windows 下直接下载最新版本的zip文件，名字如 MCSManager_8.6.7_win,zip ，下载后直接覆盖原来文件，你的服务端配置，用户配置全部都会存在。

其他的不用了解那么多的，以后才会慢慢遇到，谢谢使用~
@stevensane
