### ISSUE TITLE
后台刷屏报错

### ISSUE THREAD

**Issue by Sprite233** [Suwings/MCSManager#200]
![image](https://user-images.githubusercontent.com/42002296/76141533-482a7f80-60a0-11ea-8cc7-2e98ca6b9bb9.png)

**Comment by Suwings** [comment]
请详细描述一下你的操作步骤和系统环境？这样我才能复现这个问题，得以修复。

**Comment by Suwings** [comment]
另外在控制面板首页查看一下你的版本是否是`8.6.7 发行版本`，刚刚复查了一下代码，这行错误不应该发生，估计可能是你克隆下载了旧版本或者某开发版本的代码。

如果你的版本低于 8.6.7 发行版本，建议更新一下。

**Comment by Sprite233** [comment]
这边用的是最新的release

**Comment by Sprite233** [comment]
触发不清楚，系统server2019 Node.js v12.16.1.

**Comment by Suwings** [comment]
那你能说明一下操作过程吗？

**Comment by Sprite233** [comment]
现在还再刷屏，估计得重启才好

**Comment by Suwings** [comment]
已经修复这个问题：https://github.com/Suwings/MCSManager/releases/tag/v8.6.8

**Comment by Sprite233** [comment]
感谢
