### ISSUE TITLE
希望作者多花时间修复一些细节上的小问题

### ISSUE THREAD

**Issue by Yuii-guoguo** [Suwings/MCSManager#201]
用了之后感觉挺不错的，但是一些细节上的问题有点碍事.
1.前端判断ws超时后建议直接或者延迟几秒后自动刷新页面.
2.宝塔问题，如果开启系统加固插件内的异常进程监控一定要全部关闭服务后添加进程名的白名单后再开启，不然会造成ws(node)不工作的情况，这一点可以写到wiki,这是我遇到的坑.
3.使用cdn需要cdn支持websocket功能，连接时长需要与网站服务端反代配置相同(不然容易出现没有多久就需要刷新的提示),本人使用的是阿里云的全站加速没有遇到其他问题。
4.希望作者开发安装流程程序或者增加设置项，自定义全局服务端目录、redis/memcached，日志服务.

**Comment by Suwings** [comment]
感谢你使用本项目并且反馈踩坑结果，这些细节问题在未来会逐渐改善，相信我们会做到更好。
