### ISSUE TITLE
希望可以支持命令行和面板同时进行操作

### ISSUE THREAD

**Issue by KJZH001** [Suwings/MCSManager#202]
我的服务器平台是win10
当初时因为需要支持多人远程操作所以寻找相关的项目最后找到了这里
不过这个项目貌似会独占服务器控制端的样子，直接通过bat开启的服务端是在面板里显示为未开启的，而且不能通过面板操控
如果从面板里开启的话命令行窗口是不显示的
但是这样的话在服务器直接远程桌面的时候为了能操控服务端还要专门开个浏览器出来，感觉有点多余了= =
虽然这个功能用的人可能不太多，不过还是希望可以吧这个功能加上去

**Comment by huangsijun17** [comment]
这是开服软件，不是服务端管理软件。不能管理通过其他方法启动的服务端。

**Comment by KJZH001** [comment]
不好意思，我的表达可能不太明确
我的意思是希望可以在通过面板操控的同时能给出一个能够直接在服务器上操控的方式
毕竟有些时候完全靠面板远程肯定不如直接远程桌面操作来的方便，但是这样子的话只是为了操作个服务端而已再去开个浏览器感觉难免多余了
如果说很难实现的话还是算了吧= =

**Comment by Suwings** [comment]
懂你的意思，你是想在控制台也有一个可以输入命令的地方，输入相关的服务器名称就能直接从控制台管理对应的服务器。

这个功能会加入功能清单列表，但是确实优先级很低，因为个人觉得既然使用网页就应当尽可能使用网页来操作，而不要再远程桌面连接。但既然有人提出这个意见，则说明此面板在完全可控操作方面还缺少优势，对此我们会进行反思和设计，在未来版本尽可能的让人不再有这种想法。

希望您可以继续使用面板，若如果继续发现面板不足，还请继续反馈相关问题与具体步骤，面板作为开源项目虽精力，资金有限，但也不容许有重大缺陷存在，将会竭尽全力修复问题。


**感谢你的反馈和想法，在此对你为项目提出意见的精神给予崇高的谢意。**

**Comment by KJZH001** [comment]
嗯嗯，谢谢了
希望这个项目可以越来越好！

**Comment by DazeCake** [comment]
确实，可能be端用户非常需要这个功能，毕竟存档热备份会比较麻烦
