### ISSUE TITLE
希望能有能直接执行指定服务器命令的api

### ISSUE THREAD

**Issue by mwx2006** [Suwings/MCSManager#203]
希望能通过编程对接服务器来执行指定命令

**Comment by huangsijun17** [comment]
让外部程序来调用mcsm？

**Comment by mwx2006** [comment]
网络api

**Comment by mwx2006** [comment]
我看看

**Comment by Sprite233** [comment]
mc就自带啊，rcon

**Comment by Suwings** [comment]
面板近期没有这种计划，但是以后一定会出。

感谢反馈，感谢使用面板，希望你能喜欢。

**Comment by 10935336** [comment]
同样需要此功能，rocn实在是不太好

**Comment by huangsijun17** [comment]
> 同样需要此功能，rcon实在是不太好

Rcon一般不都是拿来做跳板的吗？常见的都是拿C、PY设置易语言（QQ机器人）等来间接控制的啊。

**Comment by Redbeanw44602** [comment]
同议。希望能增加获取Console更新的API和远程执行命令的API

**Comment by Suwings** [comment]
此功能已部分实现。
https://github.com/Suwings/MCSManager/releases/tag/v8.6.11
