### ISSUE TITLE
终端无色&换行问题

### ISSUE THREAD

**Issue by Sprite233** [Suwings/MCSManager#204]
![image](https://user-images.githubusercontent.com/42002296/76422037-8b0d8f80-63df-11ea-90d6-a79f8d7bd5a8.png)
只有面板自己加上去的
启动参数 -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs -Dfile.encoding=UTF-8

使用utf8编码

且在8.6.7还存在这个问题不知道8.6.8修了没
![image](https://user-images.githubusercontent.com/42002296/76422249-daec5680-63df-11ea-8ddc-03b29ff9b23c.png)
进入历史模式触发

**Comment by Suwings** [comment]
无色问题的话，应该是服务端没输出原本的颜色，面板是能够解析 Minecraft 的颜色的，如果没有解析成功的话，也应该会在终端上看见这些颜色代码，但是终端界面上没有看见这些代码，可能是原本就没有吧。

第二张截图，日志内容长度超过1024字节后才会开始存入日志，所以一开始就访问历史模式是没有记录的。

顺便一提，我不知道是更新的问题还是其他原因，`[_b_r_]`这个关键字代替字只在旧版本才在继续使用，我不明白为什么现在还出现在截图中，我在整个项目中搜索`[_b_r_]`都是无结果的，建议你重新下载一份代码，运行一次试试。

**Comment by Sprite233** [comment]
但是按道理来说，这个参数没有阻止mc输出彩色字符emm

**Comment by huangsijun17** [comment]
> 但是按道理来说，这个参数没有阻止mc输出彩色字符emm

现在的后台需要mc**主动**输出彩色字符，才会显示彩色。

**Comment by Sprite233** [comment]
> > 但是按道理来说，这个参数没有阻止mc输出彩色字符emm
> 
> 现在的后台需要mc**主动**输出彩色字符，才会显示彩色。

但是这就很神奇，我也想知道怎么让他主动输入，我之前写了个bc插件（然后标准输出流都找不到§符号，我就很好奇翼龙面板如何实现的

**Comment by Suwings** [comment]
面板能够识别§与&符号与Linux原生颜色代码，但是如果mc服务端本身就不输出颜色代码的话，那就没办法了，只能靠面板前端自带的简单上色功能来上色。

具体还是建议你更新到最新版本再进行尝试一下，有问题欢迎继续讨论。
