### ISSUE TITLE
关于任务计划的建议

### ISSUE THREAD

**Issue by hank9999** [Suwings/MCSManager#205]
1. 希望能够增加在指定时间执行的计划  
2. 一个计划能执行多条指令  
3. 多条指令之间可以有几秒的延迟  
  
  
感谢作者的付出，面板很好用，功能很完善  
谢谢

**Comment by Suwings** [comment]
感谢你的建议，有关功能会适当考虑，争取做得更好。

**Comment by 10935336** [comment]
希望能添加暂停执行计划任务的功能
