### ISSUE TITLE
每次进入终端时的光标位置错误

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#206]
每次重新进入终端后的光标不应出现在最后一行文本的行尾，而应在下一行行首。
现在就导致了下一行内容未换行的错误。
![image](https://github.com/huangsijun17/Picture-links/raw/master/2020-3-13-001.JPG)

**Comment by Suwings** [comment]
这个细节可能我没发现，我记得好像会换行的，只是光标显示位置在末尾，到时候我测试一下，如果有问题我就看看能不能改。这个是使用的 https://xtermjs.org/ 库。

**Comment by huangsijun17** [comment]
> 这个细节可能我没发现，我记得好像会换行的，只是光标显示位置在末尾，到时候我测试一下，如果有问题我就看看能不能改。这个是使用的 https://xtermjs.org/ 库。

我是懒得截图了，下一行的内容会衔接在这一行。再往后就正常了。

**Comment by Suwings** [comment]
行，最近有点忙，过段时间我修一修吧，谢谢了。

**Comment by Suwings** [comment]
已修 https://github.com/Suwings/MCSManager/commit/e736639f6442d91d2e8ed4b3caf81cef82b82abd
