### ISSUE TITLE
控制台输入say：信息时，显示乱码

### ISSUE THREAD

**Issue by EnterFor** [Suwings/MCSManager#209]
![image](https://user-images.githubusercontent.com/10114685/76627825-b24a9500-6576-11ea-8897-a3d34173b7ab.png)
英文和数字不显示，带中文就会显示问号。
版本：8.6.8

**Comment by huangsijun17** [comment]
Windows？Linux？开服时有没有加UTF-8参数？

**Comment by EnterFor** [comment]
> Windows？Linux？开服时有没有加UTF-8参数？

Windows
![image](https://user-images.githubusercontent.com/10114685/76677972-d2c62e00-660e-11ea-8b92-41d83ad3f6a5.png)

**Comment by huangsijun17** [comment]
@Suwings 应该是GBK转UTF-8出错了

**Comment by huangsijun17** [comment]
> > Windows？Linux？开服时有没有加UTF-8参数？
> 
> Windows
> ![image](https://user-images.githubusercontent.com/10114685/76677972-d2c62e00-660e-11ea-8b92-41d83ad3f6a5.png)

附加参数加上这个试一下：

`-Dfile.encoding=UTF-8`

**Comment by Suwings** [comment]
显示看起来没问题，say指令有问题的话应该是输入有问题，把设置里面命令输入编码那里改成utf8试试吧。
