### ISSUE TITLE
添加语言包?  

### ISSUE THREAD

**Issue by edwinyoo44** [Suwings/MCSManager#21]
介面添加多国语言，例如:英文、繁体中文，以满足多语言的需求

**Comment by Suwings** [comment]
多国语言包实在没有必要，因为我相信，在国外有非常类似的项目，并且国外中大型服务器也不会考虑使用这类项目，小服务器也大部分知道一些基础的远程管理（其实是因为这个主意面向国内，大部分注释，文档都是直接中文的）。
在我看来，需求量非常小。
但是，制作 中文简体/中文繁体 语言还是有点兴趣。 @edwinyoo44

**Comment by edwinyoo44** [comment]
@Suwings  其實是因為我本人是需要繁體中文的，故才提出此議

**Comment by Suwings** [comment]
嗯，很早就已經考慮到應該製作中文繁體的語言包了，只不過在設計之初，沒有考慮多語言化，所以這個功能的更新需要一段時間，因為當初就沒想多語言話。不過既然有習慣使用中文繁體的人使用的話，我以後還是盡力做一個為好。 @edwinyoo44

**Comment by Suwings** [comment]
多語言化模板在現有的設計下修改工作量太大。我們沒有提供多語言解決方案。所以我們打算對整個代碼進行自動化翻譯。

根據台灣繁體習慣，機器自動翻譯，如有問題還請諒解。

我們提供了一個翻譯版本的下載鏈接。

下載地址：[https://pan.baidu.com/s/134W5zT0qfUOCiKPx-nuI8w ](https://pan.baidu.com/s/134W5zT0qfUOCiKPx-nuI8w )
