### ISSUE TITLE
关于服务器属性和route路由方面的建议

### ISSUE THREAD

**Issue by yaohuomhuom** [Suwings/MCSManager#210]
### 关于服务器模型属性的建议

- 问题

在进行二次路由开发并使用sendCommand函数或者刚开启服务器时，在服务器没有完全启动的情况下进行mc命令输入，可能会造成mc服务器端的报错和stdin写入流的失效，前者问题不大，但是后者会造成mcsm终端的命令输入直接无法使用的问题。

- 个人建议

通过(BaseMcserver.js中的)this.process.stdout.on的data事件监听服务器载入完全的log标志（如Done ! For help 等）从而在服务器模型添加done属性，记录服务器是否载入完全

 ### 关于route路由方面的建议

- 问题

静态载入路由，使得二次路由开发的测试过程和部署过程十分的麻烦，MCSM的重启必然导致MC服务器的重启，而大型服务器的启动时间相当长，所以这样用户体验相对较差

- 个人建议

在route创建插件路由文件夹，通过fs.watch对插件路由文件夹内的修改进行监听和动态载入

-------------------
以上问题都是实打实的问题，但是至于个人意见，也只能说是我的一些愚见或者是想当然罢了，如果有更好的想法或者我说的有什么错误，欢迎大家来讨论。

**Comment by Suwings** [comment]
感谢提供优质的开发建议，在此非常感谢。你很认真的写下如此之多的反馈描述，对此我也会同样认真的回答你所提出的每一个建议。

- 关于 `服务器模型属性` 的建议

不能采取检测列如 `Done ! For help` 这样的关键字，因为很有可能某些服务端不会有这种输出标识，并且面板本身是支持其他游戏的服务端的，所以无法一视同仁。不过关于你所说的这个输入流问题，确实需要重视。

- 关于 `路由方面` 的问题。

HTTP请求路由与Websocket请求路由是静态绑定的，每次开发都需要重新启动面板，这个确实降低了开发效率。目前我本地开发环境使用的是代码独立运行测试之后，再添加到面板代码中，但若代码与面板之间的逻辑高度耦合，那么也确实可能会要重启多次来进行测试。

- 计划

面板近期会减缓更新，因频繁的更新导致的问题也许会更多，等面板将现有的功能完善，必备的功能新增之后，必将重构面板的代码，那时再重新实现这些部分建议，我相信会更好。

> 希望你能喜欢此项目，并长期支持项目，谢谢。

@yaohuomhuom

**Comment by huangsijun17** [comment]
我有点想试试看能不能采用Screen的终端复用+MCSM来开服了。
在用MCSM前我是用sh脚本实现终端复用的（同一脚本实现新建或加载）。

**Comment by yaohuomhuom** [comment]
@Suwings 关于动态路由的问题，今天研究了一下，把昨天的写的静态MCSM对应酷q 的http插件改了一下，添加了一种新的路由载入方式，通过fs.watch监听文件修改，require的重载，修改express app handle的方式，勉强实现了动态的路由内容载入，不知道有没有一些借鉴的意义（个人感觉十分牵强）[mcsm_cq_route](https://github.com/yaohuomhuom/mcsm_cq_route/commit/55c56a3de79dd4dd3c08e4e72eb3e7ce41a67874)。

**Comment by huangsijun17** [comment]
> @Suwings 关于动态路由的问题，今天研究了一下，把昨天的写的静态MCSM对应酷q 的http插件改了一下，添加了一种新的路由载入方式，通过fs.watch监听文件修改，require的重载，修改express app handle的方式，勉强实现了动态的路由内容载入，不知道有没有一些借鉴的意义（个人感觉十分牵强）[mcsm_cq_route](https://github.com/yaohuomhuom/mcsm_cq_route/commit/35c5a95a70ee0a93ccc250388f00d42bdc8ab6c3)。

可以实现Linux下命令行控制吗？要是可以，我去整一个。

**Comment by yaohuomhuom** [comment]
@huangsijun17 不推荐使用，因为动态路由添加更新不是很稳定，并且如果不加密路由请求过程会有严重的安全问题，而且也只做过win10端的测试，Linux还没有测试过。
