### ISSUE TITLE
我无法远程开启服务器

### ISSUE THREAD

**Issue by fightingangles** [Suwings/MCSManager#213]
多次点击“开启服务器”后面板无反应。
我的版本：8.6.8

**Comment by Suwings** [comment]
无具体信息，无法判断原因。
请截图你的服务端参数截图，说明你的系统环境，上传的服务端信息等等。

重新开一个。

**Comment by fightingangles** [comment]
我很抱歉麻烦了您，事实上这是因为我的疏忽，我没有在设置内存时加上单位。
抱歉！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Suwings"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 上午10:18
收件人:&nbsp;"Suwings/MCSManager"<MCSManager@noreply.github.com&gt;;
抄送:&nbsp;"小工具有限公司"<2764879876@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Suwings/MCSManager] 我无法远程开启服务器 (#213)





 
无具体信息，无法判断原因。
 请截图你的服务端参数截图，说明你的系统环境，上传的服务端信息等等。
 
重新开一个。
