### ISSUE TITLE
希望可以在面板中限制伺服器的最多使用核心數以及頻率

### ISSUE THREAD

**Issue by zx45888190** [Suwings/MCSManager#215]
避免單個伺服器惡意吃光所有的資源

**Comment by huangsijun17** [comment]
您可以使用Docker来对每个服务端进行限制。

**Comment by zx45888190** [comment]
如果是windowns系統呢

**Comment by Suwings** [comment]
十分抱歉，對於 Windows 系統，暫無解決方案。

**Comment by Tim-Paik** [comment]
windows10可以参考这个[链接](https://www.xstui.com/read/666)

**Comment by huangsijun17** [comment]
试试看Steam 上的 [CPUCores](https://store.steampowered.com/app/384300/CPUCores__Maximize_Your_FPS/)
