### ISSUE TITLE
希望能自动安装forge

### ISSUE THREAD

**Issue by 2535317438** [Suwings/MCSManager#216]
我自己装过forge之后出了不少问题，也不确定服务器能否运作（开服时大量报错）。甚至不能用面板直接开服。如果能自动安装forge（不要直接wget，加一个选择文件的选项，防止DNS污染），可用性会大大增强。
        希望采纳。（搞出来给老哥打100块成吗）

**Comment by 2535317438** [comment]
绝了，github要自己换行的……

**Comment by Suwings** [comment]
十分抱歉，近期暂无此计划。感谢你的建议。

**Comment by huangsijun17** [comment]
个人希望最好可以自动安装Minecraft，自动安装forge，自动安装Bukkit，自动安装Paper，自动安装Sponge，自动安装craftbukkit，自动安装spigot，自动安装tacospigot，自动安装torchspigot，自动安装cauldron，自动安装thermos，自动安装glowstone，自动安装akarin，自动安装Cat-Server，自动安装Cat-Server Pro，自动安装Mohist，自动安装Bungeecord，自动安装Waterfall……
