### ISSUE TITLE
您好，内存显示似乎有点问题

### ISSUE THREAD

**Issue by Shizuri23** [Suwings/MCSManager#218]
![image](https://user-images.githubusercontent.com/46082179/77854030-46c12280-721a-11ea-864a-734e33395d4a.png)
![image](https://user-images.githubusercontent.com/46082179/77854031-4de83080-721a-11ea-81fa-c938f73e40cd.png)
不知道是我的设置问题还是什么，麻烦请看一下谢谢

**Comment by Shizuri23** [comment]
![image](https://user-images.githubusercontent.com/46082179/77854050-69533b80-721a-11ea-9b47-169086376021.png)

**Comment by 10935336** [comment]
因为MCSM算的是系统真实空闲内存，所以buff/cache也算在内。
你可以用top看一下,KiB Mem项的free应该是和MCSM显示一样的

**Comment by huangsijun17** [comment]
> 因为MCSM显示的是系统真实空闲内存，所以buff/cache也算在已用内存内。
> 你可以用top看一下，Mem项的free应该是和MCSM显示一样的。

而且，这个获取剩余内存是Node.js里面的，基本无解。

**Comment by MaoliWolf** [comment]
調用系統函式free來解析是可行的
希望這部分能修改

**Comment by huangsijun17** [comment]
> 調用系統函式free來解析是可行的
> 希望這部分能修改

Windows怎么办？这个是Node.js的问题，MCSM无法解决。

**Comment by MaoliWolf** [comment]
可以的
node.js 可以用 os.platform() 來判斷作業系統
linux就調用 `free`
windows 則調用 `wmic OS get FreePhysicalMemory` 取得剩餘的RAM
