### ISSUE TITLE
nginx反向代理？

### ISSUE THREAD

**Issue by lesoleil** [Suwings/MCSManager#22]
我在`/etc/nginx/conf.d`目录Nginx反向代理配置文件，内容如下：
```
upstream mcsmanager {
    server 127.0.0.1:23333;
    keepalive 64;
}

server {
    listen 80;
    server_name _;
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Nginx-Proxy true;
        proxy_set_header Connection "";
        proxy_pass http://mcsmanager;
    }
}
```
登陆界面正常，登入之后显示如下，不知是什么问题？

![](http://ofwomxy5g.bkt.clouddn.com/%E5%9B%BE%E5%83%8F%20273.png)

**Comment by Suwings** [comment]
这个项目的主界面绝大部分内容使用的 Webscoket 与 Ajax 结合产生的页面与数据，你的反向代理似乎没有为 ws 提供完全长连接支持？

你可以考虑加上这两个配置项目：
` proxy_set_header Upgrade $http_upgrade;  ` 
` proxy_set_header Connection "upgrade";  `

**Comment by lesoleil** [comment]
感谢！添加后显示正常了！

**Comment by xuemaojiao-888** [comment]
那个，我在使用Nginx反代后，出现这种情况，登录没问题，但是登录后就说与服务器链接断开，这是怎么回事？麻烦帮我解决一下，谢谢！

**Comment by masnn** [comment]
> 这个项目的主界面绝大部分内容使用的 Webscoket 与 Ajax 结合产生的页面与数据，你的反向代理似乎没有为 ws 提供完全长连接支持？
> 
> 你可以考虑加上这两个配置项目：
> `proxy_set_header Upgrade $http_upgrade; `
> `proxy_set_header Connection "upgrade"; `

**Comment by xuemaojiao-888** [comment]
没有用，还是这样
![1](https://user-images.githubusercontent.com/53249654/62095364-c628db80-b2b2-11e9-9913-57f7106fb132.png)
![2](https://user-images.githubusercontent.com/53249654/62095365-c628db80-b2b2-11e9-8fc8-f346378e9a79.PNG)

**Comment by Suwings** [comment]
https://github.com/Suwings/MCSManager/issues/34

**Comment by ghostzwc** [comment]
如果你实在宝塔上面用Nginx做反代加入下面这些

    location ~ / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Nginx-Proxy true;
        proxy_pass http://mcsmanager;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

**Comment by ghostzwc** [comment]
如果你实在宝塔上面用Nginx做反代加入下面这些

    location ~ / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Nginx-Proxy true;
        proxy_pass http://mcsmanager;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
