### ISSUE TITLE
Windows 10 連接異常

### ISSUE THREAD

**Issue by zx45888190** [Suwings/MCSManager#221]
目前不知觸發原因
有時無法連接至面板
假如至該主機終端按下任何一個按鍵
連接將恢復正常
跪求解決

**Comment by huangsijun17** [comment]
Windows 10?
伺服器？客户端？

**Comment by zx45888190** [comment]
客戶和伺服器接為win10

**Comment by zx45888190** [comment]
更新 至該終端點一個英文字母才會恢復

**Comment by Suwings** [comment]
使用過程中不要對控制台點擊，這樣Windows可能會將面板暫停，左上角應該會顯示 選擇狀態 ，這種狀態面板會卡頓。取消選擇即可。

**Comment by nikissXI** [comment]
换Linux就行，因为这个问题我从Windows转Linux了
