### ISSUE TITLE
您好，我用了樱花外网映射，但是一直“请稍等,正在传输资源 ...............”运行环境：win10

### ISSUE THREAD

**Issue by 745404527** [Suwings/MCSManager#222]
@Suwings

**Comment by Suwings** [comment]
使用tcp协议，并且要支持websocket。

https://github.com/Suwings/MCSManager/issues/182

**Comment by 745404527** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Suwings"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月2日(星期四) 下午3:16
收件人:&nbsp;"Suwings/MCSManager"<MCSManager@noreply.github.com&gt;;
抄送:&nbsp;"叶项承宇"<745404527@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Suwings/MCSManager] 您好，我用了樱花外网映射，但是一直“请稍等,正在传输资源 ...............”运行环境：win10 (#222)





 
使用tcp协议，并且要支持websocket。
 
#182
