### ISSUE TITLE
关闭mcsm

### ISSUE THREAD

**Issue by stevensane** [Suwings/MCSManager#223]
直接從任務管理器關閉mcsm可以嗎？
windows如何開機啟動（不登錄情況下）
啟動資料夾不行

**Comment by huangsijun17** [comment]
可以用任務管理器，但不能直接終止進程。
開機啟動可以用Windows工作排程器（Windows计划任务）。

**Comment by Suwings** [comment]
盡可能使用正常手段關閉，列如使用ctrl+c。
請不要從任務管理器直接關閉，這樣會導致某些伺服器依然在運行無法結束。不過如果能保證所有伺服器都已經關閉，從任務管理器強制關閉不會有明顯的問題。
