### ISSUE TITLE
实时终端控制台输入指令无效，计划任务项目也失效了

### ISSUE THREAD

**Issue by EmeraldBoat** [Suwings/MCSManager#224]
前两天就失效了，计划任务项目弄了清理掉落物的指令发现不发了，重新添加也一样，控制台输入指令也没用了，我朋友在控制台试了也输不了指令

**Comment by huangsijun17** [comment]
是不是服务端卡住了，或者失去控制了？关服看一下能不能关闭。

**Comment by EmeraldBoat** [comment]
没卡，能正常玩，点关闭服务器和重启服务器也没用，只能在游戏里输入stop，然后在面板上开启

**Comment by huangsijun17** [comment]
失控了……我之前遇到过，在非常卡的时候容易遇到。

**Comment by EmeraldBoat** [comment]
确实，1.14.4优化貌似不好，而且常加载区块里有个经验熔炉

**Comment by EmeraldBoat** [comment]
那怎么整？

**Comment by EmeraldBoat** [comment]
刚关了下又可以了,不知道以后还会不会出现

**Comment by huangsijun17** [comment]
> 刚关了下又可以了,不知道以后还会不会出现

不常见，而且难以复现。如果反复出现并找到规律，再说吧。偶尔一次，原因成谜。

**Comment by Suwings** [comment]
更新面板下载最新版本的面板。这个问题最新版本应该已经修复。
