### ISSUE TITLE
给个MCS面板使用Systemd的建议

### ISSUE THREAD

**Issue by FantWings** [Suwings/MCSManager#225]
为了保证服务器能够自启和崩溃自重启，建议采用Systemd模式运行而不是screen或者tmux
在`/etc/systemd/system/`下创建一个`mcsd.service`文件

文件内容给个示例：
```
[Unit]
#程序名称
Description=Minecraft MCS Panel Daemon
After=network.target
#启动延迟
StartLimitIntervalSec=5

[Service]
#以特定用户运行
User=minecraft
#工作目录
WorkingDirectory=/opt/mcsmanager/
#启动命令
ExecStart=node app.js
#日志输出方式
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=mcsd
#崩溃自重启
Restart=always
#重启延迟
RestartSec=1

[Install]
WantedBy=multi-user.target
```

写入文件内容后，使用下面的指令：
设为开机启动：`systemctl enable mcsd`
关闭开机启动：`systemctl disable mcsd`
启动面板：`systemctl start mcsd` / `service mscd start`
关闭面板：`systemctl stop mcsd` / `service mscd stop`
查询面板状态：`systemctl status mcsd` / `service mscd status`

Readme貌似没提过这个，可以考虑此种方式。

**Comment by huangsijun17** [comment]
然而wiki有，我也在用。你这个多了指定用户，和我的用户名不一样。
虽然差不多。

**Comment by FantWings** [comment]
> 然而wiki有，我也在用。你这个多了指定用户，和我的用户名不一样。
> 虽然差不多。

指定低权限用户可以防止程序bug被人拿到shell越权，不强制但是建议这样做，给大家养成个习惯比较好。

**Comment by huangsijun17** [comment]
> > 然而wiki有，我也在用。你这个多了指定用户，和我的用户名不一样。
> > 虽然差不多。
> 
> 指定低权限用户可以防止程序bug被人拿到shell越权，不强制但是建议这样做，给大家养成个习惯比较好。

然而Wiki上面不但只写了怎么给当前用户安装nodejs，还推荐上Root用户。
