### ISSUE TITLE
Windows下实例日志历史记录文件错误

### ISSUE THREAD

**Issue by MAX-XiaoKui** [Suwings/MCSManager#227]
winserver2008，面板版本8.6.8，经常显示实例日志历史记录文件创建错误，检查发现文件(MCSManager\server\tmp_log_history\实例名.log)可能被锁定，试过的任何暴力删除工具都无法删除，导致面板上无法显示历史消息，必须重启服务器(机器)才行，希望尽早解决。
![image](https://user-images.githubusercontent.com/53287753/78979709-f9fd1600-7b4e-11ea-99ca-47ef842f18e6.png)

**Comment by huangsijun17** [comment]
如果在关闭MCSM服务后文件依然无法删除，可能是文件系统或硬件问题。建议针对性排查。

**Comment by Suwings** [comment]
新版本已经修复，但是没有为此发布新版本，重新到官网下载一份即可解决。

**Comment by RimuruChan** [comment]
可以关了，修了
