### ISSUE TITLE
希望计划任务可以添加每天几点定时开关mc

### ISSUE THREAD

**Issue by zsqw123** [Suwings/MCSManager#228]
因为服务器有夜间关服需求，这样可以积攒阿里云突发实例积分，之前隔多长时间开关服实在是用的不是很舒服，导致事实上只能每天手动开关，希望添加。

然后最好可以显示控制台当前时间，因为服务器时间往往有可能和本地不同步

**Comment by MAX-XiaoKui** [comment]
本来就是可以实现的
![Screenshot_2020-04-11-12-41-08-17_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/53287753/79035486-c7582980-7bf1-11ea-92e6-4ae60d6fbaf3.jpg)
这样是每天5点半关服，每天整点开服（已经开了就不会重复开），并且要把崩溃自动重启关闭，要不然关服后会自动开启

**Comment by zsqw123** [comment]
> 本来就是可以实现的
> ![Screenshot_2020-04-11-12-41-08-17_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/53287753/79035486-c7582980-7bf1-11ea-92e6-4ae60d6fbaf3.jpg)
> 任务次数 任务间隔 任务指令 操作
> 0 , 1 30 5 * * * ,**stop**, [ 配置 ] [ 删除 ]
> 0 , 1 1 * * * * ,**start**, [ 配置 ] [ 删除 ]
> 
> 这样是每天5点半关服，每天整点开服（已经开了就不会重复开），并且要把崩溃自动重启关闭，要不然关服后会自动开启

是这样的嘛  那就是下面参数手册写的不全 我试试 如果可以我就关了issue
