### ISSUE TITLE
请求适配基岩版服务器状态监控

### ISSUE THREAD

**Issue by Lozumi** [Suwings/MCSManager#230]
现在的状态监控应该是Java版的，希望能加一个基岩版的。

**Comment by DeeRenjie** [comment]
同希望

**Comment by Suwings** [comment]
感谢提供建议。

十分抱歉，近期本作者较忙，本项目不得不暂停功能更新，有兴趣的话可以自己贡献代码，但必须经过测试。作者大概在7月中旬左右，将会重启本项目更新。
此为公益项目，来之不易，还请理解。
