### ISSUE TITLE
建议将管理页面所有绝对路径修改为相对路径

### ISSUE THREAD

**Issue by issueser** [Suwings/MCSManager#232]
在nginx反向代理使用二级目录时，绝对路径会导致一些问题，建议修改成相对路径。
如将网站MCSManager目录反向代理到本程序，未登录情况下访问http://example.com/MCSManager/ 会跳转http://example.com/public/login/ 而不是http://example.com/MCSManager/public/login/
页面资源也是一样的。
谢谢。

**Comment by FDuiv** [comment]
我也遇到了这个问题，困扰了我很久，目前只能用不同的域名去区分。

**Comment by GoblinCwl** [comment]
+1 添加可配置项目名也可以
