### ISSUE TITLE
 版本8.6.8 服务器正常开启 但是MCSM后台显示未开启 且无法操作控制台 1.15.2 paper端

### ISSUE THREAD

**Issue by zsqw123** [Suwings/MCSManager#233]
这种情况经常出现，而且出现后就得结束MCSM进程重启。

如图 服务器事实上已经开启， 也能进得去，就是后台显示未开启。
![Screenshot_2020-04-17-15-31-45-741_com quark brow](https://user-images.githubusercontent.com/49520432/79565200-cc7e1280-80e2-11ea-8db1-504588117d6e.jpg)
![Screenshot_2020-04-17-15-31-42-072_com quark brow](https://user-images.githubusercontent.com/49520432/79565203-ce47d600-80e2-11ea-8485-0c484240f456.jpg)

或者改成监听指定端口来确定MC是否运行？

**Comment by Suwings** [comment]
可能是一个 BUG，有时间我会测试一下 paper 端的运行，谢谢提交。
