### ISSUE TITLE
希望可以增加服务器CPU利用率高自动重启之类

### ISSUE THREAD

**Issue by zsqw123** [Suwings/MCSManager#235]
希望可以增加服务器在多长时间内CPU利用率多于百分之多少以后可以自动重启服务器

服务器有时候CPU利用率跑到很高 但是只要一重启 即使重启后人又都回来了 但是CPU利用率能降不少。
触发式重启要比定时重启高效

**Comment by Suwings** [comment]
想法不错，但是十分抱歉的是，近期其他事物较忙，项目暂停功能性更新，只进行质量性更新。
