### ISSUE TITLE
使用MCDR无法及时更新Log和后台显示BUG

### ISSUE THREAD

**Issue by ghost** [Suwings/MCSManager#236]
我在使用MCDR[https://github.com/Fallen-Breath/MCDReforged]，开启服务器时无法及时更新Log，需要输入指令才能更新（修改配置文件的刷新速度也无效），还有后台命令显示BUG,详见视频链接[https://lanzous.com/ic08bub]

**Comment by Suwings** [comment]
暂时还不清楚原因，作者本人最近较忙，暂停项目更新。

但是你这个有一个解决方案，既然输入一次命令之后会刷新回显，那么你可以在定时计划里面，设置每一秒钟执行一次list命令即可，这样就每秒刷新了一次回显，间接性的修复了这个问题。

另外感谢你提供的视频，这非常有利于找到出问题所在。
