### ISSUE TITLE
可以添加服务器限制功能吗

### ISSUE THREAD

**Issue by junxiesky** [Suwings/MCSManager#237]
比如限制某个服务器的人数,最大内存,端口

**Comment by huangsijun17** [comment]
服务端的人数和端口可以由MC服务端自带的配置文件`server.properties`决定，如果对外租赁是不希望被修改，可以通过文件权限系统加以限制。
最大内存是一个可选的java启动参数，添加服务端时就可以设置。如果希望限制虚拟机整体占用，可以使用Docker。当然，也可以使用Docker限制端口。

**Comment by junxiesky** [comment]
> 服务端的人数和端口可以由MC服务端自带的配置文件`server.properties`决定，如果对外租赁是不希望被修改，可以通过文件权限系统加以限制。
> 最大内存是一个可选的java启动参数，添加服务端时就可以设置。如果希望限制虚拟机整体占用，可以使用Docker。当然，也可以使用Docker限制端口。

但是 server.properties 内其他文件是需要用户需要修改的时候，该怎么解决

**Comment by junxiesky** [comment]
> 服务端的人数和端口可以由MC服务端自带的配置文件`server.properties`决定，如果对外租赁是不希望被修改，可以通过文件权限系统加以限制。
> 最大内存是一个可选的java启动参数，添加服务端时就可以设置。如果希望限制虚拟机整体占用，可以使用Docker。当然，也可以使用Docker限制端口。

我用的是其他服务端,无法使用java参数

**Comment by junxiesky** [comment]
> 服务端的人数和端口可以由MC服务端自带的配置文件`server.properties`决定，如果对外租赁是不希望被修改，可以通过文件权限系统加以限制。
> 最大内存是一个可选的java启动参数，添加服务端时就可以设置。如果希望限制虚拟机整体占用，可以使用Docker。当然，也可以使用Docker限制端口。

我的系统是Windows10,无法使用docker

**Comment by Suwings** [comment]
感谢提供建议。

十分抱歉，近期本作者较忙，本项目不得不暂停功能更新，有兴趣的话可以自己贡献代码，但必须经过测试。作者大概在7月中旬左右，将会重启本项目更新。
此为公益项目，来之不易，还请理解。

**Comment by junxiesky** [comment]
> 感谢提供建议。
> 
> 十分抱歉，近期本作者较忙，本项目不得不暂停功能更新，有兴趣的话可以自己贡献代码，但必须经过测试。作者大概在7月中旬左右，将会重启本项目更新。
> 此为公益项目，来之不易，还请理解。

好的，谢谢

**Comment by junxiesky** [comment]
> 感谢提供建议。
> 
> 十分抱歉，近期本作者较忙，本项目不得不暂停功能更新，有兴趣的话可以自己贡献代码，但必须经过测试。作者大概在7月中旬左右，将会重启本项目更新。
> 此为公益项目，来之不易，还请理解。

请问此功能何时支持？
