### ISSUE TITLE
希望在监控数据中心添加显示服务器硬盘容量大小

### ISSUE THREAD

**Issue by DeeRenjie** [Suwings/MCSManager#238]
希望在监控数据中心添加服务器硬盘可用容量和容量大小
如 2.5GB/500GB

**Comment by huangsijun17** [comment]
同意添加该功能，但对于监控的分区最好可以手动定义。比如我想监控`/dev/sdb`

**Comment by DeeRenjie** [comment]
例如这样： https://s1.ax1x.com/2020/04/28/J5V056.jpg

**Comment by White-NX** [comment]
臣附议，最好可以监控所有分区

**Comment by DeeRenjie** [comment]
现在看个磁盘空间都要去ssh使用 df -h 查看。

**Comment by Suwings** [comment]
感谢提供建议。

十分抱歉，最近因其他事物较忙，本项目不得不暂停功能更新，大概在7月左右，将会重启本项目更新。
此为公益项目，来之不易，还请理解。
