### ISSUE TITLE
额这咋回事

### ISSUE THREAD

**Issue by Zi-Gao** [Suwings/MCSManager#239]
![image](https://user-images.githubusercontent.com/57441907/80576223-66c14d00-8a37-11ea-94bc-24e572aa7188.png)
centos系统
![image](https://user-images.githubusercontent.com/57441907/80576292-822c5800-8a37-11ea-995a-20154e3591ae.png)
日志

**Comment by Suwings** [comment]
暂不清楚，从日志上来看无报错一切正常，无其他信息可供分析。

你是否搭建了反向代理，或者CDN之类的服务？
如果没有，请删除面板 user 文件夹下的所有#开头的账号，这回重置新建一个#master账号（密码123456），再来尝试。
如果前两步依然重复出现这种现象，建议重新安装面板。

另外浏览器建议使用Chrome现代浏览器，感谢提供反馈。

**Comment by Zi-Gao** [comment]
我的确使用了反向代理，也使用了cdn我现在关掉cdn试试，谢谢

**Comment by Zi-Gao** [comment]
请问用户名和密码在哪里？我在/users文件中的#master.json看到了密码和用户名但是无法登陆，请问管理员身份登陆需要带 # 吗

**Comment by huangsijun17** [comment]
面板需要一个 Websocket 链接，一个 http 链接。所以你需要将此两个协议均代理。

管理员的账户名需要带#

**Comment by huangsijun17** [comment]
> 暂不清楚，从日志上来看无报错一切正常，无其他信息可供分析。
> 
> 你是否搭建了反向代理，或者CDN之类的服务？
> 如果没有，请删除面板 user 文件夹下的所有#开头的账号，这回重置新建一个#master账号（密码123456），再来尝试。
> 如果前两步依然重复出现这种现象，建议重新安装面板。
> 
> 另外浏览器建议使用Chrome现代浏览器，感谢提供反馈。

可否考虑加一个测试页面，甚至不连接到主页上，拿来测试Websocket、http、https链接是否正常。
以便设置反代、CDN等时排除问题？

**Comment by Zi-Gao** [comment]
我不管是关闭面板后重新打开，或者修改文件都无法登陆

**Comment by Zi-Gao** [comment]
![image](https://user-images.githubusercontent.com/57441907/80663991-252cb280-8ac8-11ea-93b1-417049baa716.png)
这是使用#master 123456登陆的日志

**Comment by Zi-Gao** [comment]
![image](https://user-images.githubusercontent.com/57441907/80664183-a6844500-8ac8-11ea-93db-157e2b792522.png)
我重新安装后还是无法登陆

**Comment by Zi-Gao** [comment]
谢谢，我刷新了浏览器缓存成功登陆

**Comment by Zi-Gao** [comment]
但是如果我使用域名反代，并关闭cdn缓存还是会出现服务器错误

**Comment by Zi-Gao** [comment]
![image](https://user-images.githubusercontent.com/57441907/80669005-e56cc780-8ad5-11ea-906b-9bbf7a3fa029.png)
使用Nginx反代并且ssl，出现的问题。应为用宝塔面板搭建的反代所以不知道给出的反代配置放在哪里

**Comment by huangsijun17** [comment]
> ![image](https://user-images.githubusercontent.com/57441907/80669005-e56cc780-8ad5-11ea-906b-9bbf7a3fa029.png)
> 使用Nginx反代并且ssl，出现的问题。应为用宝塔面板搭建的反代所以不知道给出的反代配置放在哪里

参考这个：
https://github.com/Suwings/MCSManager/wiki/%E5%85%B3%E4%BA%8E%E5%AE%9D%E5%A1%94%E9%9D%A2%E6%9D%BF%E7%9A%84-Nginx-%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86%E4%BB%A5%E5%8F%8ASSL%E8%AF%81%E4%B9%A6%E9%83%A8%E7%BD%B2
