### ISSUE TITLE
如何正确关闭呢

### ISSUE THREAD

**Issue by lupohan44** [Suwings/MCSManager#24]
Windows整合版直接Ctrl+V结束配置信息不会保存 服务器的配置丢失 重新开启后需要重新配置 那么要怎样正确关闭呢

**Comment by Suwings** [comment]
Ctrl + C 来关闭，在关闭之前，确认没有其他用户在使用服务端配置和开关服修改配置操作。
程序结束时，会有数据I/O结束，确保所有文件读入和写出。
另外注意的是，不要直接关机来结束这个程序。

如果还有问题，请继续反馈，我将检查一下 Windows 整合版本。

**Comment by Suwings** [comment]
不过直接 Ctrl + C 来关闭确实可能有点不妥，尽管我认为对于这个程序而言，这是不错的方式。
我添加了新的代码。
现在监听了退出的信号事件，现在退出的时候会保存一次所有数据结构到文件。
详情请看 Commit。
