### ISSUE TITLE
有没有办法可以实现非最高管理账号完全封闭文件管理与查看母机的占用

### ISSUE THREAD

**Issue by roughanddai** [Suwings/MCSManager#240]
我正在准备实现多人同时管理服务器，但是我想他人不使用文件管理，这样可以保证无恶意管理删除重要信息

- 同时也希望可以限制控制台使用命令吧

**Comment by Suwings** [comment]
面板目前没有这种定制化的功能，但是可以用较为暴力的方式来间接实现。

- 删除文件管理
将 `onlinefs` 与 `public/onlinefs_public` 目录彻底删除，文件管理功能所有代码均在此目录下，删除后，网页界面依然会显示文件管理的选项，但是点击任何操作均不会有任何反应。

- 不显示宿主机资源
第一种较为简单，在 `public/template/component/`目录下，有各种各样的html文件，这些里的每个文件分别对应着不同的网页，你可以尝试删除掉以下代码段：
> https://github.com/Suwings/MCSManager/blob/master/public/template/center.html#L49
> https://github.com/Suwings/MCSManager/blob/master/public/template/component/console.html#L153
> https://github.com/Suwings/MCSManager/blob/master/public/template/component/console.html#L11


但这只是从网页上来阻止**普通**用户看见数据，稍微高级些的用户便能简单的从开发者工具中获取相关消息，得知宿主机资源。


另外的一种方法，较为复杂，需要删除前端网页代码的同时，又要删除后端的代码，来阻止无法获取任何数据，前端代码刚刚已经举例，这是后端发送数据的相关代码段：

> https://github.com/Suwings/MCSManager/blob/master/route/websocket/center.js#L74

你可以通过修改这些代码，来达成你的目的，但是一旦改错，面板无法启动应该也会存在。建议你找一个稍微懂一点JavaScript语言的技术人员，协助你完成这个任务，它十分简单。

祝你好运。

**Comment by Suwings** [comment]
另外，“同时也希望可以限制控制台使用命令吧” 这个方法，通过配置文件即可修改，详情请务必仔细查看阅读配置文件。

**Comment by roughanddai** [comment]
非常感谢，还好我会点js
