### ISSUE TITLE
希望可以增加启动后直接启动全部实例功能

### ISSUE THREAD

**Issue by mocha666** [Suwings/MCSManager#243]
*机器在夜间自动重启时，目前好像仅能提供启动管理功能，不可以直接启动全部实例*

> 可能我不会调整~

**Comment by huangsijun17** [comment]
可以加一个定时开启实例的功能，详见wiki

**Comment by Suwings** [comment]
这个功能可能会有点难操作，计划任务这块的用户体验做的不是很好，建议你仔细研究一下，wiki应该有写。
