### ISSUE TITLE
使用面板Unzip文件 中文内容全部变样

### ISSUE THREAD

**Issue by limjianhui789** [Suwings/MCSManager#244]
上传了zip文件 在面板unzip后 任何有关中文的都变奇奇怪怪的符号 或者 问号
在自己电脑解压却没有任何问题

**Comment by lone-wolf-akela** [comment]
很可能是因为你的自己的电脑是windows的而服务器是linux的。Windows下zip文件默认使用本机编码（对于简体中文电脑，一般是GBK编码）来存储文件名，而linux使用的是UTF8编码。
你可能需要一个能够在选项里开启使用utf8存储文件名的压缩软件（比如Bandizip）

**Comment by Suwings** [comment]
压缩和解压默认采用 GBK 编码。
