### ISSUE TITLE
推荐出租给人家 可以设定出租给那个用户 他能否创建子用户

### ISSUE THREAD

**Issue by limjianhui789** [Suwings/MCSManager#245]
用户可以设定 子用户只能read什么文件 write什么文件 等等
可以设定子用户 只能访问哪个文件 、能否使用终端
能否start stop kill服务器

**Comment by Suwings** [comment]
暂无这类功能，似乎市面上也很少有mc服务端面板拥有你这么细致化的权限管理。

未来也暂无这类计划，但若需求提议重复率较高，则会重新考虑这个功能是否需要开发。

谢谢你的反馈。
