### ISSUE TITLE
泰拉瑞亚以及部分Minecraft核心的控制台异常

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#246]
泰拉瑞亚服务器提示：

> Terraria Server is running in the background and input is disabled.

然后，一切命令无效。此外，`Thermos-1.7.10-1614-57-server.jar`核心的MInecraft服务端也无法输入命令。
两者均是更新了MCSM版本（更改控制台模型）后出现的问题。

此外，泰拉瑞亚开服后显示有大量的端口访问，疑似为在线人数监测的问题。服务器独立可选关闭？

**Comment by Suwings** [comment]
了解，感谢测试，虽然面板并不是专门为泰拉瑞亚而设计的，但是也应该会尽可能的接近相通的程序，但更新时间一段时间，短期内暂无时间更新。

**Comment by huangsijun17** [comment]
不止泰拉瑞亚，Thermos-1.7.10-1614-57-server.jar 也是这一症状。日志我没去翻，格雷服，MOD太多。

**Comment by huangsijun17** [comment]
查了一下泰拉瑞亚[服务端的源码](https://github.com/Pryaxis/TerrariaAPI-Server/blob/8d92ec645ba538e1a75274c78875c78c6339beb6/TerrariaServerAPI/TerrariaApi.Server/Hooking/ServerHooks.cs)，他直接用了.net的API: [Console.IsInputRedirected](https://docs.microsoft.com/en-us/dotnet/api/system.console.isinputredirected?view=netcore-3.1)。
而我这是Linux开服，还跑了个Mono。

**Comment by Suwings** [comment]
我记得好像有用户跟我反馈过泰拉瑞亚无法输入，也许就是这个原因。
具体我也不清楚，没玩过泰拉瑞亚。

**Comment by huangsijun17** [comment]
我定位到问题了，只要解决Console.IsInputRedirected的检测问题就可以了。

**Comment by haojie06** [comment]
> Console.IsInputRedirected

我也遇到了这个问题，所以想问一下你是怎么解决的呢

**Comment by huangsijun17** [comment]
> > Console.IsInputRedirected
> 
> 我也遇到了这个问题，所以想问一下你是怎么解决的呢

尚未解决，仍在研究中。

**Comment by 798725856** [comment]
我可以运行但是 服务器指令

**Comment by 798725856** [comment]
不可以选择世界

**Comment by huangsijun17** [comment]
> 不可以选择世界

不可以选择世界是什么意思？

**Comment by 798725856** [comment]
就是输入1 没有反应

**Comment by 798725856** [comment]
只可以一键那种吧

**Comment by ragnaroks** [comment]
如果你使用windows的话,可以试试 [wind](https://github.com/ragnaroks/Wind/tree/master/windctl/Readme)

**Comment by ragnaroks** [comment]
@Suwings 个人网站上线后,考虑加一个友链?

**Comment by Suwings** [comment]
> @Suwings 个人网站上线后,考虑加一个友链?

我没有个人网站，suwings.top 此站已经不开了，mcsm.suwings.top 是此项目的官方网页，这个网页的话已经不考虑再加友链了，谢谢邀请~
