### ISSUE TITLE
希望ipv6和ipv4能访问

### ISSUE THREAD

**Issue by 1248429482** [Suwings/MCSManager#249]
希望ipv6和ipv4能访问

**Comment by huangsijun17** [comment]
面板不干涉ipv6访问，建议详询主机租赁商。

**Comment by adsa562** [comment]
IPV4和IPV6的外網連接訪問是取決於架站平台的開放和支援程度，如果機台所處的網路沒有支援IPV6那就無解。請詢問網路服務供應商以獲得最準確的訊息。
