### ISSUE TITLE
对启用ssl服务器的支持

### ISSUE THREAD

**Issue by yhrC** [Suwings/MCSManager#25]
在使用nginx反向代理的使用https的服务器上使用时，因为默认的请求协议是http和ws。导致浏览器阻止请求而无法和后台建立连接。
在将public/common/URL.js第10行中的'http://'改成'https://'
以及将public/common/js/websocket.js第18行中的'ws://'改成'wss://'解决了问题。
不过希望对这个问题可以有更方便的设置或者是指引（而不是像我一样看浏览器控制台的报错来猜=-=）

**Comment by Suwings** [comment]
你所改的地方是对的，那里的设计就是专门为了实现 https 和 wss 而设计的。
只不过一直忘记写在 readme 上，实在抱歉。
稍后必当补上。 @yhrC

**Comment by Suwings** [comment]
已补上 [Commit](https://github.com/Suwings/MCSManager/commit/a8147634b54c6b2b6bda975a16e69aeddeca734b)
