### ISSUE TITLE
500内部错误

### ISSUE THREAD

**Issue by FPDADA** [Suwings/MCSManager#250]
500内部Privoxy错误
Privoxy在处理您的请求时遇到错误：

无法加载模板文件no-server-data或其包含的组件之一。

请与您的代理管理员联系。

如果您是代理管理员，请把所需文件放在(confdir)/templates目录中。该(confdir)目录的位置在主Privoxy config文件中指定。（通常是Privoxy安装目录）。
按照教程来的
centos

**Comment by huangsijun17** [comment]
不知说云。

您是在做什么操作？参考了哪个教程？在哪一步发生的问题？

**Comment by Shuazijun** [comment]
请关闭代理软件
