### ISSUE TITLE
增加对MCDR的支持

### ISSUE THREAD

**Issue by LiamSho** [Suwings/MCSManager#251]
目前MCSM对MCDR支持并不够好，希望能增加对MCDR的支持。
[MCDR的Github仓库](https://github.com/Fallen-Breath/MCDReforged)
以下为目前存在的问题的所需要的功能：
* 能够访问Minecraft服务器配置文件：使用自定义启动命令模式创建服务器，项目存放目录选择的是MCDR文件夹，启动命令为` python3 MCDReforged.py `，Minecraft服务器文件夹默认在项目存放目录中的server文件夹中，希望在使用MCDR时添加访问该文件夹中的服务器配置文件的功能。如果项目目录选择server文件夹，启动命令为`python3 ../MCDReforged.py`则MCDR启动失败。
* 控制台中的指令支持：MCDR指令默认使用`!!`开头，比如`!!MCDR status`，而MCSM控制台发出的指令都为`/`开头，希望添加自定义控制台发送指令头的功能，自带开头其实去掉也不影响使用。

**Comment by huangsijun17** [comment]
mcsm的默认指令不包含`/`，mc的后台命令一般也不需要/。
你直接输入!![命令]即可

**Comment by LiamSho** [comment]
> mcsm的默认指令不包含`/`，mc的后台命令一般也不需要/。
> 你直接输入!![命令]即可

刚刚换了好几个版本的MCDR试了试，好像是某几个版本的MCDR有这个输入指令不输出的问题，最新的好像没有问题。毕竟MCDR还是alpha版本。。

**Comment by Suwings** [comment]
个人感觉应该只需要修改启动命令，输入命令的时候加两个感叹号应该就可以解决了，根据你的描述，只是某些版本可能存在一些小问题，我觉得至少也得等mcdr成熟完善之后再进行适配更好。
感谢反馈。

**Comment by wanshanning** [comment]
可以使用shell脚本来启用，亲测正常
新建一个start.sh后输入
```
cd ../
python3 MCDReforged.py
```
保存即可

**Comment by CNlong-Py** [comment]
打开MCDR的文件夹的config.yml
将advanced_console 高级控制台设置成false
`advanced_console: false
`
MCSM中启动目录选择MCDReforged.py文件下
启动命令
`python3 -m MCDReforged`

**Comment by unitwk** [comment]
> 打开MCDR的文件夹的config.yml 将advanced_console 高级控制台设置成false `advanced_console: false ` MCSM中启动目录选择MCDReforged.py文件下 启动命令 `python3 -m MCDReforged`

新版本只要在终端设置中启动仿真终端即可。
