### ISSUE TITLE
推荐docker镜像源无法打开

### ISSUE THREAD

**Issue by smallXueTu** [Suwings/MCSManager#256]
推荐的 无法打开 https://registry.docker-cn.com
然后启动导致：
![image](https://user-images.githubusercontent.com/36348070/85844465-5af2cc80-b7d5-11ea-94a4-8bbdcf3a6a21.png)
找不到默认镜像

**Comment by Suwings** [comment]
报错信息为镜像名mcsd未找到。

建议先去面板中的，服务端管理，右上角有个创建镜像功能，先去创建名为mcsd的镜像。

网络上是没有名为mcsd的镜像的，是需要使用面板本地创建并且取名为mcsd。

如果面板创建镜像功能不正常，那就只能手动复制面板提供的dockerfile文本，来手动创建镜像，不过一般情况下，面板的创建镜像功能都能正常执行，只不过需要等待一段时间而已。

**Comment by smallXueTu** [comment]
> 报错信息为镜像名mcsd未找到。
> 
> 建议先去面板中的，服务端管理，右上角有个创建镜像功能，先去创建名为mcsd的镜像。
> 
> 网络上是没有名为mcsd的镜像的，是需要使用面板本地创建并且取名为mcsd。
> 
> 如果面板创建镜像功能不正常，那就只能手动复制面板提供的dockerfile文本，来手动创建镜像，不过一般情况下，面板的创建镜像功能都能正常执行，只不过需要等待一段时间而已。

好的 没注意服务器管理右上角 我以为是推荐镜像源的问题
