### ISSUE TITLE
文件管理上传文件异常

### ISSUE THREAD

**Issue by WindLeaf233** [Suwings/MCSManager#260]
为什么上传文件每次都失败？只有小文件可以，超过5MB的要不是上传到99%就停下怎么上传也没用，就是上传完了出现错误上传失败

**Comment by Suwings** [comment]
是否有反向代理？运行在何种操作系统上？

**Comment by WindLeaf233** [comment]
没有，windows 7 x32，x64也有这种问题

**Comment by Suwings** [comment]
暂不清楚此问题出现的原因，经过服务器搭建后，通过互联网链接上传文件，分别尝试上传10MB，50MB，1GB文件，均没有发现你所说的情况。 

建议检查防火墙设置，文件目录权限，并用管理员权限运行面板。

**Comment by Mereithhh** [comment]
我用ngxinx反代也出现了同样的问题，经测试在nginx配置文件里加上：
client_max_body_size 1000m;
就好了。
