### ISSUE TITLE
对输入法的兼容问题

### ISSUE THREAD

**Issue by MyBlueHorizon** [Suwings/MCSManager#262]
使用输入法输入字符时按下enter，会发送未输入完成的字符，希望如果是输入法状态下按下enter不要响应。

**Comment by huangsijun17** [comment]
浏览器是无法获取到系统的输入法状态的。更何况，和你交互的只是一个文本输入框。

**Comment by MyBlueHorizon** [comment]
那可否添加一个两次按下回车才发送命令的功能

**Comment by MyBlueHorizon** [comment]
或者如果回车是在最后一个字符输入后立刻触发的自动忽略之类的
