### ISSUE TITLE
更多服务端支持

### ISSUE THREAD

**Issue by 1812z** [Suwings/MCSManager#263]
就算不是minecraft的服务端，都会显示编辑server.properties文件按钮，不管文件在不在
还有能像翼龙面板一样 ，在创建服务器后一键选择服务端，自动复制文件吗

**Comment by Suwings** [comment]
面板未来版本有考虑新增“标签”的功能，用户可以给自己不同的服务端打上各种各样的“标签”，面板将会根据这些“标签”，来针对性的显示相关配置，但是由于各种服务端的特殊配置繁多，所以无法全部考虑到，很多配置文件还是只能依靠文件在线管理的在线编辑来手动编辑。

感谢你的建议。
