### ISSUE TITLE
面板API的问题

### ISSUE THREAD

**Issue by liaosunny123** [Suwings/MCSManager#264]
请问有关于面板的API吗？
比如我可以通过编程实现新增用户，删除用户，设置时间等等问题。
然后面板关于用户的配置路径在哪里？

**Comment by Suwings** [comment]
API 只有获取服务端信息的，比如玩家人数，服务器是否运行，最后启动时间这种。暂无新增，删除和修改数据的API，包括开启服务器和关闭服务器的API。还请理解，未来版本会逐渐加入。

**Comment by Suwings** [comment]
已增加：https://github.com/Suwings/MCSManager/releases/tag/v8.6.11
