### ISSUE TITLE
关于win自动启动的问题

### ISSUE THREAD

**Issue by 1235789gzy1** [Suwings/MCSManager#266]
我想知道有办法实现win环境下自动启动管理器吗？我曾经尝试使用win自带的计划任务进行启动，但是启动命令行之后无法正常访问网页即使我已经在任务管理器中看见了MCS命令行的进程，只能在手动结束进程并重新打开的情况下才能正常访问网页

**Comment by stevensane** [comment]
可以吧捷径放在启动资料夹，通常我都是放在用户启动资料夹

**Comment by huangsijun17** [comment]
写一个bat，把bat加入自启动。
注意先CD到MCSM所在目录。

**Comment by 1235789gzy1** [comment]
> 写一个蝙蝠，蝙蝠把加入自启动。
> 注意先CD到MCSM所在目录。

我突然发现这样有个问题，你这样可以设置登陆自启，但是并不意味着“启动自启”，电脑开机后，如果账户有密码，你必须手动登陆之后才能启动MCSM，而计划任务只需要预先设置好这个用户的密码，即可做到开机后直接启动程序，而不需要手动登陆。虽然计划任务启动之后的程序没有任何的窗口，但是你仍能在任务管理器中看见它，并且也是正常运行的（个人不是特别需要bat一直显示着，有没有窗口其实无所谓），所以我觉得我还是需要对win环境下计划任务的支持。

**Comment by stevensane** [comment]
> > 寫一個蝙蝠，蝙蝠把加入自啟動。
> > 注意先CD到MCSM所在目錄。
> 
> 我突然發現這樣有個問題，你這樣可以設置登陸自啟，但並不意味著“啟動自啟”，電腦開機後，如果賬戶有密碼，你必須手動登陸之後才能啟動MCSM，而計劃任務只需要預先設置好這個用戶的密碼，即可做到開機後直接啟動程序，而不需要手動登陸。雖然計劃任務啟動之後的程序沒有任何窗口，但您仍能在任務管理器中看到它，並且也是正常運行的（個人不是特別需要bat一直顯示著，有沒有窗口其實無所謂），所以我覺得我還是需要對win環境下計劃任務的支持。

关闭视窗需要使用ctrl+c 所以视窗最好不要关
不用手动登录只要开启免登录就好，我都是放在系统的开机资料夹不是user资料夹下的

**Comment by 1235789gzy1** [comment]
解决了，在计划任务中必须设置起始位置与.bat文件一致（默认为空）
如图：
![image](https://user-images.githubusercontent.com/52618207/91241792-4fd9ff80-e778-11ea-9c98-0994e29535b1.png)

**Comment by bddjr** [comment]
考古（来自必应）。  

现在可以直接用下面这个工具，双击bat设置为service了，完美解决开机启动以及关闭进程。  
https://github.com/bddjr/mcsmanager-services-for-windows

***
我之前折腾的时候因为计划任务还有edge在阻碍，导致不能自动启动，于是我选择了在组策略里启动脚本，但现在已经有更好的方案了。

**Comment by 06jiaozi** [comment]
> 解决了，在计划任务中必须设置起始位置与.bat文件一致（默认为空） 如图： ![image](https://user-images.githubusercontent.com/52618207/91241792-4fd9ff80-e778-11ea-9c98-0994e29535b1.png)

确实有用，研究了半天的问题，在你这解决了，感谢

**Comment by bddjr** [comment]
@06jiaozi  官方文档已经有设置Windows自启动服务端的教程了，你还搁这考古干啥啊
