### ISSUE TITLE
希望添加子服资源占用监控功能

### ISSUE THREAD

**Issue by MyPictureBed** [Suwings/MCSManager#267]
最近服务器总会突然CPU占满，很难找到到底是哪个子服占用的
希望在服务器列表里面显示每个子服的资源占用情况

**Comment by 1235789gzy1** [comment]
不是已经有了么

**Comment by 1235789gzy1** [comment]
![超级截屏_20200711_143634](https://user-images.githubusercontent.com/52618207/87218295-f2cee980-c383-11ea-937d-d2ea179aac7e.png)

**Comment by MyPictureBed** [comment]
额，这应该是总使用率。因为我完全关闭服务端后仍有CPU占有率显示。
