### ISSUE TITLE
PC登入速度慢

### ISSUE THREAD

**Issue by liaosunny123** [Suwings/MCSManager#268]
面板有一定的用户，但是不知道为什么目前面板的登入打开速度很慢。我尝试关闭所有的服务端发现仍然如此，但是手机登入的速度非常快，电脑登入的速度非常慢。不知道是什么情况？我换了两个浏览器都是的

**Comment by Suwings** [comment]
手机登陆非常快，电脑登陆非常慢，这个挺奇怪的。如果是面板存在问题，应该两种情况都登陆较慢才对。手机访问与电脑访问都是同一个网页，只是响应式布局看起来有点不一样，但是所有文件与所有代码都是一样的。

你可以按F12，调整到Console和Network选项卡，进行登陆，看看是否有报错，并且在network里面看看响应请求返回时间。

具体情况暂不清楚。
