### ISSUE TITLE
希望增加上传错误时的提示

### ISSUE THREAD

**Issue by KatyushaScarlet** [Suwings/MCSManager#271]
使用文件在线管理器，上传一个1.2G的文件时提示：“错误，文件上传失败！ undefined”
查看response后发现，nginx返回413 Request Entity Too Large
但前端没有做出正确的判断，不查看请求就不知道是什么错误
希望能够考虑改进一下，谢谢！

**Comment by Suwings** [comment]
感谢提供意见，文件在线管理模块在以后可能需要重构，近期不便再修复，待有时间会将文件在线管理重构。

**Comment by KatyushaScarlet** [comment]
加油！
