### ISSUE TITLE
计划任务与崩溃自动重启冲突

### ISSUE THREAD

**Issue by MakesYT** [Suwings/MCSManager#273]
如果使用计划任务关闭服务器（__stop__），MCSM会认为服务器是崩溃然后重新启动服务器

**Comment by 2696703792** [comment]
![image](https://user-images.githubusercontent.com/42534870/87551735-5ab66480-c6e3-11ea-8719-9f4d8304c63b.png)

**Comment by Suwings** [comment]
了解，感谢反馈问题，这个问题下个版本将会修复。

**Comment by huangsijun17** [comment]
我们拿这个来实现定时重启的……

**Comment by 2696703792** [comment]
再添加一个开启的任务就可以定时重启了

**Comment by huangsijun17** [comment]
> 再添加一个开启的任务就可以定时重启了

MOD太多，关闭太慢……

**Comment by 2696703792** [comment]
没有区别啊，你新建一个每分钟执行一次的启动不就完了

**Comment by huangsijun17** [comment]
> 没有区别啊，你新建一个每分钟执行一次的启动不就完了

我服务端还不能关了？

**Comment by huangsijun17** [comment]
而且，明天定时重启，我关服维护的时候还要去把开服参数改掉？

**Comment by 2696703792** [comment]
那你去请求添加功能噻，而且关服也就十几秒，隔一分钟启动不行，就再弄一个2分钟的呗

**Comment by 2696703792** [comment]
关服都关那么久，开服开几十分钟？

**Comment by 2696703792** [comment]
我开260多个mod，关服也就5，6秒

**Comment by huangsijun17** [comment]
看了一下，计划任务支持直接输入MCSM的管理命令。我把命令改成`__restart__`就可以重启了。你把命令改成`__stop__`试试看。

**Comment by huangsijun17** [comment]
> 我开260多个mod，关服也就5，6秒

三个格雷服务MOD，5、6、CE各一个。

**Comment by 2696703792** [comment]
> 看了一下，计划任务支持直接输入MCSM的管理命令。我把命令改成`__restart__`应该就可以重启了。你把命令改成`__stop__`试试看。

你是没看截图？

**Comment by 2696703792** [comment]
> 看了一下，计划任务支持直接输入MCSM的管理命令。我把命令改成`__restart__`应该就可以重启了。你把命令改成`__stop__`试试看。

不对呀，你开了崩溃重启对吧，那你输stop不就完了，而不是输`__stop__`

**Comment by Suwings** [comment]
那个重启功能，说实话在某些特别情况下，可能会不稳定，比如关服时长如果超过10分钟，面板就不会再尝试启动，重启功能就会变成关服功能了。

但是10分钟的关服时间应该是适用于绝大部分情况了。

**Comment by 2696703792** [comment]
> 那个重启功能，说实话在某些特别情况下，可能会不稳定，比如关服时长如果超过10分钟，面板就不会再尝试启动，重启功能就会变成关服功能了。
> 
> 但是10分钟的关服时间应该是适用于绝大部分情况了。

看一下这个https://github.com/Suwings/MCSManager/issues/274建议呗

**Comment by Suwings** [comment]
最近其他项目工期将至，我是真没时间更新了，花了一下午更新了API功能，先缓缓吧，这几天我要把工作安排的任务做完。 @2696703792

**Comment by 2696703792** [comment]
> 最近其他项目工期将至，我是真没时间更新了，花了一下午更新了API功能，先缓缓吧，这几天我要把工作安排的任务做完。 @2696703792

没事你忙你的，有时间弄一下就行，感谢！
