### ISSUE TITLE
功能请求：服务器自启

### ISSUE THREAD

**Issue by MakesYT** [Suwings/MCSManager#274]
可以选择某个或某些服务器在面板启动时自动启动

**Comment by MAX-XiaoKui** [comment]
添加计划任务执行__start__指令就行了啊

**Comment by 2696703792** [comment]
> 添加计划任务执行__start__指令就行了啊

麻烦看清楚需求

**Comment by huangsijun17** [comment]
> 添加计划任务执行__start__指令就行了啊

任务计划不支持在启动面板后直接执行特定命令。

**Comment by huangsijun17** [comment]
> 可以选择某个或某些服务器在面板启动时自动启动

你是第3个还是第4个提这个建议的人了。

**Comment by 2696703792** [comment]
> > 可以选择某个或某些服务器在面板启动时自动启动
> 
> 你是第3个还是第4个提这个建议的人了。

不是吧，阿Sir

**Comment by Suwings** [comment]
感谢反馈，鉴于此需求反馈较多，下个版本会推出一个初版。
