### ISSUE TITLE
功能建议 批量&编组 + bug

### ISSUE THREAD

**Issue by RimuruChan** [Suwings/MCSManager#276]
## 批量操作
勾选指定服务器开启，关闭
发送指令，分发文件等
## 编组
同批量操作内容

## bug
服务器thread dump后会处于停滞状态，这时候崩溃重启不会触发，因为进程没死，但是服务器已经崩溃了

**Comment by Suwings** [comment]
感谢提供建议，我们会仔细考虑的。

**Comment by Suwings** [comment]
关于你所说的那个BUG，恕我们短时间内无法修复，因为控制面板为了适配更多的程序，服务端和其他游戏服务端，所以不可能深度适配每一个服务端。因为如此，控制面板只能通过服务端进程的开启和关闭来判定一个服务端是否开启和关闭，崩溃检测并没有办法从游戏内部的角度来检测状态，只能通过进程的结束来检测。

总而言之，这类服务端内部的崩溃导致的进程卡死，恕控制面板无法检测到，只能人为手动干涉。

**Comment by RimuruChan** [comment]
> 关于你所说的那个BUG，恕我们短时间内无法修复，因为控制面板为了适配更多的程序，服务端和其他游戏服务端，所以不可能深度适配每一个服务端。因为如此，控制面板只能通过服务端进程的开启和关闭来判定一个服务端是否开启和关闭，崩溃检测并没有办法从游戏内部的角度来检测状态，只能通过进程的结束来检测。
> 
> 总而言之，这类服务端内部的崩溃导致的进程卡死，恕控制面板无法检测到，只能人为手动干涉。

确实
