### ISSUE TITLE
翻譯

### ISSUE THREAD

**Issue by jing-shiun** [Suwings/MCSManager#277]
請問可以翻譯成繁體嗎
我這邊需要繁體

**Comment by huangsijun17** [comment]
项目貌似没有独立的语言文件……繁体化需要硬改代码了。

**Comment by jing-shiun** [comment]
那 可以提供給我嗎 翻譯好後回傳給你

**Comment by Suwings** [comment]
https://public-z.oss-cn-shenzhen.aliyuncs.com/MCSManager_8.6%20%E7%B9%81%E4%BD%93%E4%B8%AD%E6%96%87.zip

请下载，一天后此链接将失效，如果是Linux使用，则直接全部覆盖即可。

**Comment by jing-shiun** [comment]
感謝
