### ISSUE TITLE
手机端经常断开连接

### ISSUE THREAD

**Issue by MAX-XiaoKui** [Suwings/MCSManager#279]
MCSM8.6.11，winserver2008

**Comment by Suwings** [comment]
面板后端与前端采用 Websocket 链接，内部有一套心跳包机制，当手机把浏览器置于后台时，浏览器就不再会执行js脚本发送心跳包，从而后端等待一段时间后，便会认为已与前端丢失链接，自动断开，这也是面板自身的一套安全机制。

关于这个情况，目前只能不断延长心跳包断开阈值，来减少这种情况的发生，下个版本将继续增加心跳包阈值。

**Comment by MAX-XiaoKui** [comment]
问题是我有时候没把浏览器放后台就会断开
甚至几秒钟就断开
不知道是啥情况

**Comment by Suwings** [comment]
这种情况不应频繁，如果是几秒钟断开，便确实有问题，稍后我们便会在手机端上自检。感谢反馈。
