### ISSUE TITLE
[Feature Request] 希望能自定义docker参数

### ISSUE THREAD

**Issue by himekifee** [Suwings/MCSManager#280]
RT

**Comment by Suwings** [comment]
感谢反馈，Docker 相关功能肯定是不断增加与支持的，但更新能力有限，功能会逐步增加，Docker 相关的支持肯定不会少，毕竟属于靠核心位置的功能需求。

**Comment by YooKing** [comment]
> 感谢反馈，Docker 相关功能肯定是不断增加与支持的，但更新能力有限，功能会逐步增加，Docker 相关的支持肯定不会少，毕竟属于靠核心位置的功能需求。

支持了吗支持了吗

**Comment by YooKing** [comment]
> 感谢反馈，Docker 相关功能肯定是不断增加与支持的，但更新能力有限，功能会逐步增加，Docker 相关的支持肯定不会少，毕竟属于靠核心位置的功能需求。

支持了吗支持了吗

**Comment by Suwings** [comment]
已经实现。
https://github.com/Suwings/MCSManager/releases/tag/v8.6.15

**Comment by Suwings** [comment]
https://github.com/Suwings/MCSManager/releases/tag/v8.6.15
8.6.15版本已经新增docker API部分支持，更多部分还得以后再更新。
