### ISSUE TITLE
关于本项目的建议

### ISSUE THREAD

**Issue by Li-Dicker** [Suwings/MCSManager#281]
1. 建议将node的运行放在后台，防止手贱

2. 整合成一个软件，方便小白用户使用

3. JAVA内存堆栈默认单位MB

4. 在后台面板内贴上各大MC服务端以及客户端的下载链接

5. 自动读取json文件，并在在线编辑时转成UI界面方便操作

6. 将update logs换一个地方放

7. 侧边栏增加二级到多级目录

8. ~~说实话这个项目真的很好，我也很想把它改成一个用nodejs编写的Web后台，类似于宝塔但又不同于宝塔，但是本人太菜做不到，如果开发者大大有这个心思的话希望能这样做吧，谢谢！各位MC大佬不喜勿喷啊！~~

**Comment by Suwings** [comment]
感谢提供建议，部分建议会慎重考虑的，谢谢你，祝你使用愉快。

**Comment by huangsijun17** [comment]
1. wiki中有关于如何使用systemctl后台开启的方法。
2. 面板主要服务于MC租赁商或Bungeecord服主或其他多服务端的服主。大多具有一定的计算机水平。
3. 我们平时都是直接输XG的……
4. 各大MC服务端以及客户端的下载链接？？？几十个东西，还三天两头换地址，甚至都没地址的。
5. 在线绘制UI的难度和复杂程度不亚于一个独立的项目。

**Comment by Li-Dicker** [comment]
抱歉，打扰了





------------------&nbsp;Original&nbsp;------------------
