### ISSUE TITLE
Wiki：登录传递过程图

### ISSUE THREAD

**Issue by Li-Dicker** [Suwings/MCSManager#282]
这个wiki里面的流程图挂掉了

**Comment by 10935336** [comment]
然而它并没有挂掉
https://github.com/Suwings/Suwings.github.io/raw/master/mcserver/pass.png

**Comment by Li-Dicker** [comment]
但是我这里挂掉了呢，并且一直还加载不去，包括开了代理也是一样的，可能是我的问题？抱歉




------------------&nbsp;Original&nbsp;------------------

**Comment by huangsijun17** [comment]
> 但是我这里挂掉了呢，并且一直还加载不去，包括开了代理也是一样的，可能是我的问题？抱歉
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: "Suwings/MCSManager" <notifications@github.com&gt;; Date:&nbsp;Wed, Jul 22, 2020 10:48 PM To:&nbsp;"Suwings/MCSManager"<MCSManager@noreply.github.com&gt;; Cc:&nbsp;"顾亦辰"<Li_Dicker@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject:&nbsp;Re: [Suwings/MCSManager] Wiki：登录传递过程图 (#282) 然而它并没有挂掉 https://github.com/Suwings/Suwings.github.io/raw/master/mcserver/pass.png — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

一切正常，浏览器缓存问题？

**Comment by Li-Dicker** [comment]
可能吧，抱歉麻烦你了。





------------------&nbsp;Original&nbsp;------------------
