### ISSUE TITLE
关闭服务器后完整版终端没有开启服务器按钮

### ISSUE THREAD

**Issue by MAX-XiaoKui** [Suwings/MCSManager#283]
![Screenshot_2020-07-23-00-29-00-94_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/53287753/88202563-a8027b00-cc7b-11ea-9f90-f89a89bc52a6.jpg)
如图，服务器关闭后命令控制台的“关闭”按钮还是“关闭”而不是“开启”，开启服务器还得到“管理”页面或者迷你型终端
mcsm8.6.11, winserver 2008

**Comment by MAX-XiaoKui** [comment]
@Suwings

**Comment by huangsijun17** [comment]
看了一下，貌似是屏幕分辨率窄时被隐藏了。
![image](https://user-images.githubusercontent.com/31504595/88260939-efc6e800-ccf7-11ea-8476-3d4d89994e8e.png)

**Comment by huangsijun17** [comment]
https://github.com/Suwings/MCSManager/compare/master...huangsijun17:patch-3

已修复，等待合并……

**Comment by Suwings** [comment]
十分抱歉，开启按钮因为排版的问题在手机屏幕上隐藏了，刚刚经过与开发团队的商讨，还是决定下个版本将开启和关闭按钮合并在一起，服务器开启时显示关闭按钮，服务器关闭时显示开启按钮便可。
