### ISSUE TITLE
关于wiki中systemd的建议

### ISSUE THREAD

**Issue by MAX-XiaoKui** [Suwings/MCSManager#285]
[wiki中关于systemd的部分](https://github.com/Suwings/MCSManager/wiki/%E4%BD%BF%E7%94%A8-systemctl-%E7%AE%A1%E7%90%86%E5%99%A8)中，如果用nvm安装node的话（wiki里面是用nvm装的），.service文件中的ExecStart的node程序目录应该是/root/.nvm/versions/node/node版本/bin/node（我用的是root账户）
所以完整的ExecStart应该是`ExecStart=/home/用户名/.nvm/versions/node/node版本/bin/node /home/用户名/mcsmanager/app.js`
建议在wiki里面更改一下

**Comment by huangsijun17** [comment]
反对，理由如下:
1. 安装方式不同，设置会不同。例如我会使用`n`来安装，就会自动写入环境变量。
2. 我尝试过Ubuntu、CentOS7、Centos8等多个系统，其中的其它设置也各不相同。所以，不建议对其修改。

**Comment by Snowflake-Pink** [comment]
> 反对，理由如下:
> 
> 1. 安装方式不同，设置会不同。例如我会使用`n`来安装，就会自动写入环境变量。
> 2. 我尝试过Ubuntu、CentOS7、Centos8等多个系统，其中的其它设置也各不相同。
>    所以，我不建议对其修改。

的确各种安装方式不同，路径很不一样，但是应当在上面加些提示，让每个人自己去找自己的 `node` 路径，不然小白很容易直接照抄上去，然后一堆 `fail` `error` 的

**Comment by MAX-XiaoKui** [comment]
> > 反对，理由如下:
> > 
> > 1. 安装方式不同，设置会不同。例如我会使用`n`来安装，就会自动写入环境变量。
> > 2. 我尝试过Ubuntu、CentOS7、Centos8等多个系统，其中的其它设置也各不相同。
> >    所以，我不建议对其修改。
> 
> 的确各种安装方式不同，路径很不一样，但是应当在上面加些提示，让每个人自己去找自己的 `node` 路径，不然小白很容易直接照抄上去，然后一堆 `fail` `error` 的

有点道理

**Comment by Suwings** [comment]
已经将这部分内容重写，并且发布了一键安装脚本，安装成功后会自动将配置文件写入到 `/usr/lib/systemd/system/mcsm.service` 中，面板和 node 环境将自动安装在 /opt/ 目录下。

各位可以重新试试这个脚本，目前支持 Ubuntu 和 Centos。
