### ISSUE TITLE
运行python脚本不兼容某些unicode

### ISSUE THREAD

**Issue by zhang-anzhi** [Suwings/MCSManager#286]
使用MSCM自定义参数`python test.py`启动python脚本，无法正常显示`\u00bb`也就是`↻`
**test.py**
```python
print('启动测试脚本')
print('\u00bb')
print('↻')
```
正常从控制台运行如下图
![image](https://user-images.githubusercontent.com/37402126/88395998-7d87fd80-cdf4-11ea-8a01-d227453f8165.png)
从MSCM运行如下图
![image](https://user-images.githubusercontent.com/37402126/88396057-95f81800-cdf4-11ea-8e28-c76958a8896b.png)
MSCM设置尝试过gbk及utf8编码都会报错
以上为使用[MCDReforged](https://github.com/Fallen-Breath/MCDReforged)启动MC服务器时发现的问题，单独提取出来方便复现
实例配置如下
![image](https://user-images.githubusercontent.com/37402126/88396243-d5beff80-cdf4-11ea-804c-768dfb6a77d8.png)

**Comment by zhang-anzhi** [comment]
啊对了，用bat启动python脚本也不行的

**Comment by zhang-anzhi** [comment]
我尝试过以下方法，所以才会报这个BUG：

1.编码部分设置为 `gbk` `GBK` `utf8` `utf-8` UTF8` `UTF-8`

2.将自定义命令设置绝对路径和相对路径

3.自定义命令使用 `python xxx.py` `python.exe xxx.py` (至于`xxx.py`会显示以下提示)

![image](https://user-images.githubusercontent.com/37402126/88398348-dad17e00-cdf7-11ea-98e0-93550b777c08.png)

4.使用一个 `xxx.bat` 脚本在里面放启动命令然后自定义命令填写 `xxx.bat`

**Comment by huangsijun17** [comment]
系统环境？
中文Windows？
Python版本？2还是3？

**Comment by huangsijun17** [comment]
![image](https://user-images.githubusercontent.com/31504595/88398940-add19b00-cdf8-11ea-9ed0-ff80936ae6d7.png)
下面那个是什么字符？

**Comment by zhang-anzhi** [comment]
> 系统环境？
> 中文Windows？
> Python版本？2还是3？

系统Windows 10 中文 专业版
Python 3.8

**Comment by huangsijun17** [comment]
> ![image](https://user-images.githubusercontent.com/31504595/88398940-add19b00-cdf8-11ea-9ed0-ff80936ae6d7.png)
> 下面那个是什么字符？

[21BB | ↻ | CLOCKWISE OPEN CIRCLE ARROW
](http://unicode.org/charts/nameslist/n_27F0.html)

**Comment by zhang-anzhi** [comment]
> ![image](https://user-images.githubusercontent.com/31504595/88398940-add19b00-cdf8-11ea-9ed0-ff80936ae6d7.png)
> 下面那个是什么字符？

整个案子罪魁祸首是** `↻`** 字符和它的unicode码 **`\u21bb`**
![image](https://user-images.githubusercontent.com/37402126/88399394-61d32600-cdf9-11ea-899a-6cec8103a7b6.png)

**Comment by zhang-anzhi** [comment]
> [21BB | ↻ | CLOCKWISE OPEN CIRCLE ARROW ](http://unicode.org/charts/nameslist/n_27F0.html)

这几个字符也不支持

**Comment by huangsijun17** [comment]
![image](https://user-images.githubusercontent.com/31504595/88551532-8a575c00-d055-11ea-8264-9c6e95d101d2.png)
Linux下测试一切正常。

系统版本：CentOS Linux release 7.8.2003 
PY版本：Python 3.6.8
MCSM版本： 8.6.10 发行版本

**Comment by huangsijun17** [comment]
试一下加一个`-X utf8`参数：`py -X utf8 .\test.py`
实测Windows下加入参数后正常。

我测试了C和Java的输出，在MCSM里是正常的。确认了是PY的编码问题。外加错误代码里提到了GBK，所以怀疑是PY用GBK编码去跑了这个使用自定义UTF-8字符的程序导致的错误。外加默认使用UTF-8的Linux系统下正常，就常识了让PY直接跑UTF-8。成功了。

应该是node.js的模拟shell的问题。

**Comment by zhang-anzhi** [comment]
感谢！
已经成功解决

**Comment by zhang-anzhi** [comment]
经过测试自定义启动命令必须是 `-X utf8`，不能写 `utf-8` 否则就控制台乱码
