### ISSUE TITLE
server.properties 配置文件修改页面翻译错误

### ISSUE THREAD

**Issue by ghost** [Suwings/MCSManager#287]
![QQ图片20200725180536](https://user-images.githubusercontent.com/43809955/88454335-7539cc00-cea1-11ea-9cd2-a01554198d40.png)
设置为“0”可以取消出生点保护！

**Comment by huangsijun17** [comment]
直接PR吧。

**Comment by huangsijun17** [comment]
查了一下[Minecraft WiKi](https://minecraft-zh.gamepedia.com/index.php?title=Server.properties)，原话如下：

> 通过将该值进行2x+1的运算来决定出生点的保护半径。设置为0将不会禁用出生点保护，但会保护位于出生点的那一个方块。设置为1会保护以出生点为中心的3x3方块的区域，2会保护5x5方块的区域，3会保护7x7方块的区域，以此类推。这个选项不在第一次服务器启动时生成，只会在第一个玩家加入服务器时出现。如果服务器没有设置OP，这个选项会自动禁用。

确实是`不会禁用出生点保护`，但是项目内的描述可能节选不当，我去改一下吧。

**Comment by AlexanderMC8533** [comment]
> 查了一下[Minecraft WiKi](https://minecraft-zh.gamepedia.com/index.php?title=Server.properties)，原话如下：
> 
> > 通过将该值进行2x+1的运算来决定出生点的保护半径。设置为0将不会禁用出生点保护，但会保护位于出生点的那一个方块。设置为1会保护以出生点为中心的3x3方块的区域，2会保护5x5方块的区域，3会保护7x7方块的区域，以此类推。这个选项不在第一次服务器启动时生成，只会在第一个玩家加入服务器时出现。如果服务器没有设置OP，这个选项会自动禁用。
> 
> 确实是`不会禁用出生点保护`，但是项目内的描述可能节选不当，我去改一下吧。

也就是说：如果设定为0，根据f（x）=2x+1，游戏实际实现为仅脚下的方块为出生点保护

**Comment by huangsijun17** [comment]
> > 查了一下[Minecraft WiKi](https://minecraft-zh.gamepedia.com/index.php?title=Server.properties)，原话如下：
> > > 通过将该值进行2x+1的运算来决定出生点的保护半径。设置为0将不会禁用出生点保护，但会保护位于出生点的那一个方块。设置为1会保护以出生点为中心的3x3方块的区域，2会保护5x5方块的区域，3会保护7x7方块的区域，以此类推。这个选项不在第一次服务器启动时生成，只会在第一个玩家加入服务器时出现。如果服务器没有设置OP，这个选项会自动禁用。
> > 
> > 
> > 确实是`不会禁用出生点保护`，但是项目内的描述可能节选不当，我去改一下吧。
> 
> 也就是说：如果设定为0，根据f（x）=2x+1，游戏实际实现为仅脚下的方块为出生点保护

是的，仅仅出生点脚下那一个方块
