### ISSUE TITLE
非正常关闭下次无法正常启动

### ISSUE THREAD

**Issue by lupohan44** [Suwings/MCSManager#29]
因为某些原因导致服务端有时候会非正常关闭 一旦非正常关闭就无法再次启动 会报错 请问能解决一下吗

**Comment by HonokaClub** [comment]
请补充一下报错日志
非正常关闭是指强行关闭后端程序吗？

**Comment by lupohan44** [comment]
服务器直接关闭 未正常退出后端程序




在2018年5月5日 09:12，HonokaClub<notifications@github.com> 写道：
请补充一下报错日志
非正常关闭是指强行关闭后端程序吗？

**Comment by HonokaClub** [comment]
console没有输出任何信息吗？还请查看一下

**Comment by Suwings** [comment]
无法启动的现象是什么？终端应该报错了一些数据，并且你是如何强行关闭这个面板程序的？直接断电式的关闭？
如果下次遇到还请保存错误信息，以方便我们检查。
还有你说的 `因为某些原因` 这个原因是什么？

目前来看，最有可能的是，强制性的直接关闭这个程序，导致这个程序的某个IO流输出不完全，然后`core/info.json`文件或 `users/*.json`文件不完整导致的。

**Comment by lupohan44** [comment]
似乎是断电式关闭
因为某些原因 这个原因应该是主机商的问题
似乎是core/下的某个文件报错的




在2018年5月5日 11:35，Suwings<notifications@github.com> 写道：

无法启动的现象是什么？终端应该报错了一些数据，并且你是如何强行关闭这个面板程序的？直接断电式的关闭？
如果下次遇到还请保存错误信息，以方便我们检查。
还有你说的 因为某些原因 这个原因是什么？

目前来看，最有可能的是，强制性的直接关闭这个程序，导致这个程序的某个IO流输出不完全，然后core/info.json文件或 users/*.json文件不完整导致的。

**Comment by Suwings** [comment]
根据你现在提供的信息，我大致可以猜到，是  core/info.json 文件损坏导致的。
此文件用于统计面板各类数据，每隔一定时间就会重新写入。
删除此文件即可恢复正常启动，不会损失用户与服务端数据，只会需要重新统计某些数据。
