### ISSUE TITLE
可否在用户量标出显示该用户是否已开启API-Key？

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#294]
某些时候临时开启的，怕忘关。

没有HTTPS，不敢玩get和post啊。

**Comment by Suwings** [comment]
目前功能就可以实现吧？
点击用户的API key，如果是空的就是关闭的，如果不为空就是开启的。

**Comment by huangsijun17** [comment]
现在需要依次打开每一个用户。我现在有7个用户了……

**Comment by huangsijun17** [comment]
![image](https://user-images.githubusercontent.com/31504595/89480184-47b92080-d7c7-11ea-8927-bba8fd277831.png)
如图，加一个用户开启了API的提示就行……

**Comment by Suwings** [comment]
原来如此，感谢提供意见。下个版本加入。
