### ISSUE TITLE
这个已经崩了我好多次浏览器了！

### ISSUE THREAD

**Issue by TLSteve** [Suwings/MCSManager#299]
开服就这种 电脑也是变成未响应
都只能回归最原始的开服端了.. 
求修复...
问题出现在出现较多日志（启动）的时候
并且一直在启动后持续存在 导致控制台无法进入
一进去 浏览器就就崩溃
![IMG20200805234610](https://user-images.githubusercontent.com/66633960/89434255-e583ff80-d775-11ea-8dc9-1498b1b024f9.jpg)

**Comment by Suwings** [comment]
使用模拟型迷你控制台即可，在8.6.11以上版本，控制台左侧有个模拟型控制台，可以适用于内存小的手机，不会崩溃。
