### ISSUE TITLE
建议修改登录页背景图片样式

### ISSUE THREAD

**Issue by Nchyn** [Suwings/MCSManager#30]
当前我所使用的版本（8.3.0）及刚刚发布的最新版本登陆页面背景图片当前设置为拉伸铺满
这在视觉效果上比较糟糕
建议对背景div样式表phone_not内添加 background-size: cover
删除内联样式中的width与height属性即可保证背景图片不被拉伸
![image](https://user-images.githubusercontent.com/28627461/39660583-a4d86f0a-5074-11e8-81b8-f7f511ebf356.png)

当前设置
`<div id="view-bg" class="phone_not">
        <img src="./static/bg.jpg">
    </div>`
`#view-bg {
    z-index: -3;
    width: 100%;
    height: 100%;
    position: fixed;
    min-height: 475px;
    background-size: cover;
}`

**Comment by Suwings** [comment]
十分感激发现这个客户体验问题，并且给出建议，下个小版本之前我们将会把这个问题修复完成。
