### ISSUE TITLE
添加对Geyser的支持

### ISSUE THREAD

**Issue by MyBlueHorizon** [Suwings/MCSManager#301]
如题运行后会出现这个警告并弹出gui，希望可以添加支持方便开设互通服务器
2020-08-07 11:41:12,199 main WARN Advanced terminal features are not available in this environment

**Comment by nkxingxh** [comment]
弹出这个警告是正常的，我的geyser运行没有问题

**Comment by MyBlueHorizon** [comment]
emm 主要是桌面弹出来个gui有点。。。

**Comment by MyBlueHorizon** [comment]
系统是Kubuntu 20.04 不知道是不是linux的过

**Comment by nkxingxh** [comment]
那好吧这就比较.......我的windows系统，并不会弹出GUI

**Comment by adsa562** [comment]
跳出這項是正常的，如果認為跳出GUI很醜的話就試著加入 nogui 看看吧

**Comment by MyBlueHorizon** [comment]
emm 可是命令也无法正常的输入...

**Comment by Rabbit0w0** [comment]
Geyser是服务端插件 跳出GUI一般为Geyser的安装提示, 请把对应版本的Geyser放入服务端plugins目录当中.
