### ISSUE TITLE
Centos7 文件管理系统无法上传文件  500 Internal Server Error

### ISSUE THREAD

**Issue by wangxso** [Suwings/MCSManager#302]
![image](https://user-images.githubusercontent.com/35062162/90093931-42c41600-dd5f-11ea-8e05-f51ce037f2e5.png)
![image](https://user-images.githubusercontent.com/35062162/90093973-58d1d680-dd5f-11ea-9471-1e0b5be30cec.png)
![image](https://user-images.githubusercontent.com/35062162/90093981-5e2f2100-dd5f-11ea-9607-88e74c2f0f5a.png)

**Comment by huangsijun17** [comment]
Centos7的表示经常上传，没有类似问题。

**Comment by Suwings** [comment]
文件上传虽然成功，但是处理文件出错，很明显跟文件上传无关，应该是权限问题导致。

**Comment by huangsijun17** [comment]
目录没有写入权限？root建立的？

**Comment by wky809982944** [comment]
![image](https://user-images.githubusercontent.com/44250397/90361318-7d47ee80-e090-11ea-8ec7-dcee98a74455.png)
不行，改了权限777也还是出现这个问题，应该不是文件权限问题

**Comment by huangsijun17** [comment]
您需要注意的是您运行面板的账户是否在根目录下有完整的权限。建议您使用`chown`命令将该目录的归属者更改为面板的运行用户，或者直接使用Root用户运行面板。另外，MCSManager所在目录的用户归属建议也修改为运行用户。

**Comment by wangxso** [comment]
> 您需要注意的是您运行面板的账户是否在根目录下有完整的权限。建议您使用`chown`命令将该目录的归属者更改为面板的运行用户，或者直接使用Root用户运行面板。另外，MCSManager所在目录的用户归属建议也修改为运行用户。

谢谢 我尝试一下
