### ISSUE TITLE
MCSERVER is not defined

### ISSUE THREAD

**Issue by ColorfulGhost** [Suwings/MCSManager#303]
MCSManager/onlinefs/module/extend_worker.js:49:17

**Comment by ColorfulGhost** [comment]
TypeError: Cannot read property 'toString' of undefined
    at /home/www/MCSManager/onlinefs/controller/function.js:115:35

**Comment by Suwings** [comment]
你是在进行什么操作时触发这个错误？并烦请告知一下操作系统环境，面板使用版本。

**Comment by ColorfulGhost** [comment]
> 你是在进行什么操作时触发这个错误？并烦请告知一下操作系统环境，面板使用版本。

在触发解压文件的时候会有这个报错 

node -v  
v12.18.3

 cat /proc/version 
Linux version 4.18.0-187.el8.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.2.1 20180905 (Red Hat 8.2.1-3) (GCC)) #1 SMP Mon Mar 16 20:11:36 UTC 2020

**Comment by ColorfulGhost** [comment]
发行版本: 8.6.12 发行版本

发行编号: No.20200721-02

**Comment by Suwings** [comment]
已定位问题所在并且修复，最新的代码已经上传到项目，待下次发布版本将一并整合，感谢你！

修复处代码已留下你的名字以表感谢。

https://github.com/Suwings/MCSManager/commit/c8b09e837aa8d0a4fb289c609f5273ea65ab9659
