### ISSUE TITLE
如何通过内网穿透使用面板

### ISSUE THREAD

**Issue by junxiesky** [Suwings/MCSManager#304]
我用的是sakurafrp内网穿透软件
可是通过内网穿透的ip:端口无法进入mcsm面板

**Comment by Zhusiyuan354** [comment]
这就扯到内网穿透实名认证的问题了
如果没有实名认证，使用国内节点是无法通过TCP隧道映射http/https的，那么就建议你使用外国的隧道节点(比如洛杉矶CN2)
如果实名认证了且通过，那就要检查你的隧道配置了

**Comment by junxiesky** [comment]
> 这就扯到内网穿透实名认证的问题了
> 如果没有实名认证，使用国内节点是无法通过TCP隧道映射http/https的，那么就建议你使用外国的隧道节点(比如洛杉矶CN2)
> 如果实名认证了且通过，那就要检查你的隧道配置了

我试试
