### ISSUE TITLE
状态监控协议不能正常工作

### ISSUE THREAD

**Issue by Jiabccc** [Suwings/MCSManager#305]
我的其中一个服务端无法读取在线人数，其他服务端是正常的，如果我打开一个没有实际mc在运行的服务端（仅作为cmd用），监控协议里的信息填的是这个异常的服务器的信息，也是能成功监控人数的。我尝试复制其他服务端的server.properties，但是依旧无法成功监控。我这个服务端的特殊之处，能想到的是开启时间将近十分钟，是否是该问题导致的无法监控？如果需要的话，我可以上传我的服务端到百度云并提供下载链接。
![image](https://user-images.githubusercontent.com/69742658/90326229-7057cc00-dfb8-11ea-84ae-f04459ec003f.png)
如图，左侧为异常服务端，实际已正常启动并已有一名玩家进入，右侧的natapp并不是一个mc服务端，1/20其实监测的是异常服务端的数据。

**Comment by huangsijun17** [comment]
mc版本？1.7.10及以下可能不兼容。现在有重写那块的计划。

**Comment by Jiabccc** [comment]
> mc版本？1.7.10及以下可能不兼容。现在有重写那块的计划。

1.12.2的mod服。Mohist端 https://github.com/Mohist-Community

**Comment by huangsijun17** [comment]
8ad9a5f ，4月22日的版本，Jenkins上都下不到了，要不先更新一下Mohist试试看？

**Comment by Suwings** [comment]
你的意思是，最左侧的Mohist服务端开启之后，未能获取到人数等信息，但是你在 natapp 这个并非mc端的实例填写了你最左侧的 Mohist 服务端的地址与端口，从而成功获取到了人数，这个最右侧的 natapp 人数是最左侧的 Mohist 服务端的人数信息？

如果我理解没有错，那么足以证明面板是可以成功获取到 Mohist 服务端人数，只是因为过长的启动时间导致服务端误判启动失败或者卡顿，从而人数监控协议自动失效。

如果我对你所写的内容理解错误，还望进一步指正。

稍后我将对代码进行相关业务逻辑的检查，如有问题将继续在此反馈。

**Comment by Suwings** [comment]
寻找到一处潜在问题。

当服务器开启后，面板将获取服务端的状态信息，此时会启动一个定时器，但是为了避免定时器遗漏，当经过 20 * 5 秒，即 100 秒之后服务端依然未能启动，人数监控将自动销毁。所以你所描述的现象应该是因为启动时间过长所导致。

此处考虑确实欠佳，接下来我将会大幅度提升此定时器销毁时限，即将此阈值调整到更长时间的等待，也不至于遗漏。

感谢你的反馈。

> 另外，如果你想立刻手动修复，请直接改下列文件的第 113 行，将 20 改为 200 即可，重启面板生效。

https://github.com/Suwings/MCSManager/blob/8d388e87205fed5fa492f8a44f4a74a75186ca02/helper/MCPingProtocol.js#L113
```js

以下是部分代码：

// 当服务器开启时，为其创建一个定时任务
function CreateMCPingTask(id, ip, port) {
    // 若任务存在，禁止重复创建，每个服务器有且只有一个定时查询任务
    if (TASK_DATABASE[id]) {
        return;
    }
    // 任务参数对象，用于记录错误次数和其他数据
    TASK_OBJECT_DATABASE[id] = {
        errorCount: 0
    }
    // 每隔 5 秒，ping 查询一次服务器状态，并且缓存结果
    const taskInterval = setInterval(() => {
        // 进行查询
        PingMCServer(ip, port, (v, e) => {
            if (v != null && e == null) {
                // 查询成功则缓存值
                MCPING_RESULT_DATABASE[id] = v;
            } else {
                // 连续查询错误次数20次以上，主动销毁自身
                TASK_OBJECT_DATABASE[id] && TASK_OBJECT_DATABASE[id].errorCount++;
                if (TASK_OBJECT_DATABASE[id] && TASK_OBJECT_DATABASE[id].errorCount > 20) {
                    DestroyMCPingTask(id);
                }
            }
        });
    }, 1000 * 5);
    // 记录定时任务
    TASK_DATABASE[id] = taskInterval;
}


```

**Comment by Jiabccc** [comment]
修改后问题已经解决。感谢您开发这么好用的web面板(o´ω`o)ノ

**Comment by huangsijun17** [comment]
确认问题了，是Mohist的前戏太多，i18n检测等等各种检测。

**Comment by Jiabccc** [comment]
> 确认问题了，是Mohist的前戏太多，i18n检测等等各种检测。

1.12.2的mod插件服务端，catserver不支持高级火箭，atom没玩明白😂。前戏多就多吧，忍了，客户端也得开七八分钟呢
