### ISSUE TITLE
建议增加关于glowstone服务器的“properties”的支持

### ISSUE THREAD

**Issue by KnightBlood** [Suwings/MCSManager#31]
在glowstone服务器中properties文件并不存在 取而代之的是config文件夹中的glowstone.yml文件

建议增加支持

**Comment by Suwings** [comment]
很抱歉我们目前不打算实现这个功能，因为这需要我们再加入一个 YML 解析。
在最近的一段时间内，因为要更新其他功能或者其他项目，可能不会更新。十分抱歉。
