### ISSUE TITLE
用户管理处的说明可能有错误

### ISSUE THREAD

**Issue by Xuyiyang23333** [Suwings/MCSManager#310]
![图片](https://user-images.githubusercontent.com/44458111/90978952-0628c380-e584-11ea-97d6-852d0fc378dc.png)

```
普通用户无法查看具体内存值与CPU具体信息，保证主机的信息。
```
此处也许是`普通用户无法查看具体内存值与CPU具体信息，保证主机的信息安全。`？

**Comment by Suwings** [comment]
感谢反馈，确实有此问题，下版本修复。
