### ISSUE TITLE
关于终端界面的设计上改进

### ISSUE THREAD

**Issue by TalexDreamSoul** [Suwings/MCSManager#313]
在最主要的终端界面系统信息监控增加图表还有就是权限系统

另外建议可以加入消息系统 管理用户可以给普通用户发消息

另外建议给每个服务器新增人数统计功能 如我的服务器是Bungeecord就无法实时显示人数此时可以通过点击设置输入指定IP来获取正确的人数 并且可以通过一个新的路由查看所有分服务器的人数分布历史统计等

**Comment by TalexDreamSoul** [comment]
其实我自己也在终端界面有过修改 但是不知道如何获取到 内存占用百分比等

**Comment by Suwings** [comment]
感谢反馈。这都是一些很不错的想法，不过目前还是以稳中求胜为好，暂时性还不会进行很大规模的功能性更新。

再次谢谢你的提议。
