### ISSUE TITLE
mcdr能不能用

### ISSUE THREAD

**Issue by stevensane** [Suwings/MCSManager#315]
能不能使用mcdr呢

**Comment by huangsijun17** [comment]
可能存在部分兼容性问题，建议参看：
https://github.com/Suwings/MCSManager/issues/286

**Comment by wangsleepingstar** [comment]
可以使用，而且暂未发现有中文乱码现象。（centos8 UTF-8编码）

**Comment by huangsijun17** [comment]
> 可以使用，而且暂未发现有中文乱码现象。（centos8 UTF-8编码）

window下不是显示乱码，是直接崩溃。加参数可治。

**Comment by stevensane** [comment]
> > 可以使用，而且暫時未發現有中文亂碼現象。（centos8 UTF-8編碼）
> 
> window下不是顯示亂碼，是直接崩潰。加參數可治。

怎麼加參數呢，加那些

**Comment by huangsijun17** [comment]
> > > 可以使用，而且暫時未發現有中文亂碼現象。（centos8 UTF-8編碼）
> > 
> > 
> > window下不是顯示亂碼，是直接崩潰。加參數可治。
> 
> 怎麼加參數呢，加那些

建议查看 #286
