### ISSUE TITLE
mcdr关闭时出现错误

### ISSUE THREAD

**Issue by stevensane** [Suwings/MCSManager#318]
[Server] [16:39:54] [Server thread/INFO]: Done (2.449s)! For help, type "help"
[Server] [16:39:58] [Server thread/INFO]: Stopping the server
[Server] [16:39:58] [Server thread/INFO]: Unknown or incomplete command, see below for error
[Server] [16:39:58] [Server thread/INFO]: end<--[HERE]
[Server] [16:39:58] [Server thread/INFO]: Unknown or incomplete command, see below for error
[Server] [16:39:58] [Server thread/INFO]: exit<--[HERE]
[Server] [16:39:58] [Server thread/INFO]: Stopping server
[Server] [16:39:58] [Server thread/INFO]: Saving players
[Server] [16:39:58] [Server thread/INFO]: Saving worlds
[Server] [16:39:58] [Server thread/INFO]: Saving chunks for level 'ServerLevel[new_world]'/minecraft:overworld
[Server] [16:40:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [16:40:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[new_world]'/minecraft:the_nether
[Server] [16:40:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [16:40:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[new_world]'/minecraft:the_end
[Server] [16:40:03] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [16:40:03] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [16:40:03] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [16:40:03] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[MCDR] [16:40:03] [MainThread/INFO]: 等待服务端进程停止
[MCDR] [16:40:03] [MainThread/INFO]: 服务端进程返回代码: 0
[MCDR] [16:40:03] [MainThread/INFO]: 服务端已关闭
[MCDR] [16:40:03] [MainThread/INFO]: bye
Fatal Python error: could not acquire lock for <_io.BufferedReader name='<stdin>'> at interpreter shutdown, possibly due to daemon threads
>Python runtime state: finalizing (tstate=0000020922839E20)

Thread 0x00003bc4 (most recent call first):
>  File "C:\Program Files\Python38\lib\threading.py", line 306 in wait
>  File "C:\Program Files\Python38\lib\queue.py", line 179 in get
>  File "M:\MCSM8.6.1\server\server_core\test\utils\reactor_manager.py", line 39 in run
>  File "C:\Program Files\Python38\lib\threading.py", line 870 in run
>  File "C:\Program Files\Python38\lib\threading.py", line 932 in _bootstrap_inner
>  File "C:\Program Files\Python38\lib\threading.py", line 890 in _bootstrap

Thread 0x00003cac (most recent call first):
>  File "M:\MCSM8.6.1\server\server_core\test\utils\server.py", line 384 in console_input
>  File "C:\Program Files\Python38\lib\threading.py", line 870 in run
>  File "C:\Program Files\Python38\lib\threading.py", line 932 in _bootstrap_inner
>  File "C:\Program Files\Python38\lib\threading.py", line 890 in _bootstrap

Thread 0x00003164 (most recent call first):
>  File "M:\MCSM8.6.1\server\server_core\test\utils\update_helper.py", line 23 in check_update_loop
>  File "C:\Program Files\Python38\lib\threading.py", line 870 in run
>  File "C:\Program Files\Python38\lib\threading.py", line 932 in _bootstrap_inner
>  File "C:\Program Files\Python38\lib\threading.py", line 890 in _bootstrap

Thread 0x00003d84 (most recent call first):
>  File "C:\Program Files\Python38\lib\threading.py", line 306 in wait
>  File "C:\Program Files\Python38\lib\queue.py", line 179 in get
>  File "M:\MCSM8.6.1\server\server_core\test\utils\plugin_thread.py", line 33 in run
>  File "C:\Program Files\Python38\lib\threading.py", line 932 in _bootstrap_inner
>  File "C:\Program Files\Python38\lib\threading.py", line 890 in _bootstrap

Thread 0x00002f0c (most recent call first):
>  File "C:\Program Files\Python38\lib\threading.py", line 306 in wait
>  File "C:\Program Files\Python38\lib\queue.py", line 179 in get
>  File "M:\MCSM8.6.1\server\server_core\test\utils\plugin_thread.py", line 33 in run
>  File "C:\Program Files\Python38\lib\threading.py", line 932 in _bootstrap_inner
>  File "C:\Program Files\Python38\lib\threading.py", line 890 in _bootstrap

Thread 0x0000040c (most recent call first):
>  File "C:\Program Files\Python38\lib\threading.py", line 306 in wait
>  File "C:\Program Files\Python38\lib\queue.py", line 179 in get
>  File "M:\MCSM8.6.1\server\server_core\test\utils\plugin_thread.py", line 33 in run
>  File "C:\Program Files\Python38\lib\threading.py", line 932 in _bootstrap_inner
>  File "C:\Program Files\Python38\lib\threading.py", line 890 in _bootstrap

Thread 0x0000371c (most recent call first):
>  File "C:\Program Files\Python38\lib\threading.py", line 306 in wait
>  File "C:\Program Files\Python38\lib\queue.py", line 179 in get
>  File "M:\MCSM8.6.1\server\server_core\test\utils\plugin_thread.py", line 33 in run
>  File "C:\Program Files\Python38\lib\threading.py", line 932 in _bootstrap_inner
>  File "C:\Program Files\Python38\lib\threading.py", line 890 in _bootstrap

Current thread 0x00003e18 (most recent call first):
<no Python frame>

**Comment by Suwings** [comment]
控制面板关闭服务器时是以 stop，end，exit 三条命令依次执行，至于 MCDR 我并没有使用过，此 MCDR 错误我也不清楚是何原因所产生。

你可以再尝试几次，如果只是偶尔出现，可能只是几次意外，但若是经常出现，则有可能跟面板的关闭方式有所联系。你可以试试只用 MCDR 启动与关闭服务器，再用面板+MCDR 启动与关闭服务器，形成一个对照测试。如果面板+MCDR反复出现错误，则可以认定是面板关闭方式所致。

但是现在，我暂时无法给出此错误的原因。还请理解。
