### ISSUE TITLE
Wiki API 文档中一处 current 拼写错误

### ISSUE THREAD

**Issue by Mythologyli** [Suwings/MCSManager#319]
[链接](https://github.com/Suwings/MCSManager/wiki/API-Documentation#查看所有服务器信息)

"currnetPlayers": "--"
这里的 current 被写成 currnet。在 #311 前 API 确实存在此错误，不过在 #311 中被修复。因此 API 文档有待修改。

**Comment by Suwings** [comment]
已更改，感谢你的反馈，谢谢！
