### ISSUE TITLE
群組問題

### ISSUE THREAD

**Issue by jing-shiun** [Suwings/MCSManager#320]
請問怎用群組福功能呢

**Comment by LazyCreeper** [comment]
例如這樣![TIM截图20201001084937.jpg](https://i.loli.net/2020/10/01/V8s2NLQv5acegjr.jpg)

**Comment by jing-shiun** [comment]
我的意似是 跨主機連接

**Comment by huangsijun17** [comment]
> 我的意似是 跨主機連接

暂不支持。预计下一大版本（重构）可能会支持。

**Comment by jing-shiun** [comment]
好 感謝
