### ISSUE TITLE
能不能在启动 MCSManager 时自动启动游戏

### ISSUE THREAD

**Issue by yanxiangrong** [Suwings/MCSManager#321]
能不能设置在启动 MCSManager 时自动启动游戏，或者在计划任务设置MCSManager启动时执行的类型，类似于Linux 的@reboot

**Comment by Suwings** [comment]
你是指启动游戏服务端吧？应该不是说启动 Minecraft 游戏客户端吧。

目前还不支持启动时的触发式条件任务，还请谅解。不过你可以设置一个每隔一分钟或一小时就启动一次服务器计划任务，面板启动后此计划任务便会执行，一小时后服务器便会开启，下次执行时由于服务器已经开启，所以不会重复开启服务器，也就自动忽略了多次启动。

**Comment by Jiabccc** [comment]
这个我熟，你可以在启动MCSM的同时启动一个脚本，延时30秒通过api的方式启动服务器即可。
