### ISSUE TITLE
Waterfall服务端无法检测在线人数

### ISSUE THREAD

**Issue by MAX-XiaoKui** [Suwings/MCSManager#322]
如题
![Screenshot_2020-10-02-15-26-20-25_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/53287753/94898657-7f410200-04c4-11eb-94d0-0c39428631de.jpg)
用API也是没有
（Waterfall是BungeeCord的一个分支）

**Comment by Suwings** [comment]
目前人数检测是使用的 mcping 的方式，如果此服务端不支持，那就没有办法获取到人数，更多的人数检测方案暂时还没加入，还请谅解。

**Comment by huangsijun17** [comment]
我这的Waterfall正常啊，可能需要修改一下监控协议的端口号设置。

**Comment by MAX-XiaoKui** [comment]
> 我这的Waterfall正常啊，可能需要修改一下监控协议的端口号设置。

在哪修改呢

**Comment by Suwings** [comment]
> > 我这的Waterfall正常啊，可能需要修改一下监控协议的端口号设置。
> 
> 在哪修改呢

在控制面板，服务器控制台右上角显示人数的地方，点击那个大框框就行。

**Comment by MAX-XiaoKui** [comment]
> > > 我这的Waterfall正常啊，可能需要修改一下监控协议的端口号设置。
> > 
> > 
> > 在哪修改呢
> 
> 在控制面板，服务器控制台右上角显示人数的地方，点击那个大框框就行。

我把waterfall的query设置开启并且和加入服务器的端口一样
但是还是不行
是要把query关掉吗

**Comment by Suwings** [comment]
应该与 Query 协议无关，点击你第一张图片那个贴块，然后会弹出一个对话框，设置对话框里面的端口号为你服务器的端口号。

**Comment by MAX-XiaoKui** [comment]
> 应该与 Query 协议无关，点击你第一张图片那个贴块，然后会弹出一个对话框，设置对话框里面的端口号为你服务器的端口号。

行了我把Query关掉了就好了
