### ISSUE TITLE
内置一个显示服务器当前人数及占用率的页面

### ISSUE THREAD

**Issue by ZhuZhujun0718** [Suwings/MCSManager#327]
内置一个显示服务器当前人数及占用率的页面，让玩家看，如果可以（不想搞API了

**Comment by Kiritow** [comment]
这个目前版本有的吧？
![image](https://user-images.githubusercontent.com/13619158/107117050-6f8e5b80-68b2-11eb-90c9-5ec3b7bab898.png)
