### ISSUE TITLE
windows10如何在有node环境的状态下安裝

### ISSUE THREAD

**Issue by stevensane** [Suwings/MCSManager#328]

**Comment by stevensane** [comment]
尝试无数办法一直报错
C:\Users\wangl\OneDrive\桌面\MCSManager-8.6.14>1.bat
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'fs-extra'
Require stack:
- C:\Users\wangl\OneDrive\桌面\MCSManager-8.6.14\app.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:903:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (C:\Users\wangl\OneDrive\桌面\MCSManager-8.6.14\app.js:34:14)
[90m    at Module._compile (internal/modules/cjs/loader.js:1015:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:879:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:724:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'C:\\Users\\wangl\\OneDrive\\桌面\\MCSManager-8.6.14\\app.js'[39m ]
}

**Comment by huangsijun17** [comment]
1.bat是什么鬼？

**Comment by stevensane** [comment]
> 1.bat是什麼鬼？

自定义的启动文件内容是
@echo off  
node app.js
pause

**Comment by huangsijun17** [comment]
> > 1.bat是什麼鬼？
> 
> 自定义的启动文件
> 内容是
> @echo off
> node app.js
> pause

npm install成功了吗？

**Comment by stevensane** [comment]
> > > 1.bat是什麼鬼？
> > 
> > 
> > 自定義的啟動文件
> > 內容是
> > @echo off 
> > node app.js
> > 暫停
> 
> npm install成功了嗎？

mcsm目錄下執行的？

**Comment by huangsijun17** [comment]
> > > > 1.bat是什麼鬼？
> > > 
> > > 
> > > 自定義的啟動文件
> > > 內容是
> > > @echo off
> > > node app.js
> > > 暫停
> > 
> > 
> > npm install成功了嗎？
> 
> mcsm目錄下執行的？

如果是你自己git chlone的，建议参看Linux安装方法

**Comment by stevensane** [comment]
> > > > > 1.bat是什麼鬼？
> > > > 
> > > > 
> > > > 自定義的啟動文件
> > > > 內容是
> > > > @echo off 
> > > > node app.js
> > > > 暫停
> > > 
> > > 
> > > npm install成功了嗎？
> > 
> > 
> > mcsm目錄下執行的？
> 
> 如果是你自己git chlone的，建議參見Linux安裝方法

我是直接下载最新版的然后解压缩到桌面用的，git chlone我不会用要研究看看

**Comment by stevensane** [comment]
> > > > > 1.bat是什麼鬼？
> > > > 
> > > > 
> > > > 自定義的啟動文件
> > > > 內容是
> > > > @echo off
> > > > node app.js
> > > > 暫停
> > > 
> > > 
> > > npm install成功了嗎？
> > 
> > 
> > mcsm目錄下執行的？
> 
> 如果是你自己git chlone的，建议参看Linux安装方法

我在桌面新建文件夹使用git chlone安装了一个新的
但是在npm start的时候报错如下
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\wangl\OneDrive\桌面\mcsm\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\wangl\OneDrive\桌面\mcsm\package.json'
npm ERR! enoent This is related to npm not being able to find a file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wangl\AppData\Roaming\npm-cache\_logs\2020-10-14T01_53_00_918Z-debug.log

**Comment by huangsijun17** [comment]
> npm install成功了嗎？

所以说，npm install成功了嗎？

**Comment by stevensane** [comment]
> > npm install成功了嗎？
> 
> 所以說，npm install成功了嗎？

不知道就報了一堆警告
C:\Users\wangl\OneDrive\桌面\mcsm>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\wangl\OneDrive\桌面\mcsm\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\wangl\OneDrive\桌面\mcsm\package.json'
npm WARN mcsm No description
npm WARN mcsm No repository field.
npm WARN mcsm No README data
npm WARN mcsm No license field.

up to date in 0.732s
found 0 vulnerabilities

**Comment by stevensane** [comment]
> > npm install成功了嗎？
> 
> 所以说，npm install成功了嗎？

搞好久总算成功了，现在唯一知道的就是，windows不用整合包也可以用
我自己也不知道咋成功的
但是为什么git下来的是13版本？
疑惑不解

**Comment by Suwings** [comment]
Windows 有 Node 环境的话，按照以下步骤即可：
1. 从 Github 下载最新代码，ZIP 格式就行。
2. 解压，进入目录，执行 npm install 安装依赖库
3. npm start 启动，完成。
