### ISSUE TITLE
MCSManager 可以运行Steam游戏吗？

### ISSUE THREAD

**Issue by axuanfeng** [Suwings/MCSManager#329]

**Comment by Suwings** [comment]
十分抱歉。关于 Steam 游戏服务端不完全支持，少部分可以开启与管理，大部分应该都不行，尤其是那些用 RCON 通信的。

**Comment by axuanfeng** [comment]
我把它改成 Steam Squad 服务器 的面板管理了2333~

**Comment by Suwings** [comment]
> 我把它改成 Steam Squad 服务器 的面板管理了2333~

可以的，开源吗？如果开源可以发下链接，有空我看看，也为以后可能兼容Steam游戏做点提前工作，不开源的话也没关系，无妨。

**Comment by axuanfeng** [comment]
我可以私发给你，但我不想它被公布。。。
你可以联系我的QQ510600087

**Comment by Suwings** [comment]
> 我可以私发给你，但我不想它被公布。。。
> 你可以联系我的QQ510600087

这样的话，到也不强求，我只是有点感兴趣而已。没事~
