### ISSUE TITLE
关于物理内存使用率的问题

### ISSUE THREAD

**Issue by CG-man** [Suwings/MCSManager#33]
关于我后台的java进程开了Xmx4G的内存，ssh连接看到java只用了1.6G，服务器的总的内存占用也就60%左右，可是后台的页面上的物理内存使用率却给我显示内存占用80%。这个80%确实我不太明白。

**Comment by Suwings** [comment]
是这样的，我们取的剩余内存是系统的（free）未使用的空闲内存，代指还未被任何程序使用的内存区域。
但是实际上，有一部分内存是用做程序 （buff/cache）缓冲/临时储存，用于加快程序运行。
这也就导致了，面板上显示的剩余内存比实际可用内存要少一部分的原因。

虽然看起来显示很大，实际上系统已充分利用。
不过这个问题我们以后会尽可能修复。
