### ISSUE TITLE
能否改进文件管理系统

### ISSUE THREAD

**Issue by Rabbit0w0** [Suwings/MCSManager#330]
如题，现在的文件管理系统只支持单连接，能否改进这一系统，或是将其解除归档状态以便贡献

**Comment by Suwings** [comment]
那个已经归档的项目代码进度已经跟不上mcsm代码进度，所以文件管理系统独立项目便直接归档了。

目前最新的文件管理系统的源代码在 public/online_fs/src中。需要使用Vue编译之后才能正常使用。

只支持单链接是必然的，因为如果一个浏览器登录了两个账号，又为了预防可能的越权，干脆直接就限制严格较好。

以后有这方面的改进计划，即将文件管理系统那方面的代码直接写进面板的原有框架之下，采用单页形式加载出来，这样就更方便使用。
