### ISSUE TITLE
BDS无法使用Docker

### ISSUE THREAD

**Issue by Tonycola** [Suwings/MCSManager#331]
BDS无法使用Docker

**Comment by huangsijun17** [comment]
BDS？BSD？

**Comment by Tonycola** [comment]
> BDS？BSD？

Hi! BDS= BedRock Server! 在Bedrock Edition下的服务端原生

**Comment by Suwings** [comment]
Docker 默认环境是 Java 环境的虚拟化镜像，至于你需要开 BDS的话，可能需要在创建Docker镜像的时候，修改那个 DockerFile 代码。
