### ISSUE TITLE
请问如何向控制终端发送日志，web的控制台

### ISSUE THREAD

**Issue by axuanfeng** [Suwings/MCSManager#332]
请问如何向控制终端发送日志，web的控制台
![image](https://user-images.githubusercontent.com/49741457/97801519-4f7a4b00-1c78-11eb-94d1-647515c749e0.png)

**Comment by Suwings** [comment]
十分抱歉这么晚回复你，但是我没有完全理解你这是想做什么？也许现在你已经解决了这个问题，如果有其他疑问，可以再次回复。
