### ISSUE TITLE
centos7无法上传文件

### ISSUE THREAD

**Issue by tyy77** [Suwings/MCSManager#333]
显示上传失败undefined

**Comment by 1523789353** [comment]
同，而且我确信端口都是开的

**Comment by Suwings** [comment]
用root账号运行试试，并且确保目录权限设置正确。

**Comment by tyy77** [comment]
> 用root帐户运行试试，并确保目录权限设置正确。

确定为root账户，并且权限为777，仍然上传失败，只能通过finalshell进行上传

**Comment by Shuazijun** [comment]
是否经过反代？请提供后台日志
Linux 一键安装版日志所在位置：/opt/MCSManager/logs/

**Comment by 1523789353** [comment]
没使用反代，root权限，文件夹为0777，每次穿完跟我说失败

XD

**Comment by Suwings** [comment]
刚刚经过 Centos 7 实际测试，上传文件无误，可能需要更多的信息来分析你的这个问题。

建议你上传前，使用Chrome 浏览器，按下F12，点击`Network`选项卡，勾选左上角的 `Preserve log`。

接下来进行上传文件，失败之后下面会有Ajax请求列表，选中一个叫`/fs/upload`的请求，点开它的 `Response` 子选项卡，里面应该就有错误的具体原因，你可以将它发送到这里，以便我们分析。

另外在 /opt/MCSManager/logs/ 下也有日志，上传文件之后也可以贴上报错那部分的日志，以便分析。

**Comment by tyy77** [comment]
错误500

**Comment by tyy77** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by tyy77** [comment]
TypeError: Cannot read property '0' of undefined

**Comment by tyy77** [comment]
function.js文件里第110行 oReq.send(oMyForm); 报错Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by 123485k** [comment]
你的node.js版本是多少

**Comment by tyy77** [comment]
v14.15.1

**Comment by 123485k** [comment]
换成12的试试，我一台服务器是12，一台服务器是14，14的那个不行

**Comment by tyy77** [comment]
麻烦给个详细版本号

**Comment by tyy77** [comment]
试过了 换成12依然报错

**Comment by 123485k** [comment]
换了12之后重新npm install一下在mscm的目录里

**Comment by Suwings** [comment]
也就是说 v14.15.1 版本上传文件会出错，需要换回 v12 版本才能正常运行吗？

**Comment by 123485k** [comment]
> 也就是说 v14.15.1 版本上传文件会出错，需要换回 v12 版本才能正常运行吗？
是的，面板似乎和node14不兼容

**Comment by Suwings** [comment]
问题已经修复，在最新的Master分支中。

明日再发行新版本。Windows 整合版暂时应该不会有这个问题，只有 Linux 用户受影响，重新使用 git pull 命令更新代码，然后再使用 npm install 更新依赖库即可。

https://github.com/Suwings/MCSManager
