### ISSUE TITLE
建议/不足：状态监控导致的 Bungee 服务端报错

### ISSUE THREAD

**Issue by BingYanchi** [Suwings/MCSManager#334]
先说下情况，帮助你复现。
我使用的是 Waterfall 的最新构建，在 config.yml 里设定了 proxy_protocol: true
![image](https://user-images.githubusercontent.com/36477925/98379766-9f934c00-2082-11eb-91ae-74bbac88ea2e.png)

我简要介绍下这是干啥的吧，可以使内网映射的服务器，获取到玩家真实ip，但也会导致一个问题
就是本地地址，无法访问服务器，通常都会被拒绝连接。
我也不知道 MCSM 是因为什么原理，导致每隔几秒就会出现 WARN，蛮影响查阅 log 的。
而且在这种情况下，本地无法访问，也获取不到人数信息，这时候状态监控就很鸡肋了。

没有关闭的选项，只要在 MCSM 运行，就会每隔 6 秒 WARN 一次。（我已经测试过，在 MCSM 外运行，不会出现这种情况）
![image](https://user-images.githubusercontent.com/36477925/98380011-f9941180-2082-11eb-8f1d-3ec185f27536.png)

我推测是状态监控导致的问题。（而且此时也获取不到状态信息）
![image](https://user-images.githubusercontent.com/36477925/98380135-221c0b80-2083-11eb-98e5-e6f7dfebe0b7.png)

建议加个针对某个服务器关闭状态监控的选项，这是我想到的最简单的解决方法了。

附：使用 MCSM 8.6.15，Windows Server 2019，Waterfall #381 2020-11-02

**Comment by Suwings** [comment]
感谢反馈，可能的确有这种不兼容的情况，临时解决方案：

点击你最后一张截图右上角的 `状态监控协议`，会弹出一个监听设置窗口，将里面的端口和地址填写成其他服务器或者直接写一个错误的地址与端口，则可以间接性的关闭这个功能，不再会出现控制台定时刷警告的情况。

若如此设置之后，控制台依然刷新了警告信息，请再继续反馈。谢谢~

**Comment by BingYanchi** [comment]
> 感谢反馈，可能的确有这种不兼容的情况，临时解决方案：
> 
> 点击你最后一张截图右上角的 `状态监控协议`，会弹出一个监听设置窗口，将里面的端口和地址填写成其他服务器或者直接写一个错误的地址与端口，则可以间接性的关闭这个功能，不再会出现控制台定时刷警告的情况。
> 
> 若如此设置之后，控制台依然刷新了警告信息，请再继续反馈。谢谢~

我刚刚尝试了这么做，但是情况再次出现，或许不是这个原因。

**Comment by Suwings** [comment]
重启服务器了吗？这个设置需要重启才能生效。

**Comment by BingYanchi** [comment]
> 重启服务器了吗？这个设置需要重启才能生效。
> 面板似乎没有其他跟socket通讯有关的代码了。

我也觉得很不可思议，但是我确实重启了

**Comment by Suwings** [comment]
> 我尝试重启了面板，这确实有效，我以为重启服务器能解决。
> 那么问题应该就出在监控上了。


你的问题解决了吗？你的这段文字我没有理解，控制台是否已经停止输出多余的警告信息？

另外我想到了一个方案，因为你好像只是不准许内网或本地进行访问，MCSM 面板的状态查询是否支持 `Bungee` 我不清楚，因为这个依赖库并不是我所写，没有经过这个服务端的测试。但是我觉得你可以尝试把状态监控的地址填写成你的外网ip（最好是IP而不是域名），端口也写玩家正常进入服务器的端口。

这样做也许可以查询到人数，如果上述方案无法查询到玩家数量，那么就说明 MCSM 的状态查询暂时还不能支持 `Bungee ` 服务端程序，这个也只能等以后再做兼容性处理，还请理解。

**Comment by BingYanchi** [comment]
> > 我尝试重启了面板，这确实有效，我以为重启服务器能解决。
> > 那么问题应该就出在监控上了。
> 
> 你的问题解决了吗？你的这段文字我没有理解，控制台是否已经停止输出多余的警告信息？
> 
> 另外我想到了一个方案，因为你好像只是不准许内网或本地进行访问，MCSM 面板的状态查询是否支持 `Bungee` 我不清楚，因为这个依赖库并不是我所写，没有经过这个服务端的测试。但是我觉得你可以尝试把状态监控的地址填写成你的外网ip（最好是IP而不是域名），端口也写玩家正常进入服务器的端口。
> 
> 这样做也许可以查询到人数，如果上述方案无法查询到玩家数量，那么就说明 MCSM 的状态查询暂时还不能支持 `Bungee ` 服务端程序，这个也只能等以后再做兼容性处理，还请理解。

问题解决了，没有再出现这种情况。
你的说法确实是对的，确实可以用这种方法查询。但我使用 `srv` 记录，没办法获取到监控信息。

**Comment by huangsijun17** [comment]
[http://mc.mengmeet.com:23333/api/status/BC](http://mc.mengmeet.com:23333/api/status/BC)
???
我这的BC默认设置正常啊。
PS，Unicode乱码不要去管。

**Comment by huangsijun17** [comment]
MC监控是使用了Minecraft的Server List Ping来实现的，详见wiki：

[https://wiki.vg/Server_List_Ping#1.6](https://wiki.vg/Server_List_Ping#1.6)

**Comment by BingYanchi** [comment]
> http://mc.mengmeet.com:23333/api/status/BC
> ???
> 我这的BC默认设置正常啊。
> PS，Unicode乱码不要去管。
> 不过，我没设置“proxy_protocol”

我说的情况是启用了 `proxy_protocol`
