### ISSUE TITLE
建议在一键安装脚本中添加用于专门启动面板的用户

### ISSUE THREAD

**Issue by 123485k** [Suwings/MCSManager#336]
面板默认脚本安装的时候是以root账户来启动服务的，也就是说，只要取得管理员账号，就可以轻松的取得服务器端管理员权限，这无疑是非常危险的。

**Comment by Suwings** [comment]
感谢提供建议，目前正在开发其他项目，待有时间之时，再重新优化安装脚本。谢谢~
