### ISSUE TITLE
内存使用率会把缓存内存计算在内

### ISSUE THREAD

**Issue by yanxiangrong** [Suwings/MCSManager#338]
![Screenshot_2020-11-23-08-38-19](https://user-images.githubusercontent.com/39958055/99922014-085c1300-2d69-11eb-913f-ff0a18c670f6.png)
![Screenshot_2020-11-23-08-41-18](https://user-images.githubusercontent.com/39958055/99922022-1316a800-2d69-11eb-9504-5257ce6ef9c6.png)
如图，内存实际使用3.08G，剩下部分是作为缓存。实际内存使用不到一半。但是MCSManager会将缓存部分计算在内，然后显示内存使用97%。

**Comment by Suwings** [comment]
谢谢你的反馈。面板确实存在这个问题。

**Comment by huangsijun17** [comment]
老问题了，我看过代码，是node的锅。

**Comment by yanxiangrong** [comment]
> 谢谢你的反馈。面板确实存在这个问题。

我也看了一下代码，os.freemem() 获得的内存的是 free 内存，而不是 available 内存。所以我将 os.freemem() 换成了 1024 * Number(/MemAvailable:[ ]+(\d+)/.exec(fs.readFileSync('/proc/meminfo', 'utf8'))[1]) 问题解决。

**Comment by huangsijun17** [comment]
> > 谢谢你的反馈。面板确实存在这个问题。
> 
> 我也看了一下代码，os.freemem() 获得的内存的是 free 内存，而不是 available 内存。所以我将 os.freemem() 换成了 1024 * Number(/MemAvailable:[ ]+(\d+)/.exec(fs.readFileSync('/proc/meminfo', 'utf8'))[1]) 问题解决。

1. node在windows下获取的是 available 内存。
2. 跨系统兼容性问题。

个人建议还是要nodejs去改源码。

**Comment by RedCarl** [comment]
这个咋修复呀，有没有修复过程，比如文件在哪里，改成什么

**Comment by huangsijun17** [comment]
> 这个咋修复呀，有没有修复过程，比如文件在哪里，改成什么

上游的nodejs的bug，我报过，作者不肯修。目测要改nodejs的源码。
