### ISSUE TITLE
FTP默认访问密码

### ISSUE THREAD

**Issue by Yang161941** [Suwings/MCSManager#339]
## 发行版本: 8.6.11 发行版本
---
在我开启ftp服务后，尝试访问发现需要账号密码，我试过输入默认的账号密码以及我自己建立的账号密码，都不行，想问问默认的账号密码是什么，如果能修改在哪里修改？

**Comment by Suwings** [comment]
开启 FTP 功能之后，在控制面板的服务器控制台页面（就是有CPU图表的那个页面），左下边有账号和密码。
