### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by xmgcstudio** [Suwings/MCSManager#343]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境:**
Ubuntu Server 20.10 for arm
**面板版本:**
默认
**Node版本:**
12.16.1
**出现概率:**
每次
**出现的问题 (BUG):**
● mcsm.service - MCSManager
     Loaded: loaded (/lib/systemd/system/mcsm.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2020-12-13 04:21:07 UTC; 13s ago
    Process: 752697 ExecStart=/usr/bin/node /opt/MCSManager/app.js (code=exited, status=203/EXEC)
   Main PID: 752697 (code=exited, status=203/EXEC)

Dec 13 04:21:07 ubuntu systemd[1]: mcsm.service: Scheduled restart job, restart counter is at 5.
Dec 13 04:21:07 ubuntu systemd[1]: Stopped MCSManager.
Dec 13 04:21:07 ubuntu systemd[1]: mcsm.service: Start request repeated too quickly.
Dec 13 04:21:07 ubuntu systemd[1]: mcsm.service: Failed with result 'exit-code'.
Dec 13 04:21:07 ubuntu systemd[1]: Failed to start MCSManager.
**复现操作步骤:**
root@ubuntu:/home/ubuntu# systemctl start mcsm
root@ubuntu:/home/ubuntu# systemctl status mcsm

**Comment by Suwings** [comment]
在 Logs 目录下应该有日志文件（txt），如果可以的话希望能够提供一下txt部分内容。

你目前提供的信息无法识别出具体的错误原因。
