### ISSUE TITLE
自动启动MC服务器

### ISSUE THREAD

**Issue by moyilong** [Suwings/MCSManager#346]
**你对哪些功能有建议或想法？**
希望能在MCS启动的时候设置同步启动MC服务器

**这些功能有哪些代替方案？**

**对应你提出的内容，你觉得有什么价值？**
Windows Server用户打补丁每次都要手动启动

**其他内容:**

（功能请求或者功能建议均准许自由发挥，无特定限制模板，你可以在这里写下任何你想说的文字。）

**Comment by Yang161941** [comment]
### 作者之前说过：
可以在**服务端管理>计划任务项目>新建计划任务**中添加计划任务来达到开启面板就可以自动开启服务器的功能
## 例如：
|间隔表达式|次数|任务指令|
|---|---|---|
|* 1 * * * *|0|\_\_start\_\_ #每一分钟尝试开启一次|

**Comment by Yang161941** [comment]
如果服务器已经开启，则任务就不会尝试再次开启服务器（好像吧）

**Comment by Suwings** [comment]
可以试试，目前面板还没有自带这种开启面板就启动服务器的功能，只能通过一些其他功能的组合来实现一些高级功能。
