### ISSUE TITLE
如何設定JAVA路徑

### ISSUE THREAD

**Issue by BearLeonLight** [Suwings/MCSManager#347]
**内容:**
我不知道如何設定自己下載的JAVA路徑，嘗試過很多方法都沒有作用

**Comment by Suwings** [comment]
在服务器管理 ，一个服务器右边按钮组，参数按钮，进入界面，左侧有一个Java变量设置，写入绝对路径即可生效。

**Comment by BearLeonLight** [comment]
絕對路徑 是指 E:\Minecraft\jdk-11.0.9\bin 這樣嗎?
能給個範例嗎?
因為我測試很多方法都出不來
E:\Minecraft\jdk-11.0.9\bin
E:\Minecraft\jdk-11.0.9\bin\
E:\Minecraft\jdk-11.0.9\bin\java
E:\Minecraft\jdk-11.0.9\bin\java\
E:\Minecraft\jdk-11.0.9\bin\java.exe
E:\Minecraft\jdk-11.0.9
E:\Minecraft\jdk-11.0.9\
把\改成 /樣也不行，再改成./XXX.jdk-11.0.9 等都用不出來，作業系統WIN10

**Comment by Suwings** [comment]
使用 E:\Minecraft\jdk-11.0.9\bin\java.exe 這個。

使用之後依然無法啟動？有無其他錯誤信息？

**Comment by BearLeonLight** [comment]
抱歉後來發現是我個人問題，我在重新用同樣方法後可以正常運作@@

**Comment by BearLeonLight** [comment]
我能問問之後 使用者帳號權限部分的功能會增加嗎?
例如限制玩家只能用什麼指令，或是只能看但不能輸入。
或是編輯特地的資料夾

**Comment by Suwings** [comment]
我無法給出準確的時間，也不一定會新增這個功能，目前面板項目的新功能計劃被推遲了一些。

**Comment by BearLeonLight** [comment]
> 目前面板項目的新功能計劃被推遲了一些。

好的
