### ISSUE TITLE
修改服务实例标识名导致服务端目录被删除

### ISSUE THREAD

**Issue by yzy613** [Suwings/MCSManager#348]
**系统环境:**
Ubuntu Server 20.04 LTS x86_64
**面板版本:**
v8.6.15
**Node版本:**
v12.16.1
**出现概率:**
100%
**出现的问题 (BUG):**
修改服务端标识名导致服务端目录被删除
**复现操作步骤:**
修改服务端标识名

> 已修改描述

**Comment by Suwings** [comment]
面板控制台（终端）界面有无更多错误？会不会是其他因素导致的结果？

关于复现操作，面板已经经过了无数次的启动与停止服务器操作，从未出现过你所说的这种情况，为了寻找根本的问题，可能需要更多的信息。

**Comment by yzy613** [comment]
对了，我期间改了一次服务器的名字。我看了日志，没有记录报错

**Comment by yzy613** [comment]
还有就是我第一次用这个面板的时候，我的核心基岩服务器也被莫名其妙地删了，还好备份了地图，不然一切付之东流。和这次情况一样，被删掉了。第一次我还以为是我手残，这次是真的只操作了面板，然后很快啊，不能启动了，文件找不到了

**Comment by Suwings** [comment]
可能修改服务器名字导致发问题，具体原因咱不明确，我这里没有出现这种情况。

过段时间我会检查一下服务器名字修改这部分的代码，但愿能够找到点线索。

**Comment by yzy613** [comment]
好的！☆ﾐ(o*･ω･)ﾉ

**Comment by chengziorange** [comment]
@Suwings 确认是修改服务器标识名导致的服务端目录整个被删除。我这边稳定复现。同时log中无日志。

**Comment by yzy613** [comment]
> @Suwings 确认是修改服务器标识名导致的服务端目录整个被删除。我这边稳定复现。同时log中无日志。
> 非常严重的问题，已经导致我的mc服务器丢档，希望能尽快解决。

终于找到复现了🤣
我现在把存档 ln 出去了，删也是只删符号链接，保留了存档。那也可以试试用 ln 命令

**Comment by chengziorange** [comment]
> > @Suwings 确认是修改服务器标识名导致的服务端目录整个被删除。我这边稳定复现。同时log中无日志。
> > 非常严重的问题，已经导致我的mc服务器丢档，希望能尽快解决。
> 
> 终于找到复现了🤣
> 我现在把存档 ln 出去了，删也是只删符号链接，保留了存档。你也可以试试用 ln 命令

可惜丢了的档找不回来了

**Comment by yzy613** [comment]
> > > @Suwings 确认是修改服务器标识名导致的服务端目录整个被删除。我这边稳定复现。同时log中无日志。
> > > 非常严重的问题，已经导致我的mc服务器丢档，希望能尽快解决。
> > 
> > 终于找到复现了🤣
> > 我现在把存档 ln 出去了，删也是只删符号链接，保留了存档。你也可以试试用 ln 命令
> 
> 可惜丢了的档找不回来了

我就是被坑过一次之后才弄的 ln 😭

**Comment by Suwings** [comment]
好的，已知晓此问题，谢谢你们的尝试！感谢你们。

**Comment by huangsijun17** [comment]
所以，我们的服务端都是放在MCSM目录外面的。

**Comment by yzy613** [comment]
> 所以，我们的服务端都是放在MCSM目录外面的。

放在目录外一样的，我的照样被删........
mcsm在 `/opt/mcsm/`，服务端在 `/opt/mc-bedrock/` 还是被删了

**Comment by yzy613** [comment]
emm......弱弱的问一下，新版本只是禁用修改服务器名字功能吗？

**Comment by Suwings** [comment]
> emm......弱弱的问一下，新版本只是禁用修改服务器名字功能吗？

是的，最近比较忙，没时间更新mcsm，暂时禁用更改名字，已实现这个BUG暂时不会被触发。待有时间后再进行修复。

**Comment by ColorfulGhost** [comment]
> > emm......弱弱的问一下，新版本只是禁用修改服务器名字功能吗？
> 
> 是的，最近比较忙，没时间更新mcsm，暂时禁用更改名字，已实现这个BUG暂时不会被触发。待有时间后再进行修复。

太惨了 ....我改名字删了2次存档，希望玩家们不会打死我Q_Q.........还有不止改名字 ，已存在的服务端目录，新建示例的话也会清空服务端目录

**Comment by ilwork** [comment]
MCSM发行编号: No.20210212-01  运行在Ubuntu 20.04.1 LTS 服务端放在/home/用户名内 也是在这种情况被删除了，希望您修复有所帮助
