### ISSUE TITLE
开启崩服重启后，通过Api或者定时命令执行关闭服务器后又自动开回来

### ISSUE THREAD

**Issue by ddos-ling** [Suwings/MCSManager#350]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境:** Linux x64 4.18.0-240.1.1.el8_3.x86_64

**面板版本:** 8.6.16 发行版本

**Node版本:** 未知

**出现概率:** 每次都是

**出现的问题 (BUG):** 开启崩服重启功能后，无法通过api和定时任务完全关闭服务器

**复现操作步骤:** 
1.打开服务器的崩服重启功能，调用关服api，服务器关闭后又启动
2.打开服务器的崩服重启功能，设置计划任务执行__stop__，服务器关闭后又启动

**Comment by Suwings** [comment]
感谢提供BUG，这个问题确实存在，过段时间再修复这个小问题。

谢谢你~

**Comment by ddos-ling** [comment]
这个问题一直存在，希望尽早修复
