### ISSUE TITLE
[新功能建议]支持控制台自动补全

### ISSUE THREAD

**Issue by Yang161941** [Suwings/MCSManager#351]
**你对哪些功能有建议或想法？**
在控制台输入命令时可以像在cmd窗口输入的命令一样，可以用TAB自动补全
例如
```cmd
>game<TAB>
gamemode  gamerule
>gamemode c<TAB>
>gamemode creative
```
**这些功能有哪些代替方案？**
目前不知

**对应你提出的内容，你觉得有什么价值？**
对于一些难背的指令可以轻松的使用
提高输入命令的效率

**其他内容:**

（功能请求或者功能建议均准许自由发挥，无特定限制模板，你可以在这里写下任何你想说的文字。）

**Comment by Suwings** [comment]
目前的网页控制台是无法做这种操作的，只有模拟型的终端才能实现这样的操作而且还只能是在 tty 环境下，而且MC服务端程序终端本身就不自带这种功能吧。

**Comment by Yang161941** [comment]
好的知道了，谢谢
