### ISSUE TITLE
[新功能建议]建议文件管理添加离线下载功能

### ISSUE THREAD

**Issue by luluxiaoyu** [Suwings/MCSManager#352]
**你对哪些功能有建议或想法？**
建议文件管理添加离线下载功能

因为使用了frp穿透，有流量限制，有离线下载的话可以省一点流量

**Comment by Suwings** [comment]
感谢提供建议。

只不过离线下载这个功能，感觉跟MC管理面板已经搭不上什么关系了吧...

**Comment by luluxiaoyu** [comment]
更新服务端可以先上传去某个地方
再离线下载，就不会消耗frp了嘛········

**Comment by AlexanderMC8533** [comment]
已经再次提过了，坐等MCSM9.0更新。#466
反正来的不会很快但是应该可能会有

**Comment by AlexanderMC8533** [comment]
其实有一个开源项目aria2/aria2可以直接使用这个后端，没有必要去再在MCSM里面内置一个下载器。我其实知道Windows系统里面有curl指令，Linux系统有wget指令，但是有时会出现连不上的问题就。。。嗯，很麻烦
