### ISSUE TITLE
文件管理器有改进计划吗？

### ISSUE THREAD

**Issue by Kogasa-touhou** [Suwings/MCSManager#354]
mcsm的文件管理器觉得有点小简陋
也许是我的问题吧，点一下文件就下载，而不是打开。这个一开始让我有点困扰啊（想编辑文件总是默认点击一下）
其次是文本编辑
（如果支持行数显示和代码高亮就好了）

**Comment by Suwings** [comment]
有重写的计划。

**Comment by AlexanderMC8533** [comment]
能不能加一点批量上传和进度条之类的
