### ISSUE TITLE
请调用系统unzip和tar -xf解压，别自己造轮子了

### ISSUE THREAD

**Issue by koiNoCirculation** [Suwings/MCSManager#355]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境:**
Centos7 
**面板版本:**
latest
**Node版本:**
12
**出现概率:**
always
**出现的问题 (BUG):**
解压大文件卡死, 此时面板也卡死.
top查看cpu占用率发现没有node占用cpu，反而发现了大量的wa占用，说明大量的io在等待
系统tty终端有如下日志，显示内核任务hung死
在内核等待结束后，面板才恢复
怀疑是解压缩的锅
即使我用的是辣鸡的机械硬盘也不应性能如此差劲才对
经对比，解压同一个文件
系统的unzip命令运行起来完全没有看到wa，全部在用户空间
建议您换掉那辣鸡的不行的解压算法
输入文件：1gb
请直接调用系统unzip谢谢
[ 4921.572301] INFO: task node:32596 blocked for more than 120 seconds.
[ 4921.572541] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 4921.572774] node            D ffff8be4bfd9acc0     0 32596  32477 0x00000080
[ 4921.572775] Call Trace:
[ 4921.572781]  [<ffffffffc0140006>] ? perf_trace_btrfs__qgroup_rsv_data+0x136/0x150 [btrfs]
[ 4921.572782]  [<ffffffff9b387169>] schedule+0x29/0x70
[ 4921.572790]  [<ffffffffc017843f>] wait_current_trans.isra.21+0xef/0x140 [btrfs]
[ 4921.572791]  [<ffffffff9acc6d10>] ? wake_up_atomic_t+0x30/0x30
[ 4921.572798]  [<ffffffffc017af1b>] start_transaction+0x30b/0x4b0 [btrfs]
[ 4921.572805]  [<ffffffffc017b0d8>] btrfs_start_transaction+0x18/0x20 [btrfs]
[ 4921.572812]  [<ffffffffc018ad6b>] btrfs_create+0x4b/0x240 [btrfs]
[ 4921.572815]  [<ffffffff9ae5acea>] vfs_create+0x13a/0x1b0
[ 4921.572816]  [<ffffffff9ae5e9a8>] do_last+0x1168/0x1340
[ 4921.572817]  [<ffffffff9ae289c6>] ? kmem_cache_alloc_trace+0x1d6/0x200
[ 4921.572819]  [<ffffffff9ae5ec4d>] path_openat+0xcd/0x5a0
[ 4921.572822]  [<ffffffff9ad11db8>] ? get_futex_key+0x1c8/0x2c0
[ 4921.572823]  [<ffffffff9ae60e9d>] do_filp_open+0x4d/0xb0
[ 4921.572824]  [<ffffffff9ae6ef97>] ? __alloc_fd+0x47/0x170
[ 4921.572825]  [<ffffffff9ae4c9e4>] do_sys_open+0x124/0x220
[ 4921.572827]  [<ffffffff9b393ec9>] ? system_call_after_swapgs+0x96/0x13a
[ 4921.572829]  [<ffffffff9ae4cafe>] SyS_open+0x1e/0x20
[ 4921.572831]  [<ffffffff9b393f92>] system_call_fastpath+0x25/0x2a
[ 4921.572832]  [<ffffffff9b393ed5>] ? system_call_after_swapgs+0xa2/0x13a
[ 4921.572834] INFO: task postdrop:32613 blocked for more than 120 seconds.
[ 4921.573085] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 4921.573335] postdrop        D ffff8be4bfc9acc0     0 32613  32612 0x00000080
[ 4921.573337] Call Trace:
[ 4921.573339]  [<ffffffff9b387169>] schedule+0x29/0x70
[ 4921.573345]  [<ffffffffc017843f>] wait_current_trans.isra.21+0xef/0x140 [btrfs]
[ 4921.573347]  [<ffffffff9acc6d10>] ? wake_up_atomic_t+0x30/0x30
[ 4921.573354]  [<ffffffffc017af1b>] start_transaction+0x30b/0x4b0 [btrfs]
[ 4921.573361]  [<ffffffffc017b0d8>] btrfs_start_transaction+0x18/0x20 [btrfs]
[ 4921.573368]  [<ffffffffc018ad6b>] btrfs_create+0x4b/0x240 [btrfs]
[ 4921.573371]  [<ffffffff9ae5acea>] vfs_create+0x13a/0x1b0
[ 4921.573372]  [<ffffffff9ae5e9a8>] do_last+0x1168/0x1340
[ 4921.573373]  [<ffffffff9ae289c6>] ? kmem_cache_alloc_trace+0x1d6/0x200
[ 4921.573375]  [<ffffffff9ae5ec4d>] path_openat+0xcd/0x5a0
[ 4921.573380]  [<ffffffff9b38044d>] ? avc_compute_av+0x1d2/0x1e4
[ 4921.573381]  [<ffffffff9ae60e9d>] do_filp_open+0x4d/0xb0
[ 4921.573382]  [<ffffffff9ae6ef97>] ? __alloc_fd+0x47/0x170
[ 4921.573384]  [<ffffffff9ae4c9e4>] do_sys_open+0x124/0x220
[ 4921.573386]  [<ffffffff9b393ec9>] ? system_call_after_swapgs+0x96/0x13a
[ 4921.573387]  [<ffffffff9ae4cafe>] SyS_open+0x1e/0x20
[ 4921.573389]  [<ffffffff9b393f92>] system_call_fastpath+0x25/0x2a
[ 4921.573390]  [<ffffffff9b393ed5>] ? system_call_after_swapgs+0xa2/0x13a
**复现操作步骤:**
任意一个玩过一段时间，上gb的存档，从网页上传解压就能复现

**Comment by koiNoCirculation** [comment]
![图片](https://user-images.githubusercontent.com/57739338/103425152-85da3500-4beb-11eb-90e9-f380a8ad8c46.png)
我随便构建个小文件多的压缩包，你服务器是不是就要炸了？
腐竹一不小心就可能搞炸自己面板，不知所措。

**Comment by koiNoCirculation** [comment]
![图片](https://user-images.githubusercontent.com/57739338/103425215-d94c8300-4beb-11eb-9d3f-b092c1fa855c.png)
这个性能问题我只能说耗子尾汁

**Comment by Suwings** [comment]
好的，这并不是我所造轮子，只是依赖库，谢谢你的反馈。
