### ISSUE TITLE
通过网页上传文件失败（仅出现在mc文件夹在非系统盘上）

### ISSUE THREAD

**Issue by TciBan** [Suwings/MCSManager#356]
**系统环境:** Ubuntu20.10

**面板版本:** 发行版本: 8.6.16 发行版本 发行编号: No.20201205-01

**Node版本:** node-v12.16.1-linux-x64

**出现概率:** 始终

**出现的问题 (BUG):**  当mc文件夹在系统盘上时一切正常。但是当我把mc文件夹转移到其他硬盘上之后，就会出现无法通过网页上传文件的问题

**复现操作步骤:** 要两个硬盘

**Comment by koiNoCirculation** [comment]
这类问题八成跟权限有关。

**Comment by TciBan** [comment]
> 这类问题八成跟权限有关。

权限我给足了。chmod 777设置过了没有用

**Comment by ddos-ling** [comment]
我是CentOS系统的，遇到同样的问题

**Comment by Suwings** [comment]
现已修复，是因为Node版本过高，旧版的文件上传依赖库不兼容导致的上传失败，现在已经替换新的依赖库，但还未发行新版本。

https://github.com/Suwings/MCSManager/commit/ff5ad55ee673515408c02af1d0929e0c63dad9af

**Comment by ddos-ling** [comment]
> 
> 
> 现已修复，是因为Node版本过高，旧版的文件上传依赖库不兼容导致的上传失败，现在已经替换新的依赖库，但还未发行新版本。
> 
> 如果你想现在修复这个问题，可以使用 `git pull`拉取最新代码，再使用 `npm i` 安装新版依赖库，即可完成在Linux下的更新。至于Windows系统应该不会出现这个情况，因为Windows系统的运行时环境是锁定版本的。
> 
> [ff5ad55 ](https://github.com/Suwings/MCSManager/commit/ff5ad55ee673515408c02af1d0929e0c63dad9af)

已根据指引进行更新，但是问题依然存在，上传过程正常，但是上传到100%后还是提示“错误，文件上传失败！ undefined”

**Comment by ddv12138** [comment]
> 现已修复，是因为Node版本过高，旧版的文件上传依赖库不兼容导致的上传失败，现在已经替换新的依赖库，但还未发行新版本。
> 
> 如果你想现在修复这个问题，可以使用 `git pull`拉取最新代码，再使用 `npm i` 安装新版依赖库，即可完成在Linux下的更新。至于Windows系统应该不会出现这个情况，因为Windows系统的运行时环境是锁定版本的。
> 
> [ff5ad55](https://github.com/Suwings/MCSManager/commit/ff5ad55ee673515408c02af1d0929e0c63dad9af)

同样的问题也出现在我试图想把MCSManger封装成docker镜像的时候，按道理在容器里就不存在这里说的路径在非系统盘的问题，但是文件上传也会出现一样的问题

**Comment by AirWSW** [comment]
按如下脚本构建的Docker容器，运行后使用网页上传文件到100%后也会提示“错误，文件上传失败！  #undefined”，应该不是权限的问题

```Dockerfile
FROM timbru31/java-node:8-12

RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
    && apt-get clean -y \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

ENV MCSM_VERSION 8.6.17

RUN set -ex \
    && cd /opt \
    && curl -L -o "MCSManager-$MCSM_VERSION.tar.gz" "https://github.com/Suwings/MCSManager/archive/v$MCSM_VERSION.tar.gz" \
    && tar -xvzf "MCSManager-$MCSM_VERSION.tar.gz" \
    && rm -f "MCSManager-$MCSM_VERSION.tar.gz" \
    && mv "/opt/MCSManager-$MCSM_VERSION" /opt/MCSManager \
    && cd /opt/MCSManager \
    && npm install

WORKDIR /opt/MCSManager

EXPOSE 23333, 25565

CMD ["npm", "start"]
```
