### ISSUE TITLE
apache反向代理无法登录

### ISSUE THREAD

**Issue by luluxiaoyu** [Suwings/MCSManager#358]
**系统环境:**
Windows server 2019
**面板版本:**
最新版
**Node版本:**

**出现概率:**
一直
**出现的问题 (BUG):**
使用apache反向代理后，登录提示：服务器错误
再点一次提示：
Cannot POST /public/login/
（使用了frphttps转发）

**复现操作步骤:**

**Comment by Suwings** [comment]
应该是没有代理Websocket链接。

参考：https://github.com/Suwings/MCSManager/wiki/%E4%BD%BF%E7%94%A8-Apache2.4-%E8%BF%9B%E8%A1%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86

**Comment by luluxiaoyu** [comment]
谢谢 行了

**Comment by luluxiaoyu** [comment]
配置好后
登录后提示：与服务器断开连接

**Comment by Suwings** [comment]
恩？有什么报错？具体表现如何？

**Comment by luluxiaoyu** [comment]
![image](https://user-images.githubusercontent.com/58876608/103727581-90933080-5016-11eb-85ed-bd90aea6b7e3.png)
登录是正常的
控制台只提示：用户请求更新令牌 | 准许
就没了
