### ISSUE TITLE
[建议]压缩多文件和群发指令功能

### ISSUE THREAD

**Issue by luluxiaoyu** [Suwings/MCSManager#359]
两个功能建议

1.建议文件管理可以压缩多个文件夹/文件，我有用着某宝的面板服，文件管理直接给了根目录，导致我想打包服务端的时候特别麻烦，只能一个一个文件夹压缩。（选中多个文件夹压缩会提示：非法操作，不可解压空文件或同时解压多个文件！）

2.建议添加群发指令功能，因为用的群组服，有时候需要群发信息

**Comment by Suwings** [comment]
关于第一点压缩多文件的问题。你可以建一个目录，然后将其他文件批量移动到这个目录下，再压缩这个目录即可。

第二点会考虑。

谢谢你的反馈！
