### ISSUE TITLE
windows安装异常

### ISSUE THREAD

**Issue by MMDKZT** [Suwings/MCSManager#36]
在windows上用npm安装不了
Windows Server 2012 R2 x64
Windows 7 x64
都不行 @Suwings 
![default](https://user-images.githubusercontent.com/26001589/40882800-e43ada68-671f-11e8-99ad-bea3ad405bf8.png)

**Comment by ZhangqianStudio** [comment]
请确保 Git 已经安装, 并且写入的了环境变量

**Comment by Suwings** [comment]
npm 的运行需要 git 环境，请确保git工具已经安装，当然我们推荐你下载 Windows 整合版本
[点击下载](https://pan.baidu.com/s/1bpbB8Az)
