### ISSUE TITLE
控制台输入中文无法正常显示

### ISSUE THREAD

**Issue by SnowMoonSS** [Suwings/MCSManager#361]
**系统环境:**Windows 10 专业版 20H2

**面板版本:**8.6.15 发行版本

**Node版本:**面板自带的

**出现概率:**100%

**出现的问题 (BUG):**向控制台发送中文，返回问号`?`

**复现操作步骤:**使用`/say`指令发送命令，客户端只会收到`?`，控制台也只会显示`?`，但是控制台能正确显示玩家从客户端发送的中文。使用`/give`指令也会出现同样的问题

**Comment by Suwings** [comment]
在服务器列表，点击“参数”，右下角应该有输入输出编码设置，更改这个选项的编码，一般是gbk，big5，utf8三种编码进行尝试。

**Comment by SnowMoonSS** [comment]
> 在服务器列表，点击“参数”，右下角应该有输入输出编码设置，更改这个选项的编码，一般是gbk，big5，utf8三种编码进行尝试。

感谢，命令输入编码改成`UTF-8`行了
