### ISSUE TITLE
CentOS8下手动安装启动后登录进去后立即就提示与服务器链接中断，数据发送失败，请刷新或登陆重试

### ISSUE THREAD

**Issue by yunbro** [Suwings/MCSManager#364]
**内容:**
如题，网上查不到资料不知道该如何处理了

**Comment by Suwings** [comment]
是否有进行反向代理？如果有，是否已经反向代理了websocket链接？

如果没有，建议重新安装MCSM面板，再尝试一下。有更多情况欢迎再讨论。

**Comment by yunbro** [comment]
> 是否有进行反向代理？如果有，是否已经反向代理了websocket链接？
有反向代理，websocket链接不知道有这个事啊不知道咋代理啊

**Comment by yunbro** [comment]
> 是否有进行反向代理？如果有，是否已经反向代理了websocket链接？
> 
> 如果没有，建议重新安装MCSM面板，再尝试一下。有更多情况欢迎再讨论。

感谢大佬指点，在文档中找到了
![image](https://user-images.githubusercontent.com/62164344/106078990-59182f80-614f-11eb-8d1a-8570caafb46a.png)
