### ISSUE TITLE
模拟终端和命令控制台无法发送命令只能监控

### ISSUE THREAD

**Issue by ACGMC** [Suwings/MCSManager#367]
发行版本: 8.6.17 发行版本
发行编号: No.20210125-01

自定义命令开gta5服务器然
./run.sh +set serverProfile dev_server +set txAdminPort 40121

只能监控,,发送命令不行
会打印下面信息,实际控制台没反应,
Sending heartbeat to https://servers-ingress-live.fivem.net/ingress[gta@app]addwl

命令控制台:   addwl

Local data is up to date
Plugin will check it again after 120s
[ SYSTEM ] 正在监听服务端日志输出.
Checking version and blacklist...

其实毫无反应,

下面是正常console输出用FXServer Console发命令: addwl
[txAdmin:WebConsole:SocketIO] MANA221 executing  addwl 
No such command addwl.
Checking version and blacklist...

![image](https://user-images.githubusercontent.com/38478564/106368170-8fb49c80-633f-11eb-9963-914ac8909df6.png)

**Comment by Suwings** [comment]
现已是否解决？可能当前面板并不能开GTA5服务器吧，没有在这个方面进行过测试。

**Comment by huangsijun17** [comment]
`./run.sh`改成`sh run.sh`试试看。
