### ISSUE TITLE
加个开服前自动生成ELUA？

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#369]
添加后或启动前加一个可选的同意ELUA的功能，带上mojang的协议……

**Comment by Suwings** [comment]
以前有一款软件因为自动同意elua协议在mcbbs被人举报并且下架，可能从法律角度来说，本身就不能自动同意eula。

**Comment by huangsijun17** [comment]
加个勾选框，放上协议……

**Comment by stydxm** [comment]
可以在创建服务端的时候确认按钮旁边放个选项：自动同意EULA（具体内容请查看xxxx）

**Comment by Rabbit0w0** [comment]
事实上服务器不是香草端开公益，全都无一例外违反了EULA 我觉得这个可以加上

**Comment by Suwings** [comment]
已新增，创建服务器时自动添加 eula.txt 
https://github.com/Suwings/MCSManager/commit/64d758de0daedc4252701ad5314d09c754f784f4
