### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by MomentQYC** [Suwings/MCSManager#370]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境:**
CentOS7.6
**面板版本:**
GitHub最新版
**Node 版本:**
默认安装
**出现概率:**
Always
**出现的问题 (BUG):**
无法启动（已进行常规修复诸如systemctl daemon-reload）
**复现操作步骤:**
systemctl start mcsm

![QQ截图20210203110031](https://user-images.githubusercontent.com/62551256/106691782-14890a00-660f-11eb-814d-d1e63d3426ed.png)
![QQ截图20210203110158](https://user-images.githubusercontent.com/62551256/106692348-47cb9900-660f-11eb-91e7-113b9748970b.png)

**Comment by Suwings** [comment]
十分抱歉回复较晚。

根据你的截图。原因是未能成功安装依赖库，建议重新安装面板或者进入 /opt/mcsmanager 目录下执行 npm i 命令。

**Comment by EITSxiaozhai** [comment]
@Suwings 进入输入过后提示
/usr/bin/node: 1: /usr/bin/node: ELF: not found
/usr/bin/node: 12: /usr/bin/node: Syntax error: word unexpected (expecting ")")
如何解决

**Comment by Suwings** [comment]
此错误无法准确的找出问题所在，建议你删除node环境并且重新安装环境，面板和依赖库。
