### ISSUE TITLE
内存引用出错，明明剩余至少20GBRAM可用

### ISSUE THREAD

**Issue by COOPER-ZiLie** [Suwings/MCSManager#372]
内存引用出错，明明剩余至少20GBRAM可用，但是死活说只有几百M...
系统centos7
<a href="https://sm.ms/image/q5rPaK2Tdn4swGf" target="_blank"><img src="https://i.loli.net/2021/02/05/q5rPaK2Tdn4swGf.png" ></a>

<a href="https://sm.ms/image/OuhcbLAGeVK7svR" target="_blank"><img src="https://i.loli.net/2021/02/05/OuhcbLAGeVK7svR.png" ></a>

**Comment by Shuazijun** [comment]
c7已测试正常.你可以试下单独虚拟一台机器出来安装面板
