### ISSUE TITLE
申请支持mcdr

### ISSUE THREAD

**Issue by mentlesoul** [Suwings/MCSManager#374]
申请mcsm支持mcdr，以bat脚本打开mcdr，mcdr打开服务器
这是基于python的mcdr的作者在github的库
https://github.com/Fallen-Breath/MCDReforged

**Comment by Suwings** [comment]
近期较忙，mcsm部分功能开发进度延后，可能没有太多时间做其他功能。

**Comment by huangsijun17** [comment]
我看到过很多人直接在MCSM里允许py来启动MCDR的。
之前还因为特殊字符的BUG研究过。

**Comment by mentlesoul** [comment]
> 
> 
> 我看到过很多人直接在MCSM里允许py来启动MCDR的。
> 之前还因为特殊字符的BUG研究过。

嗯嗯嗯？？？请问有无配置的截图或者链接，谢谢

**Comment by xslingcn** [comment]
> > 我看到过很多人直接在MCSM里允许py来启动MCDR的。
> > 之前还因为特殊字符的BUG研究过。
> 
> 嗯嗯嗯？？？请问有无配置的截图或者链接，谢谢

直接在自定义命令栏输入python3 MCDReforged.py即可。
同理MCSM可以用来管理任何命令行程序。

**Comment by zhang-anzhi** [comment]
> 申请mcsm支持mcdr，以bat脚本打开mcdr，mcdr打开服务器
> 这是基于python的mcdr的作者在github的库
> https://github.com/Fallen-Breath/MCDReforged

参考 #286
