### ISSUE TITLE
面板中打开服务器无法被外网和内网访问

### ISSUE THREAD

**Issue by BZX6666** [Suwings/MCSManager#376]
**系统环境:**
树莓派raspbian
**面板版本:**
8.6.17 发行版本
**Node 版本:**
node-v12.16.1-linux-armv7l
**出现概率:**

**出现的问题 (BUG):**
我可以在/home/pi/Desktop中运行服务端文件服务器 可以被外网访问，但是面板里打开服务端文件，服务器不能被外网和内网访问，面板也可以通过外网访问
**复现操作步骤:**

**Comment by huangsijun17** [comment]
是否使用了Docker？
建议检查防火墙、端口转发、反代等。

**Comment by BZX6666** [comment]
我能用外网远程桌面打开终端运行/home/pi（用户名）/Desktop下的.jar 可以成功开服 外网也可以进
换成面板里开服就不行了连内网都进不去游戏
两次运行的jar都是同一个同一个目录下

**Comment by Rabbit0w0** [comment]
你确定防火墙放行了docker吗------------------&nbsp;Original&nbsp;------------------

**Comment by BZX6666** [comment]
没用面板里的docker指令，也需要吗

**Comment by huangsijun17** [comment]
Docker自带端口限制……

**Comment by BZX6666** [comment]
> 你确定防火墙放行了docker吗------------------&nbsp;Original&nbsp;------------------ From:&nbsp;&quot;BZX6666&quot;<notifications@github.com&gt; Date:&nbsp;Thu, Feb 11, 2021 10:57 AM To:&nbsp;&quot;Suwings/MCSManager&quot;<MCSManager@noreply.github.com&gt;; Cc:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; Subject:&nbsp;Re: [Suwings/MCSManager] 面板中打开服务器无法被外网和内网访问 (#376)

没用面板服务器设置里的docker指令也需要吗？我是小白不懂

**Comment by BZX6666** [comment]
我去试试关闭防火墙

**Comment by BZX6666** [comment]
输入docker version ：未找到命令
docker没安装？

**Comment by BZX6666** [comment]
我也没防火墙啊
输入systemctl stop firewalld
Failed to stop 。。。：Unit firewalld.service not loaded

**Comment by BZX6666** [comment]
有个mcsm.service
[Unit]
Description=MCSManager

[Service]
ExecStart=/usr/bin/node /opt/MCSManager/app.js
Restart=always
Environment=PATH=/usr/bin:/usr/local/bin:/usr/local/node/bin
Environment=NODE_ENV=production
WorkingDirectory=/opt/MCSManager/

[Install]
WantedBy=multi-user.target


看看有什么问题ExecStart？

**Comment by BZX6666** [comment]
坐等大佬帮忙···

**Comment by BZX6666** [comment]
坐等大佬帮忙，现在只能远程桌面跑去开服了。
