### ISSUE TITLE
使用bt面板的nginx反代无法正常登陆MCSM：服务器错误

### ISSUE THREAD

**Issue by danuonuo** [Suwings/MCSManager#377]
**系统环境:**
Ubuntu20.04LTS

**面板版本:**
v8.6.17

**Node 版本:**
v14.15.4

**出现概率:**
总是

**出现的问题 (BUG):**

使用bt面板的nginx反代https无法正常登陆MCSM，登录时提示：服务器错误
PS：已经在nginx配置文件中配置ws，并已经按要求更改URL.js

**复现操作步骤:**
https反向代理后直接打开https网址，输入账号密码，点击登录

**Comment by Suwings** [comment]
理论上只要配置好 ws 和 http 代理应该就不会有什么问题，你参考一下WIKI试试吧：

https://github.com/Suwings/MCSManager/wiki

**Comment by danuonuo** [comment]
> 理论上只要配置好 ws 和 http 代理应该就不会有什么问题，你参考一下WIKI试试吧：
> 
> https://github.com/Suwings/MCSManager/wiki

试过，就是按他操作的，但是一点登录就提示服务器错误，直接ip连接就没问题，ws已经配置

**Comment by Suwings** [comment]
logs文件夹下有日志文件，看看里面是否有最新的错误信息吧。目前我也不清楚是什么原因导致的这种情况。

**Comment by danuonuo** [comment]
> logs文件夹下有日志文件，看看里面是否有最新的错误信息吧。目前我也不清楚是什么原因导致的这种情况。

但是并没有报错

**Comment by danuonuo** [comment]
已解决，疑似为cloudflare不缓存设置未同步造成，谢谢Suwings！

**Comment by danuonuo** [comment]
Solved
^-^
