### ISSUE TITLE
Install仓库失败

### ISSUE THREAD

**Issue by TheCurchi** [Suwings/MCSManager#379]
**系统环境:**
Linux Ubuntu x64

**面板版本:**
8.6.18

**Node 版本:**
12.16.1

**出现概率:**
99%

**出现的问题 (BUG):**
按照Linux上的搭建教程克隆github上面的仓库并执行npm install之后，有极大概率会卡在某个包一直无法install成功。尝试过更换淘宝镜像反而会出现更多问题。阿里与/腾讯云都会出现这个问题。

**复现操作步骤:**
安装全部依赖项后clone仓库并npm install

> root@VM-0-9-ubuntu:/newtry# git clone https://gitee.com/Suwingser/MCSManager.git
> Cloning into 'MCSManager'...
> 
> remote: Enumerating objects: 8408, done.
> remote: Counting objects: 100% (8408/8408), done.
> remote: Compressing objects: 100% (4052/4052), done.
> remote: Total 8408 (delta 5227), reused 7148 (delta 4249), pack-reused 0
> Receiving objects: 100% (8408/8408), 7.79 MiB | 2.04 MiB/s, done.
> Resolving deltas: 100% (5227/5227), done.
> Checking connectivity... done.
> root@VM-0-9-ubuntu:/newtry# 
> root@VM-0-9-ubuntu:/newtry# wget -qO- https://gitee.com/Suwingser/MCSManager-installer/raw/master/install.sh | bash
> Start to install MCSManager...
> 
> --2021-02-17 22:46:26--  https://npm.taobao.org/mirrors/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz
> Resolving npm.taobao.org (npm.taobao.org)... 114.55.80.225
> Connecting to npm.taobao.org (npm.taobao.org)|114.55.80.225|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://cdn.npm.taobao.org/dist/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz [following]
> --2021-02-17 22:46:26--  https://cdn.npm.taobao.org/dist/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz
> Resolving cdn.npm.taobao.org (cdn.npm.taobao.org)... 61.147.223.244, 61.147.223.248, 61.147.223.239, ...
> Connecting to cdn.npm.taobao.org (cdn.npm.taobao.org)|61.147.223.244|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 23005690 (22M) [application/octet-stream]
> Saving to: ‘node-v12.16.1-linux-x64.tar.gz’
> 
> node-v12.16.1-linux-x64.tar.gz                   100%[==========================================================================================================>]  21.94M  17.3MB/s    in 1.3s    
> 
> 2021-02-17 22:46:27 (17.3 MB/s) - ‘node-v12.16.1-linux-x64.tar.gz’ saved [23005690/23005690]
> 
> Unpacking...
>  tar -zxf node-v12.16.1-linux-x64.tar.gz
> complete.
> Linking...
>  ln -s /opt/node-v12.16.1-linux-x64//node-v12.16.1-linux-x64/bin/node /usr/bin/node
>  ln -s /opt/node-v12.16.1-linux-x64//node-v12.16.1-linux-x64/bin/node /usr/bin/node
> complete.
> --------------- Node Version ---------------
>  node: v12.16.1
>  npm: 6.13.4
> --------------- Node Version ---------------
> Installing git...
> There are no enabled repos.
>  Run "yum repolist all" to see the repos you have.
>  You can enable repos with yum-config-manager --enable <repo>
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> git is already the newest version (1:2.7.4-0ubuntu1.9).
> 0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
> bash: line 46: pacman: command not found
> complete.
> Download MCSManager...
> fatal: destination path 'MCSManager' already exists and is not an empty directory.
> complete.
> Start to install dependent libraries...
> [            ......] | extract:moment: sill extract moment@2.24.0 extracted to /opt/MCSManager/node_modules/.staging/moment-67915d13 (773ms)

每次都在[            ......] | extract:moment: sill extract moment@2.24.0 extracted to /opt/MCSManager/node_modules/.staging/moment-67915d13 (773ms) 这个地方卡住。测试了十来次，有一次可以往下走，其他情况下就会卡死在这里

**Comment by Suwings** [comment]
这个依赖库安装过程可能得需要等久一点（5~10分钟左右，耐心一点），过段时间我会尝试修复这个问题。

**Comment by nidbCN** [comment]
如果npm安装由于网络关系容易卡住，可以考虑使用cnpm代替，具体步骤看 [CNPM官网](https://cnpmjs.org/)

**Comment by Suwings** [comment]
此问题应该已经在 https://github.com/Suwings/MCSManager/releases/tag/v8.6.20 `8.6.20` 版本中修复。
