### ISSUE TITLE
日志问题

### ISSUE THREAD

**Issue by zhouchengzhe** [Suwings/MCSManager#38]
从windows切换回linux之后，发现无法查看网页后台打开以前刷新的日志（历史日志？

**Comment by Suwings** [comment]
Version 8.3.2
https://github.com/Suwings/MCSManager/releases/tag/v8.3.2
这是最后一个支持 历史日志的版本。

**Comment by Suwings** [comment]
亲~你要功能已经实现，欢迎品尝。
[https://github.com/Suwings/MCSManager/releases/tag/v8.4.3](https://github.com/Suwings/MCSManager/releases/tag/v8.4.3)
@zhouchengzhe
