### ISSUE TITLE
CentOs启动报错

### ISSUE THREAD

**Issue by Evil0ctal** [Suwings/MCSManager#382]
[root@VM-0-6-centos opt]# systemctl status mcsm
● mcsm.service - MCSManager
   Loaded: loaded (/usr/lib/systemd/system/mcsm.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2021-02-26 16:10:28 CST; 52s ago
  Process: 145230 ExecStart=/usr/bin/node /opt/MCSManager/app.js (code=exited, status=1/FAILURE)
 Main PID: 145230 (code=exited, status=1/FAILURE)

Feb 26 16:10:28 VM-0-6-centos systemd[1]: mcsm.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 16:10:28 VM-0-6-centos systemd[1]: mcsm.service: Failed with result 'exit-code'.
Feb 26 16:10:28 VM-0-6-centos systemd[1]: mcsm.service: Service RestartSec=100ms expired, scheduling restart.
Feb 26 16:10:28 VM-0-6-centos systemd[1]: mcsm.service: Scheduled restart job, restart counter is at 5.
Feb 26 16:10:28 VM-0-6-centos systemd[1]: Stopped MCSManager.
Feb 26 16:10:28 VM-0-6-centos systemd[1]: mcsm.service: Start request repeated too quickly.
Feb 26 16:10:28 VM-0-6-centos systemd[1]: mcsm.service: Failed with result 'exit-code'.
Feb 26 16:10:28 VM-0-6-centos systemd[1]: Failed to start MCSManager.

**Comment by huangsijun17** [comment]
npm start可以开吗？报错什么？

**Comment by Evil0ctal** [comment]
> npm start可以开吗？报错什么？

已找到错误，端口被占用，谢谢。
