### ISSUE TITLE
希望添加域名

### ISSUE THREAD

**Issue by NiuBoss** [Suwings/MCSManager#385]
虽然不是什么重要事情，但是我觉得连接地址是个域名总好过IP对吧，即使是给自己朋友。
说实在，真心希望添加，一方面不违反国家法律（IP不能作为网址，虽然可以通过其他方法解决掉，但是我懒），另一方面，连接可以安全一点

不太期望更新出来，不过也请注意一下

**Comment by lone-wolf-akela** [comment]
域名是需要自己去买然后去买域名的地方设置绑定ip的，和面板有什么关系呢？

**Comment by NiuBoss** [comment]
可能我描述的不好
类比其他面板，在控制台添加一个域名填写框，在以后如果添加了IP显示的位置时就可以不显示主机的外网IP了，可以自动改显示域名的地址，不然怕有人攻击服务器

麻烦考虑一下，我描述可能不是很好，往谅解

**Comment by NiuBoss** [comment]
如果说本来就没有添加IP显示的功能的话，前面的可以当我没说，但是网站不能是以IP地址作为网址这个，望谅解

**Comment by NiuBoss** [comment]
如果说本来就没有添加IP显示的功能的意思，前面的可以当我没说，但是网站不能是以IP地址作为网址这个，望谅解
