### ISSUE TITLE
FTP传输因为网络等原因中断后导致没有传输完成的那个目录无法访问

### ISSUE THREAD

**Issue by xiaozha13** [Suwings/MCSManager#39]
FTP传输因为网络等原因中断后导致没有传输完成的那个目录无法访问
![image](https://user-images.githubusercontent.com/29670018/41199648-1f619692-6cc8-11e8-8382-1c25d9f99736.png)

**Comment by Suwings** [comment]
感谢你的反馈，这个问题我们没有仔细测试过，也许这是一个bug。

过段时间我将重新模拟一下这类活动，来调查问题，此FTP库是第三方依赖库。

**Comment by Suwings** [comment]
我使用了 FileZilla 64 ，Windows(Win10 64 1807) 浏览器 和 FlashFTP 64 进行模拟，没有发现你所说的情况，纵使限速，突然断开 WiFi 也没有发现你所说的情况。

不过我依然还是会保持谨慎，这既有可能是一个 BUG。只是没有发现而已，或者在某种特定的情况下才会发生。

**Comment by xiaozha13** [comment]
有时间我会尝试去录制一个视频

**Comment by Suwings** [comment]
感谢，如果下次再发现这类现象，还请再开一个 issue 反馈。
