### ISSUE TITLE
官方使用方法不明白

### ISSUE THREAD

**Issue by Pantyhose-X** [Suwings/MCSManager#390]
**内容:**
官方使用方法,写的不明白、不提示要安装Mohist 核心
详细使用方法
https://southcat.net/646/

**Comment by huangsijun17** [comment]
面板只是允许、管理Minecraft服务端的，和你安装、使用什么Minecraft服务端无关。
面板不会也不应当引导用户安装指定的服务端。

**Comment by stydxm** [comment]
这和面板有啥关系吗？这个核心和这个面板有联系吗？

**Comment by liuran001** [comment]
面板只是用来管理服务端的，核心使用什么是用户自己的事，甚至使用其管理非mc服务器的程序也没有问题

> 这是一款可以管理多个 Minecraft 服务端（支持群组端）的 Web 管理面板，并且可以分配多个子账号来分别管理不同的 Minecraft 服务端，支持绝大部分主流的服务端，甚至是其他非 Minecraft 的程序。

并且wiki中已经写了 Bedrock_server 服务端的[开启方法](https://github.com/Suwings/MCSManager/wiki/%E4%BD%BF%E7%94%A8%E9%9D%A2%E6%9D%BF%E5%BC%80%E5%90%AF-Bedrock_server-%E6%9C%8D%E5%8A%A1%E7%AB%AF) ，其他服务端依葫芦画瓢就行的
