### ISSUE TITLE
API文档什么时候会开启？

### ISSUE THREAD

**Issue by Evil0ctal** [Suwings/MCSManager#391]
**内容:**
9小时前关闭了API文档，请问有任何副本可以参考吗？

**Comment by huangsijun17** [comment]
API接口文档？接口是接口，文档是文档。你到底是要开还是要关？

**Comment by Evil0ctal** [comment]
我说的是API文档
URL:https://github.com/Suwings/MCSManager/wiki/API-Documentation
_________________________________________________________________________________
通知：

原有的 API 文档暂时关闭阅读，待API稳定后再更新发布，敬请谅解。

**Comment by Suwings** [comment]
过段时间就行。很快。
