### ISSUE TITLE
浏览器的上一级按钮无法工作

### ISSUE THREAD

**Issue by mzdluo123** [Suwings/MCSManager#392]
**系统环境:**
Linux x64 ubuntu-server 5.4.0-67-generic

**面板版本:**
发行版本: 8.6.20 发行版本
发行编号: No.20210313-01

**Node 版本:**

**出现概率:**
100%

**出现的问题 (BUG):**

在任何一个后台管理的页面上 ，浏览器的上一级按钮均不能工作

**复现操作步骤:**

在web管理的前端界面任意一个页面上按下浏览器的上一级按钮

浏览器版本:
Windows 10  Microsoft Edge
版本 89.0.774.54 (官方内部版本) (64 位)

**Comment by Suwings** [comment]
感谢发起反馈。

此情况并不是bug，从8.0的第一个版本开始浏览器的上一级按钮就已经被禁止了。原因是因为网页在设计上并不存在“上一页”和“下一页”的概念，整个网页相当于均是在一个网页内的子网页。

在后来的版本才在url上新增的伪装的地址以便于刷新网页时能够到达上次浏览的位置，但是并没有考虑新增“上一页”功能。

**Comment by mzdluo123** [comment]
虽然网页是一个整体，但是在一些页面上还是有上一级和下一级关系的。
例如服务器列表和具体服务器的信息页面，只能通过侧边栏进行导航会给一些习惯于上一级按钮的用户带来一些不适应（比如我），同时，在Android设备上无法使用返回键也比较难受
