### ISSUE TITLE
建议：添加当mcsm自动启动时可以自动启动服务器

### ISSUE THREAD

**Issue by FirstMelody** [Suwings/MCSManager#393]
建议当启动mcsm时选择性自动启动服务端
这样可以在服务器（硬件）意外重启后service启动mcsm后使服务器重新上线
实现无人值守服务器自动完全崩溃启动

**Comment by MagmaBlock** [comment]
可以在计划任务里添加个循环__start__的任务，这样子只要mcsm在线服务器就关不掉

**Comment by huangsijun17** [comment]
> 可以在计划任务里添加个循环__start__的任务，这样子只要mcsm在线服务器就关不掉

所以关服都不让关了？

**Comment by MagmaBlock** [comment]
> > 可以在计划任务里添加个循环__start__的任务，这样子只要mcsm在线服务器就关不掉
> 
> 所以关服都不让关了？

w我个人是这样解决的
我那个服基本上不关
找作者罢

**Comment by Anders233** [comment]
这个功能还没添加吗，记得好久之前就看到过类似的Issues了

**Comment by Anders233** [comment]
这个功能还没添加吗，记得好久之前就看到过类似的Issues了

**Comment by Cubik65536** [comment]
> 这个功能还没添加吗，记得好久之前就看到过类似的Issues了

控制面板内的崩溃重启是否就是在实现此功能？

**Comment by huangsijun17** [comment]
> > 这个功能还没添加吗，记得好久之前就看到过类似的Issues了
> 
> 控制面板内的崩溃重启是否就是在实现此功能？

并不是。

**Comment by huangsijun17** [comment]
这个功能很久以前就有人说了，但是一直没加是真的。
另外，我建议是通过启动参数解决，例如启动时带有`-autostart`就全部自动开服，开机自启动的服主，改一下配置文件加上参数即可。

PS，现在还有是有解决方法的，例如使用systemctl中的运行服务后执行命令功能，搞一个延时开启xxx服务器的python脚本等等，就可以了。

**Comment by yzy613** [comment]
**这个功能太需要了！！！**

**Comment by KYLN24** [comment]
太需要了😭😭

**Comment by KagurazakaNyaa** [comment]
可以考虑这样实现，对于docker方式运行的服务器，配置其docker容器的`restart`参数，使其为`always`或`unless-stopped`，这样在docker.service启动后，会自动尝试保持此容器的运行
推荐使用`unless-stopped`参数，这样在停止服务器时只需要`stop`容器而不需要`remove`容器

**Comment by keywet06** [comment]
建议在服务器`崩溃监视与配置`一栏中增加`服务器自启`的功能
因为设置开机自启比较简单，但没办法用命令让程序开服务器（API没了awa

**Comment by keywet06** [comment]
**这个功能太需要了！！！**

**Comment by Suwings** [comment]
此功能已由 @keywet06 实现，具体可参考最新发行版。
