### ISSUE TITLE
我在pterodactyl面板裡面做出了專屬的EGG

### ISSUE THREAD

**Issue by jing-shiun** [Suwings/MCSManager#394]
我在pterodactyl面板裡面做出了專屬的egg
希望大大可以公開他
附上我的github網址:https://github.com/jing-shiun/pterodactyl-panel-mcsmanager
感謝

**Comment by Suwings** [comment]
感謝提交反饋。

Pterodactyl 面板和 MCSManager 面板不應該屬於同類產品嗎？盡管 Pterodactyl 面板很好，但一般而言這兩者之間不會互相存在才對，你的這個項目我不太清楚是否有意義。

**Comment by jing-shiun** [comment]
這樣可以讓pterodactyl多出更多延伸功能 增加一些方便的服務
