### ISSUE TITLE
[求助]使用Nginx反代无法上传文件

### ISSUE THREAD

**Issue by SealsTak** [Suwings/MCSManager#395]
![image](https://user-images.githubusercontent.com/65878832/111896519-273b8f00-8a55-11eb-8d92-5dc49fb55755.png)
如图，server.***.cn为部署Nginx的机子，使用网页上传文件时显示上传失败，而使用mj.***.cn:2002直接连接时上传成功
![image](https://user-images.githubusercontent.com/65878832/111896572-94e7bb00-8a55-11eb-8bcf-23b15c84e5bf.png)
Nginx配置如下图
![image](https://user-images.githubusercontent.com/65878832/111896594-cc566780-8a55-11eb-9111-0d1496ae2ce0.png)

**Comment by huangsijun17** [comment]
在nginx配置文件中尝试添加参数：
`client_max_body_size 1000m;`
参考：
https://github.com/Suwings/MCSManager/issues/260#issuecomment-657235126
