### ISSUE TITLE
希望早日支持Java16

### ISSUE THREAD

**Issue by nidbCN** [Suwings/MCSManager#397]
**你对哪些功能有建议或想法？**
服务器面板并不支持Java16，如果使用Java16并用面板开服会提示：
```
Unsupported Java detected (60.0). Only up to Java 15 is supported.
```
**这些功能有哪些代替方案？**
使用旧版本的Java
**对应你提出的内容，你觉得有什么价值？**
Java16 Release了ZGC，对于服务器的内存控制有很大帮助，有效减小负载。
**其他内容:**
当然也可以考虑更改一下默认的Dockerfile，java:latest 镜像是Java8

**Comment by Suwings** [comment]
关于支持 Java16 环境。面板并不需要任何 Java 环境运行，只需要 Nodejs 环境即可运行面板程序。需要早日支持 Java 16 的应该是你使用的MC服务端，而不是面板，面板仅仅只是使用了一条系统命令来启动服务端而已。

关于 Dockerfile。默认是 Java 8 一般情况足以应付，特殊情况的话可能需要自行修改，或者等待 MCSM 面板下个版本。

谢谢你的反馈。

**Comment by nidbCN** [comment]
感谢您的解答，我将尝试使用新版本的服务器核心。Dockerfile已经自行修改
