### ISSUE TITLE
面板内命令控制台部分字符乱码（我猜它应该是颜色编码）

### ISSUE THREAD

**Issue by nidbCN** [Suwings/MCSManager#398]
**系统环境:**
```
操作系统：Ubuntu(Server) 20.04.2 LTS
Docker：Docker version 19.03.8, build afacb8b7f0
容器镜像：openjdk:15
Minecraft核心：paper-1.16.5-551
```
**面板版本:**
```
8.6.15
```
**Node 版本:**
```
v14.16.0 LTS
```
**出现概率:**
ALWAYS
**出现的问题 (BUG):**
在"命令控制台中"，部分地方（尤其是中括号前后）出现乱码（如`[0;37m[3m`、`....[?1h=[?2004h>.... [K[12:14:25 INFO]`等）。更改编码后扔存在此问题。  
在"模拟型终端"中无此问题。  
详见下图：  
[![6jtxfS.png](https://z3.ax1x.com/2021/03/26/6jtxfS.png)](https://imgtu.com/i/6jtxfS)
**复现操作步骤:**
在Ubuntu Server 20.04中安装nodejs、docker，使用该DockerFile：
```
FROM openjdk:15
RUN mkdir -p /mcsd
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo "Asia/Shanghai" >/etc/timezone
WORKDIR /mcsd
```
创建镜像，并启动服务器。  
点开"命令控制台"，可见输出中存在乱码

## 其它

issue模板中刚开始那句请删掉的提示语，可以考虑默认为注释状态，即：
```html
<!--对于模板的提示-->
```
这样编辑者能看见提示语，而发出issue后又不会显示在页面里。  

最后，感谢Suwings团队带来如此方便的作品！

**Comment by Suwings** [comment]
此问题已经在 `8.6.19` 得到了改善。

你可以考虑使用最新版本：https://github.com/Suwings/MCSManager/releases

更新方法在此链接稍下处应该有写，感谢你详情的反馈，谢谢你。

**Comment by nidbCN** [comment]
对不起，我issue内的版本号存在问题，我使用的是`package.json`里面写的版本号。我没有从Release下载，而是从GitHub clone下来的。我看了一下十几天前clone的，应该是最新的版本。
感谢您的解答，我考虑从Release下载并迁移一下。

**Comment by nidbCN** [comment]
后端面板上面显示版本为8.6.20

**Comment by Suwings** [comment]
那可能确实存在这类问题，不过mcsm面板目前处于缓慢更新状态，正在准备开发9.0版本，所以短期内可能不会修复这个问题，谢谢你的反馈。

**Comment by nidbCN** [comment]
期待您的更新，另：记得更新`package.json`里面的版本号。
