### ISSUE TITLE
WebSocket超时自动断开的问题

### ISSUE THREAD

**Issue by BBleae** [Suwings/MCSManager#4]
某些不会自动更新数据的页面 (比如添加服务器的时候填写信息的页面), 
停留在这些页面上的时候WebSocket连接长时间不发送消息, 导致连接超时自动断开,  不得不刷新页面
可以通过心跳包来解决这个问题
比如加一段这样的JS代码:
```JavaScript
window.setInterval(function(){ //每隔10秒钟发送一次心跳，避免websocket连接因超时而自动断开
	WS.sendMsg("ping","");
	},10000);
```
_上面这段代码我测试过 可以解决ws自动断开的问题_

**Comment by Suwings** [comment]
感觉提供建议与代码，将于今日添加于项目上。

**Comment by Suwings** [comment]
完成
