### ISSUE TITLE
请问怎么设置SSL反向代理和隐藏端口

### ISSUE THREAD

**Issue by shuiqing2046** [Suwings/MCSManager#40]
如题，希望作者能出个具体SSL教程（本人只有少量自学的网页知识，请谅解），就是让网站https://开头的那个，还有就是有没有办法隐藏连接端口，目前用的是MCBBS分享的那个最新版...非常感谢您

**Comment by shuiqing2046** [comment]
我知道怎么申请免费SSL证书，但是不知道怎么在MCSManager里启用和设置

**Comment by Suwings** [comment]
短时间内暂时不会写相关教程。具体ssl配置方法网上有很多。

隐藏链接端口？你可以使用默认端口 80/443 即可隐藏端口。

@shuiqing2046
