### ISSUE TITLE
无法监听Arclight服务端的日志

### ISSUE THREAD

**Issue by molehzy** [Suwings/MCSManager#402]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境: Win10 **

**面板版本: 8.6.20 **

**Node 版本: 12.16.0 **

**出现概率: 100% **

**出现的问题 (BUG): 无法监听[Arclight](https://github.com/IzzelAliz/Arclight)服务端的日志 **

**复现操作步骤: https://1drv.ms/u/s!AnzleC2286obkxwN_3chj5996ycm?e=77LMBy **

**Comment by Suwings** [comment]
我很早就已经看了你的视频只是忘记回复一直到现在。这个原因我从视频上没有看出来为什么，似乎是安装日志是能显示，但是真正启动后的那部分日志就无法显示了，这个原因暂时不清楚。

可能现有面板确实兼容不了，面板的以后下一代大版本会尝试兼容，谢谢你的反馈。
