### ISSUE TITLE
服务端失控在后台运行无法关闭

### ISSUE THREAD

**Issue by TheSmileCat** [Suwings/MCSManager#403]
**系统环境:**
Windows_NT ia32 WIN-4ATJ94TD0RU 10.0.17763
**面板版本:**
8.6.11 发行版本
**Node 版本:**
未知，没有权限得到
**出现概率:**
偶然
**出现的问题 (BUG):**
服务端脱离控制，在后台异常运行，无法关闭，而且占用了端口
**复现操作步骤:**
服务端测试启动时插件出现问题，线程被阻塞，玩家无法登陆，关闭时先点了关闭服务器，然后又点击了强行关闭服务器，再次启动时发现文件和端口被另一个服务端占用了，而且也关不掉
![image](https://user-images.githubusercontent.com/53056806/113583604-6cb6a980-965c-11eb-9b42-2ab32b0383e5.png)
这两句话是后台另一个服务端发出的

**Comment by Suwings** [comment]
使用的服务端是ChobitsMc？还是其他游戏服务端？如果只是正常关闭服务器不使用强制关闭功能的话，这种情况还会出现吗？

**Comment by TheSmileCat** [comment]
是同一个，而且因为启动了自动重启功能，反复启动并报错退出
这种情况没法正常关闭，因为服务器阻塞了，正常关闭没出现过（服务器正常运行的情况下）

**Comment by TheSmileCat** [comment]
我觉得对从其他途径启动的服务端有重连或者杀进程的功能就好了，就像这个失控的服务端
我没有服务器的桌面或者SSH等权限，遇到这个就举手无措了，上级运营也联系不上，没法重启服务器或关闭服务端

现在遇到一个问题就是服务端莫名其妙正常运行了（这个应该和控制面板没关系），但是控制面板（MCS管理器）进不去了，一直转圈圈，就像HTTP请求被挂起了一样，白屏进不去，也没报错404或者502或连接超时啥的，就一直转圈

**Comment by huangsijun17** [comment]
服务端失控是老问题了，但我几个月甚至几年难得见到一次……
除了手动强制结束进程，我也没有办法。
MCSM可以添加一个shell做webshell使用，打命令杀一下就行……

**Comment by TheSmileCat** [comment]
我没在MCSM控制面板找到能运行命令行的功能，内嵌个cmd/powershell应该也是可以的
你们不这么做或许是因为安全问题？

还有，**建议增加日志级别筛选的功能**
1. 日志等级 Warn Info Error 的简单筛选（复选框方式）
2. 允许用户使用自定义正则表达式匹配日志，以确定这“一条”日志是否在控制台显示（即某个插件中的（某个组件的）报错或某类消息直接忽略）（正则表达式，一行一个，允许反向匹配）

我这里的控制台一直一秒10几个报错，控制台清空的还贼快，啥也看不到，其他插件的消息也看不到，控制台指令返回的消息也看不到，玩家说了什么也看不到（我准备换掉这个插件了，腐竹这样用了好几个月，我都不知道他怎么能用到现在的）

**Comment by Suwings** [comment]
感谢你的建议。

关于 **建议增加日志级别筛选的功能** 在以后的版本会提供，不过目前可以通过支持搜索的编辑器来实现所需要的日志文本。

关于 **允许用户自由设置控制台显示文本的长度** 。如果你说的是控制台历史记录的话，在面板的 `property.js` 中应该有相关配置，如果你是说网页控制台到达指定长度会自动清空的功能，暂时无配置文件可直接修改，只能修改 Javascript 代码实现功能。

关于 **默认自动滚动到日志末尾**。 默认情况下会滚到日志末尾，只不过可能在短时间内输出了大量的日志，会导致来不及滚动而失灵，这个情况有时候确实发生过。

**Comment by stydxm** [comment]
是套了MCDR吗？我也有这个问题，不是面板的问题，问题在MCDR，它线程会堵塞而且性能似乎不太好，所以我服一开世吞MCDR插件就全部失效，后台输指令MCDR也没法传递给服务器，面板结束进程只能结束MCDR的进程，但服务器本身的进程还在运行

**Comment by AlexanderMC8533** [comment]
你好！
针对服务端失控的解决方案是，关闭崩溃重启，强制结束服务器进程
如果无法解决您的问题，大概路上是因为预留给系统的剩余内存不足，请扩充内存容量

**Comment by AlexanderMC8533** [comment]
> 我觉得对从其他途径启动的服务端有重连或者杀进程的功能就好了，就像这个失控的服务端
> 我没有服务器的桌面或者SSH等权限，遇到这个就举手无措了，上级运营也联系不上，没法重启服务器或关闭服务端
> 
> 现在遇到一个问题就是服务端莫名其妙正常运行了（这个应该和控制面板没关系），但是控制面板（MCS管理器）进不去了，一直转圈圈，就像HTTP请求被挂起了一样，白屏进不去，也没报错404或者502或连接超时啥的，就一直转圈

服务器占用接近满

**Comment by TheSmileCat** [comment]
麻烦你们了，确实有服务器内存严重不足的问题，之前32/32GB占满，前段时间我们服务器升级到了64GB，内存空出来了，也没出什么奇怪BUG
4月5号……这个Issues挺早的了，我现在已经接近服主权限了，老服主已经全国云游去了（doge），远程桌面等权限很早之前就拿到了
有些其他的建议，有空开个新Issues写（

**Comment by AlexanderMC8533** [comment]
欢迎继续提交*问题*，我会持续关注这个板块，为故障服务器提供应急性解决方案



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(周四) 中午11:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] 服务端失控在后台运行无法关闭 (#403)




 
麻烦你们了，确实有服务器内存严重不足的问题，之前32/32GB占满，前段时间我们服务器升级到了64GB，内存空出来了，也没出什么奇怪BUG
 4月5号……这个Issues挺早的了，我现在已经接近服主权限了，老服主已经全国云游去了（doge），远程桌面等权限很早之前就拿到了
 有些其他的建议，有空开个新Issues写（
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kiritow** [comment]
Linux里如果启动命令是一个bash脚本的话, 被kill的时候有可能出现java进程逃逸的情况. 大概是node的`SIGKILL`只关闭了bash但不会关闭bash的子进程.

**Comment by xrh0905** [comment]
我的解决方法是在spigot.yml中restart-on-crash设置为false

**Comment by huangsijun17** [comment]
> 麻烦你们了，确实有服务器内存严重不足的问题，之前32/32GB占满，前段时间我们服务器升级到了64GB，内存空出来了，也没出什么奇怪BUG
> 4月5号……这个Issues挺早的了，我现在已经接近服主权限了，老服主已经全国云游去了（doge），远程桌面等权限很早之前就拿到了
> 有些其他的建议，有空开个新Issues写（

在内存占满/硬盘占满时很容易会有这种问题，平时基本没有。
