### ISSUE TITLE
IPV6无法被访问

### ISSUE THREAD

**Issue by ghostzwc** [Suwings/MCSManager#404]
因为使用IPV6就不用端口映射。我就用IPV6开服。
后来觉得ssh开服控制有点难受就用MCSManager开服
服务器打开后我的世界客户端只可以用IPV4访问游戏服务器
通过IPV6可以看MCSManager的面板但是无法通过IPV6链接游戏

**Comment by ghostzwc** [comment]
操作系统
系统与平台: Linux arm64 ubuntu 5.8.0-1019-raspi
版本
发行版本: 8.6.20 发行版本

发行编号: No.20210313-01

**Comment by Suwings** [comment]
可以用 ipv6 访问到 MCSManager 面板？那不就说明在面板这方面一切是正常的吗？至于无法通过 ipv6 访问游戏，我想这个并不是面板的问题，而是你游戏服务端的配置文件或者它本身就不支持。

谢谢反馈。

**Comment by ghostzwc** [comment]
我啥也不改直接用命令 java -jar 1.16.5.jar 开启的服务器就可以使用IPV6
原封不动放到MCSM里用MCSM打开就无法用IPV6访问游戏
还有创建Docker镜像。我老是失败。

**Comment by Suwings** [comment]
那你在面板的服务器参数界面设置自定义命令，自定义命令为 ` java -jar 1.16.5.jar ` ，再进行尝试，这样面板就会执行一模一样的命令，应该就不会有问题。

**Comment by ghostzwc** [comment]
我又尝试了一样还是那样。
有点神奇的是它直接显示无法连接到服务器
如果我随便输入一个IP他会等半天再无法连接到服务器

**Comment by ghostzwc** [comment]
难道是MCSM用了别的用户？导致java无法使用IPV6?

**Comment by ghostzwc** [comment]
我尝试一下JAVA8LIB\JAVA8-LINUX-ARM64\bin\java

**Comment by ghostzwc** [comment]
emm
直接就无法启动

**Comment by ghostzwc** [comment]
/home/ubuntu/server/server_core/MYSERVER/JAVA8LIB/JAVA8-LINUX-ARM64/bin/java 这样也启动不了

**Comment by Suwings** [comment]
那这样尝试，新建一个 start,sh 文件，将你的jar启动命令写入，再回到面板的参数界面，设置启动命令为 sh ./start.sh ，再上传这个sh文件到jar的同目录中。开服。

**Comment by ghostzwc** [comment]
好想法

**Comment by ghostzwc** [comment]
我试试

**Comment by ghostzwc** [comment]
Error: 进程启动时异常:TypeError:The argument 'file' cannot be empty. Received ''

**Comment by ghostzwc** [comment]
什么鬼

**Comment by ghostzwc** [comment]
我再改一下

**Comment by huangsijun17** [comment]
我插一个问题，有没有使用SE-Linux或者Docker？

**Comment by ghostzwc** [comment]
sudo bash ./start.sh

**Comment by ghostzwc** [comment]
Docker 我老是构建失败

**Comment by ghostzwc** [comment]
666了 用sudo bash ./start.sh后无法强制关闭

**Comment by huangsijun17** [comment]
另外，github不是聊天平台，请善用“编辑”等功能优化版面，或者前往QQ群聊天咨询。

**Comment by Suwings** [comment]
我觉得依照你这个发表速度，此“贴”将成为交流数量最多的。

**Comment by ghostzwc** [comment]
。。。。。

**Comment by ghostzwc** [comment]
应该不会影响什么的吧

**Comment by Suwings** [comment]
检查一下命令是否配置正确，SE-Linux 是否关闭，防火墙等配置，实在不行你还是用命令行来进行开服吧，或者在面板中使用 bash 自定义命令启动终端，在终端中手动写 java -jar xxx.jar 命令来进行开服。

另外，你回复的话字数可以几个情况一起写进来，不用一次写一句话。

**Comment by ghostzwc** [comment]
天啊用sudo 权限后面板只能看命令行输入命令不起效果

**Comment by huangsijun17** [comment]
> 666了 用sudo bash ./start.sh后无法强制关闭

没事别乱用sudo命令。
我们这跑MCSM，除了安装node、管理防火墙等阶段，我全程使用普通管理员用户；实际服务运行时使用的都是无管理员权限的一般用户。

再者，即使需要尝试使用root权限，也应当是直接使用root用户开启MCSM，即使用`sudo npm start`命令，而非在开服命令/脚本中随意使用`sudo`。

**Comment by Suwings** [comment]
你还是用命令行开服吧，可能的确是面板的问题导致的，但是我也不清楚原因是什么。

**Comment by ghostzwc** [comment]
奥

**Comment by huangsijun17** [comment]
> 天啊用sudo 权限后面板只能看命令行输入命令不起效果

你运行MCSM的是一般管理员，而运行Java进程的却是root，怎么可能能对其管理？命令当然下不下去啦~~~

您可以尝试使用kill命令或者直接重启Linux系统。另外，鉴于您对于Linux系统的了解程度，如果您切实有使用MCSM的寻求，可以考虑使用Windows系统开服。

**Comment by ghostzwc** [comment]
我为了低功耗使用的是树莓派4b

**Comment by ghostzwc** [comment]
树莓派使用windows对硬盘有很大的要求且没有wifi驱动

**Comment by ghostzwc** [comment]
然而树莓派用linux一张内存卡就可以解决且除了加载世界慢点其他都挺好

**Comment by Suwings** [comment]
好吧，你先暂时性用命令行开服吧，面板的话如果不是非得需要 ipv6 的话，可以正常使用的，这个看你怎么选择了。

此问题关闭。

**Comment by ghostzwc** [comment]
[MYSERVER@app] 
[控制面板]: 暂无任何历史记录.
[MCSMANAGER] -------------------------------------------------------------- 
[MCSMANAGER] [ 2021/3/5 20:12:42 ]: 服务端 MYSERVER 执行开启命令. 
[MCSMANAGER] -------------------------------------------------------------- 
./start.sh: 行 1: /home/ubuntu/MCSManager/server/server_core/MYSERVER/JAVA8LIB/JAVA8-LINUX-ARM64/bin/java: 权限不够
[MCSMANAGER] -------------------------------------------------------------- 
[MCSMANAGER] [ 2021/3/5 20:12:42 ]: 服务端 MYSERVER 关闭. 
[MCSMANAGER] --------------------------------------------------------------

**Comment by ghostzwc** [comment]
我在这里学的
https://zhuanlan.zhihu.com/p/266625890

**Comment by ghostzwc** [comment]
难道是自启的问题？

**Comment by ghostzwc** [comment]
设置后台运行和开机自启动
创建并编辑文件sudo nano /lib/systemd/system/mcsm.service，输入以下内容

[Unit]
Description=MCSManager

[Service]
ExecStart=/usr/bin/node /opt/MCSManager/app.js
Restart=always
Environment=PATH=/usr/bin:/usr/local/bin:/usr/local/node/bin
Environment=NODE_ENV=production
WorkingDirectory=/opt/MCSManager/

[Install]
WantedBy=multi-user.target
创建完成后，即可使用 systemctl 管理面板启动与关闭。

**Comment by Suwings** [comment]
有问题请加群，由于每发一段交流对话就会有些人收到通知，影响其他用户，所以此 issue 锁定。
