### ISSUE TITLE
服务无法安装以及启动

### ISSUE THREAD

**Issue by EITSxiaozhai** [Suwings/MCSManager#405]
**系统环境:**
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-140-generic aarch64)

**面板版本:**
 github最新
**Node 版本:**
未知
**出现概率:**
每次
**出现的问题 (BUG):**
**安装时的问题 (BUG):**
--------------- Node Version ---------------
bash: line 34: /usr/bin/node: cannot execute binary file: Exec format error
/usr/bin/node: 1: /usr/bin/node: ELF: not found
/usr/bin/node: 12: /usr/bin/node: Syntax error: word unexpected (expecting ")")
 node: 
 npm: 
--------------- Node Version ---------------
Installing git...
bash: line 44: yum: command not found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.17.1-1ubuntu0.8).
The following packages were automatically installed and are no longer required:
  libdrm-etnaviv1 libllvm8 linux-headers-4.15.0-55 linux-headers-4.15.0-55-generic linux-image-4.15.0-55-generic linux-modules-4.15.0-55-generic
  linux-modules-extra-4.15.0-55-generic
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
bash: line 46: pacman: command not found
complete.
Download MCSManager...
fatal: destination path 'MCSManager' already exists and is not an empty directory.
complete.
Start to install dependent libraries...
/usr/bin/node: 1: /usr/bin/node: ELF: not found
**启动时报错**
root@ecs-kc1-large-2-linux-20210409083932:~/129# systemctl status mcsm
● mcsm.service - MCSManager
   Loaded: loaded (/lib/systemd/system/mcsm.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2021-04-09 09:09:00 CST; 29min ago
 Main PID: 1821 (code=exited, status=203/EXEC)

Apr 09 09:09:00 ecs-kc1-large-2-linux-20210409083932 systemd[1]: mcsm.service: Main process exited, code=exited, status=203/EXEC
Apr 09 09:09:00 ecs-kc1-large-2-linux-20210409083932 systemd[1]: mcsm.service: Failed with result 'exit-code'.
Apr 09 09:09:00 ecs-kc1-large-2-linux-20210409083932 systemd[1]: mcsm.service: Service hold-off time over, scheduling restart.
Apr 09 09:09:00 ecs-kc1-large-2-linux-20210409083932 systemd[1]: mcsm.service: Scheduled restart job, restart counter is at 5.
Apr 09 09:09:00 ecs-kc1-large-2-linux-20210409083932 systemd[1]: Stopped MCSManager.
Apr 09 09:09:00 ecs-kc1-large-2-linux-20210409083932 systemd[1]: mcsm.service: Start request repeated too quickly.
Apr 09 09:09:00 ecs-kc1-large-2-linux-20210409083932 systemd[1]: mcsm.service: Failed with result 'exit-cod

**复现操作步骤:**
无法安装，无法启用
即使进入安装文件夹下，使用npm i 也会报错

**Comment by Suwings** [comment]
刚刚你在另外一个 issue 发表问题，我把另外一个关闭了，有情况可以在这里继续讨论。

根据 `bash: line 34: /usr/bin/node: cannot execute binary file: Exec format error` 相比是 node 环境安装时有错误导致安装失败，一键安装脚本应该会自动化安装好 node 环境才对，但是看起来因为某些因素此环境没有成功安装。

建议尝试手动安装方案：
https://github.com/Suwings/MCSManager/wiki/Linux-%E4%B8%8B%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8%E8%AF%A6%E8%A7%A3

> 如果依然出现问题，可以自行搜索Linux安装nodejs环境，安装最新稳定版即可。
