### ISSUE TITLE
对多个服务器的支持

### ISSUE THREAD

**Issue by msj20080623** [Suwings/MCSManager#406]
希望增加个对多个服务器的支持：
有a，b，c，d四个服务器，开启服务器找到占用率最低的开

**Comment by KagurazakaNyaa** [comment]
负载均衡的话，作者可以考虑用docker的swarm部署来实现，或者尝试支持k8s？

**Comment by Suwings** [comment]
目前版本的面板并不支持你所描述的功能，还请期待以后的版本。
