### ISSUE TITLE
如何获取监听服务器控制台 websocket 路由中发送的 Token

### ISSUE THREAD

**Issue by GreyElaina** [Suwings/MCSManager#408]

**Comment by GreyElaina** [comment]
找到了, 就是...嗯, `_LoveYouMaster_Time`, 这个字段好奇怪...

**Comment by Suwings** [comment]
这是以前特意写的，算是个小彩蛋。

**Comment by GreyElaina** [comment]
> 这是以前特意写的，算是个小彩蛋。

现在遇到了新问题: 当我连接上, 并发送了心跳包后, 客户端会因为 1005 code 断开....

**Comment by Suwings** [comment]
`1005 code` ？这似乎不是面板的错误代码，我不曾记得有过什么 1005 错误代码，你是在什么情况下断开的，又是哪里的错误信息？理论上心跳包发包速度要稳定持续发送，节奏也得快一点点。

**Comment by GreyElaina** [comment]
已经解决了 我给sessionid去掉了url编码就好了
我正在写一个类似 mcdaemon 的程序 比起直接操作tty 我认为使用类似 mcsm 这样 ws 协议的实现更好点

感谢你的跟进

**Comment by GreyElaina** [comment]
关于心跳包：我使用和 mcsm 默认的delay 即10s
