### ISSUE TITLE
Win系统下上传大小超过1M的文件会失败

### ISSUE THREAD

**Issue by disymayufei** [Suwings/MCSManager#409]
系统环境:Windows 10

面板版本:8.6.18 发行版本

出现概率:100%

出现的问题 (BUG):上传小文件的时候正常，但文件大小超过1M后即会提示：上传文件失败：undefined

复现操作步骤:以任意账号（普通/管理员均可）上传大小超过1M的文件

**Comment by Suwings** [comment]
在 Windows 10 1909 版本， MCSManager 8.6.18 版本进行复现操作步骤，分别上传了不同大小文件进行测试，均未发现你所描述的问题。

唯一有可能的不同因素是我这里是本地搭建本地上传。所以可能并不是面板所引起的问题，建议你检查一下防火墙的设置以及文件目录权限问题。谢谢你的反馈。

**Comment by huangsijun17** [comment]
是否使用了反代？
尝试在nginx配置文件中尝试添加参数：
client_max_body_size 1000m;
参考：
#260 (comment)

**Comment by disymayufei** [comment]
感谢各位，经上面huangsijun17的提醒，发现并非MCSM本身的问题，而是我设置反代时允许的bodysize过小导致的，目前已经解决
