### ISSUE TITLE
命令控制台亂碼

### ISSUE THREAD

**Issue by BearLeon** [Suwings/MCSManager#41]
繁體中文在命令控制台顯示會亂碼
我改過輸文字編碼很多種 他還是會亂碼

**Comment by Suwings** [comment]
能否提供你的系统具体编码，Minecraft服务端 和 操作系统吗？
你可能可以试试 big5 编码？
你说的`命令控制台`是指 终端 还是指 网页的命令控制台？
网页本身如果不乱码的话，解决应该还是很好解决的。

如果服务端版本大于 1.9 可以尝试输入编码为 utf8 输出编码为 big5 or utf8 。

能否多提供一些信息呢？ @BearLeon

**Comment by BearLeon** [comment]
經過剛剛嘗試 big5 utf8  等等的編碼都還是一樣
操錯系統WIN10 家用版
伺服器 spigot-1.12.2
我不知道如何查看系統編碼
我說的是網頁的命令控制台 他會繁體中文會顯示亂碼
向下面這樣
�бNUseKycHealthSetting� ]�w��0�H�קK�o�Ͱ��D

**Comment by BearLeon** [comment]
另外 我剛剛發現清屏時候 在打指令他會顯示
[ 控制面板 ]: 控制面板內容已經清空，您所查看的歷史記錄位置依然保留。
[ 控制面板 ]: 如果您在此頁面遇到卡頓，內存高等現象，請使用此功能來優化。[  18:02:49  INFO ]: [ Server ] 0 
他第一條指令不會換行

**Comment by Suwings** [comment]
感謝妳的詳細信息反饋，看起來在繁體中文上仍然有點問題，我們會過段時間檢查，來讓繁體中文正確的編碼與顯示。

**Comment by BearLeon** [comment]
感恩
