### ISSUE TITLE
Ubuntu运行基岩服务器的问题

### ISSUE THREAD

**Issue by HixGitHub** [Suwings/MCSManager#410]
**系统环境:**
Ubuntu-18.04-x64
**面板版本:**
8.6.20
**Node 版本:**
12.16.1
**出现概率:**
可复现
**出现的问题 (BUG):**
按wiki上Linux运行基岩版本的教程，开服失败。
提示：“服务端进程启动失败，建议检查启动命令与参数是否正确”

**Comment by huangsijun17** [comment]
启动命令问题。
基岩版应该是要自定义命令启动的。你启动命令写的啥？

**Comment by HixGitHub** [comment]
> 启动命令问题。
> 基岩版应该是要自定义命令启动的。你启动命令写的啥？

自定义命令是 `sh ./start.sh`

start.sh里面的内容是 `LD_LIBRARY_PATH=. ./bedrock_server`

**Comment by huangsijun17** [comment]
目录有没有指定错误？
把自定义命令改成`bash`试试看，打个`pwd`和`ls`看一下。

**Comment by HixGitHub** [comment]
> 目录有没有指定错误？
> 把自定义命令改成`bash`试试看，打个`pwd`和`ls`看一下。

pwd输出  `/opt/MCSManager/server/server_core/Bedrock`
ls输出 `bedrock_server                development_resource_packs  server.properties
bedrock_server_how_to.html    development_skin_packs      start.sh
bedrock_server_symbols.debug  Makefile                    structures
behavior_packs                minecraftpe                 treatments
cmake_install.cmake           permissions.json            valid_known_packs.json
Dedicated_Server.txt          premium_cache               whitelist.json
definitions                   release-notes.txt           worlds
development_behavior_packs    resource_packs              world_templates`

**Comment by huangsijun17** [comment]
`bash ./start.sh`试过没有？

**Comment by HixGitHub** [comment]
> `bash ./start.sh`试过没有？

试过了，返回与上面相同的错误。

测试了 start.sh 脚本，在终端上是可以正常运行的。

**Comment by echoker** [comment]
检查start.sh和bedrock_server的权限
设置为777试试
其实`./bedrock_server`就可以运行服务器

**Comment by HixGitHub** [comment]
> 检查start.sh和bedrock_server的权限
> 设置为777试试
> 其实`./bedrock_server`就可以运行服务器

自定义参数改为`./bedrock_server` 时，mcsm抛出 Error: 进程启动时异常:TypeError:The argument file" cannot be empty Received'

设置为这两个文件权限为777也不行，还是报错： `服务端进程启动失败，建议检查启动命令与参数是否正确`

**Comment by Suwings** [comment]
自定义命令写 bash，启动Linux终端，在终端里面使用 ./bedrock_server 或者你原先使用的命令进行开服。估计可以解决这个问题。

**Comment by HixGitHub** [comment]
> 自定义命令写 bash，启动Linux终端，在终端里面使用 ./bedrock_server 或者你原先使用的命令进行开服。估计可以解决这个问题。

终端可以开服，就是在mcsm里开不了服…

**Comment by echoker** [comment]
> > 自定义命令写 bash，启动Linux终端，在终端里面使用 ./bedrock_server 或者你原先使用的命令进行开服。估计可以解决这个问题。
> 
> 终端可以开服，就是在mcsm里开不了服…

意思是说，MCSM的自定义命令填写`bash`，这样你就可以直接在MCSM的终端里输入命令了；然后执行`./bedrock_server`试试

**Comment by HixGitHub** [comment]
> > > 自定义命令写 bash，启动Linux终端，在终端里面使用 ./bedrock_server 或者你原先使用的命令进行开服。估计可以解决这个问题。
> > 
> > 终端可以开服，就是在mcsm里开不了服…
> 
> 意思是说，MCSM的自定义命令填写`bash`，这样你就可以直接在MCSM的终端里输入命令了；然后执行`./bedrock_server`试试

这样还是不行
![Screenshot](https://user-images.githubusercontent.com/31057166/117559179-d4c23a80-b0b5-11eb-8c8c-40facd226e00.jpg)

**Comment by huangsijun17** [comment]
目录的权限问题？

**Comment by HixGitHub** [comment]
> 目录的权限问题？

chmod -R 777 /opt/MCSManager/server/server_core/ 执行后还是一样

**Comment by huangsijun17** [comment]
> > 目录的权限问题？
> 
> chmod -R 777 /opt/MCSManager/server/server_core/ 执行后还是一样

使用的哪个用户？归属者改了吗？

**Comment by Dep0s1t** [comment]
确实有这个问题。我个人觉得这就是面板问题，手动启动服务器没有任何问题的。

**Comment by yzy613** [comment]
我开基岩服的自定义是 startup.sh 脚本的绝对路径
```bash
/opt/mc-bedrock/mainWorld/startup.sh
```

**Comment by Zhusiyuan354** [comment]
不是 LD_LIBRARY_PATH=./bedrock_server?

**Comment by thksdhr** [comment]
尝试用./start.sh启动启动文件
