### ISSUE TITLE
大佬问下关于docker的

### ISSUE THREAD

**Issue by kkh66** [Suwings/MCSManager#411]
**内容:**
想问下，有没有办法利用别人的docker来开服比如类似这种itzg/minecraft-bedrock-server（这个是已经配置好了的只要命令就可以开）。我自己有尝试下其他方法把命令放在自定义命令可以开到可是服务器不会显示打开了。

**Comment by Suwings** [comment]
服务器的参数设置，右下角Docker设置里面，有个Docker 镜像名，把镜像名写成 `itzg/minecraft-bedrock-server` 就行。不过前提是你要先用 Docker 提前下载好这个镜像。

**Comment by kkh66** [comment]
> 服务器的参数设置，右下角Docker设置里面，有个Docker 镜像名，把镜像名写成 `itzg/minecraft-bedrock-server` 就行。不过前提是你要先用 Docker 提前下载好这个镜像。

我试了下，可是他一直显示未设置服务端核心文件,无法启动服务器。

**Comment by kkh66** [comment]
> 服务器的参数设置，右下角Docker设置里面，有个Docker 镜像名，把镜像名写成 `itzg/minecraft-bedrock-server` 就行。不过前提是你要先用 Docker 提前下载好这个镜像。

还有就是这个docker的文件位置是放在/data不是/mcsd。

**Comment by Suwings** [comment]
那就在服务器参数里面写自定义启动命令，cd /data/ && <你的服务端启动命令>，或者直接写 bash 启动终端，在终端里面手动输入启动命令启动服务器。

**Comment by kkh66** [comment]
> 那就在服务器参数里面写自定义启动命令，cd /data/ && <你的服务端启动命令>，或者直接写 bash 启动终端，在终端里面手动输入启动命令启动服务器。

老哥我尝试下就是run的时候把位置-v /data的位置放去servercore/服务器名字里面然后run了下显示这个WARNING: Error loading config file: .dockercfg: $HOME is not defined

**Comment by kkh66** [comment]
docker是run起来了。可是mcsm的服务器倒是显示还没run只是显示关闭因为这个原因

**Comment by kkh66** [comment]
我大概知道什么原因了查了下好像是权限不足够

**Comment by kkh66** [comment]
我的这个面版应该是在root权限的可是不知道怎么的显示那个错误

**Comment by kkh66** [comment]
解决了

**Comment by kkh66** [comment]
> 那就在服务器参数里面写自定义启动命令，cd /data/ && <你的服务端启动命令>，或者直接写 bash 启动终端，在终端里面手动输入启动命令启动服务器。

老哥关闭问题解决了

**Comment by kkh66** [comment]
> 那就在服务器参数里面写自定义启动命令，cd /data/ && <你的服务端启动命令>，或者直接写 bash 启动终端，在终端里面手动输入启动命令启动服务器。

老哥，问个其他问题？有没有办法改docker启动命令就是等价启动命令。改去我要的参数，我自己有试下去Mcserver.js试下改了后创建新的服务器时有显示我改的内容可是创建时docker时还是没有用到我改的东西.希望老哥有空帮我解答下

**Comment by Suwings** [comment]
没懂你的意思，docker启动在文件中有一个专门都方法，你自己仔细看看吧。

**Comment by kkh66** [comment]
> 没懂你的意思，docker启动在文件中有一个专门都方法，你自己仔细看看吧。

就是我能不能自己修改docker启动命令。我自己在mcserver.js哪里看到docker run的命令有自己修改过可是还是不行。就想问下除了mcserver.js文件还有没有其他的要修改

**Comment by Suwings** [comment]
所有根启动进程相关的代码应该都在Mcserver.js和BaseMcserver.js中。

**Comment by kkh66** [comment]
> 所有根启动进程相关的代码应该都在Mcserver.js和BaseMcserver.js中。

我看了下下我只有在mcserver.js找到docker启动相关的命令
