### ISSUE TITLE
systemctl start mcsm无法启动mcsm

### ISSUE THREAD

**Issue by EzLittleChen** [Suwings/MCSManager#416]
树莓派安装了64位Ubuntu (时间未设置，所以命令中的时间并不准确)
首先一件安装了mcsm:
root@ubuntu:/# wget -qO- https://gitee.com/Suwingser/MCSManager-installer/raw/master/install.sh | bash

Start to install MCSManager...

--2021-05-12 04:41:56--  https://npm.taobao.org/mirrors/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz
Resolving npm.taobao.org (npm.taobao.org)... 114.55.80.225
Connecting to npm.taobao.org (npm.taobao.org)|114.55.80.225|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn.npm.taobao.org/dist/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz [following]
--2021-05-12 04:41:56--  https://cdn.npm.taobao.org/dist/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz
Resolving cdn.npm.taobao.org (cdn.npm.taobao.org)... 61.162.48.178, 27.221.120.240, 61.162.48.182, ...
Connecting to cdn.npm.taobao.org (cdn.npm.taobao.org)|61.162.48.178|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23005690 (22M) [application/octet-stream]
Saving to: ‘node-v12.16.1-linux-x64.tar.gz’

node-v12.16.1-linux-x64. 100%[==================================>]  21.94M  2.98MB/s    in 7.6s    

2021-05-12 04:42:14 (2.90 MB/s) - ‘node-v12.16.1-linux-x64.tar.gz’ saved [23005690/23005690]

Unpacking...
> tar -zxf node-v12.16.1-linux-x64.tar.gz
complete.
Linking...
> ln -s /opt/node-v12.16.1-linux-x64//node-v12.16.1-linux-x64/bin/node /usr/bin/node
> ln -s /opt/node-v12.16.1-linux-x64//node-v12.16.1-linux-x64/bin/node /usr/bin/node
complete.
--------------- Node Version ---------------
 node: v14.16.1
 npm: 7.12.1
--------------- Node Version ---------------
Installing git...
bash: line 44: yum: command not found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.25.1-1ubuntu3.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
bash: line 46: pacman: command not found
complete.
Download MCSManager...
Cloning into 'MCSManager'...
remote: Enumerating objects: 8502, done.
remote: Counting objects: 100% (8502/8502), done.
remote: Compressing objects: 100% (4146/4146), done.
remote: Total 8502 (delta 5294), reused 7145 (delta 4249), pack-reused 0
Receiving objects: 100% (8502/8502), 7.78 MiB | 706.00 KiB/s, done.
Resolving deltas: 100% (5294/5294), done.
complete.
Start to install dependent libraries...

added 166 packages in 8s
--------------- Complete ---------------
 Successfully installed!!!
 Directory: /opt/MCSManager/
--------------- Complete ---------------
Joining system service...
Create file: /usr/lib/systemd/system/mcsm.service
complete.

--------------- Quickstart ---------------
 Start： systemctl start mcsm
 Stop:   systemctl stop mcsm
 Status: systemctl status mcsm
--------------- Quickstart ---------------

root@ubuntu:/# 
root@ubuntu:/#
安装完成之后使用systemctl start mcsm命令无法启动，会出现下面的错误提示
root@ubuntu:/# systemctl start mcsm
root@ubuntu:/# systemctl status mcsm
● mcsm.service - MCSManager
     Loaded: loaded (/lib/systemd/system/mcsm.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-05-12 04:51:10 UTC; 6s ago
    Process: 5088 ExecStart=/usr/bin/node /opt/MCSManager/app.js (code=exited, status=203/EXEC)
   Main PID: 5088 (code=exited, status=203/EXEC)

May 12 04:51:10 ubuntu systemd[1]: mcsm.service: Scheduled restart job, restart counter is at 5.
May 12 04:51:10 ubuntu systemd[1]: Stopped MCSManager.
May 12 04:51:10 ubuntu systemd[1]: mcsm.service: Start request repeated too quickly.
May 12 04:51:10 ubuntu systemd[1]: mcsm.service: Failed with result 'exit-code'.
May 12 04:51:10 ubuntu systemd[1]: Failed to start MCSManager.
root@ubuntu:/# 
但是如果进入到文件目录下使用node app命令就可以正常运行
root@ubuntu:/# cd /opt/MCSManager/
root@ubuntu:/opt/MCSManager# node app
-----------------------------------------------------------------------------
______  _______________________  ___                                         
___   |/  /_  ____/_  ___/__   |/  /_____ _____________ _______ _____________
__  /|_/ /_  /    _____ \__  /|_/ /_  __ `/_  __ \  __ `/_  __ `/  _ \_  ___/
_  /  / / / /___  ____/ /_  /  / / / /_/ /_  / / / /_/ /_  /_/ //  __/  /    
/_/  /_/  \____/  /____/ /_/  /_/  \__,_/ /_/ /_/\__,_/ _\__, / \___//_/     
                                                        /____/             
 + Copyright 2021 Suwings All rights reserved.
----------------------------------------------------------------------------

[05/12 04:45:55] [INFO] 控制面板正在启动中... 
[05/12 04:45:55] [INFO] OnlineFs - 正在初始化文件管理路由与中间件 
[05/12 04:45:55] [INFO] Module - 正在初始化用户管理模块
[05/12 04:45:56] [INFO] ======================================================== 
[05/12 04:45:56] [INFO] 管理用户已初始化 | 创建账号: #master 密码 123456 
[05/12 04:45:56] [INFO] ======================================================== 
[05/12 04:45:56] [INFO] 请注意！凡是以 # 符号开头的用户名,均视为管理员账号 
[05/12 04:45:56] [INFO] Module - 正在初始化服务端管理模块
[05/12 04:45:56] [INFO] Module - 正在初始化计划任务模块
[05/12 04:45:56] [INFO] HTTP - HTTP 模块监听: [ http://127.0.0.1:23333 ]
[05/12 04:45:56] [INFO] 配置文件: property.js 文件
[05/12 04:45:56] [INFO] 文档参阅: https://github.com/suwings/mcsmanager
[05/12 04:45:56] [INFO] 控制面板已经启动
[05/12 04:46:24] [INFO] 用户 #master 正在尝试登录... 
[05/12 04:46:24] [INFO] [ Login ] 用户: #master 密匙正确 准许登录 
[05/12 04:46:24] [INFO] [ Token ] 用户  #master  请求更新令牌 | 准许 
[05/12 04:46:24] [INFO] [ WS CREATE ] 新的 Ws 创建 会话ID: [ _v2TRIVAZC1JzI3wVUEVxYMr6k2r-qgO ] 
[05/12 04:46:24] [INFO] [ WebSocket INIT ]  用户: #master 与服务器建立链接 
[05/12 04:46:48] [INFO] [Online Fs] 管理员 #master 访问服务端存放目录 
[05/12 04:47:18] [INFO] [ WebSocket CLOSE ] 用户 #master 已经断开链接 
^C[05/12 04:50:39] [INFO] PROCESS - 控制面板正在结束与回收资源,请稍等...
[05/12 04:50:42] [INFO] PROCESS - EXIT...
root@ubuntu:/opt/MCSManager#
这里system文件夹中的mcsm.server文件也没有修改，没发现问题:
root@ubuntu:/home/ubuntu# cat /lib/systemd/system/mcsm.service 
[Unit]
Description=MCSManager

[Service]
ExecStart=/usr/bin/node /opt/MCSManager/app.js
Restart=always
Environment=PATH=/usr/bin:/usr/local/bin:/usr/local/node/bin
Environment=NODE_ENV=production
WorkingDirectory=/opt/MCSManager/

[Install]
WantedBy=multi-user.target 
root@ubuntu:/home/ubuntu# 
最后修改了时间之后还是不能用systemctl start mcsm命令启动，说明不是时间的问题(在错误的时间情况下node app可以正常运行)，想请问怎么能解决不能使用systemctl start mcsm命令的问题

**Comment by huangsijun17** [comment]
所以，啥情况？
敲错命令了？
