### ISSUE TITLE
systemctl start mcsm无法启动mcsm

### ISSUE THREAD

**Issue by EzLittleChen** [Suwings/MCSManager#417]
4核8G树莓派安装了64位Ubuntu (时间未设置，所以命令中的时间并不准确)

首先一键安装了mcsm:

>root@ubuntu:/# `wget -qO- https://gitee.com/Suwingser/MCSManager-installer/raw/master/install.sh | bash`

>Start to install MCSManager...

>--2021-05-12 04:41:56--  https://npm.taobao.org/mirrors/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz
>Resolving npm.taobao.org (npm.taobao.org)... 114.55.80.225
>Connecting to npm.taobao.org (npm.taobao.org)|114.55.80.225|:443... connected.
>HTTP request sent, awaiting response... 302 Found
>Location: https://cdn.npm.taobao.org/dist/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz [following]
>--2021-05-12 04:41:56--  https://cdn.npm.taobao.org/dist/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz
>Resolving cdn.npm.taobao.org (cdn.npm.taobao.org)... 61.162.48.178, 27.221.120.240, 61.162.48.182, ...
>Connecting to cdn.npm.taobao.org (cdn.npm.taobao.org)|61.162.48.178|:443... connected.
>HTTP request sent, awaiting response... 200 OK
>Length: 23005690 (22M) [application/octet-stream]
>Saving to: ‘node-v12.16.1-linux-x64.tar.gz

>node-v12.16.1-linux-x64. 100%[==================================>]  21.94M  2.98MB/s    in 7.6s    

>2021-05-12 04:42:14 (2.90 MB/s) - ‘node-v12.16.1-linux-x64.tar.gz’ saved [23005690/23005690]

>Unpacking...
> tar -zxf node-v12.16.1-linux-x64.tar.gz
>complete.
>Linking...
> ln -s /opt/node-v12.16.1-linux-x64//node-v12.16.1-linux-x64/bin/node /usr/bin/node
> ln -s /opt/node-v12.16.1-linux-x64//node-v12.16.1-linux-x64/bin/node /usr/bin/node
>complete.
>--------------- Node Version ---------------
> node: v14.16.1
> npm: 7.12.1
>--------------- Node Version ---------------
>Installing git...
>bash: line 44: yum: command not found
>Reading package lists... Done
>Building dependency tree       
>Reading state information... Done
>git is already the newest version (1:2.25.1-1ubuntu3.1).
>0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
>bash: line 46: pacman: command not found
>complete.
>Download MCSManager...
>Cloning into 'MCSManager'...
>remote: Enumerating objects: 8502, done.
>remote: Counting objects: 100% (8502/8502), done.
>remote: Compressing objects: 100% (4146/4146), done.
>remote: Total 8502 (delta 5294), reused 7145 (delta 4249), pack-reused 0
>Receiving objects: 100% (8502/8502), 7.78 MiB | 706.00 KiB/s, done.
>Resolving deltas: 100% (5294/5294), done.
>complete.
>Start to install dependent libraries...

>added 166 packages in 8s
>--------------- Complete ---------------
> Successfully installed!!!
> Directory: /opt/MCSManager/
>--------------- Complete ---------------
>Joining system service...
>Create file: /usr/lib/systemd/system/mcsm.service
>complete.

>--------------- Quickstart ---------------
> Start： systemctl start mcsm
> Stop:   systemctl stop mcsm
> Status: systemctl status mcsm
>--------------- Quickstart ---------------

>root@ubuntu:/# 
>root@ubuntu:/#
安装完成之后使用`systemctl start mcsm`命令无法启动，会出现下面的错误提示
>root@ubuntu:/# `systemctl start mcsm`
>root@ubuntu:/# `systemctl status mcsm`
>● mcsm.service - MCSManager
>     Loaded: loaded (/lib/systemd/system/mcsm.service; disabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Wed 2021-05-12 04:51:10 UTC; 6s ago
>    Process: 5088 ExecStart=/usr/bin/node /opt/MCSManager/app.js (code=exited, status=203/EXEC)
>   Main PID: 5088 (code=exited, status=203/EXEC)

>May 12 04:51:10 ubuntu systemd[1]: mcsm.service: Scheduled restart job, restart counter is at 5.
>May 12 04:51:10 ubuntu systemd[1]: Stopped MCSManager.
>May 12 04:51:10 ubuntu systemd[1]: mcsm.service: Start request repeated too quickly.
>May 12 04:51:10 ubuntu systemd[1]: mcsm.service: Failed with result 'exit-code'.
>May 12 04:51:10 ubuntu systemd[1]: Failed to start MCSManager.
>root@ubuntu:/# 
但是如果进入到文件目录下使用`node app`命令就可以正常运行
>root@ubuntu:/# `cd /opt/MCSManager/`
>root@ubuntu:/opt/MCSManager# `node app`
>-----------------------------------------------------------------------------
>______  _______________________  ___                                         
>___   |/  /_  ____/_  ___/__   |/  /_____ _____________ _______ _____________
>__  /|_/ /_  /    _____ \__  /|_/ /_  __ `/_  __ \  __ `/_  __ `/  _ \_  ___/
>_  /  / / / /___  ____/ /_  /  / / / /_/ /_  / / / /_/ /_  /_/ //  __/  /    
>/_/  /_/  \____/  /____/ /_/  /_/  \__,_/ /_/ /_/\__,_/ _\__, / \___//_/     
>                                                      /____/             
> + Copyright 2021 Suwings All rights reserved.
>----------------------------------------------------------------------------

>[05/12 04:45:55] [INFO] 控制面板正在启动中... 
>[05/12 04:45:55] [INFO] OnlineFs - 正在初始化文件管理路由与中间件 
>[05/12 04:45:55] [INFO] Module - 正在初始化用户管理模块
>[05/12 04:45:56] [INFO] ======================================================== 
>[05/12 04:45:56] [INFO] 管理用户已初始化 | 创建账号: #master 密码 123456 
>[05/12 04:45:56] [INFO] ======================================================== 
>[05/12 04:45:56] [INFO] 请注意！凡是以 # 符号开头的用户名,均视为管理员账号 
>[05/12 04:45:56] [INFO] Module - 正在初始化服务端管理模块
>[05/12 04:45:56] [INFO] Module - 正在初始化计划任务模块
>[05/12 04:45:56] [INFO] HTTP - HTTP 模块监听: [ http://127.0.0.1:23333 ]
>[05/12 04:45:56] [INFO] 配置文件: property.js 文件
>[05/12 04:45:56] [INFO] 文档参阅: https://github.com/suwings/mcsmanager
>[05/12 04:45:56] [INFO] 控制面板已经启动
>[05/12 04:46:24] [INFO] 用户 #master 正在尝试登录... 
>[05/12 04:46:24] [INFO] [ Login ] 用户: #master 密匙正确 准许登录 
>[05/12 04:46:24] [INFO] [ Token ] 用户  #master  请求更新令牌 | 准许 
>[05/12 04:46:24] [INFO] [ WS CREATE ] 新的 Ws 创建 会话ID: [ _v2TRIVAZC1JzI3wVUEVxYMr6k2r-qgO ] 
>[05/12 04:46:24] [INFO] [ WebSocket INIT ]  用户: #master 与服务器建立链接 
>[05/12 04:46:48] [INFO] [Online Fs] 管理员 #master 访问服务端存放目录 
>[05/12 04:47:18] [INFO] [ WebSocket CLOSE ] 用户 #master 已经断开链接
>`^C`[05/12 04:50:39] [INFO] PROCESS - 控制面板正在结束与回收资源,请稍等...
>[05/12 04:50:42] [INFO] PROCESS - EXIT...
>root@ubuntu:/opt/MCSManager#
这里`system`文件夹中的`mcsm.server`文件也没有修改，没发现问题:
>root@ubuntu:/home/ubuntu# `cat /lib/systemd/system/mcsm.service `
>[Unit]
>Description=MCSManager

>[Service]
>ExecStart=/usr/bin/node /opt/MCSManager/app.js
>Restart=always
>Environment=PATH=/usr/bin:/usr/local/bin:/usr/local/node/bin
>Environment=NODE_ENV=production
>WorkingDirectory=/opt/MCSManager/

>[Install]
>WantedBy=multi-user.target 
>root@ubuntu:/home/ubuntu# 
最后修改了时间之后还是不能用`systemctl start mcsm`命令启动，说明不是时间的问题(在错误的时间情况下node app可以正常运行)，想请问怎么能解决不能使用`systemctl start mcsm`命令的问题

**Comment by huangsijun17** [comment]
看了一下，现在的报错是服务重启速度过快……
先关了自动重启，再看一下是什么错误信息吧。
注释掉/lib/systemd/system/mcsm.service的`Restart=always`，再开启试试看，看一下错误信息。

**Comment by huangsijun17** [comment]
还有，Github支持编辑issues，不用关了重新开始……

**Comment by EzLittleChen** [comment]
前面那个打错个字，想改来着，结果链接丢了，我又重发了一个，不知道之前那个能不能删除。
`root@ubuntu:/home/ubuntu# systemctl daemon-reload
root@ubuntu:/home/ubuntu# systemctl start mcsm
root@ubuntu:/home/ubuntu# systemctl status mcsm
● mcsm.service - MCSManager
     Loaded: loaded (/lib/systemd/system/mcsm.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-05-12 13:25:29 CST; 6s ago
    Process: 6024 ExecStart=/usr/bin/node /opt/MCSManager/app.js (code=exited, status=203/EXEC)
   Main PID: 6024 (code=exited, status=203/EXEC)

May 12 13:25:29 ubuntu systemd[1]: Started MCSManager.
May 12 13:25:29 ubuntu systemd[6024]: mcsm.service: Failed to execute command: Exec format error
May 12 13:25:29 ubuntu systemd[6024]: mcsm.service: Failed at step EXEC spawning /usr/bin/node: Exec format error
May 12 13:25:29 ubuntu systemd[1]: mcsm.service: Main process exited, code=exited, status=203/EXEC
May 12 13:25:29 ubuntu systemd[1]: mcsm.service: Failed with result 'exit-code'.`
注释掉之后是这样的错误，之前我加过启动时间3秒，但是还是有错误

**Comment by huangsijun17** [comment]
看了一下这个的错误，是报`/usr/bin/node`命令错误，ls看一下文件是否存在？
另外，再跑个`whereis node`，看一下node的文件位置吧。。

**Comment by EzLittleChen** [comment]
`root@ubuntu:/usr/bin# whereis node
node: /usr/bin/node /www/server/nvm/versions/node/v14.16.1/bin/node`

**Comment by huangsijun17** [comment]
等等，你的树莓派是什么构架的？AMD64？IA32？ARM64？

**Comment by EzLittleChen** [comment]
树莓派4B，ARM架构

**Comment by huangsijun17** [comment]
然后，脚本自动安装了一个X64的node，写死在服务里。
你bash运行时，通过$PATH变量调用了/www/server/nvm/versions/node/v14.16.1/bin/node的ARM版node。
告诉你怎么解决吧：
前面注释的内容可以去掉了。
/lib/systemd/system/mcsm.service里的
```
ExecStart=/usr/bin/node /opt/MCSManager/app.js
Environment=PATH=/usr/bin:/usr/local/bin:/usr/local/node/bin
```
改成
```
ExecStart=/www/server/nvm/versions/node/v14.16.1/bin/node /opt/MCSManager/app.js
Environment=PATH=/usr/bin:/usr/local/bin:/www/server/nvm/versions/node/v14.16.1/bin/
```
再去删掉：
`/opt/node-v12.16.1-linux-x64/`和`/usr/bin/node`

**Comment by EzLittleChen** [comment]
解决了解决了，真是太感谢了，谢谢谢谢！

**Comment by EzLittleChen** [comment]
那能不能把这个node安装成全局变量呢，或者再安装一个全局的node而不影响mcsm，因为可能需要有别的程序需要用node

**Comment by huangsijun17** [comment]
> 那能不能把这个node安装成全局变量呢，或者再安装一个全局的node而不影响mcsm，因为可能需要有别的程序需要用node

你的树莓派本来就安装了一个node，并且在变量$PATH下。

**Comment by EzLittleChen** [comment]
好的好的，问题解决了，感谢
