### ISSUE TITLE
README.md: FTP默认端口错误

### ISSUE THREAD

**Issue by ccinv** [Suwings/MCSManager#42]
10022 instead of 10021

**Comment by ccinv** [comment]
还有用户名格式没有在 README.md 里给出，需要自己看源码。
code as doc?

**Comment by Suwings** [comment]
Readme 端口说明已经修改成 20022，可能是当初更新时编写的时候疏忽。

用户名格式`用户名 [字母 数字 下划线] (6~18位)`，在你网页创建用户时那个编辑框上面写了用户名只能包含哪些字符。这一点不需要在 Readme.md 中写入，用户界面应该给与了正确的响应。

感谢反馈。

**Comment by ccinv** [comment]
指的是登陆 ftp 时的用户名，即`管理用户名.服务器名`，这个好像需要写出来一下吧。

**Comment by Suwings** [comment]
在网页控制面板，也就是显示CPU，内存统计图的那个页面。在其左下侧有一个`FTP 链接信息`。
信息中已经包含了“账号”，“端口”，“模式”，“密码” 的基本信息。

列如我的面板（我自己在使用的），就显示 #master.xxxx 账号为 FTP 登录名。

这个不需要写入 readme.md 。在其网页上已经显示了。

可能我理解错你的意思了，如果有其他问题欢迎继续指出！必当及时改正。

**Comment by ccinv** [comment]
是我没有注意到。谢谢!

**Comment by go626201** [comment]
不好意思 我刚刚重新安装的时候发现 FTP 账号没有跟着 普通用户的名字 而是 服务器的名字.服务器的名字。可以修复下马？

**Comment by Suwings** [comment]
感谢反馈！目前这个情况我还不清楚，过段时间，我们会检查这个情况！这也许是个bug，谢谢！
