### ISSUE TITLE
Wiki新增条目建议（Windows下安装为服务并配置IIS反向代理）

### ISSUE THREAD

**Issue by CreeperKong** [Suwings/MCSManager#421]
建议加入Wiki

**内容:**
# Windows下安装为服务
## 安装
1. 首先确保Node.js环境已经安装好，MCSManager已经能够以命令行程序形式启动。
2. 下载WinSW服务安装工具 [https://github.com/winsw/winsw/releases/latest](https://github.com/winsw/winsw/releases/latest)，开始安装服务前按照自己所下载版本安装 [.NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer) 或者 [Windows Desktop Runtime 5](https://dotnet.microsoft.com/download/dotnet/5.0) 。 
3. 将WinSW可执行文件命名为`mcsm.exe`，放入mcsm目录，并在该目录新建`mcsm.xml`写入以下内容
```
<service>
  <id>mcsm</id>
  <name>MCSManager (powered by WinSW)</name>
  <description>MCSManager Service</description>
  <executable>node</executable>
  <arguments>app.js</arguments>
</service>
```
4. 在该目录打开命令行，运行`mcsm.exe install mcsm.xml`，会提示服务安装成功。
5. 打开服务管理程序或者使用命令行对mcsm服务进行管理

## 进阶权限配置
- 安装完服务以后，服务默认以`SYSTEM`用户运行，包括MCSM及服务端都拥有系统最高权限，存在一定隐患，如果不想这样，可以新建一个Windows用户，把MCSM目录的所有权限给予该用户，若不希望这个用户登录图形界面，可以打开`计算机管理`将其从`Users`组中移除。完成后在服务管理程序中修改MCSM服务登录属性为该用户即可。

# IIS反向代理配置

## 安装 IIS
1. 打开服务器管理器，选择`添加角色和功能`（较旧版本的Windows Server操作系统需要在侧栏选择`角色`后，单击`添加角色`）。安装时需要在`应用程序开发`中选择`WebSocket 协议`。
2. 下载 [URL Rewrite](https://download.microsoft.com/download/1/2/8/128E2E22-C1B9-44A4-BE2A-5859ED1D4592/rewrite_amd64_en-US.msi) 和 [APR](https://go.microsoft.com/fwlink/?LinkID=615136) 插件并安装。

## 配置反向代理
1. 打开IIS管理器，添加合适的站点配置。
2. 在左侧栏选择当前服务器，双击`Application Request Routing Cache`，在右侧栏点击`Server Proxy Settings...`，勾选`Enable Proxy`然后应用。
3. 在网站根目录打开或者新建`web.config`，替换为以下内容：

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="mcsm-in">
                    <match url="^(.*)" />
                    <action type="Rewrite" url="http://localhost:23333/{R:1}" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

## HTTPS配置
如需HTTPS代理，打开mcsm目录的`public\common`，编辑`URL.js`文件

编辑前：
```
//Ws 默认协议
MCSERVER.WS_PROTOCOL = "ws://";
//HTTP 默认协议
MCSERVER.HTTP_PROTOCOL = "http://";
```
编辑后：
```
//Ws 默认协议
MCSERVER.WS_PROTOCOL = "wss://";
//HTTP 默认协议
MCSERVER.HTTP_PROTOCOL = "https://";
```

此时MCSM将无法通过未加密的http协议登录，请配置HSTS或重定向等以免发生问题。

**Comment by Suwings** [comment]
感谢提供文字教程，已添加到 wiki：https://github.com/Suwings/MCSManager/wiki/Windows-%E4%B8%8B%E5%AE%89%E8%A3%85%E4%B8%BA%E7%B3%BB%E7%BB%9F%E6%9C%8D%E5%8A%A1%E5%92%8C%E9%85%8D%E7%BD%AEIIS%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86

作者名已经附上，感谢。

**Comment by CreeperKong** [comment]
谢啦qwq
