### ISSUE TITLE
容器化运行的时区问题和镜像问题

### ISSUE THREAD

**Issue by KagurazakaNyaa** [Suwings/MCSManager#422]
**内容:**
在镜像的默认构建Dockerfile中，使用的基础镜像是已经被重定向到`openjdk`的`java`镜像，此镜像已经非常老旧，建议更换为`openjdk:11`或`openjdk:latest`
同时我注意到，现在的默认的容器化运行解决方案中，对于时区配置的方式是在构建镜像时指定其为`Asia/Shanghai`也就是CST时区写入到`/etc/timezone`中并重新配置`tzdata`包来使其生效的，但是在重新配置`tzdata`时，如果无用户输入，会把`/etc/timezone`的内容重置为UTC时区，所以我的建议是为何不把时区相关的配置直接由主机挂载而非在镜像中进行配置，可以使用如下两个挂载来使得时区和主机同步
`/etc/timezone:/etc/timezone:ro`
`/etc/localtime:/etc/localtime:ro`

**Comment by KagurazakaNyaa** [comment]
通过修改 https://github.com/Suwings/MCSManager/blob/6d9f8722d2169e4bfb63d895a4187a79eb9abdf5/core/Process/BaseMcserver.js#L144 可以很容易地实现此功能

**Comment by huangsijun17** [comment]
强烈反对改**默认**镜像。Java11仅支持MInecraft1.16的Forge和MOD，1.12.2和1.7.10都只能跑在Java8。过4~5年，没人用Java8再换11吧。
添加一个可选的Java11镜像选项倒是可以的。

**Comment by KagurazakaNyaa** [comment]
那至少改成`openjdk:8`这个镜像吧，至少openjdk是在持续更新的，`openjdk:8`这个镜像当前是514MB，更新于`2021-05-12 14:52:18`，而`java:latest`是643MB，更新于`2017-01-17 08:52:54`

**Comment by Suwings** [comment]
支持，周末完成这个建议，谢谢你的反馈。

**Comment by Suwings** [comment]
已修改镜像，但是暂未修改时区问题，待有时间做验证后再进行修复。

https://github.com/Suwings/MCSManager/commit/c3db0248ecbce4f4da2ee8f321fca095280f7b33

**Comment by KagurazakaNyaa** [comment]
> 已修改镜像，但是暂未修改时区问题，待有时间做验证后再进行修复。
> 
> [c3db024](https://github.com/Suwings/MCSManager/commit/c3db0248ecbce4f4da2ee8f321fca095280f7b33)

我进行了一个尝试，对于大多数Java的应用来说，指定环境变量`ENV TZ="Asia/Shanghai"`并保留`/etc/timezone`和`/etc/localetime`为UTC时区配置，在应用内仍然可以识别时区配置为CST

**Comment by huangsijun17** [comment]
Mojang 要求 Minecraft 从 21w19a 开始要求用 Java 16 运行，Docker 使用 openjdk:8 镜像来实现全版本兼容貌似也做不到了。看 Mojang 是否撤回这一更新，不然……

**Comment by KagurazakaNyaa** [comment]
> Mojang 要求 Minecraft 从 21w19a 开始要求用 Java 16 运行，Docker 使用 openjdk:8 镜像来实现全版本兼容貌似也做不到了。看 Mojang 是否撤回这一更新，不然……

可以考虑构建多个镜像，在启动时除了手工输入镜像名和留空使用默认镜像，给一个镜像的列表进行版本选取来提供对不同java版本的支持，如果这样处理，则构建镜像操作可以在初始化时自动进行

**Comment by huangsijun17** [comment]
> > Mojang 要求 Minecraft 从 21w19a 开始要求用 Java 16 运行，Docker 使用 openjdk:8 镜像来实现全版本兼容貌似也做不到了。看 Mojang 是否撤回这一更新，不然……
> 
> 可以考虑构建多个镜像，在启动时除了手工输入镜像名和留空使用默认镜像，给一个镜像的列表进行版本选取来提供对不同java版本的支持，如果这样处理，则构建镜像操作可以在初始化时自动进行

最主要的是现在的构架设计看没考虑给每个服务端独立的镜像设置，设置的存储、调用等等都要大改……

**Comment by KagurazakaNyaa** [comment]
> > > Mojang 要求 Minecraft 从 21w19a 开始要求用 Java 16 运行，Docker 使用 openjdk:8 镜像来实现全版本兼容貌似也做不到了。看 Mojang 是否撤回这一更新，不然……
> > 
> > 
> > 可以考虑构建多个镜像，在启动时除了手工输入镜像名和留空使用默认镜像，给一个镜像的列表进行版本选取来提供对不同java版本的支持，如果这样处理，则构建镜像操作可以在初始化时自动进行
> 
> 最主要的是现在的构架设计看没考虑给每个服务端独立的镜像设置，设置的存储、调用等等都要大改……

可以考虑用tag，这样要改的地方其实不多，因为实际上就是加个输入选项

**Comment by Suwings** [comment]
> > > Mojang 要求 Minecraft 从 21w19a 开始要求用 Java 16 运行，Docker 使用 openjdk:8 镜像来实现全版本兼容貌似也做不到了。看 Mojang 是否撤回这一更新，不然……
> > 
> > 
> > 可以考虑构建多个镜像，在启动时除了手工输入镜像名和留空使用默认镜像，给一个镜像的列表进行版本选取来提供对不同java版本的支持，如果这样处理，则构建镜像操作可以在初始化时自动进行
> 
> 最主要的是现在的构架设计看没考虑给每个服务端独立的镜像设置，设置的存储、调用等等都要大改……

面板现有服务端参数界面中Docker配置那里不是可以给每个服务端单独设置启动镜像名吗？用那个不同的镜像名就实现多个镜像使用了，镜像默认名字是 mcsd。
