### ISSUE TITLE
主题和翻译的文件无了

### ISSUE THREAD

**Issue by happyeggchen** [Suwings/MCSManager#424]
那个博客上的链接失效了

**Comment by Suwings** [comment]
官方并无任何翻译文件和博客，你所说那个博客是一个用户所建的博客，我估计应该是这个人 @LazyCreeper 或另有他人，你可以联系他获得更多的信息。

**Comment by huangsijun17** [comment]
我能说我都不知道你们说的是什么东西吗？

**Comment by happyeggchen** [comment]
主题lazyblog的回来了，翻译我也不奢求了就这样吧

**Comment by huangsijun17** [comment]
你应该去这里发发issues：
https://github.com/LazyCreeper/LazyCreeper.github.io/issues
