### ISSUE TITLE
普通用户无法修改密码

### ISSUE THREAD

**Issue by ghost** [Suwings/MCSManager#426]
普通用户无法修改密码

**Comment by Suwings** [comment]
十分抱歉，这么久才看见你这个，原本我以为这个功能不应该失效可能是其他因素导致便忽略了，是我的失误。

我刚刚复查此功能时，我发现此功能确实存在问题，出问题来自于FTP删除时顺便删除了直接MD5密码比较旧代码，从而导致所有非登录验证的密码校验全部失效，因此再导致用户无法验证自己的密码是否正确从而无法修改密码。

现在此问题已经修复，稍后将再继续发行版本彻底性修复此问题，感谢你的反馈！
