### ISSUE TITLE
使用自建docker镜像创建mcsd镜像的实例 命令控制台输出乱码

### ISSUE THREAD

**Issue by LierJeo** [Suwings/MCSManager#427]
**系统环境:**
主机deepin20
使用docker 拉取最新Ubuntu镜像

**面板版本:**
8.6.20 发行版本

**Node 版本:**
v12.16.1

**出现概率:**
关闭实例重启后依然出现

**出现的问题 (BUG):**
网页打开命令控制台，开启mc服务核心后日志打印出现乱码，但是模拟型终端没有乱码

命令控制台截取片段如下

Checking the installation, please wait.
Finished the install verification process !
Update in check...
If you don't want to enable update check, set check_update in mohist-config/mohist.yml to false
The latest Mohist version is 1.16.5-622 but you have 1.16.5-601. The latest version has been built on 2021-06-06 00:24:33. You should update to fix recent bugs !
[[36;1m20:21:48[39;0m [32;22mINFO[39;0m]: [39;0mModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.1.24, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui][39;0m
[[36;1m20:21:48[39;0m [32;22mINFO[39;0m]: [39;0mModLauncher 8.0.9+86+master.3cf110c starting: java version 11.0.11 by Ubuntu[39;0m
>WARNING: An illegal reflective access operation has occurred
>WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/mcsd/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar) to field java.util.jar.Manifest.jv
>WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
>WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
>WARNING: All illegal access operations will be denied in a future release
[[36;1m20:21:48[39;0m [32;22mINFO[39;0m]: [39;0mAdded Lets Encrypt root certificates as additional trust[39;0m
[[36;1m20:21:48[39;0m [32;22mINFO[39;0m]: [39;0mSpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/mcsd/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER[39;0m
[[36;1m20:21:49[39;0m [32;22mINFO[39;0m]: [39;0m[jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release[39;0m
[[36;1m20:21:49[39;0m [32;22mINFO[39;0m]: [39;0m[jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release[39;0m
[[36;1m20:21:49[39;0m [32;22mINFO[39;0m]: [39;0m[jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release[39;0m
[[36;1m20:21:49[39;0m [32;22mINFO[39;0m]: [39;0mLaunching target 'fmlserver' with arguments [--gameDir, ., nogui][39;0m
[[36;1m20:21:53[39;0m [32;22mINFO[39;0m]: [39;0mForge mod loading, version 36.1.24, for MC 1.16.5 with MCP 20210115.111550[39;0m
[[36;1m20:21:53[39;0m [32;22mINFO[39;0m]: [39;0mMinecraftForge v36.1.24 Initialized[39;0m
[[36;1m20:21:54[39;0m [32;22mINFO[39;0m]: [39;0mEventDispatcherRegistry initialized[39;0m

>.... [K[[36;1m20:22:05[39;0m [32;22mINFO[39;0m]: [39;0m[WorldEdit] Enabling WorldEdit v7.2.5+57d5ac9[39;0m
>.... [K[[36;1m20:22:05[39;0m [32;22mINFO[39;0m]: [39;0mWEPIF: Using the Bukkit Permissions API.[39;0m
>.... [K[[36;1m20:22:07[39;0m [32;22mINFO[39;0m]: [39;0mUsing com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R3 as the Bukkit adapter[39;0m
>.... [K[[36;1m20:22:08[39;0m [32;22mINFO[39;0m]: [39;0m[WorldEdit] ====================================================[39;0m
>.... [K[[36;1m20:22:08[39;0m [32;22mINFO[39;0m]: [39;0m[WorldEdit]  WorldEdit works better if you use Paper [39;0m
>.... [K[[36;1m20:22:08[39;0m [32;22mINFO[39;0m]: [39;0m[WorldEdit]  as your server software. [39;0m
>.... [K[[36;1m20:22:08[39;0m [32;22mINFO[39;0m]: [39;0m[WorldEdit]   [39;0m

**复现操作步骤:**
docker拉取最新ubuntu镜像，安装java11，导出成为新镜像后导入。
使用控制台创建虚拟镜像，dockerfile第一行改为 FROM [刚刚导入的新镜像]
cp一份已有的mcserver实例，配置改为使用docker容器
开启新实例，命令控制台出现乱码

**Comment by Suwings** [comment]
服务器参数界面右下角有个输入输出编码，可以调整这个设置来进行修复。

**Comment by LierJeo** [comment]
更改为GBK或GB 2312没有任何改变，改为utf-16完全乱码

同样一行内容在模拟型终端（上）和命令控制台（下）中的对比：
[19:55:40 INFO]: mPreparing spawn area: 0%
>.... [K[[36;1m19:55:40[39;0m [32;22mINFO[39;0m]: [39;0mPreparing spawn area: 0%[39;0m

上一行的所有文字下一行都有，只是在其中参杂了额外的字符

**Comment by KagurazakaNyaa** [comment]
这个应该是xterm的颜色控制字符，模拟终端里应该会正确地解释为颜色

**Comment by Suwings** [comment]
确实，网页控制台无法解析这种颜色字符，虽然已经加了一些替换规则删掉大部分的颜色文字，但是黑名单的策略还是容易导致遗漏掉很多颜色代码。建议你还是多使用模拟终端那个小窗口来进行管理吧。

如果模拟终端也无法解析这个颜色，请再继续反馈，理论上它应该会正确处理。

**Comment by LierJeo** [comment]
确实基本上不怎么影响使用，只是发现了这个bug就来提一下:P

**Comment by MiaoAXin** [comment]
> 确实基本上不怎么影响使用，只是发现了这个bug就来提一下:P

个人认为不是一个bug
如果这个服务端可以通过Terminal启动，乱码部分应该是字符颜色的东西

**Comment by huangsijun17** [comment]
> > 确实基本上不怎么影响使用，只是发现了这个bug就来提一下:P
> 
> 个人认为不是一个bug
> 如果这个服务端可以通过Terminal启动，乱码部分应该是字符颜色的东西

原理层面的问题，都是颜色字符。对于这类模拟终端，基本没有好的方案，而另一个终端可以正常显示。除非有大神能从底层解决，不然只能靠正则表达式去删除了。
