### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by cokll** [Suwings/MCSManager#43]
- 数据库支持 --如MySQL
- 配置文件支持 --不用每次都去填写附加参数 和启动文件名
- 脚本支持  --备份与回档 自动安装等
- 命令控制台也显示其他相关日志  如启动关闭时间
- 计划任务运行内置脚本

**Comment by Suwings** [comment]
感谢提供建议。

`数据库支持`，在目前而言，设计上是可以使用数据库的，但是短期内不会支持数据库（因为我们想打造开箱即用，而且我们目前的数据量很少）。

`配置文件支持 `  你是想每个服务端可以写一个配置文件？然后依靠配置文件来直接启动？个人觉得这样并不好。

`脚本支持`   备份与回档可以考虑，自动安装短期内不给予考虑。

`相关日志`  可以考虑，我们将写入 todo 功能

`计划任务运行内置脚本`  可以考虑。

**Comment by cokll** [comment]
- 配置文件是一个总的服务器类型 比如有启动参数,比如100个服务器使用一个类型的配置文件 就只需要设置一次启动参数
- 数据库也可以选择 SQLite 文件的方法容易丢失和存储不便
@Suwings

**Comment by Suwings** [comment]
明白你的意思。感谢反馈。
近期不会进行较大版本改动，过段时间，我们尽力而为。

**Comment by ccinv** [comment]
另外的建议：
- 提供几套 one-key preset，优化新手体验（可能就是“配置文件支持”的意思）
- 提供 dockerfile

**Comment by Suwings** [comment]
感谢反馈，可以考虑。
另外，Dockerfile 也许你可以参考一下这个: [单击打开URL](https://github.com/Suwings/MCSManager/wiki/Linux-Docker-%E6%95%B4%E4%BD%93%E5%8C%96%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)

**Comment by Suwings** [comment]
#### 很抱歉我们没有实现你们所期望的全部功能。

“配置文件功能” 我们开发了复制服务器配置的选项，可以在创建服务器时，从现有的服务器配置进行读取。

“相关日志功能” 功能我们已经添加，启动服务器与关闭服务器时会在控制有具体输出。

“计划任务运行内置脚本“ 恕我们没有开发，经过我们团队的协商，这个运行内置脚本大大的提高了宿主机的危险，尽管本身没有虚拟化，但是我们还是不建议加入这个功能，因为这样连恶意插件都不需要上传就可以对主机进行恶意操作。

“数据库支持” 目前不需要数据库，存储量很少，未来版本可能会提供 `SQLite` 的选择。

[_](http://i4.bvimg.com/577294/a62ff1fed454bf9f.png)

版本: https://github.com/Suwings/MCSManager/releases/tag/v8.4.4

如有更好更多的功能想法，欢迎随时来提。
@ccinv  @cokll
