### ISSUE TITLE
关于多台机器的协同管理

### ISSUE THREAD

**Issue by HIM049** [Suwings/MCSManager#430]
希望可以连接多个控制面板，或者搭建和连接前后端。可以方便的把多台不同平台的机器进行连接，并把实例汇总到一个特定的面板或者是专门搭建的前端上。借此方便进行管理。
另外感谢开发组对MCSM面板的长期维护和更新，打造了如此方便实用的面板程序！

**Comment by huangsijun17** [comment]
下一版面板已计划重写以支持集群化管理。

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: HIM049 ***@***.***>
Sent: Thursday, June 17, 2021 6:11:24 PM
To: Suwings/MCSManager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Suwings/MCSManager] 关于多台机器的协同管理 (#430)


希望可以连接多个控制面板，或者搭建和连接前后端。可以方便的把多台不同平台的机器进行连接，并把实例汇总到一个特定的面板或者是专门搭建的前端上。借此方便进行管理。
另外感谢开发组对MCSM面板的长期维护和更新，打造了如此方便实用的面板程序！

―

**Comment by Suwings** [comment]
> 希望可以连接多个控制面板，或者搭建和连接前后端。可以方便的把多台不同平台的机器进行连接，并把实例汇总到一个特定的面板或者是专门搭建的前端上。借此方便进行管理。
> 另外感谢开发组对MCSM面板的长期维护和更新，打造了如此方便实用的面板程序！

MCSManager 9.0将支持这些功能，但是在此之前，需要本项目先到达1k star才会开始开发9.0版本，Readme.md 里面有写。

**Comment by Skely0528** [comment]
作者加油加油！ 新功能将会很实用 ， 好期待。 加油！

**Comment by Suwings** [comment]
既然关心新版本也稍微说一下。9.0版本还需要很长一段时间，目前处于停滞状态（遇到了非技术上的问题）。

此为9.0开发版本截图，此截图不代表最终产品。

![image](https://public-link.oss-cn-shenzhen.aliyuncs.com/MCSM9Dev.png)
