### ISSUE TITLE
帮助：如何升级

### ISSUE THREAD

**Issue by happyeggchen** [Suwings/MCSManager#431]
我尝试从git pull但是它提示文件冲突

**Comment by Suwings** [comment]
保留你的 /users /servers 和 property.js 文件（以上三个目录属于数据目录，其他文件夹均是代码），删除其他文件，然后在 github （https://github.com/Suwings/MCSManager）代码的右上角有个绿色的按钮 “Code”，点击下载 ZIP 格式压缩包，解压，放到你现在面板的目录中。更新完毕。

**Comment by happyeggchen** [comment]
其實pull然後讓其覆蓋當前文件就好了我試了沒問題
