### ISSUE TITLE
系統終端

### ISSUE THREAD

**Issue by happyeggchen** [Suwings/MCSManager#432]
建議添加一個系統的虛擬終端例如可以執行fish等shell的終端然後可以在上面操作系統這樣

**Comment by Suwings** [comment]
在服务器参数界面，中部底下有个自定义命令，填写 bash ，再开启服务器，在终端界面就能操作一些常用命令了，不过并不支持 tty 程序（列如 top 命令）。

**Comment by happyeggchen** [comment]
能不能稍微支持一下fish

**Comment by Suwings** [comment]
我没有使用过 fish ，但是通过官方文档的简单描述，我猜测支持 fish 的效果和支持 bash 的效果应该是一致的，同样需要 tty 模式。而MCSM面板的输入输出流并不能直接模拟出tty模式，但是 Docker 容器是可以支持 tty 模式，从而实现真正的终端体验，你可以在Linux上运行MCSM面板，安装 Docker 镜像，设置启动命令为 bash，再使用面板的 模拟终端 功能，从而可实现你的需求。
