### ISSUE TITLE
mc终端运行过程中，可以使用tar命令进行world存档备份吗？

### ISSUE THREAD

**Issue by Howardnm** [Suwings/MCSManager#434]
我想使用crontab和tar进行定时备份存档，不知道是否可以在运行情况下进行备份？
还是只能关闭mc终端后才能备份存档？

**Comment by huangsijun17** [comment]
> 我想使用crontab和tar进行定时备份存档，不知道是否可以在运行情况下进行备份？
> 还是只能关闭mc终端后才能备份存档？

备份mc服务端时的要求是取决于您的服务端核心和整合包的。例如1.7.10，必须要关闭游戏内的自动保存，才能够在运行中备份游戏。而某些特殊的插件模组等，无法在运行中备份。
个人建议是关闭服务端后备份，或使用第三方备份模组或插件较为合适。
