### ISSUE TITLE
建议在服务器`崩溃监视与配置`一栏中增加`服务器自启`的功能

### ISSUE THREAD

**Issue by keywet06** [Suwings/MCSManager#435]
建议在服务器`崩溃监视与配置`一栏中增加`服务器自启`的功能
因为设置开机自启比较简单，但没办法用命令让程序开服务器（API没了awa

_Originally posted by @keywet06 in https://github.com/Suwings/MCSManager/issues/393#issuecomment-866432930_

正在写ing

**Comment by keywet06** [comment]
请管理员同志审核awa
<https://github.com/Suwings/MCSManager/pull/436>

**Comment by Suwings** [comment]
感谢贡献代码，你的代码已经合并并且我做了一些修改，相应代码的文件名作者已经附加上你的名字。

特此感谢你的MCSManager开源项目的贡献。

https://github.com/Suwings/MCSManager/blob/master/helper/AutoStartTask.js#L2
