### ISSUE TITLE
命令行界面部分报错信息需要关闭服务器后才产生提示

### ISSUE THREAD

**Issue by Fannerdev** [Suwings/MCSManager#438]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境:**
Linux Debian 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64
**面板版本:**
8.6.20 发行版本
**Node 版本:**
v10.24.0
**出现概率:**
100%
**出现的问题 (BUG):**
命令行界面不会实时更新信息
往往是关闭服务器的时候才显示运行的报错信息
**复现操作步骤:**
服务器产生报错
关闭服务器后才看到姗姗来迟的报错提示

**Comment by Suwings** [comment]
请问你所使用的服务端是什么？我使用spigot没有遇见过你这种情况，可能船你所使用的服务端标准输出流有些许不兼容导致的这种情况，具体原因咱不清楚。

**Comment by styleteam-fannao** [comment]
一个 Linux 命令行运行的程序
**不是**Minecraft

**Comment by huangsijun17** [comment]
> 一个 Linux 命令行运行的程序
> **不是**Minecraft

MCSM不是虚拟tty，不兼容那些需要tty的软件。
