### ISSUE TITLE
关于 API 的安全问题

### ISSUE THREAD

**Issue by keywet06** [Suwings/MCSManager#439]
**内容:**

现在 API 基于 API Key 的访问方式可能有安全漏洞

截获一次访问信息后就会泄漏所有信息及权限

建议改为基于Unix时间md5/sha-256加密API Key的算法

**Comment by Suwings** [comment]
你说的是通过中间人攻击获得到API key吗？

如果对网络环境有如此的不可信，并且安全性极为重要的情况下，可以通过 apache等软件进行反向代理部署 https 链接。

否则一般情况下，管理员自身若能确保不泄露自身API，普通用户的API泄露也只能攻击他自己。

当然你的意见确实不错，使用完全明文作为API访问密码可能确实有点不妥，后续版本会想办法逐步更新的，目前同时开发项目过多，本项目暂时进入缓慢更新期。

谢谢你的提议。

**Comment by huangsijun17** [comment]
不建议在非https环境下的外网使用API功能。

**Comment by Suwings** [comment]
你的这个建议正好我们部分人作了一些假设和想法，的确要确保API安全性可能单独不止是外部的因素，也有可能是内部的因素，这个确实应该引起重视，这个API功能在以后版本会想办法升级，做到不依靠明文传输。

此 issue 暂且关闭，以后版本会逐渐加强 API 安全这方面。
