### ISSUE TITLE
Safari游览器登陆后台密码错误

### ISSUE THREAD

**Issue by Shizuri23** [Suwings/MCSManager#440]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境:**
MacOs /iPadOs/iPhone  Safari游览器
**面板版本:**
8.6.23 测试版本
**Node 版本:**
v14.17.1
**出现概率:**
100%
**出现的问题 (BUG):**
<img width="294" alt="image" src="https://user-images.githubusercontent.com/46082179/123783242-bdab0680-d908-11eb-89a4-e55fbc8b64f8.png">
已排除密码错误的问题
相同环境下使用谷歌游览器可以正常进入
**复现操作步骤:**
用Safari游览器登陆后台

**Comment by Suwings** [comment]
谢谢你得反馈，带我有时间后验证一下此功能，再想办法修复。

**Comment by Shizuri23** [comment]
之前发过issus，不知道为什么被删了。快修吧quq，我不想用谷歌游览器了，是个挺严重的问题，不只是我一个人有这种问题，我的朋友（mac，big sur，包括手机（iOS 14））也不行

**Comment by huangsijun17** [comment]
> 之前发过issus，不知道为什么被删了。快修吧quq，我不想用谷歌游览器了，是个挺严重的问题，不只是我一个人有这种问题，我的朋友（mac，big sur，包括手机（iOS 14））也不行

建议考虑时间问题，包括服务器和客户端的时间是否正确。

**Comment by Suwings** [comment]
> > 之前发过issus，不知道为什么被删了。快修吧quq，我不想用谷歌游览器了，是个挺严重的问题，不只是我一个人有这种问题，我的朋友（mac，big sur，包括手机（iOS 14））也不行
> 
> 建议考虑时间问题，包括服务器、客户端和反代服务器的时间是否正确。

我觉得跟这些应该没太多关系，我觉得纯粹就是 Safari 对于登录过程中的某个小细节方法不兼容导致的。对此我也咱不清楚是哪里的问题，很有可能是运算加密的问题导致加密结果不一样，所以一直密码错误。如果任何错误信息都没有春纯粹是因为某处算法不一致，那这个问题就难以修复。

每天再看看吧。

**Comment by Shizuri23** [comment]
> > > 之前发过issus，不知道为什么被删了。快修吧quq，我不想用谷歌游览器了，是个挺严重的问题，不只是我一个人有这种问题，我的朋友（mac，big sur，包括手机（iOS 14））也不行
> > 
> > 
> > 建议考虑时间问题，包括服务器、客户端和反代服务器的时间是否正确。
> 
> 我觉得跟这些应该没太多关系。
> 
> 应该纯粹就是 Safari 对于登录过程中的某个小细节方法不兼容导致的。对此我也暂不清楚是哪里的问题，很有可能是运算加密的问题导致加密结果不一样，所以一直密码错误。如果任何错误信息都没有纯粹是因为某处算法不一致，那这个问题就难以修复。
> 
> 每天再看看吧。

您好，感谢各位的支持和帮助，我发现服务器时间与现实世界相差2天，将其更正后解决问题，现在已可以正常进入后台

**Comment by Shizuri23** [comment]
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/46082179/123834608-2ced1e80-d93a-11eb-864a-82a42143f3f9.png">
