### ISSUE TITLE
希望增加控制台网站与实例分离运行的功能，并且对bc加入更深入的支持

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [Suwings/MCSManager#441]
举个例子
网站主机在海外[有独立ip]，国内多个受控主机[无独立ip，只有端口]运行实例，双方加密数据交换，这样可以腾出更多性能，也可以有效避免面板挂掉，连锁杀死实例导致坏档，同时通过MCSM管理的bc[运行在网站机]能直接跳转链接请求，隐藏实例机地址，防止被塞爆，面板服务商可以直接免去大部分面板，只留下mcsm链接地址，mosh能保证快速重连，rsync可以实时同步文件
**这些功能有哪些代替方案？**
数据传输可以使用mosh+rsync，BC给出配置文件编辑页面就可以，被控/指令端没有想法。
**对应你提出的内容，你觉得有什么价值？**
免去备案烦恼，同时增强容灾能力，还无需苦恼面板造成资源挤占
**其他内容:**
node.js资源占用有点小高，并且优化很差，个人认为实例作为这玩意的父进程实在不太靠谱，所以想出此法。

**Comment by Suwings** [comment]
你说的此功能属于分布式管理，此功能已经在 MCSManager 9.0 中实现（一个面板，多个远程守护进程），此版本还暂完全开发完毕，需要等待一段时日。

**Comment by Suwings** [comment]
https://github.com/Suwings/MCSManager#%E7%89%B9%E5%A4%A7%E6%9B%B4%E6%96%B0

**Comment by Mr-Ao-Dragon** [comment]
> 你说的此功能属于分布式管理，此功能已经在 MCSManager 9.0 中实现（一个面板，多个远程守护进程），此版本还暂完全开发完毕，需要等待一段时日。

好的，了解
