### ISSUE TITLE
api获取服务器信息能否加个在线玩家名字？

### ISSUE THREAD

**Issue by Suika99** [Suwings/MCSManager#442]
api获取服务器信息能否加个在线玩家名字？

**Comment by huangsijun17** [comment]
不可能。MCSM上跑的服务端千奇百怪，面板无法获取玩家名。
如果是原版或类原版，可以通过远程执行`list`命令获取在线玩家名。

**Comment by styleteam-fannao** [comment]
我不知道 ```https://wiki.vg/Protocol#Player_List_Header_And_Footer``` 对你有帮助吗？

**Comment by Suika99** [comment]
> 不可能。MCSM上跑的服务端千奇百怪，面板无法获取玩家名。
> 如果是原版或类原版，可以通过远程执行`list`命令获取在线玩家名。

![image](https://user-images.githubusercontent.com/36983663/124281307-2d74f780-db7c-11eb-9e71-cf04796437d6.png)
为何？

**Comment by Suwings** [comment]
https://github.com/Suwings/MCSManager/wiki/API-Documentation#%E5%90%91%E6%9F%90%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8F%91%E9%80%81%E5%91%BD%E4%BB%A4

向某服务器发送命令
权限: 所有用户
限制: 1 秒内只能请求一次
方式: POST
地址: http://127.0.0.1:23333/api/execute/?apikey={KEY}
参数:

name=FristMinecraftServer     // 服务器名字
command=list     

这两个参数不是 params，应该是 body 中，采用 application/x-www-form-urlencoded 格式。

**Comment by Suika99** [comment]
> https://github.com/Suwings/MCSManager/wiki/API-Documentation#%E5%90%91%E6%9F%90%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8F%91%E9%80%81%E5%91%BD%E4%BB%A4
> 
> 向某服务器发送命令
> 权限: 所有用户
> 限制: 1 秒内只能请求一次
> 方式: POST
> 地址: [http://127.0.0.1:23333/api/execute/?apikey={KEY}](http://127.0.0.1:23333/api/execute/?apikey=%7BKEY%7D)
> 参数:
> 
> name=FristMinecraftServer // 服务器名字
> command=list
> 
> 这两个参数不是 params，应该是 body 中，采用 application/x-www-form-urlencoded 格式。

感谢大佬，请求是通了，但是它不把结果返回给我也没用呀，麻了。
我该如何获取返回结果？

**Comment by Suwings** [comment]
命令接口，暂时不支持返回结果。
