### ISSUE TITLE
崩溃重启功能可能存在问题

### ISSUE THREAD

**Issue by Fannerdev** [Suwings/MCSManager#443]
**系统环境:**
Linux version 4.19.0-6-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.67-2 (2019-08-28)
**面板版本:**
Version 8.6.23
**Node 版本:**
v16.4.0
**出现概率:**
100%
**出现的问题 (BUG):**
大概率是崩溃重启功能使用之后进程还在但是服务器状态为未启动
**复现操作步骤:**
服务器崩溃 服务器重启后 面板上显示服务器状态未启动

**Comment by Suwings** [comment]
感谢你的反馈，我晚一点再测试这个功能给你回复。

**Comment by styleteam-fannao** [comment]
该问题经常复现，明明点击关闭，显示关闭了，ps看进程还在

**Comment by xrh0905** [comment]
@Fannerdev 尝试在Spigot.yml中将restart-on-crash改为false

**Comment by huangsijun17** [comment]
另外，开服有没有用bat或者sh脚本？
