### ISSUE TITLE
在用nignx反向代理後 上傳文件會報錯

### ISSUE THREAD

**Issue by jing-shiun** [Suwings/MCSManager#445]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境:** 
面板:windows10 反向代理:ubuntu18.04lts

**面板版本:** 
8.6.23

**Node 版本:** 
14

**出现概率:**
每次

**出现的问题 (BUG):** 
反向代理後無法上傳文件

**复现操作步骤:** 
無法

**Comment by KagurazakaNyaa** [comment]
是不是`client_max_body_size`没有设置？

**Comment by jing-shiun** [comment]
> 是不是`client_max_body_size`没有设置？

要如何設置呢

**Comment by KagurazakaNyaa** [comment]
> > 是不是`client_max_body_size`没有设置？
> 
> 要如何設置呢

你就加一行`client_max_body_size 1G;`在你的配置文件里
