### ISSUE TITLE
token过期后不会自动跳转到登陆界面

### ISSUE THREAD

**Issue by Fannerdev** [Suwings/MCSManager#446]
**系统环境:**
Debian
**面板版本:**
发行版本: 8.6.15 发行版本
**Node 版本:**
v10.24.0
**出现概率:**
100%
**出现的问题 (BUG):**
token过期后不会自动跳转到登陆界面
**复现操作步骤:**
登陆面板账户->等待token过期->刷新面板(然后一直在加载页面状态)

**Comment by Suwings** [comment]
可能此问题确实存在，但不算特别严重，新版本将修复此问题。

**Comment by stydxm** [comment]
> 
> 
> 可能此问题确实存在，但不算特别严重，新版本将修复此问题。
> 
> 感谢你的反馈。

是不太严重，但真挺烦的

**Comment by Suwings** [comment]
MCSM 9 将修复此问题
