### ISSUE TITLE
镜像的java版本好像有些老. 墨端好像要求jdk16

### ISSUE THREAD

**Issue by wcz0** [Suwings/MCSManager#447]
**你对哪些功能有建议或想法？**

**这些功能有哪些代替方案？**

**对应你提出的内容，你觉得有什么价值？**

**其他内容:**

（功能请求或者功能建议均准许自由发挥，无特定限制模板，你可以在这里写下任何你想说的文字。）

**Comment by SnowMoonSS** [comment]
```
FROM java:latest
RUN mkdir -p /mcsd
RUN echo "Asia/Shanghai" > /etc/timezone;dpkg-reconfigure -f noninteractive tzdata
WORKDIR /mcsd
```
这是默认的dockerfile，如果需要开1.17及以上版本的服，你需要这样修改：
1、把`FROM java:latest`改为`FROM openjdk:16.0.2`
2、删除`RUN echo "Asia/Shanghai" > /etc/timezone;dpkg-reconfigure -f noninteractive tzdata`。（更换为java16镜像后这句会报错，然后构建失败，索性就把这句删掉了……不过代价就是服务端显示的时间可能会跟本地时间有8小时的时差）

**Comment by wcz0** [comment]
蟹蟹

**Comment by huangsijun17** [comment]
> ```
> FROM java:latest
> RUN mkdir -p /mcsd
> RUN echo "Asia/Shanghai" > /etc/timezone;dpkg-reconfigure -f noninteractive tzdata
> WORKDIR /mcsd
> ```
> 
> 这是默认的dockerfile，如果需要开1.17及以上版本的服，你需要这样修改：
> 1、把`FROM java:latest`改为`FROM openjdk:16.0.2`
> 2、删除`RUN echo "Asia/Shanghai" > /etc/timezone;dpkg-reconfigure -f noninteractive tzdata`。（更换为java16镜像后这句会报错，然后构建失败，索性就把这句删掉了……不过代价就是服务端显示的时间可能会跟本地时间有8小时的时差）

试试看这个：
```
FROM  adoptopenjdk/openjdk16
RUN Runtime.getRuntime().exec("mkdir -p /mcsd") 
RUN Runtime.getRuntime().exec("echo \"Asia/Shanghai\" > /etc/timezone;dpkg-reconfigure -f noninteractive tzdata")
WORKDIR /mcsd
```
java16的docker默认启动了jshell，要运行bash命令，需要用`Runtime.getRuntime().exec()`。

**Comment by AlexanderMC8533** [comment]
mohist允许你使用java8启动1.16.5，也允许java16启动1.12.2。mohist会做初次启动补全所有库以及java（Windows是这样，Linux未知）

**Comment by Suwings** [comment]
8.7 版本已加入创建镜像时选择 Java 16 或 Java 8 的功能，不过此版本还未发布。
