### ISSUE TITLE
mcsm运行一段时间后崩溃

### ISSUE THREAD

**Issue by 12123ads** [Suwings/MCSManager#448]
**系统环境:**
Windows server 2019
**面板版本:**
8.6.23 发行版本
**Node 版本:**
官网下载自带版本
**出现概率:**
不清楚
**出现的问题 (BUG):**
运行一段时间之后自动崩溃
**复现操作步骤:**
![Screenshot_2021-07-20-22-58-49-40_2665fb67b16260a8d818298cef8dc107.jpg](https://inews.gtimg.com/newsapp_ls/0/13790143275/0)

**Comment by huangsijun17** [comment]
有A盘？在用3.5英寸软盘？
C盘根目录的ws文件夹？里面什么东西？在C盘根目录又是什么情况？

**Comment by 12123ads** [comment]
不是，，我给附加上的硬盘标成a了![Screenshot_2021-07-21-09-50-48-38_2665fb67b16260a8d818298cef8dc107.jpg](https://cdofs.oppomobile.com/cdo-portal/feedback/202107/21/a524a2b727698d01bc42bfa48e90779c.jpg)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月21日(周三) 上午9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] mcsm运行一段时间后崩溃 (#448)




 
有A盘？在用3.5英寸软盘？
 C盘根目录的ws文件夹？里面什么东西？在C盘根目录又是什么情况？
 
&mdash;

**Comment by huangsijun17** [comment]
> 不是，，我给附加上的硬盘标成a了![Screenshot_2021-07-21-09-50-48-38_2665fb67b16260a8d818298cef8dc107.jpg](https://cdofs.oppomobile.com/cdo-portal/feedback/202107/21/a524a2b727698d01bc42bfa48e90779c.jpg)
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月21日(周三) 上午9:23 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Suwings/MCSManager] mcsm运行一段时间后崩溃 (#448) 有A盘？在用3.5英寸软盘？ C盘根目录的ws文件夹？里面什么东西？在C盘根目录又是什么情况？ &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你成功治好了我的低血压。别乱用A、B盘符，可能会影响某些程序对于是否存在软驱的判断。

**Comment by 12123ads** [comment]
emmm，要把盘符改了吗

**Comment by 12123ads** [comment]
c盘目录没有ws这个文件夹
![Screenshot_2021-07-21-09-56-07-90_2665fb67b16260a8d818298cef8dc107.jpg](https://cdofs.oppomobile.com/cdo-portal/feedback/202107/21/b52f6eb96c18527671c74604fa50038a.jpg)

**Comment by huangsijun17** [comment]
> emmm，要把盘符改了吗

先按照一般惯例改了再说吧。

**Comment by 12123ads** [comment]
行
