### ISSUE TITLE
MOTD修改后乱码

### ISSUE THREAD

**Issue by wifi-left** [Suwings/MCSManager#449]
如题。

**系统环境: Windows Server 2019**

**出现概率: Sometimes (?待确定)**

**出现的问题 (BUG):**
MOTD在 文件管理器 文本修改后，配置设置能够正常读取U码，服务器MOTD正常显示。但保存后，服务器MOTD变为乱码。

**复现操作步骤:**
MOTD在 文件管理器 文本修改后，配置设置能够正常读取U码，服务器MOTD正常显示。但保存后，服务器MOTD变为乱码。

**Comment by Suwings** [comment]
在线文件管理使用 UTF8 作为读取和保存的操作编码，可能是默认的 utf8 编码不兼容现有的编码配置，建议你还是通过上传文件的方式来编辑这些可能乱码的文件，在本地编辑好后即可上传文件覆盖。

后续版本会增加一个在线文件管理功能的在线编码设置功能，还请期待。

**Comment by wifi-left** [comment]
> 在线文件管理使用 UTF8 作为读取和保存的操作编码，可能是默认的 utf8 编码不兼容现有的编码配置，建议你还是通过上传文件的方式来编辑这些可能乱码的文件，在本地编辑好后即可上传文件覆盖。
> 
> 后续版本会增加一个在线文件管理功能的在线编码设置功能，还请期待。

我可能没描述到位，文件管理的在线编辑是没有任何问题的，但在服务器设置更改prop界面是会出现问题的。

**Comment by Suwings** [comment]
是我理解错误，明白你的意思了，下个大版本修复，目前正在全力开发新版本。

**Comment by huangsijun17** [comment]
> 是我理解错误，明白你的意思了，下个大版本修复，目前正在全力开发新版本。

貌似是在MCSM的“服务端 server.properties 配置文件”里，对于UTF-8编码的内容兼容性问题。
