### ISSUE TITLE
建议切换界面的时候改变浏览器地址栏中的URL/支持浏览器的前进后退按钮

### ISSUE THREAD

**Issue by Maki-SA** [Suwings/MCSManager#45]
单页应用又不是单URL应用(小声)
现在浏览器的前进后退按钮根本没法用
刷新页面直接回到首页

抱歉表达的不太清楚, 具体实现可以参考[Microsoft Azure控制台](https://portal.azure.com)

**Comment by Suwings** [comment]
前进后退按钮我们已经把他给禁止。
因为暂时没还没“单页面后退”的实现，所以我们索性暂时禁用了“前进后退”按钮。

类似于“百度网盘”，“Microsoft Azure”控制台这样的前进后退效果还是可以实现的，只是由于不是刚需，暂时没有实现它。

感谢反馈！
