### ISSUE TITLE
解压失败 100%

### ISSUE THREAD

**Issue by mengdiao** [Suwings/MCSManager#450]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境:**
windows11
**面板版本:**
 最新
**Node 版本:**

**出现概率:**
100%
**出现的问题 (BUG):**
我解压不了 总有一个文件因为路径过长无法解压 在服务器2012R 2 和win11都不行
**复现操作步骤:**

**Comment by mengdiao** [comment]
好吧 未安装解压软件时用系统的文件管理器时才会有此bug

**Comment by Suwings** [comment]
解决了就好~
