### ISSUE TITLE
关于docker搭建问题

### ISSUE THREAD

**Issue by HopeLight** [Suwings/MCSManager#451]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境: Centos 6.8**

**面板版本: 最新版**

**Node 版本: 12.16.1**

**出现概率: 可能奇葩问题**

**出现的问题 (BUG): 关于使用docker进行搭建和构架**

**复现操作步骤: 
![VV1@V8SF`SXWTWLS2P 54E2](https://user-images.githubusercontent.com/81500235/126664138-394390e9-ad2f-47b7-b45d-527ffda02a85.png) 
![7)T5~04{4`E~$ZTE{G4YHUL](https://user-images.githubusercontent.com/81500235/126664236-da94c91d-e9ad-4aa2-8077-5e9cf4fb9328.png)1. 关于搭建docker启动面板,我有正确的按照文档进行填写DockerFile配置文件,但是在docker build时仍然是进行报错了
2. 包括在使用面板内进行创建镜像的时候,还是依旧出现了失败的问题..
![043LKED`YNLZ18VQE{E}SUF](https://user-images.githubusercontent.com/81500235/126664490-557392fe-3094-480b-9280-5b100bbb2251.png)
**

**Comment by HopeLight** [comment]
以下是在构架用docker运行面板时的报错
![VV1@V8SF`SXWTWLS2P 54E2](https://user-images.githubusercontent.com/81500235/126664841-d25bbe97-dd0b-423e-be77-ef145c5c057f.png)

**Comment by HopeLight** [comment]
如果可以...麻烦作者大大留一下QQ或者某联系方式,对于这种问题我已经感到糟糕透了

**Comment by Suwings** [comment]
看起来你的镜像环境是 node 环境？你是想将 MCSManager 面板整个套入至Docker中？这种做法是不太推荐的，你应该只需要创建 java 环境的镜像就能满足创建MC服务器的需求。

个人QQ不随便加人，你可以申请加入QQ群：287215485

**Comment by HopeLight** [comment]
> 看起来你的镜像环境是 node 环境？你是想将 MCSManager 面板整个套入至Docker中？这种做法是不太推荐的，你应该只需要创建 java 环境的镜像就能满足创建MC服务器的需求。
> 
> 个人QQ不随便加人，你可以申请加入QQ群：287215485

已经解决了大部分的问题，但还是出现在脚本上，在docker进行执行sh脚本的时候，还是没有办法进行完美的运行...
