### ISSUE TITLE
在群晖（一种Linux）上部署MCSM

### ISSUE THREAD

**Issue by AlexanderMC8533** [Suwings/MCSManager#453]
**你对哪些功能有建议或想法？**
在群晖NAS设备上搭建MCSM，使用SSH
**这些功能有哪些代替方案？**
没有
**对应你提出的内容，你觉得有什么价值？**
低成本
**其他内容:**

（功能请求或者功能建议均准许自由发挥，无特定限制模板，你可以在这里写下任何你想说的文字。）

**Comment by huangsijun17** [comment]
我只能告诉你NAS可以装，请自己研究。

**Comment by AlexanderMC8533** [comment]
没搞好才提的，难道不是按照网站上的方式吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(周四) 中午11:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] 在群晖（一种Linux）上部署MCSM (#453)




 
我只能告诉你NAS可以装，请自己研究。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlexanderMC8533** [comment]
我要是可以自己装好就不会发出来了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(周四) 中午11:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] 在群晖（一种Linux）上部署MCSM (#453)




 
我只能告诉你NAS可以装，请自己研究。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huangsijun17** [comment]
1. Github的issues不是聊天室，请善用编辑功能。
2. 群晖的NAS是一个特殊的Linux系统，在套件中心可以下载Nodejs运行环境。
3. 您只需要通过git clone克隆仓库到本地，再拿npm install命令安装即可。
4. 群晖中的计划任务可以用于MCSManager的开机自启动。

**Comment by AlexanderMC8533** [comment]
> 1. Github的issues不是聊天室，请善用编辑功能。
> 2. 群晖的NAS是一个特殊的Linux系统，在套件中心可以下载Nodejs运行环境。
> 3. 您只需要通过git clone克隆仓库到本地，再拿npm install命令安装即可。
> 4. 群晖中的计划任务可以用于MCSManager的开机自启动。

1.湖北武汉无法正常访问Github（-7）请考虑回复者的便利性
2.非常感谢你的回复，它现在可以正常工作
3.态度好一点，谢谢了。但是这个*问题*不会关闭，为了其他人继续提交内容。

**Comment by huangsijun17** [comment]
> > 1. Github的issues不是聊天室，请善用编辑功能。
> > 2. 群晖的NAS是一个特殊的Linux系统，在套件中心可以下载Nodejs运行环境。
> > 3. 您只需要通过git clone克隆仓库到本地，再拿npm install命令安装即可。
> > 4. 群晖中的计划任务可以用于MCSManager的开机自启动。
> 
> 1.湖北武汉无法正常访问Github（-7）请考虑回复者的便利性
> 2.非常感谢你的回复，它现在可以正常工作
> 3.态度好一点，谢谢了。但是这个_问题_不会关闭，为了其他人继续提交内容。

1. 你可以现在使用gitee的镜像，nodejs修改为淘宝的源。
2. 群辉开服和树莓派开服、安卓手机开服一样，性能太差，基本只能当玩具玩玩。
3. 也正因为性能不好，开完出问题的也一堆，所以我主张是别去开，别去教。

**Comment by AlexanderMC8533** [comment]
感谢回复，群晖DS920+性能过剩



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(周四) 中午12:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] 在群晖（一种Linux）上部署MCSM (#453)




    
Github的issues不是聊天室，请善用编辑功能。 

群晖的NAS是一个特殊的Linux系统，在套件中心可以下载Nodejs运行环境。 

您只需要通过git clone克隆仓库到本地，再拿npm install命令安装即可。 

群晖中的计划任务可以用于MCSManager的开机自启动。 
  
1.湖北武汉无法正常访问Github（-7）请考虑回复者的便利性
 2.非常感谢你的回复，它现在可以正常工作
 3.态度好一点，谢谢了。但是这个_问题_不会关闭，为了其他人继续提交内容。
   
你可以现在使用gitee的镜像，nodejs修改为淘宝的源。 

群辉开服和树莓派开服、安卓手机开服一样，性能太差，基本只能当玩具玩玩。 

也正因为性能不好，开完出问题的也一堆，所以我主张是别去开，别去教。 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huangsijun17** [comment]
> DS920

 J4125，4-8G，我们一个服务端的消耗的一般都不到。开个高版本的基友服，我看悬。

**Comment by AlexanderMC8533** [comment]
> > DS920
> 
> J4125，4-8G，我们一个服务端的消耗的一半都不到。开个高版本的基友服，我看都悬。
> 而且，你这样NAS的硬盘读写更加频繁，硬盘休眠废了。CPU、内存高占用，视频转码也废了。

我还是看看有没有替代性方案吧
