### ISSUE TITLE
能否解决虚拟机安装后cpu占用率几乎100%的问题

### ISSUE THREAD

**Issue by bluehysteric** [Suwings/MCSManager#457]
能否解决虚拟机安装后cpu占用率几乎100%的问题，不管是win还是linux，分配多少cpu，启动服务器后都会导致cpu占用率100%，实体安装的时候cpu占用率却少的很。

**Comment by huangsijun17** [comment]
不懂你啥意思。
MCSM会占用你虚拟机的CPU？

**Comment by bluehysteric** [comment]
> 不懂你啥意思。
> MCSM会占用你虚拟机的CPU？
> 
> ![图像](https://user-images.githubusercontent.com/31504595/128816738-94b87a1f-d6b2-43c5-8584-629a57b00ef2.png)
> 
> 我这里看一下，我这的MCSM的CPU占用率还有0.1%。如果你的node.js存在高占用，建议排查恶意程序入。
> [#242（评论）](https://github.com/Suwings/MCSManager/issues/242#issue-613726526)
好的，我去排查一下，感谢

**Comment by AlexanderMC8533** [comment]
建议：1，为虚拟机分配更多CPU核心
2,分配虚拟机可以用的内存

**Comment by huangsijun17** [comment]
> 建议：1，为虚拟机分配更多CPU核心
> 2,分配虚拟机可以用的内存

请注意，这是单纯安装MCSM后的CPU占用100%。按照个人经验，单跑MCSM能占用100%的CPU性能的虚拟机基本是装不了Linux的。所以应该不是虚拟机配置问题。
