### ISSUE TITLE
密码正确有时候就是无法登陆

### ISSUE THREAD

**Issue by lupohan44** [Suwings/MCSManager#46]
密码正确 在手机上可以登陆但是电脑上无法登陆

**Comment by lupohan44** [comment]
后台显示密匙错误

**Comment by lupohan44** [comment]
厉害了 lastpass同个网页在电脑和手机密码不一样

**Comment by lupohan44** [comment]
我密码是用lastpass记录的 结果不知道为什么这个密码在手机上和电脑上显示不一样 醉了

在 2018-07-15 13:24:29，"Suwings" <notifications@github.com> 写道：


究竟发生了什么？？？？ 能仔细说明一下吗？
@lupohan44

**Comment by Suwings** [comment]
十分感谢你的回复。

我们不太了解 Lastpass 的工作原理，也许是本软件的密码传递加密导致了这种现象的出现，也可能是其他原因，具体不太清楚，给您带来使用不便，还请谅解。
