### ISSUE TITLE
[疑问]创建服务器API中如何设置CPU限额？

### ISSUE THREAD

**Issue by RealXuChe** [Suwings/MCSManager#463]
[创建服务器](https://github.com/Suwings/MCSManager/wiki/API-Documentation#%E5%88%9B%E5%BB%BA%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%AB%98%E7%BA%A78615-%E4%BB%A5%E4%B8%8A)API中似乎没有字段用于设置CPU限额，有办法设置吗？

**Comment by Suwings** [comment]
暂时不支持此设备限制，即使不使用 API 用网页也无法限制。

**Comment by juzijun233** [comment]
这个需求，用虚拟化比较好

**Comment by Suwings** [comment]
看了下 Docker 的 API，限制CPU使用率似乎只有 Windows 下才可用，Linux 只能对 CPU 进行相对权重控制。

MCSM 9 版本会尽快新增此功能。
