### ISSUE TITLE
In wiki "Windows 下安装为系统服务和配置IIS反向代理"

### ISSUE THREAD

**Issue by qwer2003tw** [Suwings/MCSManager#464]
**内容:**
In the xml config file executable parameter need to change to "node_app.exe".

**Comment by Suwings** [comment]
Wiki has been updated, thank you.

**Comment by qwer2003tw** [comment]
Other question when I used the batch file open the MCSM, the server is on network drive it is working success
but when I used the service to open the MCSM it can't access the network drive
how do I solve this problem??

**Comment by Suwings** [comment]
It could be a permission problem, and I don't know about that.

This article was not written by me but submitted by a community worker.
