### ISSUE TITLE
文件管理改进

### ISSUE THREAD

**Issue by AlexanderMC8533** [Suwings/MCSManager#466]
**你对哪些功能有建议或想法？**
1.允许用户直接上传文件夹以及用户将文件（夹）拖入文件管理器固定区域也可以上传
2.上传进度条，具体上传明细
3.远程下载
**这些功能有哪些代替方案？**
3.远程下载
可以使用Github中Aria2开源后端下载
**对应你提出的内容，你觉得有什么价值？**
更易于上传，彻底摒弃FTP
**其他内容:**

（功能请求或者功能建议均准许自由发挥，无特定限制模板，你可以在这里写下任何你想说的文字。）

**Comment by Suwings** [comment]
感谢提供建议。新版本将实现你所写的部分功能点。

**Comment by AlexanderMC8533** [comment]
提醒：Aria2部分作者提供了不同的操作系统版本，在Windows版本下，建议使用x86的版本（请求此issue将于2021/09/30我亲自关闭）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月15日(周日) 中午11:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] 文件管理改进 (#466)




 
感谢提供建议。新版本将实现你所写的部分功能点。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huangsijun17** [comment]
> 感谢提供建议。新版本将实现你所写的部分功能点。

强烈反对提供远程下载功能，要不然别人组个服务器，拿来当下载机用了。

**Comment by Suwings** [comment]
部分功能点，我又没说是全部实现，目前的下载文件设计是反外链的，用户无法使用下载地址直接下载，必须从文件管理界面去点击下载才可实现文件下载。

**Comment by AlexanderMC8533** [comment]
不是，我是这样想的，用户通过github relase获取插件或者mod的链接（因为githubrelase发行页面可以获取固定的链接），在文件管理中输入链接来远程下载，个人认为可用但非必要



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月15日(周日) 中午11:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] 文件管理改进 (#466)




  
感谢提供建议。新版本将实现你所写的部分功能点。
  
强烈反对提供远程下载功能，要不然别人组个服务器，拿来当下载机用了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Suwings** [comment]
明白了，你所说的是离线下载即服务器来替客户下载文件到实例本地文件中， 暂时先优先完成核心功能，其他功能暂不考虑。
