### ISSUE TITLE
如何在没有代理的情况下https

### ISSUE THREAD

**Issue by stevensane** [Suwings/MCSManager#468]
最近嫖了谷歌一台vps，服务端直接扔上去，怎么用https

**Comment by huangsijun17** [comment]
同求，虽然我的结论是无解。

**Comment by stevensane** [comment]
> 同求，雖然我的結論是無解。

哦不

**Comment by huangsijun17** [comment]
> > 同求，雖然我的結論是無解。
> 
> 哦不

你可以试试看反代自己。

**Comment by stevensane** [comment]
> > > 同求，雖然我的結論是無解。
> > 
> > 
> > 哦不
> 
> 你可以试试看反代自己。
> 把443反代到80口，再去防火墙关了80。
> 成功后记得告诉我。

https://www.cloudflare.com/ 的dns服務，連證書都不用整
