### ISSUE TITLE
关于Linux基岩版的问题

### ISSUE THREAD

**Issue by thksdhr** [Suwings/MCSManager#469]
# 如果在尝试过sh start.sh启动参数报错后可以尝试已下几种命令 <h1>
* 1.执行bash start.sh
* 2.执行./start.sh
* 3.执行source start.sh
若还是行不通可以试试将服务器文件bedrock_server权限更改为777再试一次
若你使用的是官网Linux服务器文件，请将Linux系统换为ubuntu系统，Mincraft官方指定的基岩版Linux服务器系统是ubuntu，若想用官方服务器的同时用其他Linux系统可以参考[此文章](https://zhuanlan.zhihu.com/p/345012812)

*最后希望作者可以考虑开放wiki的路人编辑，方便前人补充解决过的问题*

**Comment by Suwings** [comment]
感谢提供帮助信息，过段时间会整理添加到 wiki ，至于wiki编辑权限未来会考虑的。

**Comment by Suwings** [comment]
已加，最底部https://github.com/Suwings/MCSManager/wiki/%E4%BD%BF%E7%94%A8%E9%9D%A2%E6%9D%BF%E5%BC%80%E5%90%AF-Bedrock_server-%E6%9C%8D%E5%8A%A1%E7%AB%AF
