### ISSUE TITLE
建议移除控制台日志的定时缓冲区，以实时更新取代

### ISSUE THREAD

**Issue by hcrgm** [Suwings/MCSManager#47]
在我所见的使用了websocket技术的应用，诸如Travis CI、Circle CI等持续集成服务的当前pipeline和执行日志，还有云服务器的在线远程桌面/终端，几乎都是实时更新，而不是定时刷新。本来websocket是解决轮询太消耗资源、请求无用、更新不及时等的缺陷的很好的技术，如果这么做，再把轮询里类似的概念引入websocket，那不就是本末倒置了吗？我们需要把那种实时观测大局的爽快体验引进来。移除这个feature，还能简化下代码，减轻负担。希望开发者认真考虑下

**Comment by Suwings** [comment]
在以前的版本，我们的控制台中是没有缓冲区的。控制台输出是完全实时的，后来渐渐的我们发现这样做不太合适，于是我们加了输出缓冲区。

但是这个缓冲区并不是类似于ajax的那种轮询，前端不需要发送什么多余的数据，后端每隔一段时间就会自动发送过来，我们认为建立一个输出缓冲区会更好。

如果你想要实时更新，通过修改配置，可以尽可能的接近实时更新。

打开 `property.js` 文件，找到 `MCSERVER.localProperty.console_send_times` 配置。
此配置可以设置缓冲区在有数据时强制发送时间间隔（无数据时不发送，不浪费网络资源），将其缩小即可接近实时效果。重启面板生效。

大约在 200 左右能够有一种很快的响应（已经很接近实时）。但是会额外给服务器带来一点点小负担（因为我们同时也会将输出写入到历史文件），但是负担并不是很大，这一点经过实际测试。

总而言之，我们还是建议不去除输出缓冲区，牺牲一点点实时性，也许会带来更好的效率，而且实时性也就慢了两秒（在默认情况下，通过配置文件可以修改）。

感谢你的建议！十分感谢。
@hcrgm
