### ISSUE TITLE
如果需要发布其他语言版本

### ISSUE THREAD

**Issue by AlexanderMC8533** [Suwings/MCSManager#472]
**你对哪些功能有建议或想法？**
如果发行其他语言版本，希望可以提供完整版词条以供翻译
**这些功能有哪些代替方案？**
没想好
**对应你提出的内容，你觉得有什么价值？**
可以被发现，这是一个比muticraft和翼龙操作简便的web程序
**其他内容:**

（功能请求或者功能建议均准许自由发挥，无特定限制模板，你可以在这里写下任何你想说的文字。）

**Comment by Suwings** [comment]
如果打算做多语言国际化，到时候我会把所有的中文集中在一个文件中，然后只需要替换这个文件，即可实现多语言。

**Comment by AlexanderMC8533** [comment]
嗯，希望9.0会越来越好。希望能在Mine BBS和MCBBS发一下（顺便帮我close，谢谢你）




Taleling
***@***.***

FutureLand&nbsp;Create&amp;Design&nbsp;Corp.
FutureLand首席客服



------------------ 原始邮件 ------------------
发件人: Suwings ***@***.***&gt;
发送时间: 2021年8月22日 09:27
收件人: Suwings/MCSManager ***@***.***&gt;
抄送: Taleling ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Suwings/MCSManager] 如果需要发布其他语言版本 (#472)





 
如果打算做多语言国际化，到时候我会把所有的中文集中在一个文件中，然后只需要替换这个文件，即可实现多语言。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huangsijun17** [comment]
> 如果打算做多语言国际化，到时候我会把所有的中文集中在一个文件中，然后只需要替换这个文件，即可实现多语言。

与其手动替换，还不如直接整到配置文件里面，搞一个语言选项。外加自动识别系统语言。

**Comment by AlexanderMC8533** [comment]
其实我当时也是这样想的，放到一个文件夹，需要时面板上选择那个文件就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月23日(周一) 中午11:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] 如果需要发布其他语言版本 (#472)




  
如果打算做多语言国际化，到时候我会把所有的中文集中在一个文件中，然后只需要替换这个文件，即可实现多语言。
  
与其手动替换，还不如直接整到配置文件里面，搞一个语言选项。外加自动识别系统语言。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Suwings** [comment]
但是也需要一个人来帮忙把网页中所有文本整理到一个文件中，这个我暂时不想做，以后请人帮忙做吧。

**Comment by huangsijun17** [comment]
> 但是也需要一个人来帮忙把网页中所有文本整理到一个文件中，这个我暂时不想做，以后请人帮忙做吧。

行为10开始能i18n话。

**Comment by AlexanderMC8533** [comment]
> > 但是也需要一个人来帮忙把网页中所有文本整理到一个文件中，这个我暂时不想做，以后请人帮忙做吧。
> 
> 希望MCSM 10开始能i18n话。
I think it Okay
