### ISSUE TITLE
文件在线管理的删除失效

### ISSUE THREAD

**Issue by SeaIceNX** [Suwings/MCSManager#473]
**系统环境:** Windows Server 2019

**面板版本:** 8.6.23

**Node 版本:** 10.13.0

**出现概率:** 100

**出现的问题 (BUG):** 选择删除后文件不会被删除，并且会被占用

**复现操作步骤:** 文件管理>删除

**Comment by huangsijun17** [comment]
解压到到一半，未完成？
亦或防病毒软件扫描中？

**Comment by SeaIceNX** [comment]
> 解压到到一半，未完成？
> 亦或防病毒软件扫描中？

并不是
