### ISSUE TITLE
创建服务后无法启动服务

### ISSUE THREAD

**Issue by luke-pkt** [Suwings/MCSManager#478]
环境:
  CentOS8
  Java16
  Node v12.16.1
  MinecraftServer 1.17.1

情况:
 服务器运行时异常,建议检查配置与环境

启动错误日志:
> 2021-09-08T14:55:51.869 INFO 用户  #master  正在启动  minecarft_survival_1_17_1  服务端实例...
> 2021-09-08T14:55:51.870 INFO Minecraft Server start - minecarft_survival_1_17_1
> 2021-09-08T14:55:51.870 INFO 服务器 [ minecarft_survival_1_17_1 ] 启动进程:
> 2021-09-08T14:55:51.870 INFO -------------------------------
> 2021-09-08T14:55:51.870 INFO 启动:  java -Xmx32G -Xms16G -Djline.terminal=jline.UnsupportedTerminal -jar server.jar nogui
> 2021-09-08T14:55:51.870 INFO 根: ./server/server_core/minecarft_survival_1_17_1
> 2021-09-08T14:55:51.870 INFO -------------------------------
> 2021-09-08T14:55:51.875 ERROR 服务端进程启动失败，建议检查启动命令与参数是否正确，pid:
> 2021-09-08T14:55:51.876 ERROR 服务器运行时异常,建议检查配置与环境
> 2021-09-08T14:55:51.876 ERROR Error: spawn java ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   errno: 'ENOENT',
>   code: 'ENOENT',
>   syscall: 'spawn java',
>   path: 'java',
>   spawnargs: [
>     '-Xmx32G',
>     '-Xms16G',
>     '-Djline.terminal=jline.UnsupportedTerminal',
>     '-jar',
>     'server.jar',
>     'nogui'
>   ]
> }
> 2021-09-08T14:55:51.877 ERROR 错误报告:
> 2021-09-08T14:55:51.877 ERROR TypeError: Cannot read property 'pid' of undefined
>     at ChildProcess.<anonymous> (/opt/MCSManager/core/Process/BaseMcserver.js:301:107)
>     at ChildProcess.emit (events.js:311:20)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> 
> 

在根目录下直接运行下列启动命令是成功的
java -Xmx32G -Xms16G -Djline.terminal=jline.UnsupportedTerminal -jar server.jar nogui

**Comment by Cubik65536** [comment]
尝试参考 #366 看看能不能解决？

**Comment by luke-pkt** [comment]
成功解决, 谢谢
在 /usr/bin/ 目录下创建 java的软连接
