### ISSUE TITLE
希望做到前后端可分离

### ISSUE THREAD

**Issue by zxc7895531** [Suwings/MCSManager#48]
这样自定义界面时，就不用担心改前端导致破坏后端了。而且如果支持分离，可以做到放入PHP的根目录，这样就可以支持PHP的登陆界面或者主页面，希望作者考虑一下

**Comment by HonokaClub** [comment]
您好，
暫且不討論目前是否做到了前後分離，這是一個使用 Node.js 實現的項目。我不太明白您想要使用 PHP 取代之的意義。

**Comment by zxc7895531** [comment]
@HonokaClub 
这样做可以使得那些公网端口被限制的服务器不必专门开出一个端口来访问后台，而可以让PHP和后台共用一个端口。而且支持PHP意味着可以让登陆或者其他界面更多元化，毕竟PHP可比HTML强得多。

**Comment by Suwings** [comment]
感谢提供建议！

首先，我们这个项目本身就是前后端分离设计。前端代码所有功能均是通过后端API请求来实现功能的。所以不论你怎么修改前端，都不会对后端有任何的问题。

另外你的想法是想让前端代码部署到 php 环境下，这样就可以用php来渲染html。

这种需求从目前的设计上是可以做到的。

首先将后端启动，在机器内网或同一机器上。
打开/public/common/url.js 将其所有API请求设置到实际的后端。

前端代码放置到php环境根目录，即可直接访问。

接下来，后端必须关闭CSRF攻击防御，否则前端将造成跨域问题（prototype.js文件）。

即可实现你的需求。这是理论上。
实际上我们还未实验，也许过段时间我们会进行这样的尝试实验。
