### ISSUE TITLE
（9.0）新版本更新弹窗

### ISSUE THREAD

**Issue by AlexanderMC8533** [Suwings/MCSManager#481]
**你对哪些功能有建议或想法？**
新版本发布时，弹窗显示
**这些功能有哪些代替方案？**
没有
**对应你提出的内容，你觉得有什么价值？**
很有价值，版本更新
**其他内容:**

（功能请求或者功能建议均准许自由发挥，无特定限制模板，你可以在这里写下任何你想说的文字。）

**Comment by AlexanderMC8533** [comment]
保密需要，不通过任何图像

**Comment by Suwings** [comment]
旧版本MCSManager8没有预先加入过更新弹框或者事件通知，仅仅只能从更新动态处添加文字说明，仅此而已。
