### ISSUE TITLE
docker镜像创建失败

### ISSUE THREAD

**Issue by LanceXOT** [Suwings/MCSManager#485]
**系统环境:**
CentOS7.6
**面板版本:**
8.6.23 发行版本
**Docker版本**
1.13.1
**Node 版本:**
14.17.6
**出现概率:**
100%
**出现的问题 (BUG):**
docker中成功运行Hello from docker，但面板无法创建docker镜像
![image](https://user-images.githubusercontent.com/83596484/134695004-f1ac1b8f-49d2-4989-b424-64462abe9088.png)
![image](https://user-images.githubusercontent.com/83596484/134695060-d87689ad-c04c-47d7-b2cf-d017f465d821.png)

**复现操作步骤:**
yum install -y docker
systemctl start docker
docker run hello-world

**Comment by Suwings** [comment]
可能是网络原因？尝试把 Docker 镜像改为国内源再试一次，Docker 镜像创建功能已经在以前经过多个 Linux 测试，最近版本此处功能改动不大，理论上不应会有错误。

**Comment by LanceXOT** [comment]
> 可能是网络原因？尝试把 Docker 镜像改为国内源再试一次，Docker 镜像创建功能已经在以前经过多个 Linux 测试，最近版本此处功能改动不大，理论上不应会有错误。

在docker安装的时候已经自动配置了国内镜像源，已尝试重启docker，仍然报错
服务器在香港，是否需要开启特定的服务或端口？

**Comment by LanceXOT** [comment]
使用root运行面板后问题解决了，谢谢
