### ISSUE TITLE
登录成功之后提示：与服务器连接断开,刷新网页可以重新链接

### ISSUE THREAD

**Issue by TsinbeiTech** [Suwings/MCSManager#487]
**内容:**
手动安装面板后，将面板封装为服务并启动，服务内容：
![image](https://user-images.githubusercontent.com/79034142/134804333-ffb6db52-b17b-4597-8845-29d2bcb77d6d.png)

使用默认账号密码#master 123456登录后提示链接断开：
![image](https://user-images.githubusercontent.com/79034142/134804285-d041c738-cd77-4fb3-a320-2c4deb763c7c.png)

报错信息：
![image](https://user-images.githubusercontent.com/79034142/134804414-cb747ab9-a85a-4d4d-8395-24b1c49cf60d.png)

附加说明：
通过查阅[https://github.com/Suwings/MCSManager/issues/146](url)，将/public/common/URL.js中的http、ws改成了https和wss，同时nginx反向代理部分使用了ssl。
![image](https://user-images.githubusercontent.com/79034142/134804506-6a847a9e-688c-43af-b0e4-1ceb7f13eca2.png)
![image](https://user-images.githubusercontent.com/79034142/134804514-6ff7dc3f-bf78-4186-896f-c5b421fd664d.png)

请问这是什么问题呢？

**Comment by Suwings** [comment]
根据你提供的网页的报错信息来看就是Websocket连接失败，检查反向代理是否正确配置的 WS+HTTP代理，或者防火墙，详情参考 WIKI。

**Comment by TsinbeiTech** [comment]
感谢您的回复。
通过修改反向代理的配置文件，我已成功解决此问题。
