### ISSUE TITLE
建议在程序捕获 SIGINT 信号后在关闭面板的同时，关闭 Minecraft 服务端

### ISSUE THREAD

**Issue by c057cl7** [Suwings/MCSManager#49]
现在的实现似乎只会关闭面板

**Comment by Suwings** [comment]
是的，目前的实现中只会卸载所有 Minecraft 服务端，但不是正常关闭，然后结束自身进程，系统会顺便结束掉所有服务端的进程。
在目前的新版本中，我们设计了`一键关闭所有服务端`按钮。

我们将会在接下来的新版本中，在捕获到信号时，自动顺便关闭所有服务端。

感谢反馈。

**Comment by c057cl7** [comment]
嗯，感谢阁下开发 MCSM 这一易用的 Minecraft 服务器面板。

**Comment by c057cl7** [comment]
Thanks a lot.

Suwings <notifications@github.com> 于 2018年7月27日周五 15:25写道：
