### ISSUE TITLE
Ubuntu下获取物理内存使用情况错误

### ISSUE THREAD

**Issue by ricky50575** [Suwings/MCSManager#490]
**系统环境:**
Ubuntu 20.04.3
**面板版本:**
8.6.23 发行版本
**Node 版本:**
v10.19.0
**出现概率:**
总是
**出现的问题 (BUG):**
服务器2GB物理内存，Ubuntu下获取物理内存使用情况总是为93%，实际上有1607092字节物理内存是可用的（available）。
[![2021-10-16-225308.png](https://i.postimg.cc/tRWbwdHf/2021-10-16-225308.png)](https://postimg.cc/YjrTmW0f)
[![2021-10-16-225351.png](https://i.postimg.cc/MKwwSc6G/2021-10-16-225351.png)](https://postimg.cc/w3wZ5jsK)
**复现操作步骤:**
立即出现

**Comment by Suwings** [comment]
已知情，以后会寻找代替方案。

https://github.com/Suwings/MCSManager/issues/474
