### ISSUE TITLE
无法启动服务端

### ISSUE THREAD

**Issue by Cupsoul** [Suwings/MCSManager#497]
**
![1](https://user-images.githubusercontent.com/71859309/139968924-2fe59fdc-5c3c-4c71-a913-f67dc4ad2793.png)
想问一下这是什么问题 
我在服务端根目录可以用bat文件运行服务端 但是用管理面板就没办法运行了
**

**Comment by huangsijun17** [comment]
报错的是库文件丢失，看上去像是启动目录不对。

黄思俊
上海触漫网络科技有限公司
办公电话： 021-62503031
手机（微信）：15000678476
***@***.***
地址：上海市虹口区广中路88号306室

发件人: Teng ***@***.***>
发送时间: 2021年11月3日 8:20
收件人: ***@***.***>
抄送: ***@***.***>
主题: [Suwings/MCSManager] 无法启动服务端 (Issue #497)


**
[1]<https://user-images.githubusercontent.com/71859309/139968924-2fe59fdc-5c3c-4c71-a913-f67dc4ad2793.png>
想问一下这是什么问题
我在服务端根目录可以用bat文件运行服务端 但是用管理面板就没办法运行了
**

―
