### ISSUE TITLE
网页端面板连接失败问题

### ISSUE THREAD

**Issue by CleMooling** [Suwings/MCSManager#498]
**系统环境:Windows_NT win32;Windows Server 2019 Datacenter 10.0.17763**

**面板版本:9.0.0**

**Node 版本:v14.15.1**

**出现概率:经常**

**出现的问题 (BUG):频繁无法连接到网页端面板(无论是本地还是远程)导致无法进行管理只能重启全部程序**

**复现操作步骤:无**

**Comment by Suwings** [comment]
描述不太清楚，本地浏览器是否能进入控制面板网页？如果能进入，是否能进入指定实例的终端界面，还是一直提示“连接中”。

建议描述内容再多一点，否则不好判断原因。

**Comment by CleMooling** [comment]
> 描述不太清楚，本地浏览器是否能进入控制面板网页？如果能进入，是否能进入指定实例的终端界面，还是一直提示“连接中”。
> 
> 建议描述内容再多一点，否则不好判断原因。

本地和远程浏览器都不能打开控制面板网页，但本地的进程没有任何报错且显示正常

**Comment by Suwings** [comment]
依然无法判断出问题所在，可能是最新的Windows Server不兼容Node14？我无法复现你所说的这种情况，如果您还在使用本软件，可以尝试研究一下在普通Windows10上是否会出现这种情况，以做对照组实验。

**Comment by CleMooling** [comment]
> 依然无法判断出问题所在，可能是最新的Windows Server不兼容Node14？我无法复现你所说的这种情况，如果您还在使用本软件，可以尝试研究一下在普通Windows10上是否会出现这种情况，以做对照组实验。

刚刚在进程窗口发送指令后网页可正常进入，应该是运行过久导致程序无响应产生这种问题

**Comment by Suwings** [comment]
是不是鼠标不小心点到了控制台窗口，选中了控制台中的文本。

在 Windows 中此操作会导致程序暂停，自然所有网站服务就全部失效了。

**Comment by huangsijun17** [comment]
试了一下，CMD和PS中选中文本均会暂停，但是用Windows Terminal不会。
