### ISSUE TITLE
网站域名无法进入，提示未备案

### ISSUE THREAD

**Issue by yqs112358** [Suwings/MCSManager#499]
RT，
![image](https://user-images.githubusercontent.com/37969157/140604971-6e094b35-71f9-434d-8e46-4941a0be121b.png)

**Comment by Cubik65536** [comment]
刚刚尝试访问 `https://mcsmanager.com` ，一切正常。如果这个提示是在你访问你的网站域名后出现的，那你需对你的域名进行备案

**Comment by Suwings** [comment]
是我这里的问题，现已修复。
