### ISSUE TITLE
信息框占版面

### ISSUE THREAD

**Issue by swwind** [Suwings/MCSManager#5]
在服务器配置页面点击最下方的“更新配置”后必须等待信息框消失后才能继续点击“返回控制台”。
这样有点浪费时间。

**Comment by Suwings** [comment]
刚刚去用了一下你的所说的地方，确实信息框遮挡了“返回控制台”等按钮。
不过介于这个服务器配置功能并不是一个常用的功能，并且如果增加底部外边距，会影响美观性；

不过，过段时间我们依然会在底下增加一个文字说明块，拉高整体高度，这样就不会遮挡按钮。

感谢你的反馈与建议。

**Comment by Suwings** [comment]
**已修复√**
Commit:[https://github.com/Suwings/MCSManager/commit/6be4ec145c7feed92b16a1589bdd8ac309b109b1](https://github.com/Suwings/MCSManager/commit/6be4ec145c7feed92b16a1589bdd8ac309b109b1)
