### ISSUE TITLE
想问下更新的话具体怎么操作。。。

### ISSUE THREAD

**Issue by soutou233** [Suwings/MCSManager#50]
想问下更新的话具体怎么操作。。。

**Comment by Suwings** [comment]
目前本项目没有带自动更新的方法，即更新需要人为的手动更新。
手动更新的方法很简单，使用最简单粗暴的方法即可：直接覆盖文件。

如果使用的是 git ，请直接 git pull。

注意事项：
- 如果你自定义了网页，修改了前端界面，那么覆盖时可能会覆盖掉你的自定义网页。
- 服务端配置文件在 `/servers/*.json` 下。服务端文件在 `/servers/server_core/*`下，请不要删除掉你的旧文件配置。
- 用户配置文件在 `/users/*.json` 。
- 除非发布版本时有额外说明，一般更新都是直接覆盖原文件即可。
