### ISSUE TITLE
怎样在ubuntu上使用基岩版

### ISSUE THREAD

**Issue by mghcool** [Suwings/MCSManager#500]
怎样在ubuntu上使用基岩版
创建好服务器后一直不不能运行

日志：
[ SYSTEM ] 正在监听服务端日志输出.
[MCSMANAGER] -------------------------------------------------------------- 
[MCSMANAGER] [ 2021/10/2 11:53:58 ]: 服务端 new_server_2912000 执行开启命令. 
[MCSMANAGER] -------------------------------------------------------------- 
./bedrock_server: ./bedrock_server: 无法执行二进制文件

**Comment by Suwings** [comment]
https://github.com/Suwings/MCSManager/wiki/%E4%BD%BF%E7%94%A8%E9%9D%A2%E6%9D%BF%E5%BC%80%E5%90%AF-Bedrock_server-%E6%9C%8D%E5%8A%A1%E7%AB%AF
