### ISSUE TITLE
是否能自定义密码输入多少次后禁止登录，禁止登录多少分钟

### ISSUE THREAD

**Issue by DMB-codegang** [Suwings/MCSManager#501]
**你对哪些功能有建议或想法？**
是否能自定义密码输入多少次后禁止登录，禁止登录多少分钟，或是关闭该功能
这主要是针对内网穿透用户，因为同一个IP会发送大量登录信息，如果被防火墙拦截，其他正常用户也登录不了
**这些功能有哪些代替方案？**
比如做一个内网穿透端在公网服务器，然后连接到内网服务器进行运行，防火墙运行于公网服务器上，这样就能区分IP
**对应你提出的内容，你觉得有什么价值？**
主要是针对内网穿透用户，因为同一个IP会发送大量登录信息，如果被防火墙拦截，其他正常用户也登录不了
**其他内容:**

（功能请求或者功能建议均准许自由发挥，无特定限制模板，你可以在这里写下任何你想说的文字。）

**Comment by Suwings** [comment]
可以考虑在新版上加一个“禁止IP高频验证”的开关，来解决这个需求，此功能需求已经加入 todo，但是优先级会靠后一点。

**Comment by DMB-codegang** [comment]
或者考虑把面板和服务器管理模块分开，通过端口连接传输，默认127.0.0.1，这样可以兼顾单机运行和多机协同，降低单机器的运算负载。同时，还能解决开启服务器时CPU100%导致的服务器无响应

**Comment by Suwings** [comment]
你说的这个功能需求已在 MCSM9 中实现，可以在置顶 issues 或者等待发布正式版。
