### ISSUE TITLE
面板反馈出来的内存占用异常

### ISSUE THREAD

**Issue by DMB-codegang** [Suwings/MCSManager#503]
**系统环境:**
arch
Linux x64 Quantum-Server 5.10.71-1-lily
**面板版本:**
8.7.0发行版
**Node 版本:**

**出现概率:**

**出现的问题 (BUG):**
内存显示占用14776.9 MB
但实际占用仅有3000MB左右

**Comment by Suwings** [comment]
已确认为BUG，待修复中 https://github.com/Suwings/MCSManager/issues/474
