### ISSUE TITLE
管理员账号增加普通账号APIKEY申请接口

### ISSUE THREAD

**Issue by mrxiaozhuox** [Suwings/MCSManager#504]
管理员账号能拥有用户账号 APIKEY 申请的接口及权限，这样能方便一些系统的管理。否则需要实现某种功能时，还得让用户手动申请Key后再填写到其他系统，太过麻烦了。

**Comment by huangsijun17** [comment]
友情提示一下，HTTP的post和get都是明文，容易被ARP等中间人攻击。MCSM的API-Key是一种不安全的通讯方式，不建议跨设备通信。

**Comment by Cubik65536** [comment]
> 友情提示一下，HTTP的post和get都是明文，容易被ARP等中间人攻击。MCSM的API-Key是一种不安全的通讯方式，不建议跨设备通信。

HTTPS能够相对的缓解这个问题吧？

**Comment by mrxiaozhuox** [comment]
> 友情提示一下，HTTP的post和get都是明文，容易被ARP等中间人攻击。MCSM的API-Key是一种不安全的通讯方式，不建议跨设备通信。

问题不大

**Comment by mrxiaozhuox** [comment]
> 友情提示一下，HTTP的post和get都是明文，容易被ARP等中间人攻击。MCSM的API-Key是一种不安全的通讯方式，不建议跨设备通信。

且照你这么说，GET的Query参数本身也是不安全的传递方式，所以说这种东西本身就不好定义懂吗。

**Comment by huangsijun17** [comment]
> > 友情提示一下，HTTP的post和get都是明文，容易被ARP等中间人攻击。MCSM的API-Key是一种不安全的通讯方式，不建议跨设备通信。
> 
> 且照你这么说，GET的Query参数本身也是不安全的传递方式，所以说这种东西本身就不好定义懂吗。

java的mod/插件里传一个ARP中间人监听程序上来，没ARP手动绑定的话，HTTP传输基本就透明了。当然，Docker可防。

**Comment by huangsijun17** [comment]
> > 友情提示一下，HTTP的post和get都是明文，容易被ARP等中间人攻击。MCSM的API-Key是一种不安全的通讯方式，不建议跨设备通信。
> 
> HTTPS能够相对的缓解这个问题吧？

是的，HTTPS可以解决，但是和反代中间还是明文。

**Comment by mrxiaozhuox** [comment]
> java的mod/插件里传一个ARP中间人监听程序上来，没ARP手动绑定的话，HTTP传输基本就透明了。当然，Docker可防。

这种操作方法在API开发中再正常不过了，这套程序的ApiKey本身设计就比较简陋，一般来说我们做接口鉴权都会用类似JWT的技术，但是ApiKey这种不手动更新就永久有效的鉴权方法本身就不安全，且Api这种东西的存在就是为了与外部其他程序进行通讯。且目前大部分Web项目都使用的前后端分离开发，即接口加鉴权；只要把鉴权手段完善好，就不会出现问题。

**Comment by Suwings** [comment]
感谢贡献代码。

我仔细阅读了你的代码，没有发现什么问题，不过格式化程序影响的代码量太多，建议下次提交前不要修改这么多地方。

晚上我再仔细看下逻辑，没有问题后便会合并，合并后我会将你的代码通过统一格式化工具再进行格式化。

**Comment by huangsijun17** [comment]
> 

MCSM9就已经前后端分离了，可以使用自己写的前端和deamon交互。
