### ISSUE TITLE
自动重启问题

### ISSUE THREAD

**Issue by jakfc** [Suwings/MCSManager#506]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境:**
centos8
**面板版本:**
8.7.0 发行版本
**Node 版本:**
16.13.0
**出现概率:**
100
**出现的问题 (BUG):**
使用stop命令关闭服务器后，服务器未自动重启，自动重启设置已经打开(有个插件实现重启的方式就是stop命令，需要配合外部的自动重启)
**复现操作步骤:**
![image](https://user-images.githubusercontent.com/51145366/143380670-7e9bcec3-e4f3-4ac5-9d7d-15a611116fa8.png)

**Comment by jakfc** [comment]
已解决，通过在服务端下写自启动脚本，并用面板的自定义参数执行脚本

**Comment by huangsijun17** [comment]
建议试试看使用`/minecraft:stop`命令。高版本的Minecraft服务端可以指定命令的mod归属。
