### ISSUE TITLE
是否添加绝对路径变量?

### ISSUE THREAD

**Issue by TelDragon** [Suwings/MCSManager#51]
尊敬的作者您好，
我非常喜欢该应用，但是我再使用时遇到一个不便的情况。
我想使用第三方工具来守护此服务，例如 systemctl 或 forerver 。
但是我查看了下本项目的 app.js 貌似路径获取是当前目录。因此导致 无法守护，

可不可以增加一个绝对路径变量 或者其他的方式，能让我来对该服务进行守护。

**Comment by Suwings** [comment]
感谢反馈！

这个项目中确实很多地方使用了相对路径，对于这种绝对路径变量的需求，暂时性还是做不到。
十分抱歉。

**Comment by c057cl7** [comment]
阁下可以尝试将此应用程序注册为一个系统服务，这样可以就通过 service 命令进行管理了。也可以尝试用 Shell 实现，见[知乎](https://www.zhihu.com/question/20356184)。
