### ISSUE TITLE
稳健

### ISSUE THREAD

**Issue by shimakazeDivine** [Suwings/MCSManager#52]
默认密码是123456 我还去配置文件里一顿改

**Comment by Suwings** [comment]
控制面板第一次启动时候时候，在控制台不应该已经告诉你了默认密码是多少吗？
另外在配置文件改虽然可以，不过你得 salt 和 md5 的组合更改。

另外感谢 Star ， 您是正好第一百位。不过我们没有什么奖品送罢了。
