### ISSUE TITLE
控制台输出编码不正常

### ISSUE THREAD

**Issue by Er-S** [Suwings/MCSManager#55]
环境 : Node.js 8.11.3LTS || Windows Server 2012R2 中文版 || 腾讯云服务器
服务器版本 : PaperSpigot-1169 (MC 1.12)

原本使用 GBK
我先是把服务器日志/命令编码改为UTF-8, 然后发现乱码了...
就把编码调回了 GBK.
然后日志信息就好了.
不过, 控制台命令却出现了乱码.

**Comment by Suwings** [comment]
感谢你的反馈。
控制台命令是指发送一个含有中文的Minecraft命令到服务端，但是中文却乱码？

如果是输入命令乱码，建议只将命令输入改成 utf8 尝试一下。
因为似乎1.9.X以上版本，标准输入编码默认变成了 utf8 。如果这样无作用，请尝试一下通过自定义参数，添加启动附件参数，强制性设置mc端输入为 utf8。

如果以上均不行，还烦请细节报告。 @Er-S

**Comment by Er-S** [comment]
问题已解决。
只将命令输入改为UTF-8后就好了。
谢谢
