### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zxc7895531** [Suwings/MCSManager#56]
1.希望可以加上更详细后台日志记录功能，告诉后台哪个时间某个用户从某个IP访问某个页面是成功还是失败。
举几个例子：比如我在12:00:00使用#master用户使用127.0.0.1这个IP访问了/public/index.html并访问成功；有人在14:00:00使用了一个未登录用户使用192.168.1.123这个IP访问了/server/server_core/server/test.jar并访问失败。
如果后台被攻击了这样可以更准确的告诉用户是什么状况，是否防御成功等等。
2.将数据中心所有的变量写出，这样可以让一些使用者更方便的自定义后台界面

**Comment by Suwings** [comment]
感谢反馈。
以上两点我们会慎重考虑，可能会在未来版本加入你想要的功能。

但是我们需要一定的时间，谢谢理解。
