### ISSUE TITLE
搭建网页问题

### ISSUE THREAD

**Issue by zhlzhl123** [Suwings/MCSManager#57]
你好，我购买了云服务器后（1g1h，不知道够不够）按照：“Linux 下安装与使用详解”一步一步搭建后，最终启动成功却无法访问页面ERR_CONNECTION_TIMED_OUT，ip没有被墙，请问我是不是犯了什么蠢错误，望指出，谢谢
![1](https://user-images.githubusercontent.com/24950039/43849377-dc93a110-9b67-11e8-85d5-3fe60c8e8596.PNG)
服务器防火墙关闭了
请问是不是还有什么需要设置的呀？

**Comment by zhlzhl123** [comment]
万分抱歉，reboot后就好了，打扰了

**Comment by Suwings** [comment]
不建议 1g1h 服务器用在搭建 Minecraft 服务端。
