### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by popakrt** [Suwings/MCSManager#59]
- 一个支持配置文件的纯文本高亮编辑器，可以与文件管理器集成

- 可以使用文件管理器选择服务端核心文件

- 插件管理器

- 建议优化下在移动端访问时的排版和交互，特别是服务器控制台的那个页面，经常让手机浏览器卡死。。。

**Comment by Suwings** [comment]
感谢提供建议。
部分内容我们会进行考虑，也感谢你提出这些好注意，我们尽可能的满足一些需求，但是这一定需要一段时间。

再次感谢你的提议。
