### ISSUE TITLE
内存显示问题！

### ISSUE THREAD

**Issue by mint-k** [Suwings/MCSManager#6]
我在服务商的面板看机子使用了40%的内存 可是在MCSManager里面 却显示使用60%左右 这是为什么呢？
希望控制台增加错误信息字体颜色 明显一点 否则有点难辨认。

**Comment by Suwings** [comment]
请问你的操作系统以及具体版本？我们将模拟这一环境进行调查。 @mint-k

**Comment by mint-k** [comment]
centos7.4

**Comment by Suwings** [comment]
是这样的，我们取的剩余内存是系统的（free）未使用的空闲内存，代指还未被任何程序使用的内存区域。
但是实际上，有一部分内存是用做程序 （buff/cache）缓冲/临时储存，用于加快程序运行。
这也就导致了，面板上显示的剩余内存比实际可用内存要少一部分的原因。

我们将于尽快修复，获取可用内存（available）百分比。
