### ISSUE TITLE
Wiki页面 密码传递流程图 图片无法加载

### ISSUE THREAD

**Issue by BBleae** [Suwings/MCSManager#67]
[密码传递流程图](https://github.com/Suwings/MCSManager/wiki/%E7%99%BB%E5%BD%95%E5%AF%86%E7%A0%81%E4%BC%A0%E9%80%92%E8%BF%87%E7%A8%8B%E5%9B%BE)
其中的图片无法加载，404 Not Found

**Comment by Suwings** [comment]
感谢反馈，过段时间，我们将更新wiki 中的这些问题!谢谢!

**Comment by Suwings** [comment]
已修复。
https://github.com/Suwings/MCSManager/wiki/%E7%99%BB%E5%BD%95%E5%AF%86%E7%A0%81%E4%BC%A0%E9%80%92%E8%BF%87%E7%A8%8B%E5%9B%BE

**Comment by BBleae** [comment]
图又挂了...这次是502

**Comment by Suwings** [comment]
好的，等会我就补上！放到github上，保证不会再出去挂的情况

**Comment by Suwings** [comment]
https://github.com/Suwings/MCSManager/wiki/%E7%99%BB%E5%BD%95%E5%AF%86%E7%A0%81%E4%BC%A0%E9%80%92%E8%BF%87%E7%A8%8B%E5%9B%BE
已修复 @BBleae
