### ISSUE TITLE
提示缺少 Properties 文件或找不到 xxx.jar

### ISSUE THREAD

**Issue by fuyunjundada** [Suwings/MCSManager#68]
启动说我不存在服务器名.jar，创建服务器时服务端名字加了jar，点开服务器配置说缺少properties。
请问如何解决。

**Comment by Suwings** [comment]
软件启动时，提示你不存在 xxx.jar 你虽然配置了这项，但是你应该是忘记上传了，或者你设置的服务端根目录错误；请检查一下你的服务端目录是否设置正确，或者你可以从文件管理上传这个这个 xxx.jar 文件。

关于 properties 配置，这是因为你需要先启动一次服务器，这个文件才会生成。
