### ISSUE TITLE
请求添加命令行补全功能

### ISSUE THREAD

**Issue by Jecvay** [Suwings/MCSManager#69]
打了一半命令按个 Tab 建, 普通 Console 是有提示的, 这个功能可以添加一下吗?

**Comment by Suwings** [comment]
十分抱歉，这个毕竟是网页形式，不是那种模拟终端的，所以自然不会有按tab提示功能，这个功能个人认为目前还是不太需要吧，而且实现起来也很麻烦，毕竟网页中tab的作用应该是跳转光标焦点。

感谢反馈。

**Comment by Jecvay** [comment]
好的, 再问下如果想为此管理系统  使用Electron.js开发客户端, 会得到精神上的支持吗
既然是前后端分离这个应该很好做各种客户端与其配套.

**Comment by Jecvay** [comment]
我也是醉了...博观而约取...
