### ISSUE TITLE
IIS下如何为MCSManager的WebSocket反向代理问题

### ISSUE THREAD

**Issue by TheMountainsLay** [Suwings/MCSManager#73]
现在我80端口是被IIS占领了，所有反向代理不得不在IIS，MCSManager在使用HTTP的同时还会打开WebSocket连接，URL为ws://或者wss://开头。这种情况下如果只转发HTTP，服务就无法正常使用。但是按照网上教程写在条件下添加一项，条件输入为{CACHE_URL}，模式为(.+)://，然后重写URL改为{C:1}://XXXXXXXX/{R:1}，还是失败了，是什么原因，求，难道是IIS问题？

**Comment by LeiZhiMin1** [comment]
这个项目貌似是必须要ws来进行通信的，多试试吧，我组反向就没问题啊。
