### ISSUE TITLE
默认密码是什么？

### ISSUE THREAD

**Issue by wuyucun** [Suwings/MCSManager#75]
打开面板后就是登录界面，密码是什么？
删掉了user目录下的所有文件，也没有效果

**Comment by Suwings** [comment]
账号 #master
密码 123456

控制台有输出的，这里回答一下方便以后别人搜索到。

**Comment by masnn** [comment]
我当年也找好久
最后翻源码按照加密方式手动生成的密码填进去..

**Comment by Suwings** [comment]
你很有折腾的精神，值得鼓励。 @masnn

**Comment by masnn** [comment]
23333333

________________________________
发件人: Suwings <notifications@github.com>
发送时间: Friday, January 4, 2019 11:09:47 PM
收件人: Suwings/MCSManager
抄送: masnn; Mention
主题: Re: [Suwings/MCSManager] 默认密码是什么？ (#75)


你很有折腾的精神，值得鼓励。 @masnn<https://github.com/masnn>

―

**Comment by yumao233** [comment]
新版已经没有默认密码和账号，如果你第一次安装直接访问的是登录界面，请去掉 URL 地址中 /login 相关文本，重新刷新试试。
