### ISSUE TITLE
希望改进自动重启功能

### ISSUE THREAD

**Issue by zxc7895531** [Suwings/MCSManager#76]
希望可以做到检测是否为面板后台手动关服，如果是则不自动重启，这样省去了一大波的麻烦。加个插件还得手动把自动重启关掉，加完了可能又会忘记开，非常麻烦

**Comment by masnn** [comment]
同求

**Comment by Suwings** [comment]
好吧，这个功能细节问题确实值得改进一下，过段时间我将完善这个功能。

即，有且只有在控制面板中单击 `关闭服务器`，`强制关闭服务器` 这些按钮时，才会无视自动重启功能，其他任何情况下（包括您插件功能的关服，/stop指令），自动重启功能依然有效。

**Comment by huangsijun17** [comment]
貌似，Java运行MC会返回允许成功（正常关服）或错误代码。
是否可以在自动重启前加一个判断？

**Comment by Suwings** [comment]
嗯嗯，明白，但是最近一段时间实在太忙了，我是计划下周再更新代码 @huangsijun17
