### ISSUE TITLE
該如何使玩家開啟面板

### ISSUE THREAD

**Issue by fushimitei** [Suwings/MCSManager#78]
RT，請問該如何使其他玩家成功連線到服主的面板

**Comment by HonokaClub** [comment]
連接是指，讓玩家加入游戲，還是登錄你服務器的管理平臺？

**Comment by fushimitei** [comment]
抱歉沒有說明清楚，是只登入服務器的管理平台。

**Comment by HonokaClub** [comment]
你可以創建一個子賬戶，將這個子賬戶和 Panel 的管理地址發送給你的用戶，讓他們用子賬戶登錄

**Comment by fushimitei** [comment]
emmmm，貌似可以了，非常感謝
