### ISSUE TITLE
希望能够更改控制台的字体

### ISSUE THREAD

**Issue by mnixry** [Suwings/MCSManager#79]
因为我们在浏览器中使用的一般是非等宽字体，而且很容易造成`l`和`I`混淆不清的问题和将两个单引号误认为双引号的可能，所以建议更改控制台字体为`Consolas`或者`DejaVu Sans Mono`这类字体会更加容易辨认

**Comment by Suwings** [comment]
感谢提供意见。以前有人跟我提过这些事情，看起来确实继续用这些原字体不妥，过段时间我们将会优化这个问题。
