### ISSUE TITLE
汇报,发现于8.1版本

### ISSUE THREAD

**Issue by 1013403878** [Suwings/MCSManager#8]
1.创建的用户删除如果被删除的用户在被删除前在线并未下线的情况。
2.被删除用户不会被强制下线。
3.更改用户密码也不会导致用户强制下线
4.以上所述问题在用户在线的时候 还是有权限的。

**Comment by Suwings** [comment]
感谢反馈，我们将会模拟这一情况调查，在我们完成目前计划的功能之后，将修正这个问题。 @1013403878
