### ISSUE TITLE
1. 希望可以显示实时的在线人数

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#81]
其他面板大多都有，希望可以显示。

**Comment by Suwings** [comment]
这个功能的确，我们也缺少。

刚刚说过了。近期计划的话我们不会对代码进行太多的修改，功能也不会再进行新增。毕竟这是一个免费开源的项目，压力太大，有更重要的事情需要我们去做。

**Comment by Suwings** [comment]
关闭这个议题并不代表以后不会开发出这个功能。此功能也算是一个比较重要的功能，只是我不想用，联网API获取数据的方式来取数据。想直接用兼容各个服务端的方法来取数据。
