### ISSUE TITLE
3. 对某些第三方服务器端的彩色文字兼容性欠佳

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#83]
某些第三方服务器端，可能会为了在终端（系统Shell）显示彩色文字，而加入特殊字符+数字，如1.12 的**§**符号+数字：**§4[**应该显示红色的**[**，而面板的终端却对其未做解析/转义/删除直接显示。从而严重影响阅读。

**Comment by huangsijun17** [comment]
我那个*B辅助搞了BC跨服，加了插件登录服，格雷空岛又加了不少插件。
然后，我只能看着后台那满屏的§。得，我自己来删。QAQ
求通过。

**Comment by Suwings** [comment]
谢谢！

**Comment by huangsijun17** [comment]
> 谢谢！

想到一个问题，劳烦确认一下。就是别人有没有可能通过双S符会被删除这一点，拿§来分割一些XXS的关键词从而绕过检测等？

**Comment by Suwings** [comment]
不会。
这里控制台输出时进行的过滤。
https://github.com/Suwings/MCSManager/blob/master/public/common/js/viewmodel.js#L127

这里是HTML编码的函数，所有特殊符号已经正确转义。
https://github.com/Suwings/MCSManager/blob/master/public/common/js/tools.js#L52

虽然只会encode < > " ' / & 和 空格 等，但应该足以应付这个问题。

并且在 139 行处。
https://github.com/Suwings/MCSManager/blob/master/public/common/js/tools.js#L139
所有的 < 与 > 符号都会由一个 <span> 包含，让XSS攻击实现更难。

如果您实现了XSS攻击，请务必告知我，用 /say 命令可以测试这个问题，如果一旦出现任何 XSS 攻击（不论大小与严重性），请新建提案告知，必当修复。谢谢！

**Comment by huangsijun17** [comment]
`say §<br />`
试试看吧。

**Comment by Suwings** [comment]
的确，这个算是 `XSS`，设计之初考虑过这点，只是感觉没必要，因为无法组成攻击姿态。

具体原因是，前端会将 `<br />` 元素（仅限于这6个字符）不经过过滤输出，因为它需要与后端的 `\n` 转成 `<br />` 配合，这样输出文本才有换行效果。

不过，现在已修复这个问题：https://github.com/Suwings/MCSManager/commit/2287f2ef3237b9a0c87efa9c2e9b39fd305345b1

我们将后端的 `\n` 转成 `[_b_r_]` 标识符，再从此标识符转换回 `<br />`。

*不过* 目前还剩下一个问题，即`§`符号依然会删除第二位字符（这理所当然）。

如果输入命令:
```
say §<br />
```
则会输出：
```
say span style='color:#10e616;'><br />
```

所以我把正则修改成 `/§[0-9A-Za-z]{1}/igm` 了，如依然有问题，欢迎继续反馈！

- 再次感谢提出建议！谢谢。

<br />

> 参考资料：https://minecraft-zh.gamepedia.com/%E6%A0%B7%E5%BC%8F%E4%BB%A3%E7%A0%81
