### ISSUE TITLE
5. 显示的CPU与内存占用问题

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#84]
实测，显示的占用为操作系统的占用，内存包含可释放的数据，未包含虚拟内存。
可否提供一下整个面板+各服务器的CPU与内存占用？
可否提供一下单个服务器的CPU与内存占用？谢谢了。

**Comment by Suwings** [comment]
内存显示已使用是包可释放内存（已激活内存）与已使用内存。这个是在Linux下会出现这种现象，因为使用的是node提供的原生API。这个数据显示。短期内不打算更改，因为我们还有更重要的事情要做。

关于虚拟内存显示，虚拟内存。这个东西。不是特别需要显示的东西吧？

**Comment by huangsijun17** [comment]
> 抱歉，刚刚手机误操作了一下。
> 
> 内存显示已使用是包可释放内存（已激活内存）与已使用内存。这个是在Linux下会出现这种现象，因为使用的是node提供的原生API。这个数据显示。短期内不打算更改，因为我们还有更重要的事情要做。
> 
> 关于虚拟内存显示，虚拟内存要显示也没什么环境，但是你所指的虚拟内存我的理解是Linux下的交换空间，这个东西没有太多必要显示。
> 
> 你说的那些获取各个服务端进程单独的CPU使用和内存占用。我觉得这个不太好实现。

虚拟内存指的是交换空间。另外，可否直接读取到锁运行的各个Java进程的占用？
我们现在有时候还是依赖Linux下的htop来看各个进程的占用的。好在只开了一个服务器。但考虑到由于可能会搞BC跨服，到时候开htop这种来看占用，需要通过各个Java的启动参数来区别各个服务器，着实不便。

**Comment by Suwings** [comment]
这个也不是没可能，虽然说好像是可以实现，具体我还要研究一下，现在手头没有电脑。想查看每个服务器单独占的内存，这一点确实可以考虑，是一个卖点（当然我们不卖钱）。
