### ISSUE TITLE
使用filezilla无法连接FTP服务器

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#85]
使用 filezilla 无法连接到ftp服务器，改用flashfxp后正常。兼容性问题？

**Comment by Suwings** [comment]
FTP的功能模块不是我开发的，项目也在github上，在使用过程中的确出现部分FTP客户端软件不兼容的问题，过段时间我去看一下这个模块的更新状况，如果能修复这个问题，那自然是最好。如果要是还有这类问题 ，我可以去观察一下有没有其他相关类似功能的模块。
