### ISSUE TITLE
服务器错误?

### ISSUE THREAD

**Issue by mon030** [Suwings/MCSManager#87]
登入管理页面时，提示服务器错误<img src="https://i.loli.net/2019/01/27/5c4d41c45e369.png" alt="新建文本文档.PNG" title="新建文本文档.PNG" />

**Comment by Suwings** [comment]
单凭这个截图我没有办法判断是什么原因，不过综合长期以来其他人的问题各种经验。

1. 我觉得您可能没有使用http://协议来访问文件，确认一下你的URL地址是否正确。
2. 你把控制台关了（Windows），你断开了链接（Linux）
3. 防火墙或者网络有问题，超时。

**Comment by pppwaw** [comment]
管理账户前面要加#

**Comment by Suwings** [comment]
这应该不是管理前面要加#的问题，确实如果需要管理员请加#符号。

但是不加#符号，仅仅只是普通账号登录，会提示账号或密码错误，而不是提示服务器错误。所以肯定是其他原因，原因很多，刚刚我列举的三条极有可能是新手初次使用容易犯下的错误。

**Comment by pppwaw** [comment]
你不觉得这个名字很像初始管理么，不过建议把日志发上来

**Comment by Suwings** [comment]
我知道他肯定是忘记打#符号了，但是应该提示账号或密码错误，而不是服务器错误，所以我觉得是他的打开方式不对。
