### ISSUE TITLE
mc服务器执行restart后不能自动开启

### ISSUE THREAD

**Issue by pppwaw** [Suwings/MCSManager#88]
mc服务器执行/restart后不能自动开启，如图，（似乎是缺少一个start.sh?)
![qq 20190201110843](https://user-images.githubusercontent.com/17200045/52100316-fd734400-2611-11e9-92a2-3f84e4a000db.png)

**Comment by pppwaw** [comment]
红框是执行restart后的输出

**Comment by Suwings** [comment]
是的，缺少了 start.sh。
可能是Minecraft 服务端执行 restart 时会再根据 start.sh 进行重启操作，所以你要在服务端根目录下编写这一文件，内容就是你服务端运行的内容。

但是我建议你，在控制面板中打开自动崩溃重启，以后你想重启，只需要在mc中输入/stop，控制面板检测到之后，便会自动重启。

如你想真正关闭服务器，只需要手机或电脑访问，点击关闭服务器按钮即可。

**Comment by pppwaw** [comment]
好的谢谢，这个是手下调试用这个，不过可以把启动的命令写到这个文件里
