### ISSUE TITLE
偶然发现了一个小小的时间错误

### ISSUE THREAD

**Issue by DeSireFire** [Suwings/MCSManager#90]
home>服务与支持>最新动态与信息通知
这个日期是不是写错了。。？应该是2019年1月1日吧？
<img src="https://i.loli.net/2019/02/10/5c5efbbb0bb4f.png" alt="TIM图片20190210001120.png" title="TIM图片20190210001120.png" />

**Comment by Suwings** [comment]
这个确实，等会我就把他更正。谢谢提出意见。

**Comment by DeSireFire** [comment]
啊，挺小的问题，你谢我，我会不好意思的233，新年快乐！
如果Suwings已经更正了这个时间，就把这个Issues关闭吧。
其实还发现另外的一个问题，我也没搞清楚是不是我这边screen的原因还是文件调用权限的原因..
但是今天有点事要跑出去一趟，晚点再过来发另外一个Issues吧。

**Comment by Suwings** [comment]
已更正。
https://github.com/Suwings/Suwings.github.io/blob/master/mcserver/index.html
