### ISSUE TITLE
希望未来能增加

### ISSUE THREAD

**Issue by EterLzb** [Suwings/MCSManager#91]
1. 开启mcsm自动启动服务器（可选择）
2. 一键关闭所有服务器忽略崩溃重启

  感谢您的开发

**Comment by Suwings** [comment]
感谢提供建议。
第一条的话有点不妥，不过第二条这个问题，我们以后会修复这个问题。

**Comment by luckydog6132** [comment]
同样希望可以加入第一条，MCSM开启的时候，可以选择自动跟随启动的服务器。
场景比如托管机房会有不定时维护，重启电脑以后，由于MCSM是通过服务形式注册的，会自动启动，但是对应的服务器，还是需要登录到MCSM后启动，就会比较被动

**Comment by myktw** [comment]
同样期望添加第一条自动启动

**Comment by D-Jy-lab** [comment]
同样期望添加第一条自动启动

**Comment by BingYanchi** [comment]
同样期望添加第一条自动启动

**Comment by BingYanchi** [comment]
> 感谢提供建议。
> 第一条的话有点不妥，不过第二条这个问题，我们以后会修复这个问题。

希望加入第一条，比如机房维护，重启的时候能够自动开启所有服务器
