### ISSUE TITLE
希望增加 nogui 参数

### ISSUE THREAD

**Issue by huangsijun17** [Suwings/MCSManager#95]
前些天自己本地拿win和带桌面的ubuntu测试，发现开服后弹出了mc的gui终端。可否默认添加一个nogui启动参数？

**Comment by Suwings** [comment]
这个你可以使用自定义命令来实现，在后面加个 -nogui，不过的确，这个问题下个版本我们会改进。

**Comment by huangsijun17** [comment]
> 这个你可以使用自定义命令来实现，在后面加个 -nogui，不过的确，这个问题下个版本我们会改进。

自我了断。
