### ISSUE TITLE
Firefox 下 ws 链接异常

### ISSUE THREAD

**Issue by A-new-Account** [Suwings/MCSManager#97]
win10没做任何配置下载的一键使用包
登陆后没反应打开F12发现无法连接WS
[https://i.loli.net/2019/03/20/5c92296d4f53a.png](图片)

**Comment by A-new-Account** [comment]
这是浏览器的问题吗？

**Comment by Suwings** [comment]
我使用了 Firefox 浏览器访问从下载点下载的 Windows 整合包访问，没有出现你的这种情况。建议你刷新网页或者重新启动 MCSManager 软件尝试，如果依然存在这个问题，尝试换一个端口。

或者，使用其他浏览器 Chrome，IE10+ 进行尝试一下？
如果能正常访问，说明是你的 Firefox 的某些设置导致的

我这里无法复现你的这种情况，如果你依然无法解决这种情况，还望提供浏览器版本，与 Windows 具体版本。

谢谢！ @A-new-Account
