### ISSUE TITLE
服务器无法启动 UncaughtException 机制错误报告

### ISSUE THREAD

**Issue by kirning** [Suwings/MCSManager#98]
![image](https://user-images.githubusercontent.com/7327933/55135296-39380f00-5166-11e9-9d59-198000adc9fa.png)
文件路径是没有问题的
![image](https://user-images.githubusercontent.com/7327933/55135363-72707f00-5166-11e9-8fea-76eb211260ec.png)

**Comment by Suwings** [comment]
确认一下 Java 环境是否按照正确，参数是否全部正确。

如果依然出现这类情况，可以考虑使用 Docker（不需要Java环境）。或者如果你确保 java 环境正确无误，那么可以试试自定义命令功能。

确认Java环境是否正确的方法，输入命令 `java` 是否能输出java相关命令信息。

**Comment by kirning** [comment]
您好，java环境是没有问题的，直接在目录下输入
```
java -Xmx1024M -Xms1024M -jar minecraft_server.1.13.2.jar nogui
```
是可以正常运行的

**Comment by kirning** [comment]
您好，使用绝对路径的java后，问题解决，谢谢
